'use client'
import { useLocation } from '@/lib/location-context'
import { useLanguage } from '@/lib/language-context'

const D: Record<string, any> = {
  en: { pinned:"AI Mayor • Pinned for neighbors", privateBlock:"Your private block • {area}", found:"🎉 You found us. Welcome to your private block.", space:"This is your space near {area} — not the whole internet.", ways:"3 ways to start:", s1:"Say hi and share your cross streets (no exact address needed)", s2:"Post one thing you need or one thing you can give", s3:"Tap Use my location to unlock your Block Map", robots:"No robots. No shadowbans. Faith welcome. Respect required.", speak:"Speak Freely. Love Your Neighbor." },
  es: { pinned:"Alcalde IA • Fijado para vecinos", privateBlock:"Tu bloque privado • {area}", found:"🎉 Nos encontraste. Bienvenido a tu bloque privado.", space:"Este es tu espacio cerca de {area} — no todo el internet.", ways:"3 formas de empezar:", s1:"Saluda y comparte tus calles cruzadas (sin dirección exacta)", s2:"Publica algo que necesites o algo que puedas dar", s3:"Toca Usar mi ubicación para desbloquear tu Mapa del Bloque", robots:"Sin robots. Sin censura. Fe bienvenida. Respeto requerido.", speak:"Habla Libremente. Ama a tu Vecino." },
  fr: { pinned:"Maire IA • Épinglé pour voisins", privateBlock:"Votre bloc privé • {area}", found:"🎉 Vous nous avez trouvés. Bienvenue dans votre bloc privé.", space:"C'est votre espace près de {area} — pas tout internet.", ways:"3 façons de commencer:", s1:"Dites bonjour et partagez vos rues croisées", s2:"Postez une chose dont vous avez besoin ou que vous pouvez donner", s3:"Appuyez sur Utiliser ma position pour débloquer votre carte", robots:"Pas de robots. Pas de shadowban. Foi bienvenue. Respect requis.", speak:"Parlez Librement. Aimez Votre Voisin." },
  de: { pinned:"KI Bürgermeister • Für Nachbarn angeheftet", privateBlock:"Dein privater Block • {area}", found:"🎉 Du hast uns gefunden. Willkommen in deinem privaten Block.", space:"Das ist dein Raum nahe {area} — nicht das ganze Internet.", ways:"3 Wege zu starten:", s1:"Sag hi und teile deine Kreuzstraßen", s2:"Poste eine Sache die du brauchst oder geben kannst", s3:"Tippe Standort verwenden um Block-Karte freizuschalten", robots:"Keine Roboter. Keine Shadowbans. Glaube willkommen. Respekt erforderlich.", speak:"Sprich Frei. Liebe Deinen Nachbarn." },
  zh: { pinned:"AI 市长 • 置顶给邻居", privateBlock:"你的私人街区 • {area}", found:"🎉 你找到我们了。欢迎来到你的私人街区。", space:"这是你在 {area} 附近的空间 — 不是整个互联网。", ways:"3种开始方式：", s1:"打招呼并分享你的交叉街道（无需确切地址）", s2:"发布一件你需要的或你能给予的东西", s3:"点击使用我的位置解锁你的街区地图", robots:"没有机器人。没有限流。欢迎信仰。需要尊重。", speak:"自由发言。热爱你的邻居。" },
  ja: { pinned:"AI 市長 • 近隣向けに固定", privateBlock:"あなたのプライベートブロック • {area}", found:"🎉 見つけてくれました。プライベートブロックへようこそ。", space:"ここは {area} 近くのあなたのスペース — インターネット全体ではありません。", ways:"始める3つの方法：", s1:"挨拶して交差する通りを共有（正確な住所不要）", s2:"必要なものや提供できるものを1つ投稿", s3:"現在地を使用をタップしてブロックマップを解除", robots:"ロボットなし。シャドウバンなし。信仰歓迎。敬意必須。", speak:"自由に話そう。隣人を愛そう。" },
  ko: { pinned:"AI 시장 • 이웃을 위해 고정", privateBlock:"당신의 프라이빗 블록 • {area}", found:"🎉 우리를 찾으셨네요. 프라이빗 블록에 오신 것을 환영합니다.", space:"여기는 {area} 근처의 당신의 공간 — 전체 인터넷이 아닙니다.", ways:"시작하는 3가지 방법:", s1:"인사하고 교차로를 공유하세요 (정확한 주소 불필요)", s2:"필요한 것 하나 또는 줄 수 있는 것 하나 게시", s3:"내 위치 사용을 눌러 블록 지도 잠금 해제", robots:"로봇 없음. 섀도우밴 없음. 신앙 환영. 존중 필수.", speak:"자유롭게 말하세요. 이웃을 사랑하세요." },
  pt: { pinned:"Prefeito IA • Fixado para vizinhos", privateBlock:"Seu bloco privado • {area}", found:"🎉 Você nos encontrou. Bem-vindo ao seu bloco privado.", space:"Este é seu espaço perto de {area} — não a internet toda.", ways:"3 formas de começar:", s1:"Diga oi e compartilhe suas ruas cruzadas", s2:"Poste uma coisa que precisa ou que pode dar", s3:"Toque em Usar minha localização para desbloquear seu Mapa", robots:"Sem robôs. Sem shadowban. Fé bem-vinda. Respeito obrigatório.", speak:"Fale Livremente. Ame Seu Vizinho." },
  ru: { pinned:"ИИ Мэр • Закреплено для соседей", privateBlock:"Ваш приватный блок • {area}", found:"🎉 Вы нас нашли. Добро пожаловать в ваш приватный блок.", space:"Это ваше пространство рядом с {area} — не весь интернет.", ways:"3 способа начать:", s1:"Поздоровайтесь и поделитесь перекрестками", s2:"Опубликуйте то, что вам нужно или что можете отдать", s3:"Нажмите Использовать мое местоположение чтобы разблокировать карту", robots:"Без роботов. Без теневых банов. Вера приветствуется. Уважение обязательно.", speak:"Говорите Свободно. Любите Соседа." },
  ar: { pinned:"العمدة الذكي • مثبت للجيران", privateBlock:"بلوكك الخاص • {area}", found:"🎉 وجدتنا. مرحبا بك في بلوكك الخاص.", space:"هذه مساحتك بالقرب من {area} — ليست الإنترنت كله.", ways:"3 طرق للبدء:", s1:"قل مرحبا وشارك شوارعك المتقاطعة", s2:"انشر شيئا تحتاجه أو شيئا يمكنك تقديمه", s3:"اضغط استخدم موقعي لفتح خريطة البلوك", robots:"لا روبوتات. لا حظر خفي. الإيمان مرحب به. الاحترام مطلوب.", speak:"تحدث بحرية. أحب جارك." },
  hi: { pinned:"AI मेयर • पड़ोसियों के लिए पिन", privateBlock:"आपका निजी ब्लॉक • {area}", found:"🎉 आपने हमें ढूंढ लिया। आपके निजी ब्लॉक में स्वागत है।", space:"यह {area} के पास आपकी जगह है — पूरा इंटरनेट नहीं।", ways:"शुरू करने के 3 तरीके:", s1:"हाय कहें और अपनी क्रॉस स्ट्रीट साझा करें", s2:"एक चीज पोस्ट करें जो आपको चाहिए या दे सकते हैं", s3:"ब्लॉक मैप अनलॉक करने के लिए मेरी लोकेशन उपयोग करें टैप करें", robots:"कोई रोबोट नहीं। कोई शैडोबैन नहीं। विश्वास स्वागत। सम्मान आवश्यक।", speak:"खुलकर बोलें। अपने पड़ोसी से प्यार करें।" },
  it: { pinned:"Sindaco IA • Fissato per vicini", privateBlock:"Il tuo blocco privato • {area}", found:"🎉 Ci hai trovati. Benvenuto nel tuo blocco privato.", space:"Questo è il tuo spazio vicino a {area} — non tutto internet.", ways:"3 modi per iniziare:", s1:"Saluta e condividi le tue strade incrociate", s2:"Posta una cosa di cui hai bisogno o che puoi dare", s3:"Tocca Usa la mia posizione per sbloccare la Mappa del Blocco", robots:"Niente robot. Niente shadowban. Fede benvenuta. Rispetto richiesto.", speak:"Parla Liberamente. Ama il Tuo Vicino." },
  nl: { pinned:"AI Burgemeester • Vastgezet voor buren", privateBlock:"Jouw privéblok • {area}", found:"🎉 Je hebt ons gevonden. Welkom in je privéblok.", space:"Dit is jouw ruimte nabij {area} — niet het hele internet.", ways:"3 manieren om te beginnen:", s1:"Zeg hi en deel je kruisstraten", s2:"Post één ding dat je nodig hebt of kunt geven", s3:"Tik Gebruik mijn locatie om je Blokkaart te ontgrendelen", robots:"Geen robots. Geen shadowbans. Geloof welkom. Respect vereist.", speak:"Spreek Vrij. Hou van je Buur." },
  tl: { pinned:"AI Mayor • Naka-pin para sa kapitbahay", privateBlock:"Iyong pribadong block • {area}", found:"🎉 Nahanap mo kami. Welcome sa iyong pribadong block.", space:"Ito ang iyong space malapit sa {area} — hindi buong internet.", ways:"3 paraan para magsimula:", s1:"Bumati at i-share ang cross streets", s2:"Mag-post ng isang kailangan o maibibigay", s3:"I-tap ang Gamitin ang lokasyon para i-unlock ang Block Map", robots:"Walang robots. Walang shadowbans. Faith welcome. Respect required.", speak:"Magsalita nang Malaya. Mahalin ang Kapitbahay." },
  vi: { pinned:"Thị trưởng AI • Ghim cho hàng xóm", privateBlock:"Khối riêng của bạn • {area}", found:"🎉 Bạn đã tìm thấy chúng tôi. Chào mừng đến khối riêng.", space:"Đây là không gian của bạn gần {area} — không phải toàn internet.", ways:"3 cách để bắt đầu:", s1:"Chào và chia sẻ đường giao nhau", s2:"Đăng một thứ bạn cần hoặc có thể cho", s3:"Nhấn Dùng vị trí của tôi để mở khóa Bản đồ Khối", robots:"Không có robot. Không shadowban. Chào đón đức tin. Yêu cầu tôn trọng.", speak:"Nói Tự Do. Yêu Hàng Xóm." },
  th: { pinned:"นายก AI • ปักหมุดสำหรับเพื่อนบ้าน", privateBlock:"บล็อกส่วนตัวของคุณ • {area}", found:"🎉 คุณเจอเราแล้ว ยินดีต้อนรับสู่บล็อกส่วนตัว", space:"นี่คือพื้นที่ของคุณใกล้ {area} — ไม่ใช่ทั้งอินเทอร์เน็ต", ways:"3 วิธีเริ่มต้น:", s1:"ทักทายและแชร์ถนนตัดกัน", s2:"โพสต์สิ่งที่คุณต้องการหรือให้ได้", s3:"แตะใช้ตำแหน่งของฉันเพื่อปลดล็อกแผนที่บล็อก", robots:"ไม่มีโรบอท ไม่มีแบนเงา ยินดีต้อนรับศรัทธา ต้องเคารพ", speak:"พูดอย่างอิสระ รักเพื่อนบ้าน" },
  id: { pinned:"Walikota AI • Disematkan untuk tetangga", privateBlock:"Blok pribadi Anda • {area}", found:"🎉 Anda menemukan kami. Selamat datang di blok pribadi Anda.", space:"Ini ruang Anda di dekat {area} — bukan seluruh internet.", ways:"3 cara memulai:", s1:"Sapa dan bagikan persimpangan jalan", s2:"Posting satu hal yang Anda butuhkan atau bisa berikan", s3:"Ketuk Gunakan lokasi saya untuk membuka Peta Blok", robots:"Tanpa robot. Tanpa shadowban. Iman diterima. Hormat diperlukan.", speak:"Berbicaralah Bebas. Cintai Tetanggamu." },
  tr: { pinned:"AI Başkan • Komşular için sabitlendi", privateBlock:"Özel bloğunuz • {area}", found:"🎉 Bizi buldunuz. Özel bloğunuza hoş geldiniz.", space:"Burası {area} yakınındaki alanınız — tüm internet değil.", ways:"Başlamanın 3 yolu:", s1:"Merhaba deyin ve kesişen sokakları paylaşın", s2:"İhtiyacınız olan veya verebileceğiniz bir şey paylaşın", s3:"Blok Haritasını açmak için Konumumu Kullan'a dokunun", robots:"Robot yok. Gölge yasak yok. İnanç hoş. Saygı şart.", speak:"Özgürce Konuş. Komşunu Sev." },
  pl: { pinned:"Burmistrz AI • Przypięte dla sąsiadów", privateBlock:"Twój prywatny blok • {area}", found:"🎉 Znalazłeś nas. Witamy w Twoim prywatnym bloku.", space:"To Twoja przestrzeń w pobliżu {area} — nie cały internet.", ways:"3 sposoby na start:", s1:"Przywitaj się i udostępnij skrzyżowania", s2:"Opublikuj jedną rzecz której potrzebujesz lub możesz dać", s3:"Dotknij Użyj mojej lokalizacji aby odblokować Mapę Bloku", robots:"Bez robotów. Bez shadowbanów. Wiara mile widziana. Szacunek wymagany.", speak:"Mów Swobodnie. Kochaj Sąsiada." },
  uk: { pinned:"ШІ Мер • Закріплено для сусідів", privateBlock:"Ваш приватний блок • {area}", found:"🎉 Ви нас знайшли. Ласкаво просимо у ваш приватний блок.", space:"Це ваш простір біля {area} — не весь інтернет.", ways:"3 способи почати:", s1:"Привітайтесь і поділіться перехрестями", s2:"Опублікуйте те, що вам потрібно або можете дати", s3:"Натисніть Використати моє місцезнаходження щоб розблокувати карту", robots:"Без роботів. Без тіньових банів. Віра вітається. Повага обов'язкова.", speak:"Говоріть Вільно. Любіть Сусіда." },
  el: { pinned:"Δήμαρχος AI • Καρφιτσωμένο για γείτονες", privateBlock:"Το ιδιωτικό σας block • {area}", found:"🎉 Μας βρήκατε. Καλώς ήρθατε στο ιδιωτικό σας block.", space:"Αυτός είναι ο χώρος σας κοντά στο {area} — όχι όλο το internet.", ways:"3 τρόποι να ξεκινήσετε:", s1:"Πείτε γεια και μοιραστείτε διασταυρώσεις", s2:"Αναρτήστε κάτι που χρειάζεστε ή μπορείτε να δώσετε", s3:"Πατήστε Χρήση τοποθεσίας για να ξεκλειδώσετε τον Χάρτη", robots:"Χωρίς ρομπότ. Χωρίς shadowbans. Πίστη ευπρόσδεκτη. Σεβασμός απαιτείται.", speak:"Μιλήστε Ελεύθερα. Αγαπήστε τον Γείτονα." },
  he: { pinned:"ראש עיר AI • נעוץ לשכנים", privateBlock:"הבלוק הפרטי שלך • {area}", found:"🎉 מצאת אותנו. ברוך הבא לבלוק הפרטי שלך.", space:"זה המרחב שלך ליד {area} — לא כל האינטרנט.", ways:"3 דרכים להתחיל:", s1:"תגיד שלום ושתף רחובות מצטלבים", s2:"פרסם דבר אחד שאתה צריך או יכול לתת", s3:"הקש השתמש במיקום שלי כדי לפתוח את מפת הבלוק", robots:"בלי רובוטים. בלי חסימות צל. אמונה ברוכה הבאה. כבוד נדרש.", speak:"דבר בחופשיות. אהוב את שכנך." },
  ro: { pinned:"Primar AI • Fixat pentru vecini", privateBlock:"Blocul tău privat • {area}", found:"🎉 Ne-ai găsit. Bine ai venit în blocul tău privat.", space:"Acesta este spațiul tău lângă {area} — nu tot internetul.", ways:"3 moduri de a începe:", s1:"Spune salut și împărtășește intersecțiile", s2:"Postează un lucru de care ai nevoie sau poți oferi", s3:"Apasă Folosește locația mea pentru a debloca Harta Blocului", robots:"Fără roboți. Fără shadowban. Credință binevenită. Respect obligatoriu.", speak:"Vorbește Liber. Iubește-ți Vecinul." },
  cs: { pinned:"Starosta AI • Připnuto pro sousedy", privateBlock:"Váš soukromý blok • {area}", found:"🎉 Našli jste nás. Vítejte ve vašem soukromém bloku.", space:"Toto je váš prostor poblíž {area} — ne celý internet.", ways:"3 způsoby jak začít:", s1:"Pozdravte a sdílejte křižovatky", s2:"Zveřejněte jednu věc kterou potřebujete nebo můžete dát", s3:"Klepněte na Použít mou polohu pro odemknutí Mapy Bloku", robots:"Žádní roboti. Žádné stínové bany. Víra vítána. Respekt vyžadován.", speak:"Mluvte Svobodně. Milujte Souseda." },
  hu: { pinned:"AI Polgármester • Szomszédoknak kitűzve", privateBlock:"Privát blokkod • {area}", found:"🎉 Megtaláltál minket. Üdv a privát blokkban.", space:"Ez a te tered {area} közelében — nem az egész internet.", ways:"3 mód a kezdéshez:", s1:"Köszönj és oszd meg a kereszteződéseket", s2:"Posztolj egy dolgot amire szükséged van vagy adni tudsz", s3:"Érintsd meg a Helyem használata a Blokk Térkép feloldásához", robots:"Nincsenek robotok. Nincs árnyék tiltás. Hit üdvözölve. Tisztelet kötelező.", speak:"Beszélj Szabadon. Szeresd Szomszédod." },
  fi: { pinned:"AI Pormestari • Naapureille kiinnitetty", privateBlock:"Yksityinen blokkisi • {area}", found:"🎉 Löysit meidät. Tervetuloa yksityiseen blokkiisi.", space:"Tämä on tilasi lähellä {area} — ei koko internet.", ways:"3 tapaa aloittaa:", s1:"Sano hei ja jaa risteykset", s2:"Julkaise yksi asia jota tarvitset tai voit antaa", s3:"Napauta Käytä sijaintiani avataksesi Blokki-kartan", robots:"Ei robotteja. Ei varjobanneja. Usko tervetullut. Kunnioitus vaaditaan.", speak:"Puhu Vapaasti. Rakasta Naapuriasi." },
  no: { pinned:"AI Ordfører • Festet for naboer", privateBlock:"Din private blokk • {area}", found:"🎉 Du fant oss. Velkommen til din private blokk.", space:"Dette er ditt område nær {area} — ikke hele internett.", ways:"3 måter å starte på:", s1:"Si hei og del kryssgatene", s2:"Legg ut en ting du trenger eller kan gi", s3:"Trykk Bruk posisjonen min for å låse opp Blokkkartet", robots:"Ingen roboter. Ingen skyggeforbud. Tro velkommen. Respekt kreves.", speak:"Snakk Fritt. Elsk Naboen Din." },
  da: { pinned:"AI Borgmester • Fastgjort til naboer", privateBlock:"Din private blok • {area}", found:"🎉 Du fandt os. Velkommen til din private blok.", space:"Dette er dit rum nær {area} — ikke hele internettet.", ways:"3 måder at starte på:", s1:"Sig hej og del dine krydsgader", s2:"Slå én ting op du har brug for eller kan give", s3:"Tryk Brug min placering for at låse op for Blokkortet", robots:"Ingen robotter. Ingen skyggeforbud. Tro velkommen. Respekt påkrævet.", speak:"Tal Frit. Elsk Din Nabo." },
  bg: { pinned:"Кмет AI • Закачено за съседи", privateBlock:"Вашият частен блок • {area}", found:"🎉 Намерихте ни. Добре дошли във вашия частен блок.", space:"Това е вашето пространство близо до {area} — не целият интернет.", ways:"3 начина да започнете:", s1:"Кажете здравей и споделете кръстовища", s2:"Публикувайте едно нещо от което се нуждаете или можете да дадете", s3:"Докоснете Използвай местоположението ми за да отключите картата", robots:"Без роботи. Без скрити банове. Вярата добре дошла. Уважение изисква.", speak:"Говорете Свободно. Обичайте Съседа." },
  hr: { pinned:"Gradonačelnik AI • Prikvačeno za susjede", privateBlock:"Vaš privatni blok • {area}", found:"🎉 Pronašli ste nas. Dobrodošli u vaš privatni blok.", space:"Ovo je vaš prostor blizu {area} — ne cijeli internet.", ways:"3 načina za početak:", s1:"Recite bok i podijelite križanja", s2:"Objavite jednu stvar koju trebate ili možete dati", s3:"Dodirnite Koristi moju lokaciju za otključavanje karte bloka", robots:"Bez robota. Bez shadowbanova. Vjera dobrodošla. Poštovanje obavezno.", speak:"Govorite Slobodno. Volite Susjeda." },
  sr: { pinned:"Градоначелник AI • Закачено за комшије", privateBlock:"Ваш приватни блок • {area}", found:"🎉 Пронашли сте нас. Добродошли у ваш приватни блок.", space:"Ово је ваш простор близу {area} — не цео интернет.", ways:"3 начина за почетак:", s1:"Реците здраво и поделите раскрснице", s2:"Објавите једну ствар која вам треба или можете дати", s3:"Додирните Користи моју локацију да откључате мапу блока", robots:"Без робота. Без сенки бана. Вера добродошла. Поштовање обавезно.", speak:"Говорите Слободно. Волите Комшију." },
  sk: { pinned:"Starosta AI • Pripnuté pre susedov", privateBlock:"Váš súkromný blok • {area}", found:"🎉 Našli ste nás. Vitajte vo vašom súkromnom bloku.", space:"Toto je váš priestor blízko {area} — nie celý internet.", ways:"3 spôsoby ako začať:", s1:"Pozdravte a zdieľajte križovatky", s2:"Zverejnite jednu vec ktorú potrebujete alebo môžete dať", s3:"Klepnite na Použiť moju polohu pre odomknutie Mapy Bloku", robots:"Žiadni roboti. Žiadne tieňové bany. Viera vítaná. Rešpekt vyžadovaný.", speak:"Hovorte Slobodne. Milujte Suseda." },
  sl: { pinned:"Župan AI • Pripeto za sosede", privateBlock:"Vaš zasebni blok • {area}", found:"🎉 Našli ste nas. Dobrodošli v vašem zasebnem bloku.", space:"To je vaš prostor blizu {area} — ne cel internet.", ways:"3 načini za začetek:", s1:"Recite živjo in delite križišča", s2:"Objavite eno stvar ki jo potrebujete ali lahko daste", s3:"Dotaknite se Uporabi mojo lokacijo za odklepanje zemljevida", robots:"Brez robotov. Brez senc. Vera dobrodošla. Spoštovanje zahtevano.", speak:"Govorite Svobodno. Ljubite Soseda." },
  et: { pinned:"Linnapea AI • Naabrite jaoks kinnitatud", privateBlock:"Teie privaatne blokk • {area}", found:"🎉 Leidsite meid. Tere tulemast teie privaatsesse blokki.", space:"See on teie ruum lähedal {area} — mitte kogu internet.", ways:"3 viisi alustamiseks:", s1:"Öelge tere ja jagage ristmikke", s2:"Postitage üks asi mida vajate või saate anda", s3:"Puudutage Kasuta minu asukohta Bloki kaardi avamiseks", robots:"Ei roboteid. Ei varjubanne. Usk teretulnud. Austus nõutud.", speak:"Rääkige Vabalt. Armastage Naabrit." },
  lv: { pinned:"Mērs AI • Piesprausts kaimiņiem", privateBlock:"Jūsu privātais bloks • {area}", found:"🎉 Jūs mūs atradāt. Laipni lūdzam jūsu privātajā blokā.", space:"Tā ir jūsu telpa pie {area} — ne viss internets.", ways:"3 veidi kā sākt:", s1:"Pasakiet sveiki un dalieties ar krustojumiem", s2:"Publicējiet vienu lietu kas jums vajadzīga vai ko varat dot", s3:"Pieskarieties Izmantot manu atrašanās vietu lai atbloķētu karti", robots:"Nav robotu. Nav ēnu aizliegumu. Ticība laipni gaidīta. Cieņa nepieciešama.", speak:"Runājiet Brīvi. Mīliet Kaimiņu." },
  lt: { pinned:"Meras AI • Prisegta kaimynams", privateBlock:"Jūsų privatus blokas • {area}", found:"🎉 Radote mus. Sveiki atvykę į savo privatų bloką.", space:"Tai jūsų erdvė šalia {area} — ne visas internetas.", ways:"3 būdai pradėti:", s1:"Pasakykite labas ir pasidalinkite sankryžomis", s2:"Paskelbkite vieną dalyką kurio jums reikia ar galite duoti", s3:"Palieskite Naudoti mano vietą kad atrakintumėte Bloko žemėlapį", robots:"Be robotų. Be šešėlinių draudimų. Tikėjimas laukiamas. Pagarba privaloma.", speak:"Kalbėkite Laisvai. Mylėkite Kaimyną." },
  be: { pinned:"Мэр ШІ • Замацавана для суседзяў", privateBlock:"Ваш прыватны блок • {area}", found:"🎉 Вы нас знайшлі. Сардэчна запрашаем у ваш прыватны блок.", space:"Гэта ваша прастора каля {area} — не ўвесь інтэрнэт.", ways:"3 спосабы пачаць:", s1:"Павітайцеся і падзяліцеся скрыжаваннямі", s2:"Апублікуйце адну рэч якая вам патрэбна або можаце даць", s3:"Націсніце Выкарыстоўваць маё месцазнаходжанне каб разблакаваць карту", robots:"Без робатаў. Без ценявых банаў. Вера вітаецца. Павага абавязковая.", speak:"Гаварыце Свабодна. Любіце Суседа." },
  ka: { pinned:"AI მერი • მეზობლებისთვის ჩამაგრებული", privateBlock:"თქვენი პირადი ბლოკი • {area}", found:"🎉 გვიპოვეთ. კეთილი იყოს თქვენი მობრძანება თქვენს პირად ბლოკში.", space:"ეს თქვენი სივრცეა {area}-თან ახლოს — არა მთელი ინტერნეტი.", ways:"დაწყების 3 გზა:", s1:"თქვი გამარჯობა და გააზიარე კვეთები", s2:" გამოაქვეყნე ერთი რამ რაც გჭირდება ან შეგიძლია მისცე", s3:" შეეხე გამოიყენე ჩემი მდებარეობა ბლოკის რუქის განსაბლოკად", robots:"რობოტები არა. ჩრდილოვანი ბანები არა. რწმენა მისასალმებელი. პატივისცემა საჭირო.", speak:"ილაპარაკე თავისუფლად. შეიყვარე მეზობელი." },
  hy: { pinned:"AI Քաղաքապետ • Ամրացված հարևանների համար", privateBlock:"Ձեր մասնավոր բլոկը • {area}", found:"🎉 Դուք գտաք մեզ: Բարի գալուստ ձեր մասնավոր բլոկ:", space:"Սա ձեր տարածքն է {area}-ի մոտ — ոչ ամբողջ ինտերնետը:", ways:"Սկսելու 3 եղանակ:", s1:"Ասեք բարև և կիսվեք խաչմերուկներով", s2:"Հրապարակեք մի բան որը ձեզ անհրաժեշտ է կամ կարող եք տալ", s3:"Հպեք Օգտագործել իմ գտնվելու վայրը Բլոկի քարտեզը բացելու համար", robots:"Ոչ մի ռոբոտ: Ոչ մի ստվերային արգելք: Հավատը ողջունելի է: Հարգանքը պարտադիր է:", speak:"Խոսեք Ազատ: Սիրեք Հարևանին:" },
  az: { pinned:"AI Bələdiyyə • Qonşular üçün bərkidilib", privateBlock:"Şəxsi blokunuz • {area}", found:"🎉 Bizi tapdınız. Şəxsi blokunuza xoş gəlmisiniz.", space:"Bu {area} yaxınlığındakı məkanınızdır — bütün internet deyil.", ways:"Başlamağın 3 yolu:", s1:"Salam deyin və kəsişmələri paylaşın", s2:"Ehtiyacınız olan və ya verə biləcəyiniz bir şey paylaşın", s3:"Blok Xəritəsini açmaq üçün Məkanımdan istifadə et toxunun", robots:"Robot yoxdur. Kölgə qadağası yoxdur. İnanc xoşdur. Hörmət tələb olunur.", speak:"Sərbəst Danışın. Qonşunu Sevin." },
  kk: { pinned:"AI Әкім • Көршілер үшін бекітілген", privateBlock:"Жеке блогыңыз • {area}", found:"🎉 Сіз бізді таптыңыз. Жеке блогыңызға қош келдіңіз.", space:"Бұл {area} жанындағы сіздің кеңістігіңіз — бүкіл интернет емес.", ways:"Бастаудың 3 жолы:", s1:"Сәлем айтып, қиылыстарды бөлісіңіз", s2:"Қажет нәрсені немесе бере алатын нәрсені жариялаңыз", s3:"Блок картасын ашу үшін Менің орнымды пайдалану түймесін басыңыз", robots:"Роботтар жоқ. Көлеңкелі тыйымдар жоқ. Сенім қош келеді. Құрмет қажет.", speak:"Еркін Сөйле. Көршіңді Сүй." },
  ky: { pinned:"AI Аким • Кошуналар үчүн бекитилген", privateBlock:"Жеке блогуңуз • {area}", found:"🎉 Сиз бизди таптыңыз. Жеке блогуңузга кош келиңиз.", space:"Бул {area} жанындагы сиздин мейкиндигиңиз — бүт интернет эмес.", ways:"Баштоонун 3 жолу:", s1:"Салам айтып, кесилиштерди бөлүшүңүз", s2:"Керектүү же бере ала турган нерсени жарыялаңыз", s3:"Блок картасын ачуу үчүн Менин жайгашкан жеримди колдонуу басыңыз", robots:"Роботтор жок. Көлөкө тыюулар жок. Ишеним кош келиңиз. Урмат талап кылынат.", speak:"Эркин Сүйлө. Кошунаңды Сүй." },
  uz: { pinned:"AI Hokim • Qo'shnilar uchun mahkamlangan", privateBlock:"Shaxsiy blokingiz • {area}", found:"🎉 Siz bizni topdingiz. Shaxsiy blokingizga xush kelibsiz.", space:"Bu {area} yaqinidagi joyingiz — butun internet emas.", ways:"Boshlashning 3 usuli:", s1:"Salom ayting va chorrahalarni ulashing", s2:"Kerakli yoki bera oladigan narsani joylang", s3:"Blok Xaritasini ochish uchun Joylashuvimdan foydalanish tugmasini bosing", robots:"Robotlar yo'q. Soya taqiqlari yo'q. Imon xush kelibsiz. Hurmat talab qilinadi.", speak:"Erkin Gapiring. Qo'shningizni Seving." },
  tg: { pinned:"AI Шаҳрдор • Барои ҳамсояҳо часпонида шудааст", privateBlock:"Блоки хусусии шумо • {area}", found:"🎉 Шумо моро ёфтед. Ба блоки хусусии худ хуш омадед.", space:"Ин фазои шумо дар наздикии {area} аст — на тамоми интернет.", ways:"3 роҳи оғоз:", s1:"Салом гӯед ва чорроҳаҳоро мубодила кунед", s2:"Як чизеро ки ба шумо лозим аст ё дода метавонед нашр кунед", s3:"Барои кушодани Харитаи Блок Ҷойгиршавии маро истифода баред-ро пахш кунед", robots:"Робот нест. Манъи сояафкан нест. Имон хуш омадед. Эҳтиром зарур аст.", speak:"Озодона Сухан Гӯед. Ҳамсояатонро Дӯст Доред." },
  mn: { pinned:"AI Дарга • Хөршүүдэд зориулан бэхэлсэн", privateBlock:"Таны хувийн блок • {area}", found:"🎉 Та биднийг оллоо. Хувийн блокдоо тавтай морилно уу.", space:"Энэ бол {area} ойролцоох таны орон зай — бүх интернет биш.", ways:"Эхлэх 3 арга:", s1:"Сайн уу гэж хэлээд уулзваруудыг хуваалц", s2:"Хэрэгтэй эсвэл өгч чадах нэг зүйлээ нийтэл", s3:"Блок газрын зургийг нээхийн тулд Миний байршлыг ашиглах дээр дар", robots:"Робот байхгүй. Сүүдэр хориг байхгүй. Итгэл тавтай морилно уу. Хүндэтгэл шаардлагатай.", speak:"Чөлөөтэй Ярь. Хөршөө Хайрла." },
  km: { pinned:"អភិបាល AI • បានខ្ទាស់សម្រាប់អ្នកជិតខាង", privateBlock:"ប្លុកឯកជនរបស់អ្នក • {area}", found:"🎉 អ្នកបានរកឃើញយើង។ សូមស្វាគមន៍មកកាន់ប្លុកឯកជនរបស់អ្នក។", space:"នេះជាកន្លែងរបស់អ្នកនៅជិត {area} — មិនមែនអ៊ីនធឺណិតទាំងមូលទេ។", ways:"3 វិធីដើម្បីចាប់ផ្តើម:", s1:"និយាយសួស្តីនិងចែករំលែកផ្លូវប្រសព្វ", s2:"បង្ហោះរបស់មួយដែលអ្នកត្រូវការឬអាចផ្តល់ឱ្យ", s3:"ចុចប្រើទីតាំងរបស់ខ្ញុំដើម្បីដោះសោផែនទីប្លុក", robots:"គ្មានរ៉ូបូត។ គ្មានការហាមឃាត់ស្រមោល។ សូមស្វាគមន៍ជំនឿ។ ត្រូវការការគោរព។", speak:"និយាយដោយសេរី។ ស្រឡាញ់អ្នកជិតខាងរបស់អ្នក។" },
  lo: { pinned:"ເຈົ້າເມືອງ AI • ປັກສຳລັບເພື່ອນບ້ານ", privateBlock:"ບລັອກສ່ວນຕົວຂອງເຈົ້າ • {area}", found:"🎉 ເຈົ້າພົບພວກເຮົາແລ້ວ ຍິນດີຕ້ອນຮັບສູ່ບລັອກສ່ວນຕົວຂອງເຈົ້າ", space:"ນີ້ແມ່ນພື້ນທີ່ຂອງເຈົ້າໃກ້ {area} — ບໍ່ແມ່ນອິນເຕີເນັດທັງໝົດ", ways:"3 ວິທີເລີ່ມ:", s1:"ທັກທາຍ ແລະ ແບ່ງປັນທາງຕັດ", s2:"ໂພສສິ່ງທີ່ເຈົ້າຕ້ອງການ ຫຼື ໃຫ້ໄດ້", s3:"ແຕະໃຊ້ຕຳແໜ່ງຂອງຂ້ອຍເພື່ອປົດລັອກແຜນທີ່ບລັອກ", robots:"ບໍ່ມີໂຣບອດ ບໍ່ມີແບນເງົາ ຍິນດີຕ້ອນຮັບຄວາມເຊື່ອ ຕ້ອງການເຄົາລົບ", speak:"ເວົ້າຢ່າງອິດສະຫຼະ ຮັກເພື່ອນບ້ານ" },
  my: { pinned:"AI မြို့တော်ဝန် • အိမ်နီးချင်းများအတွက် တွဲထားသည်", privateBlock:"သင့်ကိုယ်ပိုင် ဘလောက် • {area}", found:"🎉 သင်ကျွန်ုပ်တို့ကို တွေ့ပြီ။ သင့်ကိုယ်ပိုင်ဘလောက်မှ ကြိုဆိုပါတယ်။", space:"၎င်းသည် {area} အနီးရှိ သင့်နေရာ — အင်တာနက်တစ်ခုလုံး မဟုတ်ပါ။", ways:"စတင်ရန် နည်းလမ်း ၃ ခု:", s1:"နှုတ်ဆက်ပြီး လမ်းဆုံများကို မျှဝေပါ", s2:"လိုအပ်သော သို့မဟုတ် ပေးနိုင်သော အရာတစ်ခု တင်ပါ", s3:"Block Map ကိုဖွင့်ရန် ကျွန်ုပ်၏တည်နေရာကို သုံးပါ ကိုနှိပ်ပါ", robots:"စက်ရုပ်မရှိ။ Shadowban မရှိ။ ယုံကြည်မှု ကြိုဆိုသည်။ လေးစားမှု လိုအပ်သည်။", speak:"လွတ်လပ်စွာ ပြောပါ။ သင့်အိမ်နီးချင်းကို ချစ်ပါ။" },
  bn: { pinned:"AI মেয়র • প্রতিবেশীদের জন্য পিন করা", privateBlock:"আপনার ব্যক্তিগত ব্লক • {area}", found:"🎉 আপনি আমাদের খুঁজে পেয়েছেন। আপনার ব্যক্তিগত ব্লকে স্বাগতম।", space:"এটি {area} এর কাছে আপনার জায়গা — পুরো ইন্টারনেট নয়।", ways:"শুরু করার ৩টি উপায়:", s1:"হাই বলুন এবং আপনার ক্রস স্ট্রিট শেয়ার করুন", s2:"একটি জিনিস পোস্ট করুন যা আপনার প্রয়োজন বা দিতে পারেন", s3:"ব্লক ম্যাপ আনলক করতে আমার অবস্থান ব্যবহার করুন ট্যাপ করুন", robots:"কোনো রোবট নেই। কোনো শ্যাডোব্যান নেই। বিশ্বাস স্বাগত। সম্মান প্রয়োজন।", speak:"মুক্তভাবে কথা বলুন। আপনার প্রতিবেশীকে ভালোবাসুন।" },
  ms: { pinned:"Datuk Bandar AI • Disemat untuk jiran", privateBlock:"Blok peribadi anda • {area}", found:"🎉 Anda jumpa kami. Selamat datang ke blok peribadi anda.", space:"Ini ruang anda berhampiran {area} — bukan seluruh internet.", ways:"3 cara untuk bermula:", s1:"Katakan hi dan kongsi persimpangan jalan", s2:"Siarkan satu perkara yang anda perlukan atau boleh berikan", s3:"Ketik Gunakan lokasi saya untuk membuka kunci Peta Blok", robots:"Tiada robot. Tiada shadowban. Kepercayaan dialu-alukan. Hormat diperlukan.", speak:"Bercakap Bebas. Sayangi Jiran Anda." },
  fa: { pinned:"شهردار AI • سنجاق شده برای همسایگان", privateBlock:"بلوک خصوصی شما • {area}", found:"🎉 ما را پیدا کردید. به بلوک خصوصی خود خوش آمدید.", space:"این فضای شما نزدیک {area} است — نه کل اینترنت.", ways:"۳ راه برای شروع:", s1:"سلام کنید و تقاطع‌های خود را به اشتراک بگذارید", s2:"یک چیز که نیاز دارید یا می‌توانید بدهید پست کنید", s3:"برای باز کردن نقشه بلوک، روی استفاده از موقعیت من ضربه بزنید", robots:"بدون ربات. بدون شدوبن. ایمان خوش آمد. احترام لازم است.", speak:"آزادانه صحبت کنید. همسایه خود را دوست داشته باشید." },
  ur: { pinned:"AI میئر • پڑوسیوں کے لیے پن کیا گیا", privateBlock:"آپ کا نجی بلاک • {area}", found:"🎉 آپ نے ہمیں ڈھونڈ لیا۔ آپ کے نجی بلاک میں خوش آمدید۔", space:"یہ {area} کے قریب آپ کی جگہ ہے — پورا انٹرنیٹ نہیں۔", ways:"شروع کرنے کے 3 طریقے:", s1:"ہیلو کہیں اور اپنی کراس سٹریٹس شیئر کریں", s2:"ایک چیز پوسٹ کریں جس کی آپ کو ضرورت ہے یا دے سکتے ہیں", s3:"بلاک میپ انلاک کرنے کے لیے میری لوکیشن استعمال کریں پر ٹیپ کریں", robots:"کوئی روبوٹ نہیں۔ کوئی شیڈو بین نہیں۔ ایمان خوش آمدید۔ احترام ضروری۔", speak:"آزادانہ بولیں۔ اپنے پڑوسی سے پیار کریں۔" },
}

export default function WelcomePost() {
  const { zip, city } = useLocation()
  const { language } = useLanguage()
  const d = D[language] || D.en
  const area = city &&!city.includes('Manado') &&!city.includes('Sulawesi')? city : (zip && zip!== 'GLOBAL'? zip : 'your block')
  const areaLabel = area

  return (
    <div className="bg-white/[0.08] backdrop-blur-2xl rounded-2xl p-6 border border-white/15 shadow-2xl relative overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-r from-amber-500/10 to-orange-500/10 pointer-events-none" />
      <div className="relative">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-full bg-gradient-to-br from-amber-300 to-orange-500 flex items-center justify-center font-black text-black shadow">AI</div>
          <div>
            <p className="font-black text-white/90 text-xs tracking-wide">{d.pinned}</p>
            <p className="text-xs font-bold text-white/50">{d.privateBlock.replace('{area}', areaLabel)}</p>
          </div>
        </div>
        <h3 className="text-base font-black text-white leading-snug mb-2">{d.found}</h3>
        <p className="text-sm text-white/80 mb-4">{d.space.replace('{area}', areaLabel)}</p>
        <p className="font-black text-white text-sm mb-2">{d.ways}</p>
        <ol className="list-decimal list-inside space-y-1 text-white/80 text-sm font-semibold mb-4">
          <li>{d.s1}</li>
          <li>{d.s2}</li>
          <li>{d.s3}</li>
        </ol>
        <p className="text-xs font-bold text-white/40">{d.robots}</p>
        <p className="mt-3 font-black text-amber-300 tracking-widest text-xs">{d.speak}</p>
      </div>
    </div>
  )
}
