'use client'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useLanguage } from '@/lib/language-context'

const D: Record<string, any> = {
  en: { title:"Privacy & data", desc:"Under GDPR and CCPA you can export your data or delete your account at any time.", export:"Export all my data (JSON)", delTitle:"Delete my account", delDesc:"We’ll erase your account, posts, likes, and profile within 30 days. Some records may be kept longer if required by law. Type DELETE to confirm.", ph:"Type DELETE", req:"Request deletion", cookie:"Cookie settings", close:"Close", down:"Your data has been downloaded as JSON.", delRec:"Deletion request received. Your account and data will be erased within 30 days.", failExp:"Export failed", failReq:"Request failed" },
  es: { title:"Privacidad y datos", desc:"Bajo GDPR y CCPA puedes exportar tus datos o eliminar tu cuenta en cualquier momento.", export:"Exportar todos mis datos (JSON)", delTitle:"Eliminar mi cuenta", delDesc:"Borraremos tu cuenta, posts, likes y perfil en 30 días. Algunos registros pueden conservarse más si la ley lo requiere. Escribe DELETE.", ph:"Escribe DELETE", req:"Solicitar eliminación", cookie:"Ajustes de cookies", close:"Cerrar", down:"Tus datos se han descargado como JSON.", delRec:"Solicitud recibida. Tu cuenta se borrará en 30 días.", failExp:"Exportación falló", failReq:"Solicitud falló" },
  fr: { title:"Confidentialité & données", desc:"Sous GDPR et CCPA vous pouvez exporter vos données ou supprimer votre compte.", export:"Exporter toutes mes données (JSON)", delTitle:"Supprimer mon compte", delDesc:"Nous effacerons votre compte en 30 jours. Certains dossiers peuvent être conservés plus longtemps si requis par la loi. Tapez DELETE.", ph:"Tapez DELETE", req:"Demander suppression", cookie:"Paramètres cookies", close:"Fermer", down:"Vos données ont été téléchargées.", delRec:"Demande reçue. Votre compte sera effacé en 30 jours.", failExp:"Export échoué", failReq:"Demande échouée" },
  de: { title:"Datenschutz & Daten", desc:"Unter DSGVO und CCPA kannst du jederzeit Daten exportieren oder Konto löschen.", export:"Alle meine Daten exportieren (JSON)", delTitle:"Mein Konto löschen", delDesc:"Wir löschen dein Konto in 30 Tagen. Einige Aufzeichnungen können länger aufbewahrt werden. Tippe DELETE.", ph:"Tippe DELETE", req:"Löschung anfordern", cookie:"Cookie-Einstellungen", close:"Schließen", down:"Deine Daten wurden heruntergeladen.", delRec:"Löschanfrage erhalten. Konto wird in 30 Tagen gelöscht.", failExp:"Export fehlgeschlagen", failReq:"Anfrage fehlgeschlagen" },
  zh: { title:"隐私与数据", desc:"根据GDPR和CCPA，你可以随时导出数据或删除账户。", export:"导出我的所有数据 (JSON)", delTitle:"删除我的账户", delDesc:"我们将在30天内删除你的账户。某些记录可能因法律保留更久。输入DELETE。", ph:"输入 DELETE", req:"请求删除", cookie:"Cookie设置", close:"关闭", down:"你的数据已下载。", delRec:"已收到删除请求。30天内删除。", failExp:"导出失败", failReq:"请求失败" },
  ja: { title:"プライバシーとデータ", desc:"GDPR/CCPAの下でいつでもデータをエクスポートまたは削除できます。", export:"すべてのデータをエクスポート (JSON)", delTitle:"アカウントを削除", delDesc:"30日以内にアカウントを削除します。一部記録は法律で長く保持される場合があります。DELETEと入力。", ph:"DELETEと入力", req:"削除をリクエスト", cookie:"Cookie設定", close:"閉じる", down:"データがダウンロードされました。", delRec:"削除リクエストを受領。30日以内に削除。", failExp:"エクスポート失敗", failReq:"リクエスト失敗" },
  ko: { title:"개인정보 및 데이터", desc:"GDPR 및 CCPA에 따라 언제든지 데이터를 내보내거나 삭제할 수 있습니다。", export:"내 모든 데이터 내보내기 (JSON)", delTitle:"계정 삭제", delDesc:"30일 이내에 계정을 삭제합니다. 일부 기록은 더 오래 보관될 수 있습니다. DELETE 입력。", ph:"DELETE 입력", req:"삭제 요청", cookie:"쿠키 설정", close:"닫기", down:"데이터가 다운로드되었습니다。", delRec:"삭제 요청 접수。30일 이내 삭제。", failExp:"내보내기 실패", failReq:"요청 실패" },
  pt: { title:"Privacidade e dados", desc:"Sob GDPR e CCPA você pode exportar seus dados ou excluir sua conta.", export:"Exportar todos meus dados (JSON)", delTitle:"Excluir minha conta", delDesc:"Apagaremos sua conta em 30 dias. Alguns registros podem ser mantidos por lei. Digite DELETE.", ph:"Digite DELETE", req:"Solicitar exclusão", cookie:"Configurações de cookies", close:"Fechar", down:"Seus dados foram baixados.", delRec:"Pedido recebido. Conta será apagada em 30 dias.", failExp:"Exportação falhou", failReq:"Pedido falhou" },
  ru: { title:"Конфиденциальность и данные", desc:"По GDPR и CCPA вы можете экспортировать данные или удалить аккаунт.", export:"Экспортировать все данные (JSON)", delTitle:"Удалить аккаунт", delDesc:"Мы удалим аккаунт в течение 30 дней. Некоторые записи могут храниться дольше по закону. Введите DELETE.", ph:"Введите DELETE", req:"Запросить удаление", cookie:"Настройки cookies", close:"Закрыть", down:"Данные загружены.", delRec:"Запрос получен. Аккаунт будет удален за 30 дней.", failExp:"Экспорт не удался", failReq:"Запрос не удался" },
  ar: { title:"الخصوصية والبيانات", desc:"بموجب GDPR و CCPA يمكنك تصدير بياناتك أو حذف حسابك.", export:"تصدير جميع بياناتي (JSON)", delTitle:"حذف حسابي", delDesc:"سنحذف حسابك خلال 30 يوما. قد نحتفظ ببعض السجلات дольше حسب القانون. اكتب DELETE.", ph:"اكتب DELETE", req:"طلب الحذف", cookie:"إعدادات الكوكيز", close:"إغلاق", down:"تم تنزيل بياناتك.", delRec:"تم استلام الطلب. سيُحذف حسابك خلال 30 يوما.", failExp:"فشل التصدير", failReq:"فشل الطلب" },
  hi: { title:"गोपनीयता और डेटा", desc:"GDPR और CCPA के तहत आप डेटा निर्यात या खाता हटा सकते हैं।", export:"मेरा सारा डेटा निर्यात (JSON)", delTitle:"मेरा खाता हटाएं", delDesc:"हम 30 दिनों में खाता मिटा देंगे। कुछ रिकॉर्ड कानूनन дольше रखे जा सकते हैं। DELETE टाइप करें।", ph:"DELETE टाइप करें", req:"हटाने का अनुरोध", cookie:"कुकी सेटिंग्स", close:"बंद करें", down:"डेटा डाउनलोड हो गया।", delRec:"अनुरोध प्राप्त। 30 दिनों में खाता मिटेगा।", failExp:"निर्यात विफल", failReq:"अनुरोध विफल" },
  it: { title:"Privacy e dati", desc:"Sotto GDPR e CCPA puoi esportare i dati o eliminare l'account.", export:"Esporta tutti i miei dati (JSON)", delTitle:"Elimina il mio account", delDesc:"Cancelleremo il tuo account entro 30 giorni. Alcuni record possono essere conservati più a lungo per legge. Digita DELETE.", ph:"Digita DELETE", req:"Richiedi eliminazione", cookie:"Impostazioni cookie", close:"Chiudi", down:"Dati scaricati come JSON.", delRec:"Richiesta ricevuta. Account cancellato entro 30 giorni.", failExp:"Esportazione fallita", failReq:"Richiesta fallita" },
  nl: { title:"Privacy & data", desc:"Onder GDPR en CCPA kun je je data exporteren of account verwijderen.", export:"Exporteer al mijn data (JSON)", delTitle:"Mijn account verwijderen", delDesc:"We wissen je account binnen 30 dagen. Sommige records langer indien wettelijk vereist. Typ DELETE.", ph:"Typ DELETE", req:"Verwijdering aanvragen", cookie:"Cookie-instellingen", close:"Sluiten", down:"Je data is gedownload.", delRec:"Verzoek ontvangen. Account wordt binnen 30 dagen gewist.", failExp:"Export mislukt", failReq:"Verzoek mislukt" },
  tl: { title:"Privacy at data", desc:"Sa ilalim ng GDPR at CCPA maaari mong i-export data o burahin account.", export:"I-export lahat ng data ko (JSON)", delTitle:"Burahin account ko", delDesc:"Buburahin account sa loob ng 30 araw. Ilang records mas matagal kung required by law. I-type DELETE.", ph:"I-type DELETE", req:"Hilingin pagbura", cookie:"Cookie settings", close:"Isara", down:"Na-download ang data bilang JSON.", delRec:"Natanggap ang request. Buburahin sa 30 araw.", failExp:"Export failed", failReq:"Request failed" },
  bn: { title:"গোপনীয়তা ও ডেটা", desc:"GDPR এবং CCPA অনুযায়ী আপনি ডেটা এক্সপোর্ট বা অ্যাকাউন্ট মুছতে পারেন।", export:"আমার সব ডেটা এক্সপোর্ট (JSON)", delTitle:"আমার অ্যাকাউন্ট মুছুন", delDesc:"আমরা 30 দিনের মধ্যে অ্যাকাউন্ট মুছে ফেলব। আইন অনুযায়ী কিছু রেকর্ড বেশি রাখা হতে পারে। DELETE টাইপ করুন।", ph:"DELETE টাইপ করুন", req:"মোছার অনুরোধ", cookie:"কুকি সেটিংস", close:"বন্ধ করুন", down:"ডেটা JSON হিসাবে ডাউনলোড হয়েছে।", delRec:"অনুরোধ পাওয়া গেছে। 30 দিনে মুছে ফেলা হবে।", failExp:"এক্সপোর্ট ব্যর্থ", failReq:"অনুরোধ ব্যর্থ" },
  id: { title:"Privasi & data", desc:"Di bawah GDPR dan CCPA Anda dapat mengekspor data atau menghapus akun.", export:"Ekspor semua data saya (JSON)", delTitle:"Hapus akun saya", delDesc:"Kami akan menghapus akun dalam 30 hari. Beberapa catatan mungkin disimpan lebih lama jika hukum mengharuskan. Ketik DELETE.", ph:"Ketik DELETE", req:"Minta penghapusan", cookie:"Pengaturan cookie", close:"Tutup", down:"Data Anda telah diunduh.", delRec:"Permintaan diterima. Akun akan dihapus dalam 30 hari.", failExp:"Ekspor gagal", failReq:"Permintaan gagal" },
  vi: { title:"Quyền riêng tư & dữ liệu", desc:"Theo GDPR và CCPA bạn có thể xuất dữ liệu hoặc xóa tài khoản.", export:"Xuất tất cả dữ liệu (JSON)", delTitle:"Xóa tài khoản", delDesc:"Chúng tôi sẽ xóa tài khoản trong 30 ngày. Một số bản ghi có thể giữ lâu hơn nếu luật yêu cầu. Nhập DELETE.", ph:"Nhập DELETE", req:"Yêu cầu xóa", cookie:"Cài đặt cookie", close:"Đóng", down:"Dữ liệu đã tải xuống.", delRec:"Đã nhận yêu cầu. Tài khoản sẽ bị xóa trong 30 ngày.", failExp:"Xuất thất bại", failReq:"Yêu cầu thất bại" },
  th: { title:"ความเป็นส่วนตัวและข้อมูล", desc:"ภายใต้ GDPR และ CCPA คุณสามารถส่งออกข้อมูลหรือลบบัญชีได้", export:"ส่งออกข้อมูลทั้งหมด (JSON)", delTitle:"ลบบัญชีของฉัน", delDesc:"เราจะลบบัญชีภายใน 30 วัน บันทึกบางอย่างอาจเก็บนานกว่าหากกฎหมายกำหนด พิมพ์ DELETE", ph:"พิมพ์ DELETE", req:"ขอลบ", cookie:"ตั้งค่าคุกกี้", close:"ปิด", down:"ดาวน์โหลดข้อมูลแล้ว", delRec:"ได้รับคำขอลบแล้ว บัญชีจะถูกลบภายใน 30 วัน", failExp:"ส่งออกไม่สำเร็จ", failReq:"คำขอไม่สำเร็จ" },
  sv: { title:"Integritet & data", desc:"Under GDPR och CCPA kan du exportera data eller radera konto.", export:"Exportera all min data (JSON)", delTitle:"Radera mitt konto", delDesc:"Vi raderar kontot inom 30 dagar. Vissa poster kan sparas längre om lagen kräver. Skriv DELETE.", ph:"Skriv DELETE", req:"Begär radering", cookie:"Cookie-inställningar", close:"Stäng", down:"Din data har laddats ner.", delRec:"Begäran mottagen. Kontot raderas inom 30 dagar.", failExp:"Export misslyckades", failReq:"Begäran misslyckades" },
  pl: { title:"Prywatność i dane", desc:"Zgodnie z RODO i CCPA możesz wyeksportować dane lub usunąć konto.", export:"Eksportuj wszystkie dane (JSON)", delTitle:"Usuń moje konto", delDesc:"Usuniemy konto w ciągu 30 dni. Niektóre rekordy mogą być dłużej jeśli prawo wymaga. Wpisz DELETE.", ph:"Wpisz DELETE", req:"Żądaj usunięcia", cookie:"Ustawienia cookies", close:"Zamknij", down:"Dane pobrane jako JSON.", delRec:"Żądanie otrzymane. Konto zostanie usunięte w 30 dni.", failExp:"Eksport nieudany", failReq:"Żądanie nieudane" },
  tr: { title:"Gizlilik ve veri", desc:"GDPR ve CCPA kapsamında verilerinizi dışa aktarabilir veya hesabı silebilirsiniz.", export:"Tüm verilerimi dışa aktar (JSON)", delTitle:"Hesabımı sil", delDesc:"Hesabınızı 30 gün içinde sileceğiz. Bazı kayıtlar yasaya göre daha uzun tutulabilir. DELETE yazın.", ph:"DELETE yazın", req:"Silme talep et", cookie:"Çerez ayarları", close:"Kapat", down:"Verileriniz JSON olarak indirildi.", delRec:"Talep alındı. Hesap 30 gün içinde silinecek.", failExp:"Dışa aktarma başarısız", failReq:"Talep başarısız" },
  uk: { title:"Конфіденційність і дані", desc:"За GDPR та CCPA ви можете експортувати дані або видалити акаунт.", export:"Експортувати всі дані (JSON)", delTitle:"Видалити акаунт", delDesc:"Ми видалимо акаунт за 30 днів. Деякі записи можуть зберігатися довше за законом. Введіть DELETE.", ph:"Введіть DELETE", req:"Запросити видалення", cookie:"Налаштування cookies", close:"Закрити", down:"Дані завантажено як JSON.", delRec:"Запит отримано. Акаунт буде видалено за 30 днів.", failExp:"Експорт не вдався", failReq:"Запит не вдався" },
  el: { title:"Απόρρητο & δεδομένα", desc:"Υπό GDPR και CCPA μπορείτε να εξάγετε δεδομένα ή να διαγράψετε λογαριασμό.", export:"Εξαγωγή όλων των δεδομένων (JSON)", delTitle:"Διαγραφή λογαριασμού", delDesc:"Θα διαγράψουμε λογαριασμό σε 30 ημέρες. Ορισμένες εγγραφές μπορεί να κρατηθούν περισσότερο αν απαιτείται από νόμο. Πληκτρολογήστε DELETE.", ph:"Πληκτρολογήστε DELETE", req:"Αίτημα διαγραφής", cookie:"Ρυθμίσεις cookies", close:"Κλείσιμο", down:"Τα δεδομένα λήφθηκαν.", delRec:"Αίτημα ελήφθη. Λογαριασμός θα διαγραφεί σε 30 ημέρες.", failExp:"Εξαγωγή απέτυχε", failReq:"Αίτημα απέτυχε" },
  he: { title:"פרטיות ונתונים", desc:"תחת GDPR ו-CCPA ניתן לייצא נתונים או למחוק חשבון.", export:"ייצא את כל הנתונים (JSON)", delTitle:"מחק את החשבון שלי", delDesc:"נמחק את החשבון תוך 30 יום. רשומות מסוימות עשויות להישמר יותר אם החוק דורש. הקלד DELETE.", ph:"הקלד DELETE", req:"בקש מחיקה", cookie:"הגדרות קוקיז", close:"סגור", down:"הנתונים הורדו כ-JSON.", delRec:"בקשת מחיקה התקבלה. החשבון יימחק תוך 30 יום.", failExp:"ייצוא נכשל", failReq:"בקשה נכשלה" },
  ur: { title:"رازداری اور ڈیٹا", desc:"GDPR اور CCPA کے تحت آپ ڈیٹا ایکسپورٹ یا اکاؤنٹ ڈیلیٹ کر سکتے ہیں۔", export:"میرا سارا ڈیٹا ایکسپورٹ (JSON)", delTitle:"میرا اکاؤنٹ ڈیلیٹ کریں", delDesc:"ہم 30 دن میں اکاؤنٹ مٹا دیں گے۔ کچھ ریکارڈ قانوناً زیادہ رکھے جا سکتے ہیں۔ DELETE ٹائپ کریں۔", ph:"DELETE ٹائپ کریں", req:"ڈیلیشن درخواست", cookie:"کوکی سیٹنگز", close:"بند کریں", down:"ڈیٹا JSON کے طور پر ڈاؤن لوڈ ہوا۔", delRec:"درخواست موصول۔ اکاؤنٹ 30 دن میں مٹے گا۔", failExp:"ایکسپورٹ ناکام", failReq:"درخواست ناکام" },
  fa: { title:"حریم خصوصی و داده", desc:"تحت GDPR و CCPA می توانید داده را صادر یا حساب را حذف کنید.", export:"صدور همه داده های من (JSON)", delTitle:"حذف حساب من", delDesc:"حساب شما را ظرف 30 روز پاک می کنیم. برخی سوابق ممکن است طبق قانون بیشتر بماند. DELETE را تایپ کنید.", ph:"DELETE را تایپ کنید", req:"درخواست حذف", cookie:"تنظیمات کوکی", close:"بستن", down:"داده شما به صورت JSON دانلود شد.", delRec:"درخواست دریافت شد. حساب ظرف 30 روز پاک می شود.", failExp:"صدور ناموفق", failReq:"درخواست ناموفق" },
  ms: { title:"Privasi & data", desc:"Di bawah GDPR dan CCPA anda boleh eksport data atau padam akaun.", export:"Eksport semua data saya (JSON)", delTitle:"Padam akaun saya", delDesc:"Kami akan padam akaun dalam 30 hari. Beberapa rekod mungkin disimpan lebih lama jika undang-undang memerlukan. Taip DELETE.", ph:"Taip DELETE", req:"Minta pemadaman", cookie:"Tetapan kuki", close:"Tutup", down:"Data anda dimuat turun sebagai JSON.", delRec:"Permintaan diterima. Akaun akan dipadam dalam 30 hari.", failExp:"Eksport gagal", failReq:"Permintaan gagal" },
  ro: { title:"Confidențialitate și date", desc:"Sub GDPR și CCPA poți exporta datele sau șterge contul.", export:"Exportă toate datele mele (JSON)", delTitle:"Șterge contul meu", delDesc:"Vom șterge contul în 30 zile. Unele înregistrări pot fi păstrate mai mult dacă legea cere. Tastează DELETE.", ph:"Tastează DELETE", req:"Solicită ștergerea", cookie:"Setări cookie", close:"Închide", down:"Datele au fost descărcate.", delRec:"Cerere primită. Contul va fi șters în 30 zile.", failExp:"Export eșuat", failReq:"Cerere eșuată" },
  cs: { title:"Soukromí a data", desc:"Dle GDPR a CCPA můžete exportovat data nebo smazat účet.", export:"Exportovat všechna data (JSON)", delTitle:"Smazat můj účet", delDesc:"Účet smažeme do 30 dnů. Některé záznamy mohou být uchovány déle pokud vyžaduje zákon. Zadejte DELETE.", ph:"Zadejte DELETE", req:"Požádat o smazání", cookie:"Nastavení cookies", close:"Zavřít", down:"Data stažena jako JSON.", delRec:"Žádost přijata. Účet bude smazán do 30 dnů.", failExp:"Export selhal", failReq:"Žádost selhala" },
  hu: { title:"Adatvédelem és adatok", desc:"GDPR és CCPA alatt exportálhatod adataid vagy törölheted fiókod.", export:"Összes adatom exportálása (JSON)", delTitle:"Fiókom törlése", delDesc:"Fiókod 30 napon belül töröljük. Egyes rekordok tovább megmaradhatnak ha törvény előírja. Írd be DELETE.", ph:"Írd be DELETE", req:"Törlés kérése", cookie:"Cookie beállítások", close:"Bezárás", down:"Adatok letöltve JSON-ként.", delRec:"Kérés fogadva. Fiók 30 napon belül törlődik.", failExp:"Export sikertelen", failReq:"Kérés sikertelen" },
  fi: { title:"Tietosuoja ja data", desc:"GDPR:n ja CCPA:n mukaan voit viedä dataa tai poistaa tilin.", export:"Vie kaikki datani (JSON)", delTitle:"Poista tilini", delDesc:"Poistamme tilin 30 päivässä. Jotkin tiedot voidaan säilyttää pidempään lain vaatiessa. Kirjoita DELETE.", ph:"Kirjoita DELETE", req:"Pyydä poistoa", cookie:"Evästeasetukset", close:"Sulje", down:"Data ladattu JSON:na.", delRec:"Pyyntö vastaanotettu. Tili poistetaan 30 päivässä.", failExp:"Vienti epäonnistui", failReq:"Pyyntö epäonnistui" },
  no: { title:"Personvern & data", desc:"Under GDPR og CCPA kan du eksportere data eller slette konto.", export:"Eksporter all data (JSON)", delTitle:"Slett kontoen min", delDesc:"Vi sletter kontoen innen 30 dager. Noen poster kan lagres lenger hvis loven krever. Skriv DELETE.", ph:"Skriv DELETE", req:"Be om sletting", cookie:"Cookie-innstillinger", close:"Lukk", down:"Data lastet ned som JSON.", delRec:"Forespørsel mottatt. Konto slettes innen 30 dager.", failExp:"Eksport feilet", failReq:"Forespørsel feilet" },
  da: { title:"Privatliv & data", desc:"Under GDPR og CCPA kan du eksportere data eller slette konto.", export:"Eksporter al min data (JSON)", delTitle:"Slet min konto", delDesc:"Vi sletter kontoen inden 30 dage. Nogle poster kan gemmes længere hvis loven kræver. Skriv DELETE.", ph:"Skriv DELETE", req:"Anmod om sletning", cookie:"Cookie-indstillinger", close:"Luk", down:"Data downloadet som JSON.", delRec:"Anmodning modtaget. Konto slettes inden 30 dage.", failExp:"Eksport mislykkedes", failReq:"Anmodning mislykkedes" },
  bg: { title:"Поверителност и данни", desc:"Съгласно GDPR и CCPA можете да експортирате данни или изтриете акаунт.", export:"Експорт на всички данни (JSON)", delTitle:"Изтрий акаунта ми", delDesc:"Ще изтрием акаунта за 30 дни. Някои записи може да се пазят по-дълго ако законът изисква. Напишете DELETE.", ph:"Напишете DELETE", req:"Заявка за изтриване", cookie:"Настройки бисквитки", close:"Затвори", down:"Данните изтеглени като JSON.", delRec:"Заявка получена. Акаунт ще бъде изтрит за 30 дни.", failExp:"Експорт неуспешен", failReq:"Заявка неуспешна" },
  hr: { title:"Privatnost i podaci", desc:"Prema GDPR-u i CCPA-u možete izvesti podatke ili izbrisati račun.", export:"Izvezi sve moje podatke (JSON)", delTitle:"Izbriši moj račun", delDesc:"Izbrisat ćemo račun u 30 dana. Neki zapisi mogu ostati duže ako zakon zahtijeva. Upišite DELETE.", ph:"Upišite DELETE", req:"Zatraži brisanje", cookie:"Postavke kolačića", close:"Zatvori", down:"Podaci preuzeti kao JSON.", delRec:"Zahtjev primljen. Račun će biti izbrisan u 30 dana.", failExp:"Izvoz neuspješan", failReq:"Zahtjev neuspješan" },
  sr: { title:"Приватност и подаци", desc:"Према GDPR и CCPA можете извести податке или обрисати налог.", export:"Извези све податке (JSON)", delTitle:"Обриши мој налог", delDesc:"Обрисаћемо налог за 30 дана. Неки записи могу остати дуже ако закон захтева. Унесите DELETE.", ph:"Унесите DELETE", req:"Затражи брисање", cookie:"Подешавања колачића", close:"Затвори", down:"Подаци преузети као JSON.", delRec:"Захтев примљен. Налог ће бити обрисан за 30 дана.", failExp:"Извоз неуспешан", failReq:"Захтев неуспешан" },
  sk: { title:"Súkromie a údaje", desc:"Podľa GDPR a CCPA môžete exportovať údaje alebo vymazať účet.", export:"Exportovať všetky údaje (JSON)", delTitle:"Vymazať môj účet", delDesc:"Účet vymažeme do 30 dní. Niektoré záznamy môžu zostať dlhšie ak vyžaduje zákon. Zadajte DELETE.", ph:"Zadajte DELETE", req:"Požiadať o vymazanie", cookie:"Nastavenia cookies", close:"Zavrieť", down:"Údaje stiahnuté ako JSON.", delRec:"Žiadosť prijatá. Účet bude vymazaný do 30 dní.", failExp:"Export zlyhal", failReq:"Žiadosť zlyhala" },
  sl: { title:"Zasebnost in podatki", desc:"V skladu z GDPR in CCPA lahko izvozite podatke ali izbrišete račun.", export:"Izvozi vse podatke (JSON)", delTitle:"Izbriši moj račun", delDesc:"Račun bomo izbrisali v 30 dneh. Nekateri zapisi lahko ostanejo dlje če zakon zahteva. Vpišite DELETE.", ph:"Vpišite DELETE", req:"Zahtevaj izbris", cookie:"Nastavitve piškotkov", close:"Zapri", down:"Podatki preneseni kot JSON.", delRec:"Zahteva prejeta. Račun bo izbrisan v 30 dneh.", failExp:"Izvoz neuspešen", failReq:"Zahteva neuspešna" },
  et: { title:"Privaatsus ja andmed", desc:"GDPR ja CCPA alusel saate andmeid eksportida või konto kustutada.", export:"Ekspordi kõik andmed (JSON)", delTitle:"Kustuta minu konto", delDesc:"Kustutame konto 30 päeva jooksul. Mõned kirjed võivad jääda kauemaks kui seadus nõuab. Sisesta DELETE.", ph:"Sisesta DELETE", req:"Taotle kustutamist", cookie:"Küpsise seaded", close:"Sulge", down:"Andmed alla laaditud JSON-ina.", delRec:"Taotlus saadud. Konto kustutatakse 30 päeva jooksul.", failExp:"Eksport ebaõnnestus", failReq:"Taotlus ebaõnnestus" },
  lv: { title:"Privātums un dati", desc:"Saskaņā ar GDPR un CCPA varat eksportēt datus vai dzēst kontu.", export:"Eksportēt visus datus (JSON)", delTitle:"Dzēst manu kontu", delDesc:"Dzēsīsim kontu 30 dienu laikā. Daži ieraksti var palikt ilgāk ja likums prasa. Ierakstiet DELETE.", ph:"Ierakstiet DELETE", req:"Pieprasīt dzēšanu", cookie:"Sīkdatņu iestatījumi", close:"Aizvērt", down:"Dati lejupielādēti kā JSON.", delRec:"Pieprasījums saņemts. Konts tiks dzēsts 30 dienu laikā.", failExp:"Eksports neizdevās", failReq:"Pieprasījums neizdevās" },
  lt: { title:"Privatumas ir duomenys", desc:"Pagal BDAR ir CCPA galite eksportuoti duomenis arba ištrinti paskyrą.", export:"Eksportuoti visus duomenis (JSON)", delTitle:"Ištrinti paskyrą", delDesc:"Ištrinsime paskyrą per 30 dienų. Kai kurie įrašai gali likti ilgiau jei įstatymas reikalauja. Įveskite DELETE.", ph:"Įveskite DELETE", req:"Prašyti ištrynimo", cookie:"Slapukų nustatymai", close:"Uždaryti", down:"Duomenys atsisiųsti kaip JSON.", delRec:"Užklausa gauta. Paskyra bus ištrinta per 30 d.", failExp:"Eksportas nepavyko", failReq:"Užklausa nepavyko" },
  be: { title:"Прыватнасць і даныя", desc:"Па GDPR і CCPA вы можаце экспартаваць даныя або выдаліць акаўнт.", export:"Экспартаваць усе даныя (JSON)", delTitle:"Выдаліць акаўнт", delDesc:"Мы выдалім акаўнт за 30 дзён. Некаторыя запісы могуць захоўвацца даўжэй калі патрабуе закон. Увядзіце DELETE.", ph:"Увядзіце DELETE", req:"Запытаць выдаленне", cookie:"Налады cookie", close:"Закрыць", down:"Даныя загружаны як JSON.", delRec:"Запыт атрыманы. Акаўнт будзе выдалены за 30 дзён.", failExp:"Экспарт не ўдаўся", failReq:"Запыт не ўдаўся" },
  ka: { title:"კონფიდენციალურობა და მონაცემები", desc:"GDPR და CCPA-ის ქვეშ შეგიძლიათ მონაცემების ექსპორტი ან ანგარიშის წაშლა.", export:"ყველა მონაცემის ექსპორტი (JSON)", delTitle:"ჩემი ანგარიშის წაშლა", delDesc:"ანგარიშს 30 დღეში წავშლით. ზოგიერთი ჩანაწერი შეიძლება дольше დარჩეს კანონის მოთხოვნით. ჩაწერეთ DELETE.", ph:"ჩაწერეთ DELETE", req:"წაშლის მოთხოვნა", cookie:"Cookie პარამეტრები", close:"დახურვა", down:"მონაცემები ჩამოტვირთულია JSON-ად.", delRec:"მოთხოვნა მიღებულია. ანგარიში 30 დღეში წაიშლება.", failExp:"ექსპორტი ვერ მოხერხდა", failReq:"მოთხოვნა ვერ მოხერხდა" },
  hy: { title:"Գաղտնիություն և տվյալներ", desc:"GDPR և CCPA-ի ներքո կարող եք արտահանել տվյալները կամ ջնջել հաշիվը.", export:"Արտահանել բոլոր տվյալները (JSON)", delTitle:"Ջնջել իմ հաշիվը", delDesc:"Մենք կջնջենք հաշիվը 30 օրվա ընթացքում։ Որոշ գրառումներ կարող են մնալ ավելի երկար եթե օրենքը պահանջում է։ Մուտքագրեք DELETE։", ph:"Մուտքագրեք DELETE", req:"Պահանջել ջնջում", cookie:"Cookie կարգավորումներ", close:"Փակել", down:"Տվյալները ներբեռնվել են JSON-ով։", delRec:"Հարցումը ստացվել է։ Հաշիվը կջնջվի 30 օրվա ընթացքում։", failExp:"Արտահանումը ձախողվեց", failReq:"Հարցումը ձախողվեց" },
  az: { title:"Məxfilik və data", desc:"GDPR və CCPA çərçivəsində datanızı ixrac edə və ya hesabı silə bilərsiniz.", export:"Bütün datalarımı ixrac et (JSON)", delTitle:"Hesabımı sil", delDesc:"Hesabı 30 gün ərzində siləcəyik. Bəzi qeydlər qanun tələb edərsə daha uzun qala bilər. DELETE yazın.", ph:"DELETE yazın", req:"Silinmə tələb et", cookie:"Cookie ayarları", close:"Bağla", down:"Datanız JSON olaraq endirildi.", delRec:"Sorğu alındı. Hesab 30 gün ərzində silinəcək.", failExp:"İxrac uğursuz", failReq:"Sorğu uğursuz" },
  kk: { title:"Құпиялылық және деректер", desc:"GDPR және CCPA бойынша деректерді экспорттай немесе есептік жазбаны жоя аласыз.", export:"Барлық деректерді экспорттау (JSON)", delTitle:"Есептік жазбамды жою", delDesc:"Есептік жазбаны 30 күн ішінде жоямыз. Кейбір жазбалар заң талап етсе ұзағырақ сақталуы мүмкін. DELETE енгізіңіз.", ph:"DELETE енгізіңіз", req:"Жоюды сұрау", cookie:"Cookie параметрлері", close:"Жабу", down:"Деректер JSON ретінде жүктелді.", delRec:"Сұрау алынды. Есептік жазба 30 күнде жойылады.", failExp:"Экспорт сәтсіз", failReq:"Сұрау сәтсіз" },
  ky: { title:"Купуялык жана дайындар", desc:"GDPR жана CCPA боюнча дайындарды экспорттоо же аккаунтту өчүрө аласыз.", export:"Бардык дайындарды экспорттоо (JSON)", delTitle:"Аккаунтумду өчүрүү", delDesc:"Аккаунтту 30 күн ичинде өчүрөбүз. Кээ бир жазуулар мыйзам талап кылса узагыраак сакталышы мүмкүн. DELETE киргизиңиз.", ph:"DELETE киргизиңиз", req:"Өчүрүүнү сурануу", cookie:"Cookie жөндөөлөрү", close:"Жабуу", down:"Дайындар JSON катары жүктөлдү.", delRec:"Сурам алынды. Аккаунт 30 күндө өчүрүлөт.", failExp:"Экспорт ийгиликсиз", failReq:"Сурам ийгиликсиз" },
  uz: { title:"Maxfiylik va ma'lumotlar", desc:"GDPR va CCPA bo'yicha ma'lumotlarni eksport qilishingiz yoki hisobni o'chirishingiz mumkin.", export:"Barcha ma'lumotlarimni eksport (JSON)", delTitle:"Hisobimni o'chirish", delDesc:"Hisobni 30 kun ichida o'chiramiz. Ba'zi yozuvlar qonun talab qilsa uzoqroq qolishi mumkin. DELETE kiriting.", ph:"DELETE kiriting", req:"O'chirishni so'rash", cookie:"Cookie sozlamalari", close:"Yopish", down:"Ma'lumotlar JSON sifatida yuklandi.", delRec:"So'rov qabul qilindi. Hisob 30 kun ichida o'chiriladi.", failExp:"Eksport muvaffaqiyatsiz", failReq:"So'rov muvaffaqiyatsiz" },
  tg: { title:"Махфият ва маълумот", desc:"Тибқи GDPR ва CCPA шумо метавонед маълумотро содир ё ҳисобро нест кунед.", export:"Содироти ҳамаи маълумот (JSON)", delTitle:"Ҳисоби маро нест кунед", delDesc:"Мо ҳисобро дар 30 рӯз нест мекунем. Баъзе сабтҳо агар қонун талаб кунад дарозтар мемонад. DELETE нависед.", ph:"DELETE нависед", req:"Дархости несткунӣ", cookie:"Танзимоти cookie", close:"Пӯшидан", down:"Маълумот ҳамчун JSON боргирӣ шуд.", delRec:"Дархост қабул шуд. Ҳисоб дар 30 рӯз нест мешавад.", failExp:"Содирот ноком", failReq:"Дархост ноком" },
  mn: { title:"Нууцлал ба өгөгдөл", desc:"GDPR болон CCPA дагуу өгөгдлөө экспортлох эсвэл хаягаа устгах боломжтой.", export:"Бүх өгөгдлөө экспортлох (JSON)", delTitle:"Хаягаа устгах", delDesc:"Хаягийг 30 хоногт устгана. Зарим бичлэг хуулиар удаан хадгалагдаж магад. DELETE гэж бичнэ үү.", ph:"DELETE гэж бичнэ үү", req:"Устгах хүсэх", cookie:"Күүки тохиргоо", close:"Хаах", down:"Өгөгдөл JSON-оор татагдлаа.", delRec:"Хүсэлт хүлээн авлаа. Хаяг 30 хоногт устах болно.", failExp:"Экспорт амжилтгүй", failReq:"Хүсэлт амжилтгүй" },
  km: { title:"ឯកជនភាព & ទិន្នន័យ", desc:"ក្រោម GDPR និង CCPA អ្នកអាចនាំចេញទិន្នន័យ ឬលុបគណនីបាន។", export:"នាំចេញទិន្នន័យទាំងអស់ (JSON)", delTitle:"លុបគណនីរបស់ខ្ញុំ", delDesc:"យើងនឹងលុបគណនីក្នុង 30 ថ្ងៃ។ កំណត់ត្រាមួយចំនួនអាចរក្សាទុកយូរជាងនេះប្រសិនបើច្បាប់តម្រូវ។ វាយ DELETE។", ph:"វាយ DELETE", req:"ស្នើសុំលុប", cookie:"ការកំណត់ខូគី", close:"បិទ", down:"ទិន្នន័យបានទាញយកជា JSON។", delRec:"បានទទួលសំណើ។ គណនីនឹងถูกลុបក្នុង 30 ថ្ងៃ។", failExp:"នាំចេញបរាជ័យ", failReq:"សំណើបរាជ័យ" },
  lo: { title:"ຄວາມເປັນສ່ວນຕົວ & ຂໍ້ມູນ", desc:"ພາຍໃຕ້ GDPR ແລະ CCPA ທ່ານສາມາດສົ່ງອອກຂໍ້ມູນຫຼືລຶບບັນຊີໄດ້。", export:"ສົ່ງອອກຂໍ້ມູນທັງໝົດ (JSON)", delTitle:"ລຶບບັນຊີຂອງຂ້ອຍ", delDesc:"ພວກເຮົາຈະລຶບບັນຊີພາຍໃນ 30 ວັນ ບັນທຶກບາງຢ່າງອາດເກັບດົນກວ່າຖ້າກົດໝາຍຕ້ອງການ ພິມ DELETE", ph:"ພິມ DELETE", req:"ຂໍລຶບ", cookie:"ຕັ້ງຄ່າຄຸກກີ", close:"ປິດ", down:"ດາວໂຫຼດຂໍ້ມູນແລ້ວເປັນ JSON", delRec:"ໄດ້ຮັບຄຳຂໍແລ້ວ ບັນຊີຈະຖືກລຶບໃນ 30 ວັນ", failExp:"ສົ່ງອອກບໍ່ສຳເລັດ", failReq:"ຄຳຂໍບໍ່ສຳເລັດ" },
  my: { title:"ကိုယ်ရေးကိုယ်တာနှင့် ဒေတာ", desc:"GDPR နှင့် CCPA အောက်တွင် ဒေတာထုတ်ယူခြင်း သို့မဟုတ် အကောင့်ဖျက်ခြင်းပြုလုပ်နိုင်သည်။", export:"ဒေတာအားလုံးထုတ်ယူရန် (JSON)", delTitle:"ကျွန်ုပ်၏အကောင့်ကိုဖျက်ရန်", delDesc:"အကောင့်ကို ရက် 30 အတွင်းဖျက်ပါမည်။ ဥပဒေအရ အချို့မှတ်တမ်းများ ပိုကြာကြာရှိနိုင်သည်။ DELETE ရိုက်ပါ။", ph:"DELETE ရိုက်ပါ", req:"ဖျက်ရန်တောင်းဆိုရန်", cookie:"ကွတ်ကီးဆက်တင်များ", close:"ပိတ်ရန်", down:"ဒေတာကို JSON အဖြစ်ဒေါင်းလုဒ်လုပ်ပြီး။", delRec:"တောင်းဆိုမှုလက်ခံရရှိပါပြီ။ အကောင့် 30 ရက်အတွင်းဖျက်ပါမည်။", failExp:"ထုတ်ယူမှုမအောင်မြင်", failReq:"တောင်းဆိုမှုမအောင်မြင်" },
}

export function AccountSettingsDialog({ onClose }: { onClose: () => void }) {
  const { language } = useLanguage()
  const d = D[language] || D.en
  const [busy, setBusy] = useState(false)
  const [msg, setMsg] = useState('')
  const [confirmDelete, setConfirmDelete] = useState('')
  const supabase = createClient() as any

  const exportData = async () => {
    setBusy(true); setMsg('')
    try {
      const { data: u } = await supabase.auth.getUser()
      if (!u.user) return
      const [ { data: profile }, { data: privateProfile }, { data: posts }, { data: likes }, { data: reports }, { data: subs }, { data: boosts } ] = await Promise.all([
        supabase.from('profiles').select('*').eq('user_id', u.user.id).maybeSingle(),
        (supabase as any).rpc('get_my_private_profile'),
        supabase.from('posts').select('*').eq('user_id', u.user.id),
        supabase.from('post_likes').select('*').eq('user_id', u.user.id),
        supabase.from('post_reports').select('*').eq('reporter_id', u.user.id),
        supabase.from('subscriptions').select('*').eq('user_id', u.user.id),
        supabase.from('post_boosts').select('*').eq('user_id', u.user.id),
      ])
      const privateRow = Array.isArray(privateProfile)? privateProfile[0] : privateProfile
      const fullProfile = {...(profile?? {}),...(privateRow?? {}) }
      const payload = { exported_at: new Date().toISOString(), account: { id: u.user.id, email: u.user.email, created_at: u.user.created_at }, profile: fullProfile, posts, likes, reports, subscriptions: subs, post_boosts: boosts }
      const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })
      const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `sweet-social-data-${new Date().toISOString().slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(url)
      setMsg(d.down)
    } catch (e: any) { setMsg(e.message || d.failExp) } finally { setBusy(false) }
  }

  const requestDeletion = async () => {
    if (confirmDelete!== 'DELETE') return
    setBusy(true); setMsg('')
    try {
      const { data: u } = await supabase.auth.getUser()
      if (!u.user) return
      const { error } = await supabase.from('account_deletion_requests').insert({ user_id: u.user.id, reason: 'user requested via settings' })
      if (error && (error as any).code!== '23505') { setMsg(error.message); return }
      setMsg(d.delRec)
    } catch (e: any) { setMsg(e.message || d.failReq) } finally { setBusy(false) }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4" onClick={onClose}>
      <div className="w-full max-w-md rounded-2xl border border-border bg-card p-5 shadow-xl" onClick={(e) => e.stopPropagation()}>
        <h2 className="font-display text-lg font-semibold">{d.title}</h2>
        <p className="mt-1 text-xs text-muted-foreground">{d.desc}</p>
        <div className="mt-4 space-y-2"><button onClick={()=>{ try { exportData() } catch {} }} disabled={busy} className="w-full rounded-xl border border-border px-4 py-2 text-sm hover:bg-secondary disabled:opacity-50">{d.export}</button></div>
        <div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-3 dark:border-red-900/40 dark:bg-red-950/30"><p className="text-sm font-medium text-red-900 dark:text-red-200">{d.delTitle}</p><p className="mt-1 text-xs text-red-800/80 dark:text-red-200/80">{d.delDesc}</p><input value={confirmDelete} onChange={(e) => { try { setConfirmDelete(e.target.value) } catch {} }} placeholder={d.ph} className="mt-2 w-full rounded-lg border border-red-300 bg-background px-3 py-2 text-sm" /><button onClick={()=>{ try { requestDeletion() } catch {} }} disabled={busy || confirmDelete!== 'DELETE'} className="mt-2 w-full rounded-full bg-red-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{d.req}</button></div>
        {msg && <p className="mt-3 text-sm text-foreground">{msg}</p>}
        <div className="mt-5 flex items-center justify-between"><button onClick={() => { try { window.dispatchEvent(new Event('open-cookie-settings')) } catch {} }} className="text-xs text-muted-foreground underline">{d.cookie}</button><button onClick={onClose} className="rounded-full border border-border px-4 py-2 text-sm hover:bg-secondary">{d.close}</button></div>
      </div>
    </div>
  )
}
