'use client'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useLanguage } from '@/lib/language-context'

type VerifiedSourceAdminRow = {
  id: string; name: string; slug: string; kind: string; status: 'pending' | 'approved' | 'rejected' | 'suspended'
  logo_emoji: string | null; description: string | null; website: string | null; contact_email: string | null; contact_name: string | null; contact_phone: string | null
  city: string | null; state_code: string | null; country_code: string | null; latitude: number | null; longitude: number | null; review_notes: string | null
}

async function listAllVerifiedSources({ data }: any): Promise<VerifiedSourceAdminRow[]> {
  const supabase = createClient()
  const { data: rows, error } = await supabase.from('verified_sources').select('*').order('created_at', { ascending: false })
  if (error) throw error
  return rows as VerifiedSourceAdminRow[]
}
async function adminCreateVerifiedSource({ data }: any) { const supabase = createClient(); const { error } = await supabase.from('verified_sources').insert(data); if (error) throw error }
async function adminReviewVerifiedSource({ data }: any) { const supabase = createClient(); const { error } = await supabase.from('verified_sources').update({ status: data.status, review_notes: data.review_notes }).eq('id', data.id); if (error) throw error }
async function adminDeleteVerifiedSource({ data }: any) { const supabase = createClient(); const { error } = await supabase.from('verified_sources').delete().eq('id', data.id); if (error) throw error }
async function adminUpdateVerifiedSource({ data }: any) { const supabase = createClient(); const { id,...updates } = data; const { error } = await supabase.from('verified_sources').update(updates).eq('id', id); if (error) throw error }

const D: Record<string, any> = {
  en: { gov:"Government", police:"Police", fire:"Fire", school:"School", news:"News", assoc:"Community group", nonprofit:"Nonprofit", business:"Business", other:"Other", pending:"pending", approved:"approved", rejected:"rejected", suspended:"suspended", all:"all", allTypes:"All types", searchPh:"Search name / slug / description", city:"City", state:"State (CA)", noMatch:"No organizations match these filters.", loading:"Loading…", noLoc:"No location", website:"website", contact:"Contact", notes:"Notes", approve:"Approve", reject:"Reject", suspend:"Suspend", edit:"Edit", delete:"Delete", create:"+ Create verified source", newTitle:"New verified source", namePh:"Name *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://website", descPh:"Description", creating:"Creating…", createApproved:"Create (approved)", cancel:"Cancel", editTitle:"Edit verified source", close:"Close", contactName:"Contact name", contactEmail:"Contact email", contactPhone:"Contact phone", countryPh:"Country Code (US) *", lat:"Latitude", lng:"Longitude", regeo:"Re-geocode", saving:"Saving…", saveChanges:"Save changes", confirmDelete:"Delete this organization and all its updates? This cannot be undone.", reasonReject:"Reason for rejection (optional):", reasonSuspend:"Reason for suspension (optional):" },
  es: { gov:"Gobierno", police:"Policía", fire:"Bomberos", school:"Escuela", news:"Noticias", assoc:"Grupo comunitario", nonprofit:"Sin fines de lucro", business:"Negocio", other:"Otro", pending:"pendiente", approved:"aprobado", rejected:"rechazado", suspended:"suspendido", all:"todos", allTypes:"Todos los tipos", searchPh:"Buscar nombre / slug / descripción", city:"Ciudad", state:"Estado (CA)", noMatch:"Ninguna organización coincide.", loading:"Cargando…", noLoc:"Sin ubicación", website:"sitio web", contact:"Contacto", notes:"Notas", approve:"Aprobar", reject:"Rechazar", suspend:"Suspender", edit:"Editar", delete:"Eliminar", create:"+ Crear fuente verificada", newTitle:"Nueva fuente verificada", namePh:"Nombre *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://sitio", descPh:"Descripción", creating:"Creando…", createApproved:"Crear (aprobado)", cancel:"Cancelar", editTitle:"Editar fuente verificada", close:"Cerrar", contactName:"Nombre contacto", contactEmail:"Email contacto", contactPhone:"Teléfono contacto", countryPh:"Código país (US) *", lat:"Latitud", lng:"Longitud", regeo:"Re-geocodificar", saving:"Guardando…", saveChanges:"Guardar cambios", confirmDelete:"¿Eliminar esta organización y todas sus actualizaciones? No se puede deshacer.", reasonReject:"Motivo rechazo (opcional):", reasonSuspend:"Motivo suspensión (opcional):" },
  fr: { gov:"Gouvernement", police:"Police", fire:"Pompiers", school:"École", news:"Actualités", assoc:"Groupe communautaire", nonprofit:"À but non lucratif", business:"Entreprise", other:"Autre", pending:"en attente", approved:"approuvé", rejected:"rejeté", suspended:"suspendu", all:"tous", allTypes:"Tous les types", searchPh:"Rechercher nom / slug / description", city:"Ville", state:"État (CA)", noMatch:"Aucune organisation correspond.", loading:"Chargement…", noLoc:"Pas d'emplacement", website:"site web", contact:"Contact", notes:"Notes", approve:"Approuver", reject:"Rejeter", suspend:"Suspendre", edit:"Modifier", delete:"Supprimer", create:"+ Créer source vérifiée", newTitle:"Nouvelle source vérifiée", namePh:"Nom *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://site", descPh:"Description", creating:"Création…", createApproved:"Créer (approuvé)", cancel:"Annuler", editTitle:"Modifier source vérifiée", close:"Fermer", contactName:"Nom contact", contactEmail:"Email contact", contactPhone:"Téléphone contact", countryPh:"Code pays (US) *", lat:"Latitude", lng:"Longitude", regeo:"Re-géocoder", saving:"Enregistrement…", saveChanges:"Enregistrer", confirmDelete:"Supprimer cette organisation et toutes ses mises à jour? Irréversible.", reasonReject:"Raison rejet (optionnel):", reasonSuspend:"Raison suspension (optionnel):" },
  de: { gov:"Regierung", police:"Polizei", fire:"Feuerwehr", school:"Schule", news:"Nachrichten", assoc:"Gemeinschaftsgruppe", nonprofit:"Gemeinnützig", business:"Unternehmen", other:"Andere", pending:"ausstehend", approved:"genehmigt", rejected:"abgelehnt", suspended:"suspendiert", all:"alle", allTypes:"Alle Typen", searchPh:"Name / Slug / Beschreibung suchen", city:"Stadt", state:"Bundesland (CA)", noMatch:"Keine Organisationen passen zu diesen Filtern.", loading:"Laden…", noLoc:"Kein Standort", website:"Webseite", contact:"Kontakt", notes:"Notizen", approve:"Genehmigen", reject:"Ablehnen", suspend:"Sperren", edit:"Bearbeiten", delete:"Löschen", create:"+ Verifizierte Quelle erstellen", newTitle:"Neue verifizierte Quelle", namePh:"Name *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://webseite", descPh:"Beschreibung", creating:"Erstellen…", createApproved:"Erstellen (genehmigt)", cancel:"Abbrechen", editTitle:"Verifizierte Quelle bearbeiten", close:"Schließen", contactName:"Kontaktname", contactEmail:"Kontakt-E-Mail", contactPhone:"Kontakttelefon", countryPh:"Ländercode (US) *", lat:"Breitengrad", lng:"Längengrad", regeo:"Neu geokodieren", saving:"Speichern…", saveChanges:"Änderungen speichern", confirmDelete:"Diese Organisation und alle Updates löschen? Kann nicht rückgängig gemacht werden.", reasonReject:"Grund für Ablehnung (optional):", reasonSuspend:"Grund für Sperrung (optional):" },
  zh: { gov:"政府", police:"警察", fire:"消防", school:"学校", news:"新闻", assoc:"社区团体", nonprofit:"非营利", business:"企业", other:"其他", pending:"待处理", approved:"已批准", rejected:"已拒绝", suspended:"已暂停", all:"全部", allTypes:"所有类型", searchPh:"搜索名称 / 别名 / 描述", city:"城市", state:"州 (CA)", noMatch:"没有组织符合这些筛选。", loading:"加载中…", noLoc:"无位置", website:"网站", contact:"联系人", notes:"备注", approve:"批准", reject:"拒绝", suspend:"暂停", edit:"编辑", delete:"删除", create:"+ 创建已验证源", newTitle:"新建已验证源", namePh:"名称 *", slugPh:"别名", emojiPh:"表情 (🏛)", websitePh:"https://网站", descPh:"描述", creating:"创建中…", createApproved:"创建（已批准）", cancel:"取消", editTitle:"编辑已验证源", close:"关闭", contactName:"联系人姓名", contactEmail:"联系人邮箱", contactPhone:"联系人电话", countryPh:"国家代码 (US) *", lat:"纬度", lng:"经度", regeo:"重新地理编码", saving:"保存中…", saveChanges:"保存更改", confirmDelete:"删除此组织及其所有更新？无法撤销。", reasonReject:"拒绝原因（可选）：", reasonSuspend:"暂停原因（可选）：" },
  ja: { gov:"政府", police:"警察", fire:"消防", school:"学校", news:"ニュース", assoc:"コミュニティグループ", nonprofit:"非営利", business:"企業", other:"その他", pending:"保留中", approved:"承認済み", rejected:"却下", suspended:"停止中", all:"すべて", allTypes:"すべてのタイプ", searchPh:"名前 / スラッグ / 説明を検索", city:"市", state:"州 (CA)", noMatch:"フィルターに一致する組織がありません。", loading:"読み込み中…", noLoc:"場所なし", website:"ウェブサイト", contact:"連絡先", notes:"メモ", approve:"承認", reject:"却下", suspend:"停止", edit:"編集", delete:"削除", create:"+ 検証済みソースを作成", newTitle:"新規検証済みソース", namePh:"名前 *", slugPh:"スラッグ", emojiPh:"絵文字 (🏛)", websitePh:"https://ウェブサイト", descPh:"説明", creating:"作成中…", createApproved:"作成（承認済み）", cancel:"キャンセル", editTitle:"検証済みソースを編集", close:"閉じる", contactName:"連絡先名", contactEmail:"連絡先メール", contactPhone:"連絡先電話", countryPh:"国コード (US) *", lat:"緯度", lng:"経度", regeo:"再ジオコード", saving:"保存中…", saveChanges:"変更を保存", confirmDelete:"この組織とすべての更新を削除しますか？元に戻せません。", reasonReject:"却下理由（任意）：", reasonSuspend:"停止理由（任意）：" },
  ko: { gov:"정부", police:"경찰", fire:"소방", school:"학교", news:"뉴스", assoc:"커뮤니티 그룹", nonprofit:"비영리", business:"기업", other:"기타", pending:"보류 중", approved:"승인됨", rejected:"거부됨", suspended:"정지됨", all:"전체", allTypes:"모든 유형", searchPh:"이름 / 슬러그 / 설명 검색", city:"도시", state:"주 (CA)", noMatch:"필터에 맞는 조직이 없습니다.", loading:"로딩 중…", noLoc:"위치 없음", website:"웹사이트", contact:"연락처", notes:"메모", approve:"승인", reject:"거부", suspend:"정지", edit:"편집", delete:"삭제", create:"+ 검증된 소스 만들기", newTitle:"새 검증된 소스", namePh:"이름 *", slugPh:"슬러그", emojiPh:"이모지 (🏛)", websitePh:"https://웹사이트", descPh:"설명", creating:"생성 중…", createApproved:"생성 (승인됨)", cancel:"취소", editTitle:"검증된 소스 편집", close:"닫기", contactName:"연락처 이름", contactEmail:"연락처 이메일", contactPhone:"연락처 전화", countryPh:"국가 코드 (US) *", lat:"위도", lng:"경도", regeo:"재지오코딩", saving:"저장 중…", saveChanges:"변경 저장", confirmDelete:"이 조직과 모든 업데이트를 삭제하시겠습니까? 되돌릴 수 없습니다.", reasonReject:"거부 이유 (선택):", reasonSuspend:"정지 이유 (선택):" },
  pt: { gov:"Governo", police:"Polícia", fire:"Bombeiros", school:"Escola", news:"Notícias", assoc:"Grupo comunitário", nonprofit:"Sem fins lucrativos", business:"Empresa", other:"Outro", pending:"pendente", approved:"aprovado", rejected:"rejeitado", suspended:"suspenso", all:"todos", allTypes:"Todos os tipos", searchPh:"Buscar nome / slug / descrição", city:"Cidade", state:"Estado (CA)", noMatch:"Nenhuma organização corresponde.", loading:"Carregando…", noLoc:"Sem localização", website:"site", contact:"Contato", notes:"Notas", approve:"Aprovar", reject:"Rejeitar", suspend:"Suspender", edit:"Editar", delete:"Excluir", create:"+ Criar fonte verificada", newTitle:"Nova fonte verificada", namePh:"Nome *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://site", descPh:"Descrição", creating:"Criando…", createApproved:"Criar (aprovado)", cancel:"Cancelar", editTitle:"Editar fonte verificada", close:"Fechar", contactName:"Nome contato", contactEmail:"Email contato", contactPhone:"Telefone contato", countryPh:"Código país (US) *", lat:"Latitude", lng:"Longitude", regeo:"Re-geocodificar", saving:"Salvando…", saveChanges:"Salvar alterações", confirmDelete:"Excluir esta organização e todas atualizações? Não pode desfazer.", reasonReject:"Motivo rejeição (opcional):", reasonSuspend:"Motivo suspensão (opcional):" },
  ru: { gov:"Правительство", police:"Полиция", fire:"Пожарные", school:"Школа", news:"Новости", assoc:"Сообщество", nonprofit:"НКО", business:"Бизнес", other:"Другое", pending:"ожидает", approved:"одобрено", rejected:"отклонено", suspended:"приостановлено", all:"все", allTypes:"Все типы", searchPh:"Поиск имя / слаг / описание", city:"Город", state:"Штат (CA)", noMatch:"Нет организаций по этим фильтрам.", loading:"Загрузка…", noLoc:"Нет местоположения", website:"сайт", contact:"Контакт", notes:"Заметки", approve:"Одобрить", reject:"Отклонить", suspend:"Приостановить", edit:"Редакт.", delete:"Удалить", create:"+ Создать проверенный источник", newTitle:"Новый проверенный источник", namePh:"Имя *", slugPh:"слаг", emojiPh:"Эмодзи (🏛)", websitePh:"https://сайт", descPh:"Описание", creating:"Создание…", createApproved:"Создать (одобрено)", cancel:"Отмена", editTitle:"Редактировать проверенный источник", close:"Закрыть", contactName:"Имя контакта", contactEmail:"Email контакта", contactPhone:"Телефон контакта", countryPh:"Код страны (US) *", lat:"Широта", lng:"Долгота", regeo:"Перегеокодировать", saving:"Сохранение…", saveChanges:"Сохранить изменения", confirmDelete:"Удалить эту организацию и все обновления? Нельзя отменить.", reasonReject:"Причина отклонения (необязательно):", reasonSuspend:"Причина приостановки (необязательно):" },
  ar: { gov:"حكومة", police:"شرطة", fire:"إطفاء", school:"مدرسة", news:"أخبار", assoc:"مجموعة مجتمعية", nonprofit:"غير ربحي", business:"عمل", other:"أخرى", pending:"معلق", approved:"معتمد", rejected:"مرفوض", suspended:"موقوف", all:"الكل", allTypes:"جميع الأنواع", searchPh:"بحث اسم / معرف / وصف", city:"مدينة", state:"ولاية (CA)", noMatch:"لا توجد منظمات تطابق هذه الفلاتر.", loading:"جار التحميل…", noLoc:"لا يوجد موقع", website:"موقع", contact:"اتصال", notes:"ملاحظات", approve:"اعتماد", reject:"رفض", suspend:"تعليق", edit:"تعديل", delete:"حذف", create:"+ إنشاء مصدر موثق", newTitle:"مصدر موثق جديد", namePh:"اسم *", slugPh:"معرف", emojiPh:"إيموجي (🏛)", websitePh:"https://موقع", descPh:"وصف", creating:"جاري الإنشاء…", createApproved:"إنشاء (معتمد)", cancel:"إلغاء", editTitle:"تعديل مصدر موثق", close:"إغلاق", contactName:"اسم جهة الاتصال", contactEmail:"بريد جهة الاتصال", contactPhone:"هاتف جهة الاتصال", countryPh:"رمز البلد (US) *", lat:"خط عرض", lng:"خط طول", regeo:"إعادة ترميز جغرافي", saving:"جاري الحفظ…", saveChanges:"حفظ التغييرات", confirmDelete:"حذف هذه المنظمة وكل تحديثاتها؟ لا يمكن التراجع.", reasonReject:"سبب الرفض (اختياري):", reasonSuspend:"سبب التعليق (اختياري):" },
  hi: { gov:"सरकार", police:"पुलिस", fire:"फायर", school:"स्कूल", news:"समाचार", assoc:"सामुदायिक समूह", nonprofit:"गैर-लाभकारी", business:"व्यवसाय", other:"अन्य", pending:"लंबित", approved:"स्वीकृत", rejected:"अस्वीकृत", suspended:"निलंबित", all:"सभी", allTypes:"सभी प्रकार", searchPh:"नाम / स्लग / विवरण खोजें", city:"शहर", state:"राज्य (CA)", noMatch:"इन फ़िल्टर से कोई संगठन मेल नहीं खाता।", loading:"लोड हो रहा…", noLoc:"कोई स्थान नहीं", website:"वेबसाइट", contact:"संपर्क", notes:"नोट्स", approve:"स्वीकृत", reject:"अस्वीकार", suspend:"निलंबित", edit:"संपादित", delete:"हटाएं", create:"+ सत्यापित स्रोत बनाएं", newTitle:"नया सत्यापित स्रोत", namePh:"नाम *", slugPh:"स्लग", emojiPh:"इमोजी (🏛)", websitePh:"https://वेबसाइट", descPh:"विवरण", creating:"बना रहा…", createApproved:"बनाएं (स्वीकृत)", cancel:"रद्द करें", editTitle:"सत्यापित स्रोत संपादित करें", close:"बंद करें", contactName:"संपर्क नाम", contactEmail:"संपर्क ईमेल", contactPhone:"संपर्क फोन", countryPh:"देश कोड (US) *", lat:"अक्षांश", lng:"देशांतर", regeo:"पुनः जियोकोड", saving:"सहेज रहा…", saveChanges:"बदलाव सहेजें", confirmDelete:"इस संगठन और सभी अपडेट हटाएं? पूर्ववत नहीं हो सकता।", reasonReject:"अस्वीकृति कारण (वैकल्पिक):", reasonSuspend:"निलंबन कारण (वैकल्पिक):" },
  it: { gov:"Governo", police:"Polizia", fire:"Vigili del fuoco", school:"Scuola", news:"Notizie", assoc:"Gruppo comunitario", nonprofit:"No profit", business:"Azienda", other:"Altro", pending:"in attesa", approved:"approvato", rejected:"rifiutato", suspended:"sospeso", all:"tutti", allTypes:"Tutti i tipi", searchPh:"Cerca nome / slug / descrizione", city:"Città", state:"Stato (CA)", noMatch:"Nessuna organizzazione corrisponde.", loading:"Caricamento…", noLoc:"Nessuna posizione", website:"sito", contact:"Contatto", notes:"Note", approve:"Approva", reject:"Rifiuta", suspend:"Sospendi", edit:"Modifica", delete:"Elimina", create:"+ Crea fonte verificata", newTitle:"Nuova fonte verificata", namePh:"Nome *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://sito", descPh:"Descrizione", creating:"Creazione…", createApproved:"Crea (approvato)", cancel:"Annulla", editTitle:"Modifica fonte verificata", close:"Chiudi", contactName:"Nome contatto", contactEmail:"Email contatto", contactPhone:"Telefono contatto", countryPh:"Codice paese (US) *", lat:"Latitudine", lng:"Longitudine", regeo:"Re-geocodifica", saving:"Salvataggio…", saveChanges:"Salva modifiche", confirmDelete:"Eliminare questa organizzazione e tutti gli aggiornamenti? Irreversibile.", reasonReject:"Motivo rifiuto (opzionale):", reasonSuspend:"Motivo sospensione (opzionale):" },
  nl: { gov:"Overheid", police:"Politie", fire:"Brandweer", school:"School", news:"Nieuws", assoc:"Buurtgroep", nonprofit:"Non-profit", business:"Bedrijf", other:"Anders", pending:"in afwachting", approved:"goedgekeurd", rejected:"afgewezen", suspended:"geschorst", all:"alle", allTypes:"Alle types", searchPh:"Zoek naam / slug / beschrijving", city:"Stad", state:"Staat (CA)", noMatch:"Geen organisaties komen overeen.", loading:"Laden…", noLoc:"Geen locatie", website:"website", contact:"Contact", notes:"Notities", approve:"Goedkeuren", reject:"Afwijzen", suspend:"Schorsen", edit:"Bewerken", delete:"Verwijderen", create:"+ Geverifieerde bron maken", newTitle:"Nieuwe geverifieerde bron", namePh:"Naam *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://website", descPh:"Beschrijving", creating:"Maken…", createApproved:"Maken (goedgekeurd)", cancel:"Annuleren", editTitle:"Geverifieerde bron bewerken", close:"Sluiten", contactName:"Contactnaam", contactEmail:"Contact e-mail", contactPhone:"Contact telefoon", countryPh:"Landcode (US) *", lat:"Breedtegraad", lng:"Lengtegraad", regeo:"Opnieuw geocoderen", saving:"Opslaan…", saveChanges:"Wijzigingen opslaan", confirmDelete:"Deze organisatie en alle updates verwijderen? Kan niet ongedaan worden.", reasonReject:"Reden afwijzing (optioneel):", reasonSuspend:"Reden schorsing (optioneel):" },
  tl: { gov:"Gobyerno", police:"Pulis", fire:"Bumbero", school:"Paaralan", news:"Balita", assoc:"Community group", nonprofit:"Nonprofit", business:"Negosyo", other:"Iba pa", pending:"pending", approved:"approved", rejected:"rejected", suspended:"suspended", all:"lahat", allTypes:"Lahat ng uri", searchPh:"Hanapin pangalan / slug / description", city:"Lungsod", state:"Estado (CA)", noMatch:"Walang organisasyong tumutugma.", loading:"Naglo-load…", noLoc:"Walang lokasyon", website:"website", contact:"Contact", notes:"Notes", approve:"Aprubahan", reject:"Tanggihan", suspend:"Suspend", edit:"I-edit", delete:"Burahin", create:"+ Gumawa ng verified source", newTitle:"Bagong verified source", namePh:"Pangalan *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://website", descPh:"Description", creating:"Ginagawa…", createApproved:"Gawin (approved)", cancel:"Kanselahin", editTitle:"I-edit verified source", close:"Isara", contactName:"Pangalan ng contact", contactEmail:"Email ng contact", contactPhone:"Telepono ng contact", countryPh:"Code ng bansa (US) *", lat:"Latitude", lng:"Longitude", regeo:"Re-geocode", saving:"Sine-save…", saveChanges:"I-save pagbabago", confirmDelete:"Burahin organisasyong ito at lahat ng updates? Hindi na mababawi.", reasonReject:"Dahilan ng pagtanggi (optional):", reasonSuspend:"Dahilan ng suspension (optional):" },
  bn: { gov:"সরকার", police:"পুলিশ", fire:"ফায়ার", school:"স্কুল", news:"সংবাদ", assoc:"কমিউনিটি গ্রুপ", nonprofit:"অলাভজনক", business:"ব্যবসা", other:"অন্যান্য", pending:"মুলতুবি", approved:"অনুমোদিত", rejected:"প্রত্যাখ্যাত", suspended:"স্থগিত", all:"সব", allTypes:"সব ধরনের", searchPh:"নাম / স্লাগ / বিবরণ অনুসন্ধান", city:"শহর", state:"রাজ্য (CA)", noMatch:"এই ফিল্টারের সাথে কোনো সংস্থা মেলে না।", loading:"লোড হচ্ছে…", noLoc:"কোনো অবস্থান নেই", website:"ওয়েবসাইট", contact:"যোগাযোগ", notes:"নোট", approve:"অনুমোদন", reject:"প্রত্যাখ্যান", suspend:"স্থগিত", edit:"সম্পাদনা", delete:"মুছুন", create:"+ যাচাইকৃত উৎস তৈরি করুন", newTitle:"নতুন যাচাইকৃত উৎস", namePh:"নাম *", slugPh:"স্লাগ", emojiPh:"ইমোজি (🏛)", websitePh:"https://ওয়েবসাইট", descPh:"বিবরণ", creating:"তৈরি হচ্ছে…", createApproved:"তৈরি করুন (অনুমোদিত)", cancel:"বাতিল", editTitle:"যাচাইকৃত উৎস সম্পাদনা", close:"বন্ধ করুন", contactName:"যোগাযোগের নাম", contactEmail:"যোগাযোগের ইমেল", contactPhone:"যোগাযোগের ফোন", countryPh:"দেশের কোড (US) *", lat:"অক্ষাংশ", lng:"দ্রাঘিমাংশ", regeo:"পুনরায় জিওকোড", saving:"সংরক্ষণ হচ্ছে…", saveChanges:"পরিবর্তন সংরক্ষণ", confirmDelete:"এই সংস্থা এবং সমস্ত আপডেট মুছবেন? পূর্বাবস্থায় ফেরানো যাবে না।", reasonReject:"প্রত্যাখ্যানের কারণ (ঐচ্ছিক):", reasonSuspend:"স্থগিতের কারণ (ঐচ্ছিক):" },
  id: { gov:"Pemerintah", police:"Polisi", fire:"Pemadam", school:"Sekolah", news:"Berita", assoc:"Kelompok komunitas", nonprofit:"Nirlaba", business:"Bisnis", other:"Lainnya", pending:"tertunda", approved:"disetujui", rejected:"ditolak", suspended:"ditangguhkan", all:"semua", allTypes:"Semua jenis", searchPh:"Cari nama / slug / deskripsi", city:"Kota", state:"Negara Bagian (CA)", noMatch:"Tidak ada organisasi yang cocok.", loading:"Memuat…", noLoc:"Tidak ada lokasi", website:"situs web", contact:"Kontak", notes:"Catatan", approve:"Setujui", reject:"Tolak", suspend:"Tangguhkan", edit:"Edit", delete:"Hapus", create:"+ Buat sumber terverifikasi", newTitle:"Sumber terverifikasi baru", namePh:"Nama *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://situs", descPh:"Deskripsi", creating:"Membuat…", createApproved:"Buat (disetujui)", cancel:"Batal", editTitle:"Edit sumber terverifikasi", close:"Tutup", contactName:"Nama kontak", contactEmail:"Email kontak", contactPhone:"Telepon kontak", countryPh:"Kode negara (US) *", lat:"Lintang", lng:"Bujur", regeo:"Geocode ulang", saving:"Menyimpan…", saveChanges:"Simpan perubahan", confirmDelete:"Hapus organisasi ini dan semua pembaruan? Tidak dapat dibatalkan.", reasonReject:"Alasan penolakan (opsional):", reasonSuspend:"Alasan penangguhan (opsional):" },
  vi: { gov:"Chính phủ", police:"Cảnh sát", fire:"Cứu hỏa", school:"Trường học", news:"Tin tức", assoc:"Nhóm cộng đồng", nonprofit:"Phi lợi nhuận", business:"Doanh nghiệp", other:"Khác", pending:"đang chờ", approved:"đã duyệt", rejected:"bị từ chối", suspended:"bị đình chỉ", all:"tất cả", allTypes:"Tất cả loại", searchPh:"Tìm tên / slug / mô tả", city:"Thành phố", state:"Bang (CA)", noMatch:"Không có tổ chức nào khớp.", loading:"Đang tải…", noLoc:"Không có vị trí", website:"trang web", contact:"Liên hệ", notes:"Ghi chú", approve:"Duyệt", reject:"Từ chối", suspend:"Đình chỉ", edit:"Sửa", delete:"Xóa", create:"+ Tạo nguồn đã xác minh", newTitle:"Nguồn đã xác minh mới", namePh:"Tên *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://trang web", descPh:"Mô tả", creating:"Đang tạo…", createApproved:"Tạo (đã duyệt)", cancel:"Hủy", editTitle:"Chỉnh sửa nguồn đã xác minh", close:"Đóng", contactName:"Tên liên hệ", contactEmail:"Email liên hệ", contactPhone:"Điện thoại liên hệ", countryPh:"Mã quốc gia (US) *", lat:"Vĩ độ", lng:"Kinh độ", regeo:"Geocode lại", saving:"Đang lưu…", saveChanges:"Lưu thay đổi", confirmDelete:"Xóa tổ chức này và tất cả cập nhật? Không thể hoàn tác.", reasonReject:"Lý do từ chối (tùy chọn):", reasonSuspend:"Lý do đình chỉ (tùy chọn):" },
  th: { gov:"รัฐบาล", police:"ตำรวจ", fire:"ดับเพลิง", school:"โรงเรียน", news:"ข่าว", assoc:"กลุ่มชุมชน", nonprofit:"ไม่แสวงหากำไร", business:"ธุรกิจ", other:"อื่นๆ", pending:"รอดำเนินการ", approved:"อนุมัติแล้ว", rejected:"ถูกปฏิเสธ", suspended:"ถูกระงับ", all:"ทั้งหมด", allTypes:"ทุกประเภท", searchPh:"ค้นหาชื่อ / slug / คำอธิบาย", city:"เมือง", state:"รัฐ (CA)", noMatch:"ไม่มีองค์กรที่ตรงกับตัวกรอง", loading:"กำลังโหลด…", noLoc:"ไม่มีตำแหน่ง", website:"เว็บไซต์", contact:"ติดต่อ", notes:"บันทึก", approve:"อนุมัติ", reject:"ปฏิเสธ", suspend:"ระงับ", edit:"แก้ไข", delete:"ลบ", create:"+ สร้างแหล่งที่ตรวจสอบแล้ว", newTitle:"แหล่งที่ตรวจสอบแล้วใหม่", namePh:"ชื่อ *", slugPh:"slug", emojiPh:"อีโมจิ (🏛)", websitePh:"https://เว็บไซต์", descPh:"คำอธิบาย", creating:"กำลังสร้าง…", createApproved:"สร้าง (อนุมัติแล้ว)", cancel:"ยกเลิก", editTitle:"แก้ไขแหล่งที่ตรวจสอบแล้ว", close:"ปิด", contactName:"ชื่อผู้ติดต่อ", contactEmail:"อีเมลผู้ติดต่อ", contactPhone:"โทรศัพท์ผู้ติดต่อ", countryPh:"รหัสประเทศ (US) *", lat:"ละติจูด", lng:"ลองจิจูด", regeo:"ระบุพิกัดใหม่", saving:"กำลังบันทึก…", saveChanges:"บันทึกการเปลี่ยนแปลง", confirmDelete:"ลบองค์กรนี้และการอัปเดตทั้งหมด? ไม่สามารถยกเลิกได้", reasonReject:"เหตุผลปฏิเสธ (ไม่บังคับ):", reasonSuspend:"เหตุผลระงับ (ไม่บังคับ):" },
  sv: { gov:"Myndighet", police:"Polis", fire:"Brandkår", school:"Skola", news:"Nyheter", assoc:"Gemenskapsgrupp", nonprofit:"Ideell", business:"Företag", other:"Övrigt", pending:"väntande", approved:"godkänd", rejected:"avvisad", suspended:"avstängd", all:"alla", allTypes:"Alla typer", searchPh:"Sök namn / slug / beskrivning", city:"Stad", state:"Delstat (CA)", noMatch:"Inga organisationer matchar filtren.", loading:"Laddar…", noLoc:"Ingen plats", website:"webbplats", contact:"Kontakt", notes:"Anteckningar", approve:"Godkänn", reject:"Avvisa", suspend:"Stäng av", edit:"Redigera", delete:"Ta bort", create:"+ Skapa verifierad källa", newTitle:"Ny verifierad källa", namePh:"Namn *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://webbplats", descPh:"Beskrivning", creating:"Skapar…", createApproved:"Skapa (godkänd)", cancel:"Avbryt", editTitle:"Redigera verifierad källa", close:"Stäng", contactName:"Kontaktnamn", contactEmail:"Kontakt e-post", contactPhone:"Kontakt telefon", countryPh:"Landskod (US) *", lat:"Latitud", lng:"Longitud", regeo:"Geokoda igen", saving:"Sparar…", saveChanges:"Spara ändringar", confirmDelete:"Ta bort denna organisation och alla uppdateringar? Kan inte ångras.", reasonReject:"Anledning till avslag (valfritt):", reasonSuspend:"Anledning till avstängning (valfritt):" },
  pl: { gov:"Rząd", police:"Policja", fire:"Straż pożarna", school:"Szkoła", news:"Wiadomości", assoc:"Grupa społeczna", nonprofit:"Non-profit", business:"Biznes", other:"Inne", pending:"oczekujące", approved:"zatwierdzone", rejected:"odrzucone", suspended:"zawieszone", all:"wszystkie", allTypes:"Wszystkie typy", searchPh:"Szukaj nazwa / slug / opis", city:"Miasto", state:"Stan (CA)", noMatch:"Żadna organizacja nie pasuje.", loading:"Ładowanie…", noLoc:"Brak lokalizacji", website:"strona", contact:"Kontakt", notes:"Notatki", approve:"Zatwierdź", reject:"Odrzuć", suspend:"Zawieś", edit:"Edytuj", delete:"Usuń", create:"+ Utwórz zweryfikowane źródło", newTitle:"Nowe zweryfikowane źródło", namePh:"Nazwa *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://strona", descPh:"Opis", creating:"Tworzenie…", createApproved:"Utwórz (zatwierdzone)", cancel:"Anuluj", editTitle:"Edytuj zweryfikowane źródło", close:"Zamknij", contactName:"Nazwa kontaktu", contactEmail:"Email kontaktu", contactPhone:"Telefon kontaktu", countryPh:"Kod kraju (US) *", lat:"Szerokość", lng:"Długość", regeo:"Geokoduj ponownie", saving:"Zapisywanie…", saveChanges:"Zapisz zmiany", confirmDelete:"Usunąć tę organizację i wszystkie aktualizacje? Nie można cofnąć.", reasonReject:"Powód odrzucenia (opcjonalnie):", reasonSuspend:"Powód zawieszenia (opcjonalnie):" },
  tr: { gov:"Hükümet", police:"Polis", fire:"İtfaiye", school:"Okul", news:"Haber", assoc:"Topluluk grubu", nonprofit:"Kâr amacı gütmeyen", business:"İşletme", other:"Diğer", pending:"beklemede", approved:"onaylandı", rejected:"reddedildi", suspended:"askıya alındı", all:"tümü", allTypes:"Tüm türler", searchPh:"İsim / slug / açıklama ara", city:"Şehir", state:"Eyalet (CA)", noMatch:"Filtrelere uyan kuruluş yok.", loading:"Yükleniyor…", noLoc:"Konum yok", website:"web sitesi", contact:"İletişim", notes:"Notlar", approve:"Onayla", reject:"Reddet", suspend:"Askıya al", edit:"Düzenle", delete:"Sil", create:"+ Doğrulanmış kaynak oluştur", newTitle:"Yeni doğrulanmış kaynak", namePh:"İsim *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://web sitesi", descPh:"Açıklama", creating:"Oluşturuluyor…", createApproved:"Oluştur (onaylandı)", cancel:"İptal", editTitle:"Doğrulanmış kaynağı düzenle", close:"Kapat", contactName:"İletişim adı", contactEmail:"İletişim e-postası", contactPhone:"İletişim telefonu", countryPh:"Ülke kodu (US) *", lat:"Enlem", lng:"Boylam", regeo:"Yeniden coğrafi kodla", saving:"Kaydediliyor…", saveChanges:"Değişiklikleri kaydet", confirmDelete:"Bu kuruluşu ve tüm güncellemeleri sil? Geri alınamaz.", reasonReject:"Ret nedeni (isteğe bağlı):", reasonSuspend:"Askıya alma nedeni (isteğe bağlı):" },
  uk: { gov:"Уряд", police:"Поліція", fire:"Пожежна", school:"Школа", news:"Новини", assoc:"Громадська група", nonprofit:"Неприбуткова", business:"Бізнес", other:"Інше", pending:"очікує", approved:"схвалено", rejected:"відхилено", suspended:"призупинено", all:"всі", allTypes:"Всі типи", searchPh:"Пошук ім'я / слаг / опис", city:"Місто", state:"Штат (CA)", noMatch:"Жодна організація не відповідає фільтрам.", loading:"Завантаження…", noLoc:"Немає локації", website:"вебсайт", contact:"Контакт", notes:"Нотатки", approve:"Схвалити", reject:"Відхилити", suspend:"Призупинити", edit:"Редагувати", delete:"Видалити", create:"+ Створити перевірене джерело", newTitle:"Нове перевірене джерело", namePh:"Ім'я *", slugPh:"слаг", emojiPh:"Емодзі (🏛)", websitePh:"https://сайт", descPh:"Опис", creating:"Створення…", createApproved:"Створити (схвалено)", cancel:"Скасувати", editTitle:"Редагувати перевірене джерело", close:"Закрити", contactName:"Ім'я контакту", contactEmail:"Email контакту", contactPhone:"Телефон контакту", countryPh:"Код країни (US) *", lat:"Широта", lng:"Довгота", regeo:"Перегеокодувати", saving:"Збереження…", saveChanges:"Зберегти зміни", confirmDelete:"Видалити цю організацію та всі оновлення? Не можна скасувати.", reasonReject:"Причина відхилення (необов'язково):", reasonSuspend:"Причина призупинення (необов'язково):" },
  el: { gov:"Κυβέρνηση", police:"Αστυνομία", fire:"Πυροσβεστική", school:"Σχολείο", news:"Ειδήσεις", assoc:"Κοινοτική ομάδα", nonprofit:"Μη κερδοσκοπικός", business:"Επιχείρηση", other:"Άλλο", pending:"εκκρεμεί", approved:"εγκρίθηκε", rejected:"απορρίφθηκε", suspended:"ανεστάλη", all:"όλα", allTypes:"Όλοι οι τύποι", searchPh:"Αναζήτηση όνομα / slug / περιγραφή", city:"Πόλη", state:"Πολιτεία (CA)", noMatch:"Καμία οργάνωση δεν ταιριάζει.", loading:"Φόρτωση…", noLoc:"Χωρίς τοποθεσία", website:"ιστοσελίδα", contact:"Επαφή", notes:"Σημειώσεις", approve:"Έγκριση", reject:"Απόρριψη", suspend:"Αναστολή", edit:"Επεξεργασία", delete:"Διαγραφή", create:"+ Δημιουργία επαληθευμένης πηγής", newTitle:"Νέα επαληθευμένη πηγή", namePh:"Όνομα *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://ιστοσελίδα", descPh:"Περιγραφή", creating:"Δημιουργία…", createApproved:"Δημιουργία (εγκρίθηκε)", cancel:"Ακύρωση", editTitle:"Επεξεργασία επαληθευμένης πηγής", close:"Κλείσιμο", contactName:"Όνομα επαφής", contactEmail:"Email επαφής", contactPhone:"Τηλέφωνο επαφής", countryPh:"Κωδικός χώρας (US) *", lat:"Γεωγραφικό πλάτος", lng:"Γεωγραφικό μήκος", regeo:"Επαναγεωκωδικοποίηση", saving:"Αποθήκευση…", saveChanges:"Αποθήκευση αλλαγών", confirmDelete:"Διαγραφή αυτού του οργανισμού και όλων των ενημερώσεων; Μη αναστρέψιμο.", reasonReject:"Λόγος απόρριψης (προαιρετικό):", reasonSuspend:"Λόγος αναστολής (προαιρετικό):" },
  he: { gov:"ממשלה", police:"משטרה", fire:"כבאות", school:"בית ספר", news:"חדשות", assoc:"קבוצה קהילתית", nonprofit:"ללא מטרות רווח", business:"עסק", other:"אחר", pending:"ממתין", approved:"אושר", rejected:"נדחה", suspended:"מושעה", all:"הכל", allTypes:"כל הסוגים", searchPh:"חיפוש שם / slug / תיאור", city:"עיר", state:"מדינה (CA)", noMatch:"אין ארגונים תואמים למסננים.", loading:"טוען…", noLoc:"אין מיקום", website:"אתר", contact:"איש קשר", notes:"הערות", approve:"אשר", reject:"דחה", suspend:"השעה", edit:"ערוך", delete:"מחק", create:"+ צור מקור מאומת", newTitle:"מקור מאומת חדש", namePh:"שם *", slugPh:"slug", emojiPh:"אמוג'י (🏛)", websitePh:"https://אתר", descPh:"תיאור", creating:"יוצר…", createApproved:"צור (אושר)", cancel:"ביטול", editTitle:"ערוך מקור מאומת", close:"סגור", contactName:"שם איש קשר", contactEmail:"אימייל איש קשר", contactPhone:"טלפון איש קשר", countryPh:"קוד מדינה (US) *", lat:"קו רוחב", lng:"קו אורך", regeo:"קוד מחדש גיאוגרפי", saving:"שומר…", saveChanges:"שמור שינויים", confirmDelete:"למחוק ארגון זה וכל העדכונים? לא ניתן לביטול.", reasonReject:"סיבת דחייה (אופציונלי):", reasonSuspend:"סיבת השעיה (אופציונלי):" },
  ur: { gov:"حکومت", police:"پولیس", fire:"فائر", school:"اسکول", news:"خبریں", assoc:"کمیونٹی گروپ", nonprofit:"غیر منافع بخش", business:"کاروبار", other:"دیگر", pending:"زیر التوا", approved:"منظور شدہ", rejected:"مسترد", suspended:"معطل", all:"سب", allTypes:"تمام اقسام", searchPh:"نام / سلگ / تفصیل تلاش کریں", city:"شہر", state:"ریاست (CA)", noMatch:"ان فلٹرز سے کوئی تنظیم میل نہیں کھاتی۔", loading:"لوڈ ہو رہا…", noLoc:"کوئی مقام نہیں", website:"ویب سائٹ", contact:"رابطہ", notes:"نوٹس", approve:"منظور", reject:"مسترد", suspend:"معطل", edit:"ترمیم", delete:"حذف", create:"+ تصدیق شدہ ذریعہ بنائیں", newTitle:"نیا تصدیق شدہ ذریعہ", namePh:"نام *", slugPh:"سلگ", emojiPh:"ایموجی (🏛)", websitePh:"https://ویب سائٹ", descPh:"تفصیل", creating:"بنا رہا…", createApproved:"بنائیں (منظور شدہ)", cancel:"منسوخ", editTitle:"تصدیق شدہ ذریعہ ترمیم کریں", close:"بند کریں", contactName:"رابطہ نام", contactEmail:"رابطہ ایمیل", contactPhone:"رابطہ فون", countryPh:"ملک کوڈ (US) *", lat:"عرض بلد", lng:"طول بلد", regeo:"دوبارہ جیو کوڈ", saving:"محفوظ ہو رہا…", saveChanges:"تبدیلیاں محفوظ کریں", confirmDelete:"اس تنظیم اور تمام اپ ڈیٹس کو حذف کریں؟ واپس نہیں ہو سکتا۔", reasonReject:"مسترد کرنے کی وجہ (اختیاری):", reasonSuspend:"معطل کرنے کی وجہ (اختیاری):" },
  fa: { gov:"دولت", police:"پلیس", fire:"آتش نشانی", school:"مدرسه", news:"اخبار", assoc:"گروه اجتماعی", nonprofit:"غیرانتفاعی", business:"کسب و کار", other:"دیگر", pending:"در انتظار", approved:"تأیید شده", rejected:"رد شده", suspended:"تعلیق شده", all:"همه", allTypes:"همه انواع", searchPh:"جستجوی نام / اسلاگ / توضیح", city:"شهر", state:"ایالت (CA)", noMatch:"هیچ سازمانی با این فیلترها مطابقت ندارد.", loading:"در حال بارگذاری…", noLoc:"بدون مکان", website:"وب سایت", contact:"تماس", notes:"یادداشت ها", approve:"تأیید", reject:"رد", suspend:"تعلیق", edit:"ویرایش", delete:"حذف", create:"+ ایجاد منبع تأیید شده", newTitle:"منبع تأیید شده جدید", namePh:"نام *", slugPh:"اسلاگ", emojiPh:"ایموجی (🏛)", websitePh:"https://وب سایت", descPh:"توضیح", creating:"در حال ایجاد…", createApproved:"ایجاد (تأیید شده)", cancel:"لغو", editTitle:"ویرایش منبع تأیید شده", close:"بستن", contactName:"نام تماس", contactEmail:"ایمیل تماس", contactPhone:"تلفن تماس", countryPh:"کد کشور (US) *", lat:"عرض جغرافیایی", lng:"طول جغرافیایی", regeo:"باز-ژئوکد", saving:"در حال ذخیره…", saveChanges:"ذخیره تغییرات", confirmDelete:"این سازمان و همه به روز رسانی ها حذف شود؟ غیرقابل بازگشت است.", reasonReject:"دلیل رد (اختیاری):", reasonSuspend:"دلیل تعلیق (اختیاری):" },
  ms: { gov:"Kerajaan", police:"Polis", fire:"Bomba", school:"Sekolah", news:"Berita", assoc:"Kumpulan komuniti", nonprofit:"Bukan untung", business:"Perniagaan", other:"Lain-lain", pending:"tertunda", approved:"diluluskan", rejected:"ditolak", suspended:"digantung", all:"semua", allTypes:"Semua jenis", searchPh:"Cari nama / slug / penerangan", city:"Bandar", state:"Negeri (CA)", noMatch:"Tiada organisasi sepadan.", loading:"Memuat…", noLoc:"Tiada lokasi", website:"laman web", contact:"Kenalan", notes:"Nota", approve:"Luluskan", reject:"Tolak", suspend:"Gantung", edit:"Edit", delete:"Padam", create:"+ Cipta sumber disahkan", newTitle:"Sumber disahkan baharu", namePh:"Nama *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://laman web", descPh:"Penerangan", creating:"Mencipta…", createApproved:"Cipta (diluluskan)", cancel:"Batal", editTitle:"Edit sumber disahkan", close:"Tutup", contactName:"Nama kenalan", contactEmail:"E-mel kenalan", contactPhone:"Telefon kenalan", countryPh:"Kod negara (US) *", lat:"Latitud", lng:"Longitud", regeo:"Geokod semula", saving:"Menyimpan…", saveChanges:"Simpan perubahan", confirmDelete:"Padam organisasi ini dan semua kemas kini? Tidak boleh undur.", reasonReject:"Sebab penolakan (pilihan):", reasonSuspend:"Sebab penggantungan (pilihan):" },
  ro: { gov:"Guvern", police:"Poliție", fire:"Pompieri", school:"Școală", news:"Știri", assoc:"Grup comunitar", nonprofit:"Nonprofit", business:"Afacere", other:"Altul", pending:"în așteptare", approved:"aprobat", rejected:"respins", suspended:"suspendat", all:"toate", allTypes:"Toate tipurile", searchPh:"Caută nume / slug / descriere", city:"Oraș", state:"Stat (CA)", noMatch:"Nicio organizație nu corespunde.", loading:"Se încarcă…", noLoc:"Fără locație", website:"site web", contact:"Contact", notes:"Notițe", approve:"Aprobă", reject:"Respinge", suspend:"Suspendă", edit:"Editează", delete:"Șterge", create:"+ Creează sursă verificată", newTitle:"Sursă verificată nouă", namePh:"Nume *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://site", descPh:"Descriere", creating:"Se creează…", createApproved:"Creează (aprobat)", cancel:"Anulează", editTitle:"Editează sursă verificată", close:"Închide", contactName:"Nume contact", contactEmail:"Email contact", contactPhone:"Telefon contact", countryPh:"Cod țară (US) *", lat:"Latitudine", lng:"Longitudine", regeo:"Re-geocodare", saving:"Se salvează…", saveChanges:"Salvează modificările", confirmDelete:"Ștergi această organizație și toate actualizările? Ireversibil.", reasonReject:"Motiv respingere (opțional):", reasonSuspend:"Motiv suspendare (opțional):" },
  cs: { gov:"Vláda", police:"Policie", fire:"Hasiči", school:"Škola", news:"Zprávy", assoc:"Komunitní skupina", nonprofit:"Nezisková", business:"Podnik", other:"Jiné", pending:"čeká", approved:"schváleno", rejected:"zamítnuto", suspended:"pozastaveno", all:"vše", allTypes:"Všechny typy", searchPh:"Hledat název / slug / popis", city:"Město", state:"Stát (CA)", noMatch:"Žádná organizace neodpovídá.", loading:"Načítání…", noLoc:"Žádné místo", website:"web", contact:"Kontakt", notes:"Poznámky", approve:"Schválit", reject:"Zamítnout", suspend:"Pozastavit", edit:"Upravit", delete:"Smazat", create:"+ Vytvořit ověřený zdroj", newTitle:"Nový ověřený zdroj", namePh:"Název *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://web", descPh:"Popis", creating:"Vytváření…", createApproved:"Vytvořit (schváleno)", cancel:"Zrušit", editTitle:"Upravit ověřený zdroj", close:"Zavřít", contactName:"Jméno kontaktu", contactEmail:"Email kontaktu", contactPhone:"Telefon kontaktu", countryPh:"Kód země (US) *", lat:"Zem. šířka", lng:"Zem. délka", regeo:"Překódovat", saving:"Ukládání…", saveChanges:"Uložit změny", confirmDelete:"Smazat tuto organizaci a všechny aktualizace? Nelze vrátit.", reasonReject:"Důvod zamítnutí (volitelné):", reasonSuspend:"Důvod pozastavení (volitelné):" },
  hu: { gov:"Kormány", police:"Rendőrség", fire:"Tűzoltóság", school:"Iskola", news:"Hírek", assoc:"Közösségi csoport", nonprofit:"Nonprofit", business:"Vállalkozás", other:"Egyéb", pending:"függő", approved:"jóváhagyva", rejected:"elutasítva", suspended:"felfüggesztve", all:"összes", allTypes:"Minden típus", searchPh:"Keresés név / slug / leírás", city:"Város", state:"Állam (CA)", noMatch:"Nincs szervezet ami megfelel.", loading:"Betöltés…", noLoc:"Nincs hely", website:"weboldal", contact:"Kapcsolat", notes:"Jegyzetek", approve:"Jóváhagy", reject:"Elutasít", suspend:"Felfüggeszt", edit:"Szerkeszt", delete:"Töröl", create:"+ Hitelesített forrás létrehozása", newTitle:"Új hitelesített forrás", namePh:"Név *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://weboldal", descPh:"Leírás", creating:"Létrehozás…", createApproved:"Létrehoz (jóváhagyva)", cancel:"Mégse", editTitle:"Hitelesített forrás szerkesztése", close:"Bezárás", contactName:"Kapcsolat neve", contactEmail:"Kapcsolat e-mail", contactPhone:"Kapcsolat telefon", countryPh:"Országkód (US) *", lat:"Szélesség", lng:"Hosszúság", regeo:"Újra geokódolás", saving:"Mentés…", saveChanges:"Változtatások mentése", confirmDelete:"Törli ezt a szervezetet és összes frissítését? Nem vonható vissza.", reasonReject:"Elutasítás oka (opcionális):", reasonSuspend:"Felfüggesztés oka (opcionális):" },
  fi: { gov:"Hallitus", police:"Poliisi", fire:"Palokunta", school:"Koulu", news:"Uutiset", assoc:"Yhteisöryhmä", nonprofit:"Voittoa tavoittelematon", business:"Yritys", other:"Muu", pending:"odottaa", approved:"hyväksytty", rejected:"hylätty", suspended:"keskeytetty", all:"kaikki", allTypes:"Kaikki tyypit", searchPh:"Hae nimi / slug / kuvaus", city:"Kaupunki", state:"Osavaltio (CA)", noMatch:"Mikään organisaatio ei vastaa.", loading:"Ladataan…", noLoc:"Ei sijaintia", website:"verkkosivusto", contact:"Yhteyshenkilö", notes:"Muistiinpanot", approve:"Hyväksy", reject:"Hylkää", suspend:"Keskeytä", edit:"Muokkaa", delete:"Poista", create:"+ Luo vahvistettu lähde", newTitle:"Uusi vahvistettu lähde", namePh:"Nimi *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://verkkosivusto", descPh:"Kuvaus", creating:"Luodaan…", createApproved:"Luo (hyväksytty)", cancel:"Peruuta", editTitle:"Muokkaa vahvistettua lähdettä", close:"Sulje", contactName:"Yhteyshenkilön nimi", contactEmail:"Yhteyshenkilön sähköposti", contactPhone:"Yhteyshenkilön puhelin", countryPh:"Maakoodi (US) *", lat:"Leveysaste", lng:"Pituusaste", regeo:"Geokoodaa uudelleen", saving:"Tallennetaan…", saveChanges:"Tallenna muutokset", confirmDelete:"Poistetaanko tämä organisaatio ja kaikki päivitykset? Ei voi perua.", reasonReject:"Hylkäyssyy (valinnainen):", reasonSuspend:"Keskeytyssyy (valinnainen):" },
  no: { gov:"Myndighet", police:"Politi", fire:"Brannvesen", school:"Skole", news:"Nyheter", assoc:"Samfunnsgruppe", nonprofit:"Ideell", business:"Bedrift", other:"Annet", pending:"venter", approved:"godkjent", rejected:"avvist", suspended:"suspendert", all:"alle", allTypes:"Alle typer", searchPh:"Søk navn / slug / beskrivelse", city:"By", state:"Stat (CA)", noMatch:"Ingen organisasjoner matcher.", loading:"Laster…", noLoc:"Ingen plassering", website:"nettsted", contact:"Kontakt", notes:"Notater", approve:"Godkjenn", reject:"Avvis", suspend:"Suspender", edit:"Rediger", delete:"Slett", create:"+ Opprett verifisert kilde", newTitle:"Ny verifisert kilde", namePh:"Navn *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://nettsted", descPh:"Beskrivelse", creating:"Oppretter…", createApproved:"Opprett (godkjent)", cancel:"Avbryt", editTitle:"Rediger verifisert kilde", close:"Lukk", contactName:"Kontaktnavn", contactEmail:"Kontakt e-post", contactPhone:"Kontakt telefon", countryPh:"Landskode (US) *", lat:"Breddegrad", lng:"Lengdegrad", regeo:"Geokod på nytt", saving:"Lagrer…", saveChanges:"Lagre endringer", confirmDelete:"Slette denne organisasjonen og alle oppdateringer? Kan ikke angres.", reasonReject:"Årsak til avvisning (valgfritt):", reasonSuspend:"Årsak til suspensjon (valgfritt):" },
  da: { gov:"Myndighed", police:"Politi", fire:"Brandvæsen", school:"Skole", news:"Nyheder", assoc:"Fællesskabsgruppe", nonprofit:"Nonprofit", business:"Virksomhed", other:"Andet", pending:"afventer", approved:"godkendt", rejected:"afvist", suspended:"suspenderet", all:"alle", allTypes:"Alle typer", searchPh:"Søg navn / slug / beskrivelse", city:"By", state:"Stat (CA)", noMatch:"Ingen organisationer matcher.", loading:"Indlæser…", noLoc:"Ingen placering", website:"hjemmeside", contact:"Kontakt", notes:"Noter", approve:"Godkend", reject:"Afvis", suspend:"Suspender", edit:"Rediger", delete:"Slet", create:"+ Opret verificeret kilde", newTitle:"Ny verificeret kilde", namePh:"Navn *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://hjemmeside", descPh:"Beskrivelse", creating:"Opretter…", createApproved:"Opret (godkendt)", cancel:"Annuller", editTitle:"Rediger verificeret kilde", close:"Luk", contactName:"Kontaktnavn", contactEmail:"Kontakt e-mail", contactPhone:"Kontakt telefon", countryPh:"Landekode (US) *", lat:"Breddegrad", lng:"Længdegrad", regeo:"Geokod igen", saving:"Gemmer…", saveChanges:"Gem ændringer", confirmDelete:"Slette denne organisation og alle opdateringer? Kan ikke fortrydes.", reasonReject:"Årsag til afvisning (valgfrit):", reasonSuspend:"Årsag til suspension (valgfrit):" },
  bg: { gov:"Правителство", police:"Полиция", fire:"Пожарна", school:"Училище", news:"Новини", assoc:"Общностна група", nonprofit:"Нестопанска", business:"Бизнес", other:"Друго", pending:"чакащо", approved:"одобрено", rejected:"отхвърлено", suspended:"спряно", all:"всички", allTypes:"Всички видове", searchPh:"Търси име / слаг / описание", city:"Град", state:"Щат (CA)", noMatch:"Няма организации по филтрите.", loading:"Зареждане…", noLoc:"Няма местоположение", website:"уебсайт", contact:"Контакт", notes:"Бележки", approve:"Одобри", reject:"Отхвърли", suspend:"Спри", edit:"Редактирай", delete:"Изтрий", create:"+ Създай верифициран източник", newTitle:"Нов верифициран източник", namePh:"Име *", slugPh:"слаг", emojiPh:"Емоджи (🏛)", websitePh:"https://уебсайт", descPh:"Описание", creating:"Създаване…", createApproved:"Създай (одобрено)", cancel:"Отказ", editTitle:"Редактирай верифициран източник", close:"Затвори", contactName:"Име за контакт", contactEmail:"Email за контакт", contactPhone:"Телефон за контакт", countryPh:"Код на държава (US) *", lat:"Ширина", lng:"Дължина", regeo:"Прегеокодирай", saving:"Запазване…", saveChanges:"Запази промените", confirmDelete:"Изтриване на тази организация и всички обновления? Необратимо.", reasonReject:"Причина за отхвърляне (по избор):", reasonSuspend:"Причина за спиране (по избор):" },
  hr: { gov:"Vlada", police:"Policija", fire:"Vatrogasci", school:"Škola", news:"Vijesti", assoc:"Zajednička grupa", nonprofit:"Neprofitna", business:"Tvrtka", other:"Ostalo", pending:"na čekanju", approved:"odobreno", rejected:"odbijeno", suspended:"suspendirano", all:"sve", allTypes:"Sve vrste", searchPh:"Traži ime / slug / opis", city:"Grad", state:"Država (CA)", noMatch:"Nijedna organizacija ne odgovara.", loading:"Učitavanje…", noLoc:"Nema lokacije", website:"web stranica", contact:"Kontakt", notes:"Bilješke", approve:"Odobri", reject:"Odbij", suspend:"Suspendiraj", edit:"Uredi", delete:"Obriši", create:"+ Stvori verificirani izvor", newTitle:"Novi verificirani izvor", namePh:"Ime *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://web stranica", descPh:"Opis", creating:"Stvaranje…", createApproved:"Stvori (odobreno)", cancel:"Otkaži", editTitle:"Uredi verificirani izvor", close:"Zatvori", contactName:"Ime kontakta", contactEmail:"Email kontakta", contactPhone:"Telefon kontakta", countryPh:"Kod države (US) *", lat:"Širina", lng:"Dužina", regeo:"Ponovno geokodiraj", saving:"Spremanje…", saveChanges:"Spremi promjene", confirmDelete:"Izbrisati ovu organizaciju i sva ažuriranja? Nepovratno.", reasonReject:"Razlog odbijanja (neobavezno):", reasonSuspend:"Razlog suspenzije (neobavezno):" },
  sr: { gov:"Влада", police:"Полиција", fire:"Ватрогасци", school:"Школа", news:"Вести", assoc:"Група заједнице", nonprofit:"Непрофитна", business:"Предузеће", other:"Остало", pending:"на чекању", approved:"одобрено", rejected:"одбијено", suspended:"суспендовано", all:"све", allTypes:"Све врсте", searchPh:"Претражи име / слаг / опис", city:"Град", state:"Држава (CA)", noMatch:"Ниједна организација не одговара.", loading:"Учитавање…", noLoc:"Нема локације", website:"веб сајт", contact:"Контакт", notes:"Белешке", approve:"Одобри", reject:"Одбиј", suspend:"Суспендуј", edit:"Уреди", delete:"Обриши", create:"+ Направи верификован извор", newTitle:"Нови верификован извор", namePh:"Име *", slugPh:"слаг", emojiPh:"Емоји (🏛)", websitePh:"https://веб сајт", descPh:"Опис", creating:"Прављење…", createApproved:"Направи (одобрено)", cancel:"Откажи", editTitle:"Уреди верификован извор", close:"Затвори", contactName:"Име контакта", contactEmail:"Имејл контакта", contactPhone:"Телефон контакта", countryPh:"Код државе (US) *", lat:"Ширина", lng:"Дужина", regeo:"Поновно геокодирај", saving:"Чување…", saveChanges:"Сачувај измене", confirmDelete:"Обрисати ову организацију и сва ажурирања? Неповратно.", reasonReject:"Разлог одбијања (опционо):", reasonSuspend:"Разлог суспензије (опционо):" },
  sk: { gov:"Vláda", police:"Polícia", fire:"Hasiči", school:"Škola", news:"Správy", assoc:"Komunitná skupina", nonprofit:"Nezisková", business:"Podnik", other:"Iné", pending:"čaká", approved:"schválené", rejected:"zamietnuté", suspended:"pozastavené", all:"všetky", allTypes:"Všetky typy", searchPh:"Hľadať názov / slug / popis", city:"Mesto", state:"Štát (CA)", noMatch:"Žiadna organizácia nezodpovedá.", loading:"Načítanie…", noLoc:"Žiadna poloha", website:"web", contact:"Kontakt", notes:"Poznámky", approve:"Schváliť", reject:"Zamietnuť", suspend:"Pozastaviť", edit:"Upraviť", delete:"Vymazať", create:"+ Vytvoriť overený zdroj", newTitle:"Nový overený zdroj", namePh:"Názov *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://web", descPh:"Popis", creating:"Vytváranie…", createApproved:"Vytvoriť (schválené)", cancel:"Zrušiť", editTitle:"Upraviť overený zdroj", close:"Zavrieť", contactName:"Meno kontaktu", contactEmail:"Email kontaktu", contactPhone:"Telefón kontaktu", countryPh:"Kód krajiny (US) *", lat:"Zem. šírka", lng:"Zem. dĺžka", regeo:"Prekódovať", saving:"Ukladanie…", saveChanges:"Uložiť zmeny", confirmDelete:"Vymazať túto organizáciu a všetky aktualizácie? Nevratné.", reasonReject:"Dôvod zamietnutia (voliteľné):", reasonSuspend:"Dôvod pozastavenia (voliteľné):" },
  sl: { gov:"Vlada", police:"Policija", fire:"Gasilci", school:"Šola", news:"Novice", assoc:"Skupnostna skupina", nonprofit:"Neprofitna", business:"Podjetje", other:"Drugo", pending:"v čakanju", approved:"odobreno", rejected:"zavrnjeno", suspended:"začasno ustavljeno", all:"vse", allTypes:"Vse vrste", searchPh:"Išči ime / slug / opis", city:"Mesto", state:"Država (CA)", noMatch:"Nobena organizacija ne ustreza.", loading:"Nalaganje…", noLoc:"Brez lokacije", website:"spletna stran", contact:"Kontakt", notes:"Opombe", approve:"Odobri", reject:"Zavrni", suspend:"Začasno ustavi", edit:"Uredi", delete:"Izbriši", create:"+ Ustvari preverjen vir", newTitle:"Nov preverjen vir", namePh:"Ime *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://spletna stran", descPh:"Opis", creating:"Ustvarjanje…", createApproved:"Ustvari (odobreno)", cancel:"Prekliči", editTitle:"Uredi preverjen vir", close:"Zapri", contactName:"Ime kontakta", contactEmail:"E-pošta kontakta", contactPhone:"Telefon kontakta", countryPh:"Koda države (US) *", lat:"Širina", lng:"Dolžina", regeo:"Ponovno geokodiraj", saving:"Shranjevanje…", saveChanges:"Shrani spremembe", confirmDelete:"Izbrisati to organizacijo in vse posodobitve? Nepovratno.", reasonReject:"Razlog zavrnitve (neobvezno):", reasonSuspend:"Razlog začasne ustavitve (neobvezno):" },
  et: { gov:"Valitsus", police:"Politsei", fire:"Pääste", school:"Kool", news:"Uudised", assoc:"Kogukonna rühm", nonprofit:"Mittetulundus", business:"Ettevõte", other:"Muu", pending:"ootel", approved:"kinnitatud", rejected:"tagasi lükatud", suspended:"peatatud", all:"kõik", allTypes:"Kõik tüübid", searchPh:"Otsi nimi / slug / kirjeldus", city:"Linn", state:"Osariik (CA)", noMatch:"Ükski organisatsioon ei vasta.", loading:"Laadimine…", noLoc:"Asukohta pole", website:"veebisait", contact:"Kontakt", notes:"Märkmed", approve:"Kinnita", reject:"Lükka tagasi", suspend:"Peata", edit:"Muuda", delete:"Kustuta", create:"+ Loo kinnitatud allikas", newTitle:"Uus kinnitatud allikas", namePh:"Nimi *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://veebisait", descPh:"Kirjeldus", creating:"Loomine…", createApproved:"Loo (kinnitatud)", cancel:"Tühista", editTitle:"Muuda kinnitatud allikat", close:"Sulge", contactName:"Kontakti nimi", contactEmail:"Kontakti e-post", contactPhone:"Kontakti telefon", countryPh:"Riigikood (US) *", lat:"Laiuskraad", lng:"Pikkuskraad", regeo:"Geokodeeri uuesti", saving:"Salvestamine…", saveChanges:"Salvesta muudatused", confirmDelete:"Kustutada see organisatsioon ja kõik uuendused? Tagasipööramatu.", reasonReject:"Tagasilükkamise põhjus (valikuline):", reasonSuspend:"Peatamise põhjus (valikuline):" },
  lv: { gov:"Valdība", police:"Policija", fire:"Ugunsdzēsēji", school:"Skola", news:"Ziņas", assoc:"Kopienas grupa", nonprofit:"Bezpeļņas", business:"Uzņēmums", other:"Cits", pending:"gaida", approved:"apstiprināts", rejected:"noraidīts", suspended:"apturēts", all:"visi", allTypes:"Visi veidi", searchPh:"Meklēt nosaukums / slug / apraksts", city:"Pilsēta", state:"Štats (CA)", noMatch:"Neviena organizācija neatbilst.", loading:"Ielādē…", noLoc:"Nav atrašanās vietas", website:"vietne", contact:"Kontakts", notes:"Piezīmes", approve:"Apstiprināt", reject:"Noraidīt", suspend:"Apturēt", edit:"Rediģēt", delete:"Dzēst", create:"+ Izveidot verificētu avotu", newTitle:"Jauns verificēts avots", namePh:"Nosaukums *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://vietne", descPh:"Apraksts", creating:"Izveido…", createApproved:"Izveidot (apstiprināts)", cancel:"Atcelt", editTitle:"Rediģēt verificētu avotu", close:"Aizvērt", contactName:"Kontakta vārds", contactEmail:"Kontakta e-pasts", contactPhone:"Kontakta tālrunis", countryPh:"Valsts kods (US) *", lat:"Platums", lng:"Garums", regeo:"Pārkodēt", saving:"Saglabā…", saveChanges:"Saglabāt izmaiņas", confirmDelete:"Dzēst šo organizāciju un visus atjauninājumus? Neatgriezeniski.", reasonReject:"Noraidīšanas iemesls (neobligāti):", reasonSuspend:"Apturēšanas iemesls (neobligāti):" },
  lt: { gov:"Vyriausybė", police:"Policija", fire:"Ugniagesiai", school:"Mokykla", news:"Naujienos", assoc:"Bendruomenės grupė", nonprofit:"Ne pelno", business:"Verslas", other:"Kita", pending:"laukiama", approved:"patvirtinta", rejected:"atmesta", suspended:"sustabdyta", all:"visi", allTypes:"Visi tipai", searchPh:"Ieškoti pavadinimas / slug / aprašymas", city:"Miestas", state:"Valstija (CA)", noMatch:"Jokia organizacija neatitinka.", loading:"Įkeliama…", noLoc:"Nėra vietos", website:"svetainė", contact:"Kontaktas", notes:"Pastabos", approve:"Patvirtinti", reject:"Atmesti", suspend:"Sustabdyti", edit:"Redaguoti", delete:"Ištrinti", create:"+ Sukurti patvirtintą šaltinį", newTitle:"Naujas patvirtintas šaltinis", namePh:"Pavadinimas *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://svetainė", descPh:"Aprašymas", creating:"Kuriama…", createApproved:"Sukurti (patvirtinta)", cancel:"Atšaukti", editTitle:"Redaguoti patvirtintą šaltinį", close:"Uždaryti", contactName:"Kontakto vardas", contactEmail:"Kontakto el. paštas", contactPhone:"Kontakto telefonas", countryPh:"Šalies kodas (US) *", lat:"Platuma", lng:"Ilguma", regeo:"Perkoduoti", saving:"Saugoma…", saveChanges:"Išsaugoti pakeitimus", confirmDelete:"Ištrinti šią organizaciją ir visus atnaujinimus? Negrįžtama.", reasonReject:"Atmetimo priežastis (pasirinktinai):", reasonSuspend:"Sustabdymo priežastis (pasirinktinai):" },
  be: { gov:"Урад", police:"Паліцыя", fire:"Пажарная", school:"Школа", news:"Навіны", assoc:"Супольная група", nonprofit:"Некамерцыйная", business:"Бізнес", other:"Іншае", pending:"чакае", approved:"ухвалена", rejected:"адхілена", suspended:"прыпынена", all:"усе", allTypes:"Усе тыпы", searchPh:"Пошук імя / слаг / апісанне", city:"Горад", state:"Штат (CA)", noMatch:"Ніводная арганізацыя не адпавядае.", loading:"Загрузка…", noLoc:"Няма месца", website:"сайт", contact:"Кантакт", notes:"Нататкі", approve:"Ухваліць", reject:"Адхіліць", suspend:"Прыпыніць", edit:"Рэдагаваць", delete:"Выдаліць", create:"+ Стварыць правераную крыніцу", newTitle:"Новая правераная крыніца", namePh:"Імя *", slugPh:"слаг", emojiPh:"Эмодзі (🏛)", websitePh:"https://сайт", descPh:"Апісанне", creating:"Стварэнне…", createApproved:"Стварыць (ухвалена)", cancel:"Скасаваць", editTitle:"Рэдагаваць правераную крыніцу", close:"Закрыць", contactName:"Імя кантакту", contactEmail:"Email кантакту", contactPhone:"Тэлефон кантакту", countryPh:"Код краіны (US) *", lat:"Шырата", lng:"Даўгата", regeo:"Перагеакадаваць", saving:"Захаванне…", saveChanges:"Захаваць змены", confirmDelete:"Выдаліць гэтую арганізацыю і ўсе абнаўленні? Неабарачальна.", reasonReject:"Прычына адхілення (неабавязкова):", reasonSuspend:"Прычына прыпынення (неабавязкова):" },
  ka: { gov:"მთავრობა", police:"პოლიცია", fire:"სახანძრო", school:"სკოლა", news:"სიახლეები", assoc:"საზოგადოების ჯგუფი", nonprofit:"არაკომერციული", business:"ბიზნესი", other:"სხვა", pending:"მოლოდინში", approved:"დამტკიცებული", rejected:"უარყოფილი", suspended:"შეჩერებული", all:"ყველა", allTypes:"ყველა ტიპი", searchPh:"ძებნა სახელი / სლაგი / აღწერა", city:"ქალაქი", state:"შტატი (CA)", noMatch:"არცერთი ორგანიზაცია არ ემთხვევა.", loading:"იტვირთება…", noLoc:"ადგილი არ არის", website:"ვებსაიტი", contact:"კონტაქტი", notes:"შენიშვნები", approve:"დამტკიცება", reject:"უარყოფა", suspend:"შეჩერება", edit:"რედაქტირება", delete:"წაშლა", create:"+ შექმენი დადასტურებული წყარო", newTitle:"ახალი დადასტურებული წყარო", namePh:"სახელი *", slugPh:"სლაგი", emojiPh:"ემოჯი (🏛)", websitePh:"https://ვებსაიტი", descPh:"აღწერა", creating:"შექმნა…", createApproved:"შექმნა (დამტკიცებული)", cancel:"გაუქმება", editTitle:"დადასტურებული წყაროს რედაქტირება", close:"დახურვა", contactName:"კონტაქტის სახელი", contactEmail:"კონტაქტის ელფოსტა", contactPhone:"კონტაქტის ტელეფონი", countryPh:"ქვეყნის კოდი (US) *", lat:"განედი", lng:"გრძედი", regeo:"ხელახლა გეოკოდირება", saving:"შენახვა…", saveChanges:"ცვლილებების შენახვა", confirmDelete:"წავშალო ეს ორგანიზაცია და ყველა განახლება? შეუქცევადია.", reasonReject:"უარყოფის მიზეზი (არასავალდებულო):", reasonSuspend:"შეჩერების მიზეზი (არასავალდებულო):" },
  hy: { gov:"Կառավարություն", police:"Ոստիկանություն", fire:"Հրշեջ", school:"Դպրոց", news:"Նորություններ", assoc:"Համայնքային խումբ", nonprofit:"Ոչ առևտրային", business:"Բիզնես", other:"Այլ", pending:"սպասվում է", approved:"հաստատված", rejected:"մերժված", suspended:"կասեցված", all:"բոլորը", allTypes:"Բոլոր տեսակները", searchPh:"Որոնել անուն / սլագ / նկարագրություն", city:"Քաղաք", state:"Նահանգ (CA)", noMatch:"Ոչ մի կազմակերպություն չի համապատասխանում։", loading:"Բեռնում…", noLoc:"Տեղադրություն չկա", website:"կայք", contact:"Կոնտակտ", notes:"Նշումներ", approve:"Հաստատել", reject:"Մերժել", suspend:"Կասեցնել", edit:"Խմբագրել", delete:"Ջնջել", create:"+ Ստեղծել հաստատված աղբյուր", newTitle:"Նոր հաստատված աղբյուր", namePh:"Անուն *", slugPh:"սլագ", emojiPh:"Էմոջի (🏛)", websitePh:"https://կայք", descPh:"Նկարագրություն", creating:"Ստեղծում…", createApproved:"Ստեղծել (հաստատված)", cancel:"Չեղարկել", editTitle:"Խմբագրել հաստատված աղբյուրը", close:"Փակել", contactName:"Կոնտակտի անուն", contactEmail:"Կոնտակտի էլ. փոստ", contactPhone:"Կոնտակտի հեռախոս", countryPh:"Երկրի կոդ (US) *", lat:"Լայնություն", lng:"Երկայնություն", regeo:"Վերագեոկոդավորել", saving:"Պահպանում…", saveChanges:"Պահպանել փոփոխությունները", confirmDelete:"Ջնջե՞լ այս կազմակերպությունը և բոլոր թարմացումները։ Անդառնալի է։", reasonReject:"Մերժման պատճառ (ոչ պարտադիր)։", reasonSuspend:"Կասեցման պատճառ (ոչ պարտադիր)։" },
  az: { gov:"Hökumət", police:"Polis", fire:"Yanğınsöndürmə", school:"Məktəb", news:"Xəbərlər", assoc:"İcma qrupu", nonprofit:"Qeyri-kommersiya", business:"Biznes", other:"Digər", pending:"gözləmədə", approved:"təsdiqləndi", rejected:"rədd edildi", suspended:"dayandırıldı", all:"hamısı", allTypes:"Bütün növlər", searchPh:"Ad / slug / təsvir axtar", city:"Şəhər", state:"Ştat (CA)", noMatch:"Filtrlərə uyğun təşkilat yoxdur.", loading:"Yüklənir…", noLoc:"Məkan yoxdur", website:"veb sayt", contact:"Əlaqə", notes:"Qeydlər", approve:"Təsdiqlə", reject:"Rədd et", suspend:"Dayandır", edit:"Redaktə et", delete:"Sil", create:"+ Təsdiqlənmiş mənbə yarat", newTitle:"Yeni təsdiqlənmiş mənbə", namePh:"Ad *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://veb sayt", descPh:"Təsvir", creating:"Yaradılır…", createApproved:"Yarat (təsdiqləndi)", cancel:"Ləğv et", editTitle:"Təsdiqlənmiş mənbəni redaktə et", close:"Bağla", contactName:"Əlaqə adı", contactEmail:"Əlaqə e-poçtu", contactPhone:"Əlaqə telefonu", countryPh:"Ölkə kodu (US) *", lat:"En", lng:"Uzun", regeo:"Yenidən geokodla", saving:"Yadda saxlanır…", saveChanges:"Dəyişiklikləri yadda saxla", confirmDelete:"Bu təşkilatı və bütün yeniləmələri silinsin? Geri qaytarılmaz.", reasonReject:"Rədd səbəbi (könüllü):", reasonSuspend:"Dayandırma səbəbi (könüllü):" },
  kk: { gov:"Үкімет", police:"Полиция", fire:"Өрт сөндіру", school:"Мектеп", news:"Жаңалықтар", assoc:"Қауымдастық тобы", nonprofit:"Коммерциялық емес", business:"Бизнес", other:"Басқа", pending:"күтуде", approved:"бекітілді", rejected:"қабылданбады", suspended:"тоқтатылды", all:"барлығы", allTypes:"Барлық түрлер", searchPh:"Атау / слаг / сипаттама іздеу", city:"Қала", state:"Штат (CA)", noMatch:"Сүзгілерге сәйкес ұйым жоқ.", loading:"Жүктелуде…", noLoc:"Орын жоқ", website:"веб-сайт", contact:"Байланыс", notes:"Ескертпелер", approve:"Бекіту", reject:"Қабылдамау", suspend:"Тоқтату", edit:"Өңдеу", delete:"Жою", create:"+ Расталған дереккөз жасау", newTitle:"Жаңа расталған дереккөз", namePh:"Атау *", slugPh:"слаг", emojiPh:"Эмодзи (🏛)", websitePh:"https://веб-сайт", descPh:"Сипаттама", creating:"Жасалуда…", createApproved:"Жасау (бекітілді)", cancel:"Болдырмау", editTitle:"Расталған дереккөзді өңдеу", close:"Жабу", contactName:"Байланыс аты", contactEmail:"Байланыс email", contactPhone:"Байланыс телефоны", countryPh:"Ел коды (US) *", lat:"Ендік", lng:"Бойлық", regeo:"Қайта геокодтау", saving:"Сақталуда…", saveChanges:"Өзгерістерді сақтау", confirmDelete:"Бұл ұйымды және барлық жаңартуларды жою керек пе? Қайтарылмайды.", reasonReject:"Қабылдамау себебі (міндетті емес):", reasonSuspend:"Тоқтату себебі (міндетті емес):" },
  ky: { gov:"Өкмөт", police:"Полиция", fire:"Өрт өчүрүү", school:"Мектеп", news:"Жаңылыктар", assoc:"Жамааттык топ", nonprofit:"Коммерциялык эмес", business:"Бизнес", other:"Башка", pending:"күтүүдө", approved:"бекитилди", rejected:"четке кагылды", suspended:"токтотулду", all:"баары", allTypes:"Бардык түрлөр", searchPh:"Аталыш / слаг / сүрөттөмө издөө", city:"Шаар", state:"Штат (CA)", noMatch:"Чыпкаларга туура келген уюм жок.", loading:"Жүктөлүүдө…", noLoc:"Жайгашуу жок", website:"веб-сайт", contact:"Байланыш", notes:"Эскертмелер", approve:"Бекитүү", reject:"Четке кагуу", suspend:"Токтотуу", edit:"Түзөтүү", delete:"Жок кылуу", create:"+ Тастыкталган булак түзүү", newTitle:"Жаңы тастыкталган булак", namePh:"Аталыш *", slugPh:"слаг", emojiPh:"Эмодзи (🏛)", websitePh:"https://веб-сайт", descPh:"Сүрөттөмө", creating:"Түзүлүүдө…", createApproved:"Түзүү (бекитилди)", cancel:"Жокко чыгаруу", editTitle:"Тастыкталган булакты түзөтүү", close:"Жабуу", contactName:"Байланыш аты", contactEmail:"Байланыш email", contactPhone:"Байланыш телефону", countryPh:"Өлкө коду (US) *", lat:"Туурасы", lng:"Узундугу", regeo:"Кайра геокоддоо", saving:"Сакталууда…", saveChanges:"Өзгөртүүлөрдү сактоо", confirmDelete:"Бул уюмду жана бардык жаңыртууларды жок кылуу керекпи? Кайтарылгыс.", reasonReject:"Четке кагуу себеби (милдеттүү эмес):", reasonSuspend:"Токтотуу себеби (милдеттүү эмес):" },
  uz: { gov:"Hukumat", police:"Politsiya", fire:"O't o'chirish", school:"Maktab", news:"Yangiliklar", assoc:"Jamiyat guruhi", nonprofit:"Notijorat", business:"Biznes", other:"Boshqa", pending:"kutilmoqda", approved:"tasdiqlandi", rejected:"rad etildi", suspended:"to'xtatildi", all:"hammasi", allTypes:"Barcha turlar", searchPh:"Nom / slug / tavsif qidirish", city:"Shahar", state:"Shtat (CA)", noMatch:"Filtrlarga mos tashkilot yo'q.", loading:"Yuklanmoqda…", noLoc:"Joylashuv yo'q", website:"veb-sayt", contact:"Aloqa", notes:"Eslatmalar", approve:"Tasdiqlash", reject:"Rad etish", suspend:"To'xtatish", edit:"Tahrirlash", delete:"O'chirish", create:"+ Tasdiqlangan manba yaratish", newTitle:"Yangi tasdiqlangan manba", namePh:"Nom *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://veb-sayt", descPh:"Tavsif", creating:"Yaratilmoqda…", createApproved:"Yaratish (tasdiqlandi)", cancel:"Bekor qilish", editTitle:"Tasdiqlangan manbani tahrirlash", close:"Yopish", contactName:"Aloqa ismi", contactEmail:"Aloqa email", contactPhone:"Aloqa telefoni", countryPh:"Mamlakat kodi (US) *", lat:"Kenglik", lng:"Uzunlik", regeo:"Qayta geokodlash", saving:"Saqlanmoqda…", saveChanges:"O'zgarishlarni saqlash", confirmDelete:"Ushbu tashkilot va barcha yangilanishlar o'chirilsinmi? Qaytarib bo'lmaydi.", reasonReject:"Rad etish sababi (ixtiyoriy):", reasonSuspend:"To'xtatish sababi (ixtiyoriy):" },
  tg: { gov:"Ҳукумат", police:"Полис", fire:"Оташнишонӣ", school:"Мактаб", news:"Хабарҳо", assoc:"Гурӯҳи ҷомеа", nonprofit:"Ғайритиҷоратӣ", business:"Тиҷорат", other:"Дигар", pending:"интизор", approved:"тасдиқ шуд", rejected:"рад шуд", suspended:"боздошта шуд", all:"ҳама", allTypes:"Ҳама намудҳо", searchPh:"Ҷустуҷӯи ном / слаг / тавсиф", city:"Шаҳр", state:"Иёлот (CA)", noMatch:"Ҳеҷ созмоне ба ин филтрҳо мувофиқ нест.", loading:"Боркунӣ…", noLoc:"Макон нест", website:"вебсайт", contact:"Тамос", notes:"Ёддоштҳо", approve:"Тасдиқ", reject:"Рад", suspend:"Боздошт", edit:"Таҳрир", delete:"Нест кардан", create:"+ Манбаи тасдиқшуда эҷод кунед", newTitle:"Манбаи нави тасдиқшуда", namePh:"Ном *", slugPh:"слаг", emojiPh:"Эмодзи (🏛)", websitePh:"https://вебсайт", descPh:"Тавсиф", creating:"Эҷод…", createApproved:"Эҷод (тасдиқ шуд)", cancel:"Бекор", editTitle:"Манбаи тасдиқшударо таҳрир кунед", close:"Пӯшидан", contactName:"Номи тамос", contactEmail:"Email-и тамос", contactPhone:"Телефони тамос", countryPh:"Коди кишвар (US) *", lat:"Арз", lng:"Тӯл", regeo:"Боз-геокод", saving:"Захира…", saveChanges:"Захираи тағйирот", confirmDelete:"Ин созмон ва ҳама навсозиҳоро нест кардан? Бозгаштнопазир.", reasonReject:"Сабаби рад (ихтиёрӣ):", reasonSuspend:"Сабаби боздошт (ихтиёрӣ):" },
  mn: { gov:"Засгийн газар", police:"Цагдаа", fire:"Гал түймэр", school:"Сургууль", news:"Мэдээ", assoc:"Олон нийтийн бүлэг", nonprofit:"Ашгийн бус", business:"Бизнес", other:"Бусад", pending:"хүлээгдэж буй", approved:"зөвшөөрөгдсөн", rejected:"татгалзсан", suspended:"түдгэлзүүлсэн", all:"бүгд", allTypes:"Бүх төрөл", searchPh:"Нэр / slug / тайлбар хайх", city:"Хот", state:"Муж (CA)", noMatch:"Шүүлтүүрт тохирох байгууллага алга.", loading:"Ачааллаж байна…", noLoc:"Байршилгүй", website:"вебсайт", contact:"Холбоо барих", notes:"Тэмдэглэл", approve:"Зөвшөөрөх", reject:"Татгалзах", suspend:"Түдгэлзүүлэх", edit:"Засах", delete:"Устгах", create:"+ Баталгаажсан эх үүсвэр үүсгэх", newTitle:"Шинэ баталгаажсан эх үүсвэр", namePh:"Нэр *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://вебсайт", descPh:"Тайлбар", creating:"Үүсгэж байна…", createApproved:"Үүсгэх (зөвшөөрөгдсөн)", cancel:"Цуцлах", editTitle:"Баталгаажсан эх үүсвэрийг засах", close:"Хаах", contactName:"Холбоо барих нэр", contactEmail:"Холбоо барих имэйл", contactPhone:"Холбоо барих утас", countryPh:"Улсын код (US) *", lat:"Өргөрөг", lng:"Уртраг", regeo:"Дахин геокодлох", saving:"Хадгалж байна…", saveChanges:"Өөрчлөлтийг хадгалах", confirmDelete:"Энэ байгууллага болон бүх шинэчлэлтийг устгах уу? Буцаах боломжгүй.", reasonReject:"Татгалзах шалтгаан (заавал биш):", reasonSuspend:"Түдгэлзүүлэх шалтгаан (заавал биш):" },
  km: { gov:"រដ្ឋាភិបាល", police:"ប៉ូលីស", fire:"ពន្លត់អគ្គីភ័យ", school:"សាលា", news:"ព័ត៌មាន", assoc:"ក្រុមសហគមន៍", nonprofit:"មិនរកប្រាក់ចំណេញ", business:"អាជីវកម្ម", other:"ផ្សេងទៀត", pending:"រង់ចាំ", approved:"បានអនុម័ត", rejected:"បានបដិសេធ", suspended:"បានផ្អាក", all:"ទាំងអស់", allTypes:"គ្រប់ប្រភេទ", searchPh:"ស្វែងរកឈ្មោះ / slug / ការពិពណ៌នា", city:"ទីក្រុង", state:"រដ្ឋ (CA)", noMatch:"គ្មានអង្គការណាដែលត្រូវនឹងតម្រង។", loading:"កំពុងផ្ទុក…", noLoc:"គ្មានទីតាំង", website:"គេហទំព័រ", contact:"ទំនាក់ទំនង", notes:"កំណត់ចំណាំ", approve:"អនុម័ត", reject:"បដិសេធ", suspend:"ផ្អាក", edit:"កែសម្រួល", delete:"លុប", create:"+ បង្កើតប្រភពដែលបានផ្ទៀងផ្ទាត់", newTitle:"ប្រភពដែលបានផ្ទៀងផ្ទាត់ថ្មី", namePh:"ឈ្មោះ *", slugPh:"slug", emojiPh:"Emoji (🏛)", websitePh:"https://គេហទំព័រ", descPh:"ការពិពណ៌នា", creating:"កំពុងបង្កើត…", createApproved:"បង្កើត (បានអនុម័ត)", cancel:"បោះបង់", editTitle:"កែសម្រួលប្រភពដែលបានផ្ទៀងផ្ទាត់", close:"បិទ", contactName:"ឈ្មោះទំនាក់ទំនង", contactEmail:"អ៊ីមែលទំនាក់ទំនង", contactPhone:"ទូរស័ព្ទទំនាក់ទំនង", countryPh:"លេខកូដប្រទេស (US) *", lat:"រយៈទទឹង", lng:"រយៈបណ្តោយ", regeo:"Geocode ឡើងវិញ", saving:"កំពុងរក្សាទុក…", saveChanges:"រក្សាទុកការផ្លាស់ប្តូរ", confirmDelete:"លុបអង្គការនេះ និងការអាប់ដេតទាំងអស់? មិនអាចត្រឡប់វិញបានទេ។", reasonReject:"មូលហេតុបដិសេធ (ស្រេចចិត្ត):", reasonSuspend:"មូលហេតុផ្អាក (ស្រេចចិត្ត):" },
  lo: { gov:"ລັດຖະບານ", police:"ຕຳຫຼວດ", fire:"ດັບເພີງ", school:"ໂຮງຮຽນ", news:"ຂ່າວ", assoc:"ກຸ່ມຊຸມຊົນ", nonprofit:"ບໍ່ຫວັງຜົນກຳໄລ", business:"ທຸລະກິດ", other:"ອື່ນໆ", pending:"ລໍຖ້າ", approved:"ອະນຸມັດແລ້ວ", rejected:"ຖືກປະຕິເສດ", suspended:"ຖືກລະງັບ", all:"ທັງໝົດ", allTypes:"ທຸກປະເພດ", searchPh:"ຄົ້ນຫາຊື່ / slug / ຄຳອະທິບາຍ", city:"ເມືອງ", state:"ລັດ (CA)", noMatch:"ບໍ່ມີອົງການທີ່ກົງກັບຕົວກອງ", loading:"ກຳລັງໂຫຼດ…", noLoc:"ບໍ່ມີທີ່ຕັ້ງ", website:"ເວັບໄຊ", contact:"ຕິດຕໍ່", notes:"ບັນທຶກ", approve:"ອະນຸມັດ", reject:"ປະຕິເສດ", suspend:"ລະງັບ", edit:"ແກ້ໄຂ", delete:"ລຶບ", create:"+ ສ້າງແຫຼ່ງທີ່ຢັ້ງຢືນແລ້ວ", newTitle:"ແຫຼ່ງທີ່ຢັ້ງຢືນແລ້ວໃໝ່", namePh:"ຊື່ *", slugPh:"slug", emojiPh:"ອີໂມຈິ (🏛)", websitePh:"https://ເວັບໄຊ", descPh:"ຄຳອະທິບາຍ", creating:"ກຳລັງສ້າງ…", createApproved:"ສ້າງ (ອະນຸມັດແລ້ວ)", cancel:"ຍົກເລີກ", editTitle:"ແກ້ໄຂແຫຼ່ງທີ່ຢັ້ງຢືນແລ້ວ", close:"ປິດ", contactName:"ຊື່ຜູ້ຕິດຕໍ່", contactEmail:"ອີເມວຜູ້ຕິດຕໍ່", contactPhone:"ໂທລະສັບຜູ້ຕິດຕໍ່", countryPh:"ລະຫັດປະເທດ (US) *", lat:"ເສັ້ນຂະໜານ", lng:"ເສັ້ນແວງ", regeo:"ກຳນົດພິກັດໃໝ່", saving:"ກຳລັງບັນທຶກ…", saveChanges:"ບັນທຶກການປ່ຽນແປງ", confirmDelete:"ລຶບອົງການນີ້ແລະການອັບເດທັງໝົດ? ບໍ່ສາມາດຍົກເລີກໄດ້", reasonReject:"ເຫດຜົນປະຕິເສດ (ທາງເລືອກ):", reasonSuspend:"ເຫດຜົນລະງັບ (ທາງເລືອກ):" },
  my: { gov:"အစိုးရ", police:"ရဲ", fire:"မီးသတ်", school:"ကျောင်း", news:"သတင်း", assoc:"အသိုင်းအဝိုင်းအဖွဲ့", nonprofit:"အကျိုးအမြတ်မယူသော", business:"လုပ်ငန်း", other:"အခြား", pending:"ဆိုင်းငံ့ထားသည်", approved:"အတည်ပြုပြီး", rejected:"ပယ်ချပြီး", suspended:"ဆိုင်းငံ့ထားသည်", all:"အားလုံး", allTypes:"အမျိုးအစားအားလုံး", searchPh:"အမည် / slug / ဖော်ပြချက်ရှာရန်", city:"မြို့", state:"ပြည်နယ် (CA)", noMatch:"စစ်ထုတ်မှုများနှင့်ကိုက်ညီသောအဖွဲ့အစည်းမရှိပါ။", loading:"တင်နေသည်…", noLoc:"တည်နေရာမရှိပါ", website:"ဝက်ဘ်ဆိုက်", contact:"အဆက်အသွယ်", notes:"မှတ်စုများ", approve:"အတည်ပြုရန်", reject:"ပယ်ချရန်", suspend:"ဆိုင်းငံ့ရန်", edit:"ပြင်ဆင်ရန်", delete:"ဖျက်ရန်", create:"+ အတည်ပြုထားသောရင်းမြစ်ဖန်တီးရန်", newTitle:"အတည်ပြုထားသောရင်းမြစ်အသစ်", namePh:"အမည် *", slugPh:"slug", emojiPh:"အီမိုဂျီ (🏛)", websitePh:"https://ဝက်ဘ်ဆိုက်", descPh:"ဖော်ပြချက်", creating:"ဖန်တီးနေသည်…", createApproved:"ဖန်တီးရန် (အတည်ပြုပြီး)", cancel:"ပယ်ဖျက်ရန်", editTitle:"အတည်ပြုထားသောရင်းမြစ်ကိုပြင်ဆင်ရန်", close:"ပိတ်ရန်", contactName:"အဆက်အသွယ်အမည်", contactEmail:"အဆက်အသွယ်အီးမေးလ်", contactPhone:"အဆက်အသွယ်ဖုန်း", countryPh:"နိုင်ငံကုဒ် (US) *", lat:"လတ္တီကျု", lng:"လောင်ဂျီကျု", regeo:"ပြန်လည်ဘူမိကုဒ်သွင်းရန်", saving:"သိမ်းနေသည်…", saveChanges:"ပြောင်းလဲမှုများသိမ်းရန်", confirmDelete:"ဤအဖွဲ့အစည်းနှင့် အပ်ဒိတ်အားလုံးကိုဖျက်မလား? ပြန်ဖျက်မရပါ။", reasonReject:"ပယ်ချရသည့်အကြောင်းရင်း (ရွေးချယ်နိုင်သည်):", reasonSuspend:"ဆိုင်းငံ့ရသည့်အကြောင်းရင်း (ရွေးချယ်နိုင်သည်):" },
}

const KIND_KEYS = ['gov','police','fire','school','news','assoc','nonprofit','business','other'] as const

function slugify(s: string) { return s.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80) }
async function forwardGeocode(city: string, state: string) {
  if (!city) return { lat: null as number | null, lng: null as number | null }
  const q = encodeURIComponent([city, state].filter(Boolean).join(', '))
  try {
    const r = await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${q}`)
    if (!r.ok) return { lat: null, lng: null }
    const j: any = await r.json()
    if (!Array.isArray(j) || j.length === 0) return { lat: null, lng: null }
    return { lat: Number(j[0].lat), lng: Number(j[0].lon) }
  } catch { return { lat: null, lng: null } }
}

export function AdminVerifiedSources() {
  const { language } = useLanguage()
  const d = D[language] || D.en
  const KIND_OPTIONS = KIND_KEYS.map(k=> ({ value:k, label: d[k] }))
  const [tab, setTab] = useState<'pending'|'approved'|'rejected'|'suspended'|'all'>('pending')
  const [kindFilter, setKindFilter] = useState<'' | typeof KIND_KEYS[number]>('')
  const [cityFilter, setCityFilter] = useState('')
  const [stateFilter, setStateFilter] = useState('')
  const [search, setSearch] = useState('')
  const [debouncedSearch, setDebouncedSearch] = useState('')
  const [rows, setRows] = useState<VerifiedSourceAdminRow[] | null>(null)
  const [err, setErr] = useState('')
  const [reloadKey, setReloadKey] = useState(0)
  const [editing, setEditing] = useState<VerifiedSourceAdminRow | null>(null)

  useEffect(() => { const t = setTimeout(()=> setDebouncedSearch(search.trim()), 300); return ()=> clearTimeout(t) }, [search])

  useEffect(() => {
    let cancelled = false
    setRows(null)
    listAllVerifiedSources({ data: { status: tab, kind: kindFilter||undefined, city: cityFilter.trim()||undefined, state_code: stateFilter.trim()||undefined, q: debouncedSearch||undefined } as any })
    .then(r=> { if(!cancelled) setRows(r) })
    .catch(e=> { if(!cancelled) setErr(e?.message?? 'Failed to load') })
    return ()=> { cancelled = true }
  }, [tab, kindFilter, cityFilter, stateFilter, debouncedSearch, reloadKey])

  const reload = ()=> setReloadKey(n=> n+1)

  async function setStatus(id: string, status: 'approved'|'rejected'|'suspended'|'pending', notes?: string|null){
    try { await adminReviewVerifiedSource({ data: { id, status, review_notes: notes??null } }); reload() }
    catch (e:any){ alert(e?.message?? 'Failed') }
  }
  async function remove(id: string){
    if(!confirm(d.confirmDelete)) return
    try { await adminDeleteVerifiedSource({ data: { id } }); reload() }
    catch (e:any){ alert(e?.message?? 'Failed') }
  }

  return (
    <div className="space-y-6">
      <CreateForm dict={d} onCreated={reload} />
      <div className="flex flex-wrap gap-2">
        {(['pending','approved','rejected','suspended','all'] as const).map(t=>(
          <button key={t} onClick={()=> setTab(t)} className={`rounded-full border px-3.5 py-1.5 text-xs font-semibold capitalize ${tab===t? 'border-transparent bg-foreground text-background' : 'border-border bg-background text-muted-foreground'}`}>{d[t]}</button>
        ))}
      </div>
      <div className="grid gap-2 rounded-2xl border border-border bg-card p-3 sm:grid-cols-4">
        <input value={search} onChange={e=>setSearch(e.target.value)} placeholder={d.searchPh} className={cls} />
        <select value={kindFilter} onChange={e=> setKindFilter(e.target.value as any)} className={cls}>
          <option value="">{d.allTypes}</option>
          {KIND_OPTIONS.map(o=> <option key={o.value} value={o.value}>{o.label}</option>)}
        </select>
        <input value={cityFilter} onChange={e=>setCityFilter(e.target.value)} placeholder={d.city} className={cls} />
        <input value={stateFilter} onChange={e=>setStateFilter(e.target.value.toUpperCase().slice(0,4))} placeholder={d.state} className={cls} />
      </div>
      {err && <p className="text-sm text-destructive">{err}</p>}
      <div className="overflow-hidden rounded-2xl border border-border bg-card">
        <ul className="divide-y divide-border">
          {(rows?? []).map(r=>(
            <li key={r.id} className="p-4">
              <div className="flex flex-wrap items-start justify-between gap-2">
                <div className="min-w-0">
                  <div className="flex flex-wrap items-center gap-2">
                    {r.logo_emoji && <span aria-hidden>{r.logo_emoji}</span>}
                    <span className="font-semibold">{r.name}</span>
                    <StatusBadge status={r.status} dict={d} />
                    <span className="rounded-full bg-secondary px-2 py-0.5 text- font-semibold capitalize text-muted-foreground">{d[r.kind] || r.kind}</span>
                  </div>
                  <div className="mt-1 text-xs text-muted-foreground">
                    {[r.city, r.state_code].filter(Boolean).join(', ') || d.noLoc}
                    {r.latitude!=null && r.longitude!=null && <> · {r.latitude.toFixed(3)}, {r.longitude.toFixed(3)}</>}
                    {r.website && <> · <a href={r.website} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">{d.website}</a></>}
                    {r.contact_email && <> · {r.contact_email}</>}
                    {r.contact_phone && <> · {r.contact_phone}</>}
                  </div>
                  {r.contact_name && <p className="mt-0.5 text-xs text-muted-foreground">{d.contact}: {r.contact_name}</p>}
                  {r.description && <p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{r.description}</p>}
                  {r.review_notes && <p className="mt-1 text-xs italic text-muted-foreground">{d.notes}: {r.review_notes}</p>}
                </div>
                <div className="flex flex-wrap gap-2">
                  {r.status!== 'approved' && <button onClick={()=> setStatus(r.id,'approved')} className="rounded-full bg-primary px-3 py-1 text-xs font-semibold text-primary-foreground">{d.approve}</button>}
                  {r.status!== 'rejected' && <button onClick={()=>{ const notes = prompt(d.reasonReject)?? null; setStatus(r.id,'rejected', notes) }} className="rounded-full border border-border px-3 py-1 text-xs font-semibold">{d.reject}</button>}
                  {r.status!== 'suspended' && <button onClick={()=>{ const notes = prompt(d.reasonSuspend)?? null; setStatus(r.id,'suspended', notes) }} className="rounded-full border border-yellow-600 px-3 py-1 text-xs font-semibold text-yellow-700">{d.suspend}</button>}
                  <button onClick={()=> setEditing(r)} className="rounded-full border border-border px-3 py-1 text-xs font-semibold">{d.edit}</button>
                  <button onClick={()=> remove(r.id)} className="rounded-full border border-destructive px-3 py-1 text-xs font-semibold text-destructive">{d.delete}</button>
                </div>
              </div>
            </li>
          ))}
          {rows!==null && rows.length===0 && <li className="p-6 text-center text-sm text-muted-foreground">{d.noMatch}</li>}
          {rows===null && <li className="p-6 text-center text-sm text-muted-foreground">{d.loading}</li>}
        </ul>
      </div>
      {editing && <EditModal row={editing} dict={d} onClose={()=> setEditing(null)} onSaved={()=>{ setEditing(null); reload() }} />}
    </div>
  )
}

function StatusBadge({ status, dict }: { status: string, dict: any }) {
  const tone = status==='approved'? 'bg-primary/10 text-primary' : status==='pending'? 'bg-yellow-500/15 text-yellow-700' : status==='suspended'? 'bg-orange-500/15 text-orange-700' : 'bg-destructive/15 text-destructive'
  return <span className={`rounded-full px-2 py-0.5 text- font-semibold capitalize ${tone}`}>{dict[status] || status}</span>
}

function CreateForm({ onCreated, dict }: { onCreated: ()=>void, dict: any }) {
  const [open, setOpen] = useState(false)
  const [name, setName] = useState('')
  const [slug, setSlug] = useState('')
  const [slugTouched, setSlugTouched] = useState(false)
  const [kind, setKind] = useState<typeof KIND_KEYS[number]>('gov')
  const [emoji, setEmoji] = useState('')
  const [city, setCity] = useState('')
  const [stateCode, setStateCode] = useState('')
  const [countryCode, setCountryCode] = useState('')
  const [website, setWebsite] = useState('')
  const [description, setDescription] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [err, setErr] = useState<string|null>(null)
  useEffect(()=>{ if(!slugTouched) setSlug(slugify(name)) }, [name, slugTouched])
  async function submit(e: React.FormEvent){
    e.preventDefault(); setErr(null)
    if(!name.trim()||!city.trim()||!stateCode.trim()||!countryCode.trim()){ setErr('Name, city, state, and country are required.'); return }
    setSubmitting(true)
    try{
      const geo = await forwardGeocode(city, stateCode)
      await adminCreateVerifiedSource({ data: { name: name.trim(), slug: slug.trim()||slugify(name), kind, logo_emoji: emoji.trim()||null, description: description.trim()||null, website: website.trim()||null, contact_email: null, city: city.trim(), state_code: stateCode.trim().toUpperCase(), country_code: countryCode.trim().toUpperCase(), latitude: geo.lat, longitude: geo.lng, status: 'approved' } as any })
      setName(''); setSlug(''); setSlugTouched(false); setEmoji(''); setCity(''); setStateCode(''); setCountryCode(''); setWebsite(''); setDescription(''); setOpen(false); onCreated()
    }catch(e:any){ setErr(e?.message?? 'Failed to create') } finally { setSubmitting(false) }
  }
  if(!open) return <button onClick={()=> setOpen(true)} className="rounded-full bg-foreground px-4 py-2 text-sm font-semibold text-background">{dict.create}</button>
  return (
    <form onSubmit={submit} className="space-y-3 rounded-2xl border border-border bg-card p-4">
      <h3 className="text-sm font-semibold">{dict.newTitle}</h3>
      <div className="grid gap-3 sm:grid-cols-2">
        <input value={name} onChange={e=>setName(e.target.value)} placeholder={dict.namePh} required className={cls} />
        <input value={slug} onChange={e=>{ setSlugTouched(true); setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'')) }} placeholder={dict.slugPh} className={cls} />
        <select value={kind} onChange={e=> setKind(e.target.value as any)} className={cls}>{KIND_KEYS.map(k=> <option key={k} value={k}>{dict[k]}</option>)}</select>
        <input value={emoji} onChange={e=>setEmoji(e.target.value)} maxLength={4} placeholder={dict.emojiPh} className={cls} />
        <input value={city} onChange={e=>setCity(e.target.value)} placeholder={`${dict.city} *`} required className={cls} />
        <input value={stateCode} onChange={e=>setStateCode(e.target.value.toUpperCase().slice(0,4))} placeholder={`${dict.state} *`} required className={cls} />
        <input value={countryCode} onChange={e=>setCountryCode(e.target.value.toUpperCase().slice(0,2))} placeholder={dict.countryPh} required className={cls} />
        <input value={website} onChange={e=>setWebsite(e.target.value)} placeholder={dict.websitePh} className={cls} />
        <textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder={dict.descPh} rows={2} className={`${cls} sm:col-span-2`} />
      </div>
      {err && <p className="text-sm text-destructive">{err}</p>}
      <div className="flex gap-2">
        <button type="submit" disabled={submitting} className="rounded-full bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-60">{submitting? dict.creating : dict.createApproved}</button>
        <button type="button" onClick={()=> setOpen(false)} className="rounded-full border border-border px-4 py-2 text-sm">{dict.cancel}</button>
      </div>
    </form>
  )
}

function EditModal({ row, onClose, onSaved, dict }: { row: VerifiedSourceAdminRow; onClose: ()=>void; onSaved: ()=>void; dict: any }) {
  const [name, setName] = useState(row.name)
  const [kind, setKind] = useState<typeof KIND_KEYS[number]>(row.kind as any)
  const [emoji, setEmoji] = useState(row.logo_emoji?? '')
  const [description, setDescription] = useState(row.description?? '')
  const [website, setWebsite] = useState(row.website?? '')
  const [contactEmail, setContactEmail] = useState(row.contact_email?? '')
  const [contactName, setContactName] = useState(row.contact_name?? '')
  const [contactPhone, setContactPhone] = useState(row.contact_phone?? '')
  const [city, setCity] = useState(row.city?? '')
  const [stateCode, setStateCode] = useState(row.state_code?? '')
  const [countryCode, setCountryCode] = useState(row.country_code?? '')
  const [latitude, setLatitude] = useState<string>(row.latitude?.toString()?? '')
  const [longitude, setLongitude] = useState<string>(row.longitude?.toString()?? '')
  const [saving, setSaving] = useState(false)
  const [err, setErr] = useState<string|null>(null)
  async function save(){
    setErr(null); setSaving(true)
    try{
      const lat = latitude.trim()===''? null : Number(latitude)
      const lng = longitude.trim()===''? null : Number(longitude)
      if((lat!==null && Number.isNaN(lat)) || (lng!==null && Number.isNaN(lng))) throw new Error('Latitude and longitude must be numeric.')
      await adminUpdateVerifiedSource({ data: { id: row.id, name: name.trim(), kind, logo_emoji: emoji.trim()||null, description: description.trim()||null, website: website.trim()||null, contact_email: contactEmail.trim()||null, contact_name: contactName.trim()||null, contact_phone: contactPhone.trim()||null, city: city.trim()||null, state_code: stateCode.trim().toUpperCase()||null, country_code: countryCode.trim().toUpperCase()||null, latitude: lat, longitude: lng } as any })
      onSaved()
    }catch(e:any){ setErr(e?.message?? 'Failed to save') } finally { setSaving(false) }
  }
  async function regeocode(){ const geo = await forwardGeocode(city, stateCode); if(geo.lat!=null) setLatitude(String(geo.lat)); if(geo.lng!=null) setLongitude(String(geo.lng)) }
  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-foreground/40 p-4">
      <div className="w-full max-w-2xl rounded-3xl border border-border bg-card p-6 shadow-[var(--shadow-soft)]">
        <div className="flex items-center justify-between">
          <h3 className="font-display text-lg font-semibold">{dict.editTitle}</h3>
          <button onClick={onClose} className="text-sm text-muted-foreground hover:text-foreground">{dict.close}</button>
        </div>
        <div className="mt-4 grid gap-3 sm:grid-cols-2">
          <input value={name} onChange={e=>setName(e.target.value)} placeholder={dict.namePh} className={cls} />
          <select value={kind} onChange={e=> setKind(e.target.value as any)} className={cls}>{KIND_KEYS.map(k=> <option key={k} value={k}>{dict[k]}</option>)}</select>
          <input value={emoji} onChange={e=>setEmoji(e.target.value)} maxLength={4} placeholder={dict.emojiPh} className={cls} />
          <input value={website} onChange={e=>setWebsite(e.target.value)} placeholder={dict.websitePh} className={cls} />
          <input value={contactName} onChange={e=>setContactName(e.target.value)} placeholder={dict.contactName} className={cls} />
          <input value={contactEmail} onChange={e=>setContactEmail(e.target.value)} placeholder={dict.contactEmail} className={cls} />
          <input value={contactPhone} onChange={e=>setContactPhone(e.target.value)} placeholder={dict.contactPhone} className={cls} />
          <input value={city} onChange={e=>setCity(e.target.value)} placeholder={dict.city} className={cls} />
          <input value={stateCode} onChange={e=>setStateCode(e.target.value.toUpperCase().slice(0,4))} placeholder={dict.state} className={cls} />
          <input value={countryCode} onChange={e=>setCountryCode(e.target.value.toUpperCase().slice(0,2))} placeholder={dict.countryPh} className={cls} />
          <div className="flex gap-2 sm:col-span-2">
            <input value={latitude} onChange={e=>setLatitude(e.target.value)} placeholder={dict.lat} className={cls} />
            <input value={longitude} onChange={e=>setLongitude(e.target.value)} placeholder={dict.lng} className={cls} />
            <button type="button" onClick={regeocode} className="whitespace-nowrap rounded-xl border border-border px-3 text-sm">{dict.regeo}</button>
          </div>
          <textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} placeholder={dict.descPh} className={`${cls} sm:col-span-2`} />
        </div>
        {err && <p className="mt-3 text-sm text-destructive">{err}</p>}
        <div className="mt-5 flex justify-end gap-2">
          <button onClick={onClose} className="rounded-full border border-border px-4 py-2 text-sm">{dict.cancel}</button>
          <button onClick={save} disabled={saving} className="rounded-full bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-60">{saving? dict.saving : dict.saveChanges}</button>
        </div>
      </div>
    </div>
  )
}

const cls = 'rounded-xl border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary'
