import { useLanguage } from '@/lib/language-context'
import { useTranslations } from '@/lib/translations'

export function AutomatedBadge({ className = '' }: { className?: string }) {
  return (
    <span className={`inline-flex items-center gap-1 rounded-full border border-border bg-muted px-2 py-0.5 text- font-semibold uppercase tracking-wide text-muted-foreground ${className}`} title="Generated by Sweet Social Space Community Bot">
      <span aria-hidden>🤖</span>Automated
    </span>
  )
}
