/**
 * Badge shown on any item that was generated by the Sweet Social Space
 * Community Bot. Keep it small and unambiguous so users always know the
 * content is automated.
 */
export function AutomatedBadge({ className = '' }: { className?: string }) {
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full border border-border bg-muted px-2 py-0.5 text- font-semibold uppercase tracking-wide text-muted-foreground ${className}`}
      title="Generated by Sweet Social Space Community Bot"
    >
      <span aria-hidden>🤖</span>
      Automated
    </span>
  )
}
