'use client'
import { useLanguage } from '@/lib/language-context'

const D: Record<string, any> = {
  en: { automated:"Automated", title:"Generated by Sweet Social Space Community Bot" },
  es: { automated:"Automatizado", title:"Generado por Bot Comunitario Sweet Social Space" },
  fr: { automated:"Automatisé", title:"Généré par Bot Communautaire Sweet Social Space" },
  de: { automated:"Automatisiert", title:"Erstellt von Sweet Social Space Community Bot" },
  zh: { automated:"自动", title:"由 Sweet Social Space 社区机器人生成" },
  ja: { automated:"自動", title:"Sweet Social Space コミュニティボットにより生成" },
  ko: { automated:"자동", title:"Sweet Social Space 커뮤니티 봇이 생성" },
  pt: { automated:"Automatizado", title:"Gerado por Bot Comunitário Sweet Social Space" },
  ru: { automated:"Автоматически", title:"Сгенерировано ботом сообщества Sweet Social Space" },
  ar: { automated:"تلقائي", title:"تم إنشاؤه بواسطة روبوت مجتمع Sweet Social Space" },
  hi: { automated:"स्वचालित", title:"Sweet Social Space Community Bot द्वारा उत्पन्न" },
  it: { automated:"Automatizzato", title:"Generato da Bot Comunitario Sweet Social Space" },
  nl: { automated:"Geautomatiseerd", title:"Gegenereerd door Sweet Social Space Community Bot" },
  tl: { automated:"Automated", title:"Generated by Sweet Social Space Community Bot" },
  bn: { automated:"স্বয়ংক্রিয়", title:"Sweet Social Space Community Bot দ্বারা তৈরি" },
  id: { automated:"Otomatis", title:"Dihasilkan oleh Bot Komunitas Sweet Social Space" },
  vi: { automated:"Tự động", title:"Được tạo bởi Bot Cộng Đồng Sweet Social Space" },
  th: { automated:"อัตโนมัติ", title:"สร้างโดยบอทชุมชน Sweet Social Space" },
  sv: { automated:"Automatiserad", title:"Genererad av Sweet Social Space Community Bot" },
  pl: { automated:"Zautomatyzowane", title:"Wygenerowane przez Bota Społeczności Sweet Social Space" },
  tr: { automated:"Otomatik", title:"Sweet Social Space Topluluk Botu tarafından oluşturuldu" },
  uk: { automated:"Автоматично", title:"Згенеровано ботом спільноти Sweet Social Space" },
  el: { automated:"Αυτοματοποιημένο", title:"Δημιουργήθηκε από Bot Κοινότητας Sweet Social Space" },
  he: { automated:"אוטומטי", title:"נוצר על ידי בוט קהילתי Sweet Social Space" },
  ur: { automated:"خودکار", title:"Sweet Social Space Community Bot کے ذریعے تیار کردہ" },
  fa: { automated:"خودکار", title:"تولید شده توسط ربات جامعه Sweet Social Space" },
  ms: { automated:"Automatik", title:"Dijana oleh Bot Komuniti Sweet Social Space" },
  ro: { automated:"Automatizat", title:"Generat de Bot-ul Comunității Sweet Social Space" },
  cs: { automated:"Automatizováno", title:"Vygenerováno komunitním botem Sweet Social Space" },
  hu: { automated:"Automatizált", title:"Készítette Sweet Social Space Közösségi Bot" },
  fi: { automated:"Automatisoitu", title:"Luonut Sweet Social Space Community Bot" },
  no: { automated:"Automatisert", title:"Generert av Sweet Social Space Community Bot" },
  da: { automated:"Automatiseret", title:"Genereret af Sweet Social Space Community Bot" },
  bg: { automated:"Автоматизирано", title:"Генерирано от Community Bot на Sweet Social Space" },
  hr: { automated:"Automatizirano", title:"Generirao Sweet Social Space Community Bot" },
  sr: { automated:"Аутоматизовано", title:"Генерисао Sweet Social Space Community Bot" },
  sk: { automated:"Automatizované", title:"Vygenerované komunitným botom Sweet Social Space" },
  sl: { automated:"Avtomatizirano", title:"Ustvaril Sweet Social Space Community Bot" },
  et: { automated:"Automatiseeritud", title:"Loodud Sweet Social Space Community Bot poolt" },
  lv: { automated:"Automatizēts", title:"Ģenerējis Sweet Social Space Community Bot" },
  lt: { automated:"Automatizuota", title:"Sugeneravo Sweet Social Space Community Bot" },
  be: { automated:"Аўтаматызавана", title:"Створана ботам супольнасці Sweet Social Space" },
  ka: { automated:"ავტომატიზებული", title:"შექმნილია Sweet Social Space Community Bot-ის მიერ" },
  hy: { automated:"Ավտոմատացված", title:"Ստեղծվել է Sweet Social Space Community Bot-ի կողմից" },
  az: { automated:"Avtomatlaşdırılmış", title:"Sweet Social Space Community Bot tərəfindən yaradıldı" },
  kk: { automated:"Автоматтандырылған", title:"Sweet Social Space Community Bot жасаған" },
  ky: { automated:"Автоматташтырылган", title:"Sweet Social Space Community Bot тарабынан жасалган" },
  uz: { automated:"Avtomatlashtirilgan", title:"Sweet Social Space Community Bot tomonidan yaratilgan" },
  tg: { automated:"Автоматӣ", title:"Аз ҷониби Sweet Social Space Community Bot тавлид шудааст" },
  mn: { automated:"Автомат", title:"Sweet Social Space Community Bot-ын үүсгэсэн" },
  km: { automated:"ស្វ័យប្រវត្តិ", title:"បង្កើតដោយ Sweet Social Space Community Bot" },
  lo: { automated:"ອັດຕະໂນມັດ", title:"ສ້າງໂດຍ Sweet Social Space Community Bot" },
  my: { automated:"အလိုအလျောက်", title:"Sweet Social Space Community Bot မှ ထုတ်လုပ်သည်" },
}

export function AutomatedBadge({ className = '' }: { className?: string }) {
  const { language } = useLanguage()
  const d = D[language] || D.en

  return (
    <span className={`inline-flex items-center gap-1 rounded-full border border-border bg-muted px-2 py-0.5 text- font-semibold uppercase tracking-wide text-muted-foreground ${className}`} title={d.title}>
      <span aria-hidden>🤖</span>{d.automated}
    </span>
  )
}
