'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { useLanguage } from '@/lib/language-context'

const COOKIE_VERSION = 'v1.0.0'
const KEY = 'ss-cookie-consent-v1'
type Choice = { necessary: true; functional: boolean; analytics: boolean; ts: string; v: string }

function load(): Choice | null { try { const raw = typeof localStorage!== 'undefined'? localStorage.getItem(KEY) : null; return raw? (JSON.parse(raw) as Choice) : null } catch { return null } }
async function logConsent(choice: Choice) { try { const supabase = createClient() as any; const { data } = await supabase.auth.getSession(); await supabase.from('consent_log').insert({ user_id: data.session?.user?.id?? null, session_id: typeof crypto!== 'undefined'? crypto.randomUUID() : null, consent_type: `cookies:functional=${choice.functional};analytics=${choice.analytics}`, granted: choice.functional || choice.analytics, policy_version: COOKIE_VERSION }) } catch {} }
function save(choice: Choice) { try { localStorage.setItem(KEY, JSON.stringify(choice)); void logConsent(choice) } catch {} }

const D: Record<string, any> = {
  en: { main:"We use strictly-necessary cookies to keep you signed in. With your permission, we also use functional and anonymized analytics cookies to improve Sweet Social Space. No ads. No tracking across sites.", learn:"Learn more", necessary:"Strictly necessary", necDesc:"sign-in & security. Always on.", functional:"Functional", funcDesc:"remembers your language and preferences.", analytics:"Analytics", analDesc:"anonymized usage stats.", customize:"Customize", save:"Save choices", reject:"Reject non-essential", accept:"Accept all" },
  es: { main:"Usamos cookies estrictamente necesarios para mantenerte conectado. Con tu permiso, también usamos cookies funcionales y de analítica anonimizada para mejorar Sweet Social Space. Sin anuncios. Sin rastreo.", learn:"Más información", necessary:"Estrictamente necesario", necDesc:"inicio de sesión y seguridad. Siempre activo.", functional:"Funcional", funcDesc:"recuerda tu idioma y preferencias.", analytics:"Analítica", analDesc:"estadísticas de uso anonimizadas.", customize:"Personalizar", save:"Guardar elecciones", reject:"Rechazar no esenciales", accept:"Aceptar todo" },
  fr: { main:"Nous utilisons des cookies strictement nécessaires pour vous garder connecté. Avec votre permission, nous utilisons aussi des cookies fonctionnels et d'analyse anonymisés pour améliorer Sweet Social Space. Pas de pubs. Pas de suivi.", learn:"En savoir plus", necessary:"Strictement nécessaire", necDesc:"connexion et sécurité. Toujours activé.", functional:"Fonctionnel", funcDesc:"se souvient de votre langue et préférences.", analytics:"Analytique", analDesc:"statistiques d'usage anonymisées.", customize:"Personnaliser", save:"Enregistrer choix", reject:"Rejeter non-essentiels", accept:"Tout accepter" },
  de: { main:"Wir verwenden unbedingt erforderliche Cookies um dich eingeloggt zu halten. Mit deiner Erlaubnis auch funktionale und anonymisierte Analyse-Cookies um Sweet Social Space zu verbessern. Keine Werbung. Kein seitenübergreifendes Tracking.", learn:"Mehr erfahren", necessary:"Unbedingt erforderlich", necDesc:"Anmeldung & Sicherheit. Immer an.", functional:"Funktional", funcDesc:"merkt sich Sprache und Präferenzen.", analytics:"Analyse", analDesc:"anonymisierte Nutzungsstatistiken.", customize:"Anpassen", save:"Auswahl speichern", reject:"Nicht-essenzielle ablehnen", accept:"Alle akzeptieren" },
  zh: { main:"我们使用严格必要的Cookie来保持登录状态。经您许可，我们还使用功能性和匿名分析Cookie来改进Sweet Social Space。无广告。无跨站追踪。", learn:"了解更多", necessary:"严格必要", necDesc:"登录和安全。始终开启。", functional:"功能性", funcDesc:"记住你的语言和偏好。", analytics:"分析", analDesc:"匿名使用统计。", customize:"自定义", save:"保存选择", reject:"拒绝非必要", accept:"全部接受" },
  ja: { main:"サインインを維持するために厳密に必要なCookieを使用します。許可を得て、Sweet Social Space改善のため機能性および匿名分析Cookieも使用します。広告なし。サイト間追跡なし。", learn:"詳細を見る", necessary:"厳密に必要", necDesc:"サインインとセキュリティ。常にオン。", functional:"機能的", funcDesc:"言語と設定を記憶。", analytics:"分析", analDesc:"匿名化された利用統計。", customize:"カスタマイズ", save:"選択を保存", reject:"非必須を拒否", accept:"すべて受け入れる" },
  ko: { main:"로그인 유지를 위해 엄격히 필요한 쿠키를 사용합니다. 허락하시면 Sweet Social Space 개선을 위해 기능 및 익명 분석 쿠키도 사용합니다. 광고 없음. 교차 사이트 추적 없음.", learn:"더 알아보기", necessary:"엄격히 필요", necDesc:"로그인 및 보안. 항상 켜짐.", functional:"기능", funcDesc:"언어와 환경설정을 기억.", analytics:"분석", analDesc:"익명 사용 통계.", customize:"사용자 정의", save:"선택 저장", reject:"비필수 거부", accept:"모두 수락" },
  pt: { main:"Usamos cookies estritamente necessários para mantê-lo conectado. Com sua permissão, também usamos cookies funcionais e de análise anonimizada para melhorar Sweet Social Space. Sem anúncios. Sem rastreamento.", learn:"Saiba mais", necessary:"Estritamente necessário", necDesc:"login e segurança. Sempre ativo.", functional:"Funcional", funcDesc:"lembra seu idioma e preferências.", analytics:"Análise", analDesc:"estatísticas anonimizadas.", customize:"Personalizar", save:"Salvar escolhas", reject:"Rejeitar não essenciais", accept:"Aceitar tudo" },
  ru: { main:"Мы используем строго необходимые куки чтобы держать вас в системе. С вашего разрешения также функциональные и анонимные аналитические куки для улучшения Sweet Social Space. Без рекламы. Без отслеживания.", learn:"Узнать больше", necessary:"Строго необходимо", necDesc:"вход и безопасность. Всегда вкл.", functional:"Функциональные", funcDesc:"запоминает язык и предпочтения.", analytics:"Аналитика", analDesc:"анонимная статистика.", customize:"Настроить", save:"Сохранить выбор", reject:"Отклонить необязательные", accept:"Принять все" },
  ar: { main:"نستخدم ملفات تعريف الارتباط الضرورية للغاية لإبقائك مسجل الدخول. بإذنك نستخدم أيضا ملفات وظيفية وتحليلية مجهولة لتحسين Sweet Social Space. لا إعلانات. لا تتبع.", learn:"اعرف المزيد", necessary:"ضروري للغاية", necDesc:"تسجيل الدخول والأمان. دائما مفعل.", functional:"وظيفي", funcDesc:"يتذكر لغتك وتفضيلاتك.", analytics:"تحليلات", analDesc:"إحصائيات مجهولة.", customize:"تخصيص", save:"حفظ الاختيارات", reject:"رفض غير الضروري", accept:"قبول الكل" },
  hi: { main:"हम आपको साइन इन रखने के लिए सख्त आवश्यक कुकीज़ उपयोग करते हैं। आपकी अनुमति से कार्यात्मक और अनाम एनालिटिक्स कुकीज़ भी Sweet Social Space सुधारने के लिए। कोई विज्ञापन नहीं।", learn:"और जानें", necessary:"सख्त आवश्यक", necDesc:"साइन-इन और सुरक्षा। हमेशा चालू।", functional:"कार्यात्मक", funcDesc:"भाषा और प्राथमिकताएँ याद रखता है।", analytics:"एनालिटिक्स", analDesc:"अनाम उपयोग आँकड़े।", customize:"कस्टमाइज़", save:"विकल्प सहेजें", reject:"गैर-आवश्यक अस्वीकार", accept:"सभी स्वीकारें" },
  it: { main:"Usiamo cookie strettamente necessari per tenerti connesso. Con il tuo permesso, usiamo anche cookie funzionali e di analisi anonimizzati per migliorare Sweet Social Space. Niente pubblicità. Niente tracciamento.", learn:"Scopri di più", necessary:"Strettamente necessario", necDesc:"accesso e sicurezza. Sempre attivo.", functional:"Funzionale", funcDesc:"ricorda lingua e preferenze.", analytics:"Analitica", analDesc:"statistiche anonime.", customize:"Personalizza", save:"Salva scelte", reject:"Rifiuta non essenziali", accept:"Accetta tutti" },
  nl: { main:"We gebruiken strikt noodzakelijke cookies om je ingelogd te houden. Met toestemming ook functionele en geanonimiseerde analytics cookies om Sweet Social Space te verbeteren. Geen advertenties.", learn:"Meer info", necessary:"Strikt noodzakelijk", necDesc:"inloggen & beveiliging. Altijd aan.", functional:"Functioneel", funcDesc:"onthoudt taal en voorkeuren.", analytics:"Analytics", analDesc:"geanonimiseerde gebruiksstatistieken.", customize:"Aanpassen", save:"Keuzes opslaan", reject:"Niet-essentiële weigeren", accept:"Alles accepteren" },
  tl: { main:"Gumagamit kami ng strictly-necessary cookies para manatiling naka-sign in. Sa pahintulot mo, functional at anonymized analytics cookies para mapabuti Sweet Social Space. Walang ads.", learn:"Matuto pa", necessary:"Mahigpit na kailangan", necDesc:"sign-in & security. Laging on.", functional:"Functional", funcDesc:"naaalala wika at preferences.", analytics:"Analytics", analDesc:"anonymized usage stats.", customize:"I-customize", save:"I-save choices", reject:"Tanggihan non-essential", accept:"Tanggapin lahat" },
  bn: { main:"আপনাকে সাইন ইন রাখতে আমরা কঠোরভাবে প্রয়োজনীয় কুকি ব্যবহার করি। আপনার অনুমতিতে কার্যকরী এবং বেনামী অ্যানালিটিক্স কুকিও Sweet Social Space উন্নত করতে। কোনো বিজ্ঞাপন নেই।", learn:"আরও জানুন", necessary:"কঠোরভাবে প্রয়োজনীয়", necDesc:"সাইন-ইন ও নিরাপত্তা। সর্বদা চালু।", functional:"কার্যকরী", funcDesc:"ভাষা ও পছন্দ মনে রাখে।", analytics:"অ্যানালিটিক্স", analDesc:"বেনামী ব্যবহার পরিসংখ্যান।", customize:"কাস্টমাইজ", save:"পছন্দ সংরক্ষণ", reject:"অ-প্রয়োজনীয় প্রত্যাখ্যান", accept:"সব গ্রহণ" },
  id: { main:"Kami menggunakan cookie yang sangat diperlukan agar tetap masuk. Dengan izin Anda, juga cookie fungsional dan analitik anonim untuk meningkatkan Sweet Social Space. Tanpa iklan.", learn:"Pelajari lebih lanjut", necessary:"Sangat diperlukan", necDesc:"masuk & keamanan. Selalu aktif.", functional:"Fungsional", funcDesc:"mengingat bahasa dan preferensi.", analytics:"Analitik", analDesc:"statistik penggunaan anonim.", customize:"Sesuaikan", save:"Simpan pilihan", reject:"Tolak non-esensial", accept:"Terima semua" },
  vi: { main:"Chúng tôi dùng cookie thực sự cần thiết để giữ bạn đăng nhập. Với sự cho phép, chúng tôi cũng dùng cookie chức năng và phân tích ẩn danh để cải thiện Sweet Social Space. Không quảng cáo.", learn:"Tìm hiểu thêm", necessary:"Thực sự cần thiết", necDesc:"đăng nhập & bảo mật. Luôn bật.", functional:"Chức năng", funcDesc:"nhớ ngôn ngữ và tùy chọn.", analytics:"Phân tích", analDesc:"thống kê ẩn danh.", customize:"Tùy chỉnh", save:"Lưu lựa chọn", reject:"Từ chối không thiết yếu", accept:"Chấp nhận tất cả" },
  th: { main:"เราใช้คุกกี้ที่จำเป็นอย่างยิ่งเพื่อให้คุณอยู่ในระบบ เมื่อได้รับอนุญาต เรายังใช้คุกกี้ฟังก์ชันและการวิเคราะห์แบบไม่ระบุตัวตนเพื่อปรับปรุง Sweet Social Space ไม่มีโฆษณา", learn:"เรียนรู้เพิ่มเติม", necessary:"จำเป็นอย่างยิ่ง", necDesc:"ลงชื่อเข้าใช้และความปลอดภัย เปิดเสมอ", functional:"ฟังก์ชัน", funcDesc:"จดจำภาษาและการตั้งค่า", analytics:"วิเคราะห์", analDesc:"สถิติการใช้งานแบบไม่ระบุตัวตน", customize:"ปรับแต่ง", save:"บันทึกตัวเลือก", reject:"ปฏิเสธที่ไม่จำเป็น", accept:"ยอมรับทั้งหมด" },
  sv: { main:"Vi använder strikt nödvändiga cookies för att hålla dig inloggad. Med ditt tillstånd använder vi också funktionella och anonymiserade analyscookies för att förbättra Sweet Social Space. Inga annonser.", learn:"Läs mer", necessary:"Strikt nödvändigt", necDesc:"inloggning & säkerhet. Alltid på.", functional:"Funktionell", funcDesc:"kommer ihåg språk och inställningar.", analytics:"Analys", analDesc:"anonymiserad användningsstatistik.", customize:"Anpassa", save:"Spara val", reject:"Avvisa icke-nödvändiga", accept:"Acceptera alla" },
  pl: { main:"Używamy ściśle niezbędnych plików cookie aby utrzymać Cię zalogowanym. Za zgodą używamy też funkcjonalnych i anonimowych analitycznych plików cookie aby ulepszyć Sweet Social Space. Bez reklam.", learn:"Dowiedz się więcej", necessary:"Ściśle niezbędne", necDesc:"logowanie i bezpieczeństwo. Zawsze włączone.", functional:"Funkcjonalne", funcDesc:"pamięta język i preferencje.", analytics:"Analityka", analDesc:"anonimowe statystyki.", customize:"Dostosuj", save:"Zapisz wybory", reject:"Odrzuć nieistotne", accept:"Akceptuj wszystkie" },
  tr: { main:"Sizi oturumda tutmak için kesinlikle gerekli çerezleri kullanıyoruz. İzninizle Sweet Social Space'i iyileştirmek için işlevsel ve anonim analitik çerezler de kullanıyoruz. Reklam yok.", learn:"Daha fazla bilgi", necessary:"Kesinlikle gerekli", necDesc:"giriş ve güvenlik. Her zaman açık.", functional:"İşlevsel", funcDesc:"dil ve tercihlerinizi hatırlar.", analytics:"Analitik", analDesc:"anonim kullanım istatistikleri.", customize:"Özelleştir", save:"Seçimleri kaydet", reject:"Gerekli olmayanları reddet", accept:"Tümünü kabul et" },
  uk: { main:"Ми використовуємо суворо необхідні файли cookie щоб тримати вас у системі. З вашого дозволу також функціональні та анонімні аналітичні файли для покращення Sweet Social Space. Без реклами.", learn:"Дізнатися більше", necessary:"Сурово необхідні", necDesc:"вхід і безпека. Завжди ввімкнено.", functional:"Функціональні", funcDesc:"запам'ятовує мову та вподобання.", analytics:"Аналітика", analDesc:"анонімна статистика.", customize:"Налаштувати", save:"Зберегти вибір", reject:"Відхилити неістотні", accept:"Прийняти всі" },
  el: { main:"Χρησιμοποιούμε απολύτως απαραίτητα cookies για να σας κρατάμε συνδεδεμένους. Με άδειά σας, χρησιμοποιούμε επίσης λειτουργικά και ανώνυμα analytics cookies για βελτίωση του Sweet Social Space. Χωρίς διαφημίσεις.", learn:"Μάθετε περισσότερα", necessary:"Απολύτως απαραίτητα", necDesc:"σύνδεση & ασφάλεια. Πάντα ενεργό.", functional:"Λειτουργικά", funcDesc:"θυμάται γλώσσα και προτιμήσεις.", analytics:"Αναλυτικά", analDesc:"ανώνυμα στατιστικά.", customize:"Προσαρμογή", save:"Αποθήκευση επιλογών", reject:"Απόρριψη μη απαραίτητων", accept:"Αποδοχή όλων" },
  he: { main:"אנו משתמשים בעוגיות הכרחיות לחלוטין כדי להשאיר אותך מחובר. ברשותך, אנו משתמשים גם בעוגיות פונקציונליות ואנליטיקה אנונימית לשיפור Sweet Social Space. ללא פרסומות.", learn:"למידע נוסף", necessary:"הכרחי לחלוטין", necDesc:"כניסה ואבטחה. תמיד פעיל.", functional:"פונקציונלי", funcDesc:"זוכר שפה והעדפות.", analytics:"אנליטיקה", analDesc:"סטטיסטיקת שימוש אנונימית.", customize:"התאמה אישית", save:"שמור בחירות", reject:"דחה לא חיוניים", accept:"קבל הכל" },
  ur: { main:"ہم آپ کو سائن ان رکھنے کے لیے سختی سے ضروری کوکیز استعمال کرتے ہیں۔ آپ کی اجازت سے فنکشنل اور گمنام اینالیٹکس کوکیز بھی Sweet Social Space بہتر بنانے کے لیے۔ کوئی اشتہار نہیں۔", learn:"مزید جانیں", necessary:"سختی سے ضروری", necDesc:"سائن ان اور سیکیورٹی۔ ہمیشہ آن۔", functional:"فنکشنل", funcDesc:"زبان اور ترجیحات یاد رکھتا ہے۔", analytics:"اینالیٹکس", analDesc:"گمنام استعمال اعداد۔", customize:"کسٹمائز", save:"انتخاب محفوظ کریں", reject:"غیر ضروری مسترد", accept:"سب قبول کریں" },
  fa: { main:"ما از کوکی های کاملاً ضروری برای نگه داشتن شما در سیستم استفاده می کنیم. با اجازه شما، از کوکی های کاربردی و تحلیلی ناشناس برای بهبود Sweet Social Space نیز استفاده می کنیم. بدون تبلیغ.", learn:"بیشتر بدانید", necessary:"کاملاً ضروری", necDesc:"ورود و امنیت. همیشه روشن.", functional:"کاربردی", funcDesc:"زبان و ترجیحات را به خاطر می سپارد.", analytics:"تحلیلی", analDesc:"آمار ناشناس.", customize:"سفارشی سازی", save:"ذخیره انتخاب ها", reject:"رد غیرضروری ها", accept:"پذیرش همه" },
  ms: { main:"Kami menggunakan cookie yang sangat diperlukan untuk memastikan anda kekal log masuk. Dengan kebenaran anda, kami juga menggunakan cookie berfungsi dan analitik tanpa nama untuk menambah baik Sweet Social Space. Tiada iklan.", learn:"Ketahui lebih lanjut", necessary:"Sangat diperlukan", necDesc:"log masuk & keselamatan. Sentiasa aktif.", functional:"Berfungsi", funcDesc:"mengingati bahasa dan keutamaan.", analytics:"Analitik", analDesc:"statistik tanpa nama.", customize:"Sesuaikan", save:"Simpan pilihan", reject:"Tolak bukan penting", accept:"Terima semua" },
  ro: { main:"Folosim cookie-uri strict necesare pentru a vă menține conectat. Cu permisiunea dvs., folosim și cookie-uri funcționale și de analiză anonimizată pentru a îmbunătăți Sweet Social Space. Fără reclame.", learn:"Află mai multe", necessary:"Strict necesare", necDesc:"autentificare și securitate. Mereu pornite.", functional:"Funcționale", funcDesc:"își amintește limba și preferințele.", analytics:"Analiză", analDesc:"statistici anonime.", customize:"Personalizează", save:"Salvează alegeri", reject:"Respinge neesențiale", accept:"Acceptă tot" },
  cs: { main:"Používáme nezbytně nutné cookies abychom vás udrželi přihlášené. S vaším svolením také funkční a anonymizované analytické cookies ke zlepšení Sweet Social Space. Žádné reklamy.", learn:"Zjistit více", necessary:"Nezbytně nutné", necDesc:"přihlášení a bezpečnost. Vždy zapnuto.", functional:"Funkční", funcDesc:"pamatuje si jazyk a preference.", analytics:"Analytika", analDesc:"anonymizované statistiky.", customize:"Přizpůsobit", save:"Uložit volby", reject:"Odmítnout nepodstatné", accept:"Přijmout vše" },
  hu: { main:"Szigorúan szükséges sütiket használunk hogy bejelentkezve tartsunk. Engedélyeddel funkcionális és anonimizált analitikai sütiket is használunk a Sweet Social Space javítására. Nincs hirdetés.", learn:"Tudj meg többet", necessary:"Szigorúan szükséges", necDesc:"bejelentkezés és biztonság. Mindig bekapcsolva.", functional:"Funkcionális", funcDesc:"emlékszik nyelvedre és beállításokra.", analytics:"Analitika", analDesc:"anonim használati statisztika.", customize:"Testreszabás", save:"Választások mentése", reject:"Nem lényeges elutasítása", accept:"Összes elfogadása" },
  fi: { main:"Käytämme ehdottoman välttämättömiä evästeitä pitääksemme sinut kirjautuneena. Luvallasi käytämme myös toiminnallisia ja anonyymeja analytiikkaevästeitä Sweet Social Spacen parantamiseen. Ei mainoksia.", learn:"Lue lisää", necessary:"Ehdottoman välttämätön", necDesc:"kirjautuminen ja turvallisuus. Aina päällä.", functional:"Toiminnallinen", funcDesc:"muistaa kielesi ja asetukset.", analytics:"Analytiikka", analDesc:"anonymisoidut käyttötilastot.", customize:"Mukauta", save:"Tallenna valinnat", reject:"Hylkää ei-välttämättömät", accept:"Hyväksy kaikki" },
  no: { main:"Vi bruker strengt nødvendige informasjonskapsler for å holde deg innlogget. Med din tillatelse bruker vi også funksjonelle og anonymiserte analysekapsler for å forbedre Sweet Social Space. Ingen annonser.", learn:"Lær mer", necessary:"Strengt nødvendig", necDesc:"pålogging og sikkerhet. Alltid på.", functional:"Funksjonell", funcDesc:"husker språk og preferanser.", analytics:"Analyse", analDesc:"anonymisert bruksstatistikk.", customize:"Tilpass", save:"Lagre valg", reject:"Avvis ikke-essensielle", accept:"Godta alle" },
  da: { main:"Vi bruger strengt nødvendige cookies for at holde dig logget ind. Med din tilladelse bruger vi også funktionelle og anonymiserede analysecookies til at forbedre Sweet Social Space. Ingen annoncer.", learn:"Lær mere", necessary:"Strengt nødvendigt", necDesc:"login og sikkerhed. Altid til.", functional:"Funktionel", funcDesc:"husker sprog og præferencer.", analytics:"Analyse", analDesc:"anonymiseret brugsstatistik.", customize:"Tilpas", save:"Gem valg", reject:"Afvis ikke-væsentlige", accept:"Accepter alle" },
  bg: { main:"Използваме строго необходими бисквитки за да ви държим вписани. С ваше разрешение използваме и функционални и анонимни аналитични бисквитки за подобряване на Sweet Social Space. Без реклами.", learn:"Научете повече", necessary:"Строго необходими", necDesc:"вход и сигурност. Винаги включени.", functional:"Функционални", funcDesc:"помни език и предпочитания.", analytics:"Аналитика", analDesc:"анонимна статистика.", customize:"Персонализирай", save:"Запази избори", reject:"Отхвърли несъществени", accept:"Приеми всички" },
  hr: { main:"Koristimo strogo nužne kolačiće da vas držimo prijavljenima. Uz vaše dopuštenje koristimo i funkcionalne i anonimizirane analitičke kolačiće za poboljšanje Sweet Social Space. Bez oglasa.", learn:"Saznaj više", necessary:"Strogo nužno", necDesc:"prijava i sigurnost. Uvijek uključeno.", functional:"Funkcionalno", funcDesc:"pamti jezik i postavke.", analytics:"Analitika", analDesc:"anonimizirana statistika.", customize:"Prilagodi", save:"Spremi odabire", reject:"Odbij nebitno", accept:"Prihvati sve" },
  sr: { main:"Користимо строго неопходне колачиће да вас држимо пријављеним. Уз вашу дозволу користимо и функционалне и анонимизоване аналитичке колачиће за побољшање Sweet Social Space. Без огласа.", learn:"Сазнај више", necessary:"Строго неопходно", necDesc:"пријава и безбедност. Увек укључено.", functional:"Функционално", funcDesc:"памти језик и подешавања.", analytics:"Аналитика", analDesc:"анонимизована статистика.", customize:"Прилагоди", save:"Сачувај изборе", reject:"Одбиј небитно", accept:"Прихвати све" },
  sk: { main:"Používame nevyhnutne potrebné cookies aby sme vás udržali prihlásených. S vaším súhlasom aj funkčné a anonymizované analytické cookies na zlepšenie Sweet Social Space. Žiadne reklamy.", learn:"Zistiť viac", necessary:"Nevyhnutne potrebné", necDesc:"prihlásenie a bezpečnosť. Vždy zapnuté.", functional:"Funkčné", funcDesc:"pamätá si jazyk a preferencie.", analytics:"Analytika", analDesc:"anonymizované štatistiky.", customize:"Prispôsobiť", save:"Uložiť voľby", reject:"Odmietnuť nepodstatné", accept:"Prijať všetko" },
  sl: { main:"Uporabljamo nujno potrebne piškotke da vas držimo prijavljene. Z vašim dovoljenjem uporabljamo tudi funkcionalne in anonimizirane analitične piškotke za izboljšanje Sweet Social Space. Brez oglasov.", learn:"Več", necessary:"Nujno potrebno", necDesc:"prijava in varnost. Vedno vklopljeno.", functional:"Funkcionalno", funcDesc:"si zapomni jezik in nastavitve.", analytics:"Analitika", analDesc:"anonimizirana statistika.", customize:"Prilagodi", save:"Shrani izbire", reject:"Zavrni nebistveno", accept:"Sprejmi vse" },
  et: { main:"Kasutame rangelt vajalikke küpsiseid et hoida sind sisse logitud. Sinu loal kasutame ka funktsionaalseid ja anonüümseid analüütikaküpsiseid Sweet Social Space parandamiseks. Reklaame pole.", learn:"Loe lähemalt", necessary:"Rangelt vajalik", necDesc:"sisselogimine ja turvalisus. Alati sees.", functional:"Funktsionaalne", funcDesc:"mäletab keelt ja eelistusi.", analytics:"Analüütika", analDesc:"anonüümne kasutusstatistika.", customize:"Kohanda", save:"Salvesta valikud", reject:"Lükka mitteoluline tagasi", accept:"Võta kõik vastu" },
  lv: { main:"Mēs izmantojam stingri nepieciešamos sīkdatnes lai jūs paliktu pierakstījies. Ar jūsu atļauju izmantojam arī funkcionālās un anonimizētās analītikas sīkdatnes lai uzlabotu Sweet Social Space. Bez reklāmām.", learn:"Uzzināt vairāk", necessary:"Stingri nepieciešams", necDesc:"pierakstīšanās un drošība. Vienmēr ieslēgts.", functional:"Funkcionāls", funcDesc:"atceras valodu un preferences.", analytics:"Analītika", analDesc:"anonimizēta lietošanas statistika.", customize:"Pielāgot", save:"Saglabāt izvēles", reject:"Noraidīt nebūtiskas", accept:"Pieņemt visas" },
  lt: { main:"Naudojame griežtai būtinus slapukus kad liktumėte prisijungę. Su jūsų leidimu taip pat funkcinius ir anonimizuotus analitinius slapukus Sweet Social Space gerinimui. Be reklamų.", learn:"Sužinoti daugiau", necessary:"Griežtai būtina", necDesc:"prisijungimas ir saugumas. Visada įjungta.", functional:"Funkciniai", funcDesc:"prisimena kalbą ir nuostatas.", analytics:"Analitika", analDesc:"anonimizuota statistika.", customize:"Tinkinti", save:"Išsaugoti pasirinkimus", reject:"Atmesti nebūtinus", accept:"Priimti visus" },
  be: { main:"Мы выкарыстоўваем строга неабходныя файлы cookie каб трымаць вас увайшоўшымі. З вашага дазволу таксама функцыянальныя і ананімныя аналітычныя файлы для паляпшэння Sweet Social Space. Без рэкламы.", learn:"Даведацца больш", necessary:"Строга неабходна", necDesc:"уваход і бяспека. Заўсёды ўключана.", functional:"Функцыянальныя", funcDesc:"запамінае мову і перавагі.", analytics:"Аналітыка", analDesc:"ананімная статыстыка.", customize:"Наладзіць", save:"Захаваць выбар", reject:"Адхіліць неістотныя", accept:"Прыняць усе" },
  ka: { main:"ჩვენ ვიყენებთ მკაცრად აუცილებელ ქუქიებს რომ დარჩეთ შესული. თქვენი ნებართვით ასევე ფუნქციურ და ანონიმურ ანალიტიკურ ქუქიებს Sweet Social Space გასაუმჯობესებლად. რეკლამის გარეშე.", learn:"გაიგეთ მეტი", necessary:"მკაცრად აუცილებელი", necDesc:"შესვლა და უსაფრთხოება. ყოველთვის ჩართული.", functional:"ფუნქციური", funcDesc:"იმახსოვრებს ენას და პრეფერენციებს.", analytics:"ანალიტიკა", analDesc:"ანონიმური სტატისტიკა.", customize:"მორგება", save:"არჩევანის შენახვა", reject:"არაარსებითის უარყოფა", accept:"ყველას მიღება" },
  hy: { main:"Մենք օգտագործում ենք խիստ անհրաժեշտ cookie-ներ ձեզ մուտքագրված պահելու համար։ Ձեր թույլտվությամբ օգտագործում ենք նաև ֆունկցիոնալ և անանուն վերլուծական cookie-ներ Sweet Social Space-ը բարելավելու համար։ Առանց գովազդի։", learn:"Իմանալ ավելին", necessary:"Խիստ անհրաժեշտ", necDesc:"մուտք և անվտանգություն։ Միշտ միացված։", functional:"Ֆունկցիոնալ", funcDesc:"հիշում է լեզուն և նախընտրությունները։", analytics:"Վերլուծություն", analDesc:"անանուն վիճակագրություն։", customize:"Հարմարեցնել", save:"Պահպանել ընտրությունը", reject:"Մերժել ոչ էականները", accept:"Ընդունել բոլորը" },
  az: { main:"Sizi daxil saxlamaq üçün ciddi şəkildə zəruri çərəzlərdən istifadə edirik. İcazənizlə Sweet Social Space-i yaxşılaşdırmaq üçün funksional və anonim analitik çərəzlərdən də istifadə edirik. Reklamsız.", learn:"Daha çox öyrən", necessary:"Ciddi şəkildə zəruri", necDesc:"giriş və təhlükəsizlik. Həmişə açıq.", functional:"Funksional", funcDesc:"dil və üstünlükləri xatırlayır.", analytics:"Analitika", analDesc:"anonim istifadə statistikası.", customize:"Fərdiləşdir", save:"Seçimləri saxla", reject:"Qeyri-vacibləri rədd et", accept:"Hamısını qəbul et" },
  kk: { main:"Сізді жүйеде ұстау үшін қатаң қажетті cookie файлдарын қолданамыз. Рұқсатыңызбен Sweet Social Space жақсарту үшін функционалды және анонимді аналитика cookie-де пайдаланамыз. Жарнама жоқ.", learn:"Көбірек білу", necessary:"Қатаң қажет", necDesc:"кіру және қауіпсіздік. Әрқашан қосулы.", functional:"Функционалды", funcDesc:"тіл мен қалауларды есте сақтайды.", analytics:"Аналитика", analDesc:"анонимді статистика.", customize:"Баптау", save:"Таңдауды сақтау", reject:"Маңызды еместерді қабылдамау", accept:"Барлығын қабылдау" },
  ky: { main:"Сизди системада кармоо үчүн катуу зарыл cookie файлдарын колдонобуз. Уруксатыңыз менен Sweet Social Space жакшыртуу үчүн функционалдык жана анонимдүү аналитика cookie-лерин да колдонобуз. Жарнама жок.", learn:"Көбүрөөк билүү", necessary:"Катуу зарыл", necDesc:"кирүү жана коопсуздук. Дайыма күйүк.", functional:"Функционалдык", funcDesc:"тилди жана артыкчылыктарды эстейт.", analytics:"Аналитика", analDesc:"анонимдүү статистика.", customize:"Ыңгайлаштыруу", save:"Тандоону сактоо", reject:"Маанилүү эместерди четке кагуу", accept:"Баарын кабыл алуу" },
  uz: { main:"Sizni tizimda ushlab turish uchun qat'iy zarur cookie-lardan foydalanamiz. Ruxsatingiz bilan Sweet Social Space-ni yaxshilash uchun funksional va anonim analitik cookie-lardan ham foydalanamiz. Reklama yo'q.", learn:"Batafsil", necessary:"Qat'iy zarur", necDesc:"kirish va xavfsizlik. Doim yoqilgan.", functional:"Funksional", funcDesc:"til va afzalliklarni eslab qoladi.", analytics:"Analitika", analDesc:"anonim statistika.", customize:"Moslashtirish", save:"Tanlovlarni saqlash", reject:"Muhim bo'lmaganlarni rad etish", accept:"Barchasini qabul qilish" },
  tg: { main:"Мо барои дар система нигоҳ доштани шумо аз кукиҳои сахт зарурӣ истифода мебарем. Бо иҷозати шумо барои беҳтар кардани Sweet Social Space аз кукиҳои функсионалӣ ва аналитикии беном низ истифода мебарем. Бе таблиғ.", learn:"Бештар омӯзед", necessary:"Сахт зарур", necDesc:"вуруд ва амният. Ҳамеша фаъол.", functional:"Функсионалӣ", funcDesc:"забон ва афзалиятҳоро дар хотир дорад.", analytics:"Аналитика", analDesc:"омори беном.", customize:"Танзим", save:"Интихобҳоро захира кунед", reject:"Ғайримуҳимро рад кунед", accept:"Ҳамаро қабул кунед" },
  mn: { main:"Таныг нэвтэрсэн байлгахын тулд зайлшгүй шаардлагатай күүки ашигладаг. Таны зөвшөөрлөөр Sweet Social Space-ийг сайжруулахын тулд функциональ болон нэргүй аналитик күүки ашигладаг. Зар сурталчилгаагүй.", learn:"Дэлгэрэнгүй", necessary:"Зайлшгүй шаардлагатай", necDesc:"нэвтрэх & аюулгүй байдал. Үргэлж асаалттай.", functional:"Функциональ", funcDesc:"хэл болон тохиргоог санадаг.", analytics:"Аналитик", analDesc:"нэргүй статистик.", customize:"Тохируулах", save:"Сонголтыг хадгалах", reject:"Чухал бусыг татгалзах", accept:"Бүгдийг зөвшөөрөх" },
  km: { main:"យើងប្រើខូគីដែលចាំបាច់យ៉ាងតឹងរ៉ឹងដើម្បីរក្សាអ្នកឱ្យចូល។ ដោយមានការអនុញ្ញាតពីអ្នក យើងក៏ប្រើខូគីមុខងារ និងវិភាគអនាមិកដើម្បីកែលម្អ Sweet Social Space។ គ្មានការផ្សាយពាណិជ្ជកម្មទេ។", learn:"ស្វែងយល់បន្ថែម", necessary:"ចាំបាច់យ៉ាងតឹងរ៉ឹង", necDesc:"ចូល និងសុវត្ថិភាព។ បើកជានិច្ច។", functional:"មុខងារ", funcDesc:"ចងចាំភាសា និងចំណូលចិត្ត។", analytics:"វិភាគ", analDesc:"ស្ថិតិអនាមិក។", customize:"ប្ដូរតាមបំណង", save:"រក្សាទុកជម្រើស", reject:"បដិសេធមិនសំខាន់", accept:"ទទួលយកទាំងអស់" },
  lo: { main:"ພວກເຮົາໃຊ້ຄຸກກີທີ່ຈຳເປັນຢ່າງເຂັ້ມງວດເພື່ອໃຫ້ທ່ານເຂົ້າສູ່ລະບົບ ດ້ວຍການອະນຸຍາດຂອງທ່ານ ພວກເຮົາຍັງໃຊ້ຄຸກກີຟັງຊັນແລະການວິເຄາະແບບບໍ່ເປີດເຜີຍເພື່ອປັບປຸງ Sweet Social Space ບໍ່ມີໂຄສະນາ", learn:"ຮຽນຮູ້ເພີ່ມເຕີມ", necessary:"ຈຳເປັນຢ່າງເຂັ້ມງວດ", necDesc:"ເຂົ້າສູ່ລະບົບ & ຄວາມປອດໄພ ເປີດຕະຫຼອດ", functional:"ຟັງຊັນ", funcDesc:"ຈື່ພາສາແລະຄວາມມັກ", analytics:"ການວິເຄາະ", analDesc:"ສະຖິຕິການໃຊ້ແບບບໍ່ເປີດເຜີຍ", customize:"ປັບແຕ່ງ", save:"ບັນທຶກຕົວເລືອກ", reject:"ປະຕິເສດທີ່ບໍ່ຈຳເປັນ", accept:"ຍອມຮັບທັງໝົດ" },
  my: { main:"သင့်အား လော့ဂ်အင်ဝင်ထားရန် တင်းကျပ်စွာလိုအပ်သော ကွတ်ကီးများကို ကျွန်ုပ်တို့အသုံးပြုသည်။ သင့်ခွင့်ပြုချက်ဖြင့် Sweet Social Space ကိုတိုးတက်စေရန် လုပ်ဆောင်ချက်နှင့် အမည်မသိခွဲခြမ်းစိတ်ဖြာမှု ကွတ်ကီးများကိုလည်းအသုံးပြုသည်။ ကြော်ငြာမရှိပါ။", learn:"ပိုမိုလေ့လာရန်", necessary:"တင်းကျပ်စွာလိုအပ်သော", necDesc:"လော့ဂ်အင်နှင့် လုံခြုံရေး။ အမြဲဖွင့်ထားသည်။", functional:"လုပ်ဆောင်ချက်", funcDesc:"ဘာသာစကားနှင့် စိတ်ကြိုက်များကို မှတ်မိသည်။", analytics:"ခွဲခြမ်းစိတ်ဖြာမှု", analDesc:"အမည်မသိ အသုံးပြုမှုစာရင်းများ။", customize:"စိတ်ကြိုက်ပြုလုပ်ရန်", save:"ရွေးချယ်မှုများသိမ်းရန်", reject:"မရှိမဖြစ်မဟုတ်သည်များငြင်းရန်", accept:"အားလုံးလက်ခံရန်" },
}

export function CookieBanner() {
  const { language } = useLanguage()
  const d = D[language] || D.en
  const [open, setOpen] = useState(false)
  const [showDetails, setShowDetails] = useState(false)
  const [functional, setFunctional] = useState(true)
  const [analytics, setAnalytics] = useState(false)

  useEffect(() => { try { if (typeof window === 'undefined') return; const existing = load(); if (!existing || existing.v!== COOKIE_VERSION) setOpen(true); const handler = () => setOpen(true); window.addEventListener('open-cookie-settings', handler); return () => window.removeEventListener('open-cookie-settings', handler) } catch {} }, [])

  if (!open) return null
  const acceptAll = () => { try { save({ necessary: true, functional: true, analytics: true, ts: new Date().toISOString(), v: COOKIE_VERSION }); setOpen(false) } catch {} }
  const rejectNonEssential = () => { try { save({ necessary: true, functional: false, analytics: false, ts: new Date().toISOString(), v: COOKIE_VERSION }); setOpen(false) } catch {} }
  const saveChoice = () => { try { save({ necessary: true, functional, analytics, ts: new Date().toISOString(), v: COOKIE_VERSION }); setOpen(false) } catch {} }

  return (
    <div className="fixed inset-x-0 bottom-0 z-50 px-4 pb-4">
      <div className="mx-auto max-w-3xl rounded-2xl border border-border bg-card p-5 shadow-2xl">
        <p className="text-sm text-foreground">{d.main} <Link href="/cookies" className="underline">{d.learn}</Link>.</p>
        {showDetails && (<div className="mt-3 space-y-2 rounded-xl border border-border bg-background p-3 text-sm"><label className="flex items-start gap-2 opacity-60"><input type="checkbox" checked disabled className="mt-1" /><span><strong>{d.necessary}</strong> — {d.necDesc}</span></label><label className="flex items-start gap-2"><input type="checkbox" checked={functional} onChange={(e) => setFunctional(e.target.checked)} className="mt-1" /><span><strong>{d.functional}</strong> — {d.funcDesc}</span></label><label className="flex items-start gap-2"><input type="checkbox" checked={analytics} onChange={(e) => setAnalytics(e.target.checked)} className="mt-1" /><span><strong>{d.analytics}</strong> — {d.analDesc}</span></label></div>)}
        <div className="mt-4 flex flex-wrap items-center justify-end gap-2">{!showDetails? (<button onClick={() => setShowDetails(true)} className="rounded-full px-3 py-1.5 text-sm text-muted-foreground hover:text-foreground">{d.customize}</button>) : (<button onClick={saveChoice} className="rounded-full border border-border px-3 py-1.5 text-sm hover:bg-secondary">{d.save}</button>)}<button onClick={rejectNonEssential} className="rounded-full border border-border px-3 py-1.5 text-sm hover:bg-secondary">{d.reject}</button><button onClick={acceptAll} className="rounded-full bg-primary px-4 py-1.5 text-sm font-medium text-primary-foreground hover:bg-primary/90">{d.accept}</button></div>
      </div>
    </div>
  )
}
