'use client'
import { useState, useRef, useEffect } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useLocation } from '@/lib/location-context'
import { useLanguage } from '@/lib/language-context'

const D: Record<string, any> = {
  en: { general:"General", faith:"Faith", safety:"Safety", for_sale:"For Sale", free:"Free", lost_pet:"Lost Pet", event:"Event", help:"Help", recommend:"Recommend", job:"Job", postTo:"Post to {zip} - One Stop", tapMic:"Tap mic - works in {zip} - any phone or computer", postingAs:"Posting as • {zip} • {icon} {cat} • Universal Mic", postBtn:"Post to {zip} 🚀", addressPh:"📍 Address - Private", pricePh:"Price $", freePh:"Free (0)", new:"New", likeNew:"Like New", good:"Good", fair:"Fair", detecting:"Still detecting your block... wait 2 sec and post again", micBlocked:"Mic blocked - check browser permissions" },
  es: { general:"General", faith:"Fe", safety:"Seguridad", for_sale:"En Venta", free:"Gratis", lost_pet:"Mascota Perdida", event:"Evento", help:"Ayuda", recommend:"Recomendar", job:"Trabajo", postTo:"Publicar en {zip} - One Stop", tapMic:"Toca micrófono - funciona en {zip} - cualquier teléfono", postingAs:"Publicando como • {zip} • {icon} {cat} • Mic Universal", postBtn:"Publicar en {zip} 🚀", addressPh:"📍 Dirección - Privada", pricePh:"Precio $", freePh:"Gratis (0)", new:"Nuevo", likeNew:"Como Nuevo", good:"Bueno", fair:"Regular", detecting:"Aún detectando tu bloque... espera 2 seg", micBlocked:"Mic bloqueado - revisa permisos" },
  fr: { general:"Général", faith:"Foi", safety:"Sécurité", for_sale:"À Vendre", free:"Gratuit", lost_pet:"Animal Perdu", event:"Événement", help:"Aide", recommend:"Recommander", job:"Emploi", postTo:"Publier à {zip} - One Stop", tapMic:"Appuyez micro - fonctionne à {zip}", postingAs:"Publication comme • {zip} • {icon} {cat} • Mic Universel", postBtn:"Publier à {zip} 🚀", addressPh:"📍 Adresse - Privée", pricePh:"Prix $", freePh:"Gratuit (0)", new:"Neuf", likeNew:"Comme Neuf", good:"Bon", fair:"Correct", detecting:"Toujours détection de votre bloc... attendez 2 sec", micBlocked:"Micro bloqué - vérifiez permissions" },
  de: { general:"Allgemein", faith:"Glaube", safety:"Sicherheit", for_sale:"Zu Verkaufen", free:"Kostenlos", lost_pet:"Haustier Vermisst", event:"Event", help:"Hilfe", recommend:"Empfehlen", job:"Job", postTo:"Posten in {zip} - One Stop", tapMic:"Tippe Mikro - funktioniert in {zip}", postingAs:"Posten als • {zip} • {icon} {cat} • Universal Mikro", postBtn:"Posten in {zip} 🚀", addressPh:"📍 Adresse - Privat", pricePh:"Preis $", freePh:"Kostenlos (0)", new:"Neu", likeNew:"Wie Neu", good:"Gut", fair:"Akzeptabel", detecting:"Block wird noch erkannt... 2 Sek warten", micBlocked:"Mikro blockiert - Berechtigungen prüfen" },
  zh: { general:"综合", faith:"信仰", safety:"安全", for_sale:"出售", free:"免费", lost_pet:"丢失宠物", event:"活动", help:"求助", recommend:"推荐", job:"工作", postTo:"发布到 {zip} - 一站式", tapMic:"点击麦克风 - 在 {zip} 可用 - 任何手机或电脑", postingAs:"发布为 • {zip} • {icon} {cat} • 通用麦克风", postBtn:"发布到 {zip} 🚀", addressPh:"📍 地址 - 私密", pricePh:"价格 $", freePh:"免费 (0)", new:"全新", likeNew:"接近全新", good:"良好", fair:"一般", detecting:"仍在检测你的街区...等待2秒再发布", micBlocked:"麦克风被阻止 - 检查浏览器权限" },
  ja: { general:"一般", faith:"信仰", safety:"安全", for_sale:"販売", free:"無料", lost_pet:"迷子ペット", event:"イベント", help:"ヘルプ", recommend:"おすすめ", job:"仕事", postTo:"{zip} に投稿 - ワンストップ", tapMic:"マイクをタップ - {zip}で動作 - どの端末でも", postingAs:"投稿者 • {zip} • {icon} {cat} • ユニバーサルマイク", postBtn:"{zip} に投稿 🚀", addressPh:"📍 住所 - 非公開", pricePh:"価格 $", freePh:"無料 (0)", new:"新品", likeNew:"ほぼ新品", good:"良好", fair:"可", detecting:"まだブロックを検出中...2秒待って再投稿", micBlocked:"マイクがブロック - 権限を確認" },
  ko: { general:"一般", faith:"信仰", safety:"安全", for_sale:"販売", free:"無料", lost_pet:"迷子ペット", event:"イベント", help:"ヘルプ", recommend:"おすすめ", job:"仕事", postTo:"{zip} に投稿 - ワンストップ", tapMic:"マイクをタップ - {zip}で動作 - どの端末でも", postingAs:"投稿者 • {zip} • {icon} {cat} • ユニバーサルマイク", postBtn:"{zip} に投稿 🚀", addressPh:"📍 住所 - 非公開", pricePh:"価格 $", freePh:"無料 (0)", new:"新品", likeNew:"ほぼ新品", good:"良好", fair:"可", detecting:"まだブロックを検出中...2秒待って再投稿", micBlocked:"マイクがブロック - 権限を確認" },
  pt: { general:"Geral", faith:"Fé", safety:"Segurança", for_sale:"À Venda", free:"Grátis", lost_pet:"Pet Perdido", event:"Evento", help:"Ajuda", recommend:"Recomendar", job:"Emprego", postTo:"Postar em {zip} - One Stop", tapMic:"Toque micro - funciona em {zip} - qualquer celular", postingAs:"Postando como • {zip} • {icon} {cat} • Mic Universal", postBtn:"Postar em {zip} 🚀", addressPh:"📍 Endereço - Privado", pricePh:"Preço $", freePh:"Grátis (0)", new:"Novo", likeNew:"Como Novo", good:"Bom", fair:"Regular", detecting:"Ainda detectando seu bloco... espere 2 seg", micBlocked:"Micro bloqueado - verifique permissões" },
  ru: { general:"Общее", faith:"Вера", safety:"Безопасность", for_sale:"Продам", free:"Бесплатно", lost_pet:"Потерян питомец", event:"Событие", help:"Помощь", recommend:"Рекомендую", job:"Работа", postTo:"Опубликовать в {zip} - One Stop", tapMic:"Нажми микро - работает в {zip} - любой телефон", postingAs:"Публикация как • {zip} • {icon} {cat} • Универсальный микрофон", postBtn:"Опубликовать в {zip} 🚀", addressPh:"📍 Адрес - Приватно", pricePh:"Цена $", freePh:"Бесплатно (0)", new:"Новый", likeNew:"Как Новый", good:"Хорошее", fair:"Удовл.", detecting:"Все еще определяем ваш блок... подождите 2 сек", micBlocked:"Микрофон заблокирован - проверьте разрешения" },
  ar: { general:"عام", faith:"إيمان", safety:"سلامة", for_sale:"للبيع", free:"مجاني", lost_pet:"حيوان مفقود", event:"حدث", help:"مساعدة", recommend:"توصية", job:"وظيفة", postTo:"انشر في {zip} - One Stop", tapMic:"اضغط الميكروفون - يعمل في {zip} - أي هاتف", postingAs:"النشر كـ • {zip} • {icon} {cat} • ميكروفون شامل", postBtn:"انشر في {zip} 🚀", addressPh:"📍 العنوان - خاص", pricePh:"السعر $", freePh:"مجاني (0)", new:"جديد", likeNew:"كأنه جديد", good:"جيد", fair:"مقبول", detecting:"لا يزال يكتشف منطقتك... انتظر ثانيتين", micBlocked:"الميكروفون محظور - تحقق من الأذونات" },
  hi: { general:"सामान्य", faith:"आस्था", safety:"सुरक्षा", for_sale:"बिक्री के लिए", free:"मुफ़्त", lost_pet:"खोया पालतू", event:"कार्यक्रम", help:"मदद", recommend:"सिफारिश", job:"नौकरी", postTo:"{zip} में पोस्ट - One Stop", tapMic:"माइक टैप करें - {zip} में काम करता है - कोई भी फोन", postingAs:"पोस्टिंग के रूप में • {zip} • {icon} {cat} • यूनिवर्सल माइक", postBtn:"{zip} में पोस्ट 🚀", addressPh:"📍 पता - निजी", pricePh:"कीमत $", freePh:"मुफ़्त (0)", new:"नया", likeNew:"नया जैसा", good:"अच्छा", fair:"ठीक", detecting:"अभी भी ब्लॉक पता कर रहे... 2 सेकंड प्रतीक्षा", micBlocked:"माइक ब्लॉक - अनुमति जांचें" },
  it: { general:"Generale", faith:"Fede", safety:"Sicurezza", for_sale:"In Vendita", free:"Gratis", lost_pet:"Animale Smarrito", event:"Evento", help:"Aiuto", recommend:"Consiglia", job:"Lavoro", postTo:"Pubblica a {zip} - One Stop", tapMic:"Tocca micro - funziona a {zip} - qualsiasi telefono", postingAs:"Pubblicando come • {zip} • {icon} {cat} • Mic Universale", postBtn:"Pubblica a {zip} 🚀", addressPh:"📍 Indirizzo - Privato", pricePh:"Prezzo $", freePh:"Gratis (0)", new:"Nuovo", likeNew:"Come Nuovo", good:"Buono", fair:"Discreto", detecting:"Ancora rilevamento del tuo blocco... attendi 2 sec", micBlocked:"Microfono bloccato - controlla permessi" },
  nl: { general:"Algemeen", faith:"Geloof", safety:"Veiligheid", for_sale:"Te Koop", free:"Gratis", lost_pet:"Huisdier Vermist", event:"Evenement", help:"Hulp", recommend:"Aanbevelen", job:"Baan", postTo:"Posten in {zip} - One Stop", tapMic:"Tik micro - werkt in {zip} - elke telefoon", postingAs:"Posten als • {zip} • {icon} {cat} • Universele Mic", postBtn:"Posten in {zip} 🚀", addressPh:"📍 Adres - Privé", pricePh:"Prijs $", freePh:"Gratis (0)", new:"Nieuw", likeNew:"Zo Goed Als Nieuw", good:"Goed", fair:"Redelijk", detecting:"Nog steeds je blok aan het detecteren... wacht 2 sec", micBlocked:"Micro geblokkeerd - controleer rechten" },
  tl: { general:"Pangkalahatan", faith:"Pananampalataya", safety:"Kaligtasan", for_sale:"For Sale", free:"Libre", lost_pet:"Nawalang Alaga", event:"Event", help:"Tulong", recommend:"Irekomenda", job:"Trabaho", postTo:"Mag-post sa {zip} - One Stop", tapMic:"I-tap mic - gumagana sa {zip} - kahit anong phone", postingAs:"Nagpo-post bilang • {zip} • {icon} {cat} • Universal Mic", postBtn:"Mag-post sa {zip} 🚀", addressPh:"📍 Address - Pribado", pricePh:"Presyo $", freePh:"Libre (0)", new:"Bago", likeNew:"Parang Bago", good:"Mabuti", fair:"Patatas", detecting:"Dine-detect pa block mo... hintay 2 sec", micBlocked:"Naka-block mic - check permissions" },
  bn: { general:"সাধারণ", faith:"বিশ্বাস", safety:"নিরাপত্তা", for_sale:"বিক্রির জন্য", free:"বিনামূল্যে", lost_pet:"হারানো পোষা", event:"ইভেন্ট", help:"সাহায্য", recommend:"সুপারিশ", job:"চাকরি", postTo:"{zip} এ পোস্ট - One Stop", tapMic:"মাইক ট্যাপ করুন - {zip} এ কাজ করে - যেকোনো ফোন", postingAs:"পোস্ট হিসাবে • {zip} • {icon} {cat} • ইউনিভার্সাল মাইক", postBtn:"{zip} এ পোস্ট 🚀", addressPh:"📍 ঠিকানা - ব্যক্তিগত", pricePh:"দাম $", freePh:"বিনামূল্যে (0)", new:"নতুন", likeNew:"নতুনের মতো", good:"ভালো", fair:"মোটামুটি", detecting:"এখনও আপনার ব্লক সনাক্ত করছে... 2 সেকেন্ড অপেক্ষা করুন", micBlocked:"মাইক ব্লক - অনুমতি পরীক্ষা করুন" },
  id: { general:"Umum", faith:"Iman", safety:"Keamanan", for_sale:"Dijual", free:"Gratis", lost_pet:"Hewan Hilang", event:"Acara", help:"Bantuan", recommend:"Rekomendasi", job:"Pekerjaan", postTo:"Posting ke {zip} - One Stop", tapMic:"Ketuk mic - berfungsi di {zip} - ponsel apa saja", postingAs:"Posting sebagai • {zip} • {icon} {cat} • Mic Universal", postBtn:"Posting ke {zip} 🚀", addressPh:"📍 Alamat - Privat", pricePh:"Harga $", freePh:"Gratis (0)", new:"Baru", likeNew:"Seperti Baru", good:"Bagus", fair:"Cukup", detecting:"Masih mendeteksi blok Anda... tunggu 2 detik", micBlocked:"Mic diblokir - cek izin" },
  vi: { general:"Chung", faith:"Đức tin", safety:"An toàn", for_sale:"Rao Bán", free:"Miễn Phí", lost_pet:"Thú Cưng Lạc", event:"Sự Kiện", help:"Giúp Đỡ", recommend:"Đề Xuất", job:"Việc Làm", postTo:"Đăng tới {zip} - One Stop", tapMic:"Chạm mic - hoạt động ở {zip} - bất kỳ điện thoại", postingAs:"Đăng với tư cách • {zip} • {icon} {cat} • Mic Toàn Cầu", postBtn:"Đăng tới {zip} 🚀", addressPh:"📍 Địa chỉ - Riêng tư", pricePh:"Giá $", freePh:"Miễn phí (0)", new:"Mới", likeNew:"Như Mới", good:"Tốt", fair:"Khá", detecting:"Vẫn đang phát hiện khối của bạn... đợi 2 giây", micBlocked:"Mic bị chặn - kiểm tra quyền" },
  th: { general:"ทั่วไป", faith:"ศรัทธา", safety:"ความปลอดภัย", for_sale:"ขาย", free:"ฟรี", lost_pet:"สัตว์เลี้ยงหาย", event:"กิจกรรม", help:"ช่วยเหลือ", recommend:"แนะนำ", job:"งาน", postTo:"โพสต์ไปที่ {zip} - One Stop", tapMic:"แตะไมค์ - ทำงานใน {zip} - โทรศัพท์ใดก็ได้", postingAs:"โพสต์เป็น • {zip} • {icon} {cat} • ไมค์สากล", postBtn:"โพสต์ไปที่ {zip} 🚀", addressPh:"📍 ที่อยู่ - ส่วนตัว", pricePh:"ราคา $", freePh:"ฟรี (0)", new:"ใหม่", likeNew:"เหมือนใหม่", good:"ดี", fair:"พอใช้", detecting:"ยังตรวจจับบล็อกของคุณอยู่...รอ 2 วินาที", micBlocked:"ไมค์ถูกบล็อก - ตรวจสอบสิทธิ์" },
  sv: { general:"Allmänt", faith:"Tro", safety:"Säkerhet", for_sale:"Till Salu", free:"Gratis", lost_pet:"Borttappat Husdjur", event:"Evenemang", help:"Hjälp", recommend:"Rekommendera", job:"Jobb", postTo:"Posta till {zip} - One Stop", tapMic:"Tryck mic - fungerar i {zip} - vilken telefon som helst", postingAs:"Postar som • {zip} • {icon} {cat} • Universal Mic", postBtn:"Posta till {zip} 🚀", addressPh:"📍 Adress - Privat", pricePh:"Pris $", freePh:"Gratis (0)", new:"Ny", likeNew:"Som Ny", good:"Bra", fair:"Ok", detecting:"Upptäcker fortfarande ditt kvarter... vänta 2 sek", micBlocked:"Mic blockerad - kolla behörigheter" },
  pl: { general:"Ogólne", faith:"Wiara", safety:"Bezpieczeństwo", for_sale:"Na Sprzedaż", free:"Za Darmo", lost_pet:"Zaginione Zwierzę", event:"Wydarzenie", help:"Pomoc", recommend:"Poleć", job:"Praca", postTo:"Postuj do {zip} - One Stop", tapMic:"Kliknij mikro - działa w {zip} - dowolny telefon", postingAs:"Postowanie jako • {zip} • {icon} {cat} • Uniwersalny Mikrofon", postBtn:"Postuj do {zip} 🚀", addressPh:"📍 Adres - Prywatny", pricePh:"Cena $", freePh:"Za darmo (0)", new:"Nowy", likeNew:"Jak Nowy", good:"Dobry", fair:"Dostateczny", detecting:"Wciąż wykrywamy twój blok... poczekaj 2 sek", micBlocked:"Mikrofon zablokowany - sprawdź uprawnienia" },
  tr: { general:"Genel", faith:"İnanç", safety:"Güvenlik", for_sale:"Satılık", free:"Ücretsiz", lost_pet:"Kayıp Evcil", event:"Etkinlik", help:"Yardım", recommend:"Öner", job:"İş", postTo:"{zip} konumuna gönder - One Stop", tapMic:"Mikrofona dokun - {zip} içinde çalışır - herhangi telefon", postingAs:"Gönderim olarak • {zip} • {icon} {cat} • Evrensel Mikrofon", postBtn:"{zip} konumuna gönder 🚀", addressPh:"📍 Adres - Gizli", pricePh:"Fiyat $", freePh:"Ücretsiz (0)", new:"Yeni", likeNew:"Yeni Gibi", good:"İyi", fair:"Orta", detecting:"Blokunuz hala tespit ediliyor... 2 sn bekleyin", micBlocked:"Mikrofon engellendi - izinleri kontrol et" },
  uk: { general:"Загальне", faith:"Віра", safety:"Безпека", for_sale:"Продам", free:"Безкоштовно", lost_pet:"Загублений улюбленець", event:"Подія", help:"Допомога", recommend:"Рекомендую", job:"Робота", postTo:"Опублікувати в {zip} - One Stop", tapMic:"Натисни мікро - працює в {zip} - будь-який телефон", postingAs:"Публікація як • {zip} • {icon} {cat} • Універсальний мікрофон", postBtn:"Опублікувати в {zip} 🚀", addressPh:"📍 Адреса - Приватна", pricePh:"Ціна $", freePh:"Безкоштовно (0)", new:"Новий", likeNew:"Як Новий", good:"Добре", fair:"Задовільно", detecting:"Все ще визначаємо ваш блок... зачекайте 2 сек", micBlocked:"Мікрофон заблоковано - перевірте дозволи" },
  el: { general:"Γενικά", faith:"Πίστη", safety:"Ασφάλεια", for_sale:"Προς Πώληση", free:"Δωρεάν", lost_pet:"Χαμένο Κατοικίδιο", event:"Εκδήλωση", help:"Βοήθεια", recommend:"Προτείνω", job:"Εργασία", postTo:"Δημοσίευση σε {zip} - One Stop", tapMic:"Πατήστε μικρόφωνο - λειτουργεί σε {zip} - οποιοδήποτε τηλέφωνο", postingAs:"Δημοσίευση ως • {zip} • {icon} {cat} • Καθολικό Μικρόφωνο", postBtn:"Δημοσίευση σε {zip} 🚀", addressPh:"📍 Διεύθυνση - Ιδιωτική", pricePh:"Τιμή $", freePh:"Δωρεάν (0)", new:"Καινούργιο", likeNew:"Σαν Καινούργιο", good:"Καλό", fair:"Μέτριο", detecting:"Ακόμα εντοπισμός του block σας... περιμένετε 2 δευτ.", micBlocked:"Μικρόφωνο μπλοκαρισμένο - ελέγξτε δικαιώματα" },
  he: { general:"כללי", faith:"אמונה", safety:"בטיחות", for_sale:"למכירה", free:"חינם", lost_pet:"חיית מחמד אבודה", event:"אירוע", help:"עזרה", recommend:"המלצה", job:"עבודה", postTo:"פרסם ל {zip} - One Stop", tapMic:"הקש מיקרופון - עובד ב {zip} - כל טלפון", postingAs:"מפרסם כ • {zip} • {icon} {cat} • מיקרופון אוניברסלי", postBtn:"פרסם ל {zip} 🚀", addressPh:"📍 כתובת - פרטי", pricePh:"מחיר $", freePh:"חינם (0)", new:"חדש", likeNew:"כמו חדש", good:"טוב", fair:"סביר", detecting:"עדיין מזהה את הבלוק שלך... המתן 2 שניות", micBlocked:"מיקרופון חסום - בדוק הרשאות" },
  ur: { general:"عام", faith:"ایمان", safety:"حفاظت", for_sale:"برائے فروخت", free:"مفت", lost_pet:"گمشدہ پالتو", event:"تقریب", help:"مدد", recommend:"تجویز", job:"نوکری", postTo:"{zip} میں پوسٹ کریں - One Stop", tapMic:"مائک دبائیں - {zip} میں کام کرتا ہے - کوئی بھی فون", postingAs:"پوسٹ بطور • {zip} • {icon} {cat} • یونیورسل مائک", postBtn:"{zip} میں پوسٹ 🚀", addressPh:"📍 پتہ - نجی", pricePh:"قیمت $", freePh:"مفت (0)", new:"نیا", likeNew:"نئے جیسا", good:"اچھا", fair:"مناسب", detecting:"ابھی بھی آپ کا بلاک معلوم کر رہے... 2 سیکنڈ انتظار", micBlocked:"مائک بلاک - اجازت چیک کریں" },
  fa: { general:"عمومی", faith:"ایمان", safety:"ایمنی", for_sale:"برای فروش", free:"رایگان", lost_pet:"حیوان خانگی گمشده", event:"رویداد", help:"کمک", recommend:"توصیه", job:"شغل", postTo:"ارسال به {zip} - One Stop", tapMic:"میک را بزن - در {zip} کار می کند - هر تلفن", postingAs:"ارسال به عنوان • {zip} • {icon} {cat} • میک جهانی", postBtn:"ارسال به {zip} 🚀", addressPh:"📍 آدرس - خصوصی", pricePh:"قیمت $", freePh:"رایگان (0)", new:"نو", likeNew:"مثل نو", good:"خوب", fair:"متوسط", detecting:"هنوز در حال تشخیص بلوک شما... 2 ثانیه صبر کنید", micBlocked:"میک مسدود - مجوزها را بررسی کنید" },
  ms: { general:"Umum", faith:"Kepercayaan", safety:"Keselamatan", for_sale:"Untuk Dijual", free:"Percuma", lost_pet:"Haiwan Hilang", event:"Acara", help:"Bantuan", recommend:"Syorkan", job:"Kerja", postTo:"Post ke {zip} - One Stop", tapMic:"Ketik mic - berfungsi di {zip} - apa-apa telefon", postingAs:"Posting sebagai • {zip} • {icon} {cat} • Mic Universal", postBtn:"Post ke {zip} 🚀", addressPh:"📍 Alamat - Peribadi", pricePh:"Harga $", freePh:"Percuma (0)", new:"Baru", likeNew:"Seperti Baru", good:"Baik", fair:"Sederhana", detecting:"Masih mengesan blok anda... tunggu 2 saat", micBlocked:"Mic disekat - semak kebenaran" },
  ro: { general:"General", faith:"Credință", safety:"Siguranță", for_sale:"De Vânzare", free:"Gratis", lost_pet:"Animal Pierdut", event:"Eveniment", help:"Ajutor", recommend:"Recomandă", job:"Job", postTo:"Postează în {zip} - One Stop", tapMic:"Atinge micro - funcționează în {zip} - orice telefon", postingAs:"Postare ca • {zip} • {icon} {cat} • Mic Universal", postBtn:"Postează în {zip} 🚀", addressPh:"📍 Adresă - Privat", pricePh:"Preț $", freePh:"Gratis (0)", new:"Nou", likeNew:"Ca Nou", good:"Bun", fair:"Acceptabil", detecting:"Încă detectăm blocul tău... așteaptă 2 sec", micBlocked:"Microfon blocat - verifică permisiuni" },
  cs: { general:"Obecné", faith:"Víra", safety:"Bezpečnost", for_sale:"Na Prodej", free:"Zdarma", lost_pet:"Ztracený Mazlíček", event:"Událost", help:"Pomoc", recommend:"Doporučit", job:"Práce", postTo:"Publikovat do {zip} - One Stop", tapMic:"Klepni na mikro - funguje v {zip} - jakýkoli telefon", postingAs:"Publikování jako • {zip} • {icon} {cat} • Univerzální mikrofon", postBtn:"Publikovat do {zip} 🚀", addressPh:"📍 Adresa - Soukromá", pricePh:"Cena $", freePh:"Zdarma (0)", new:"Nové", likeNew:"Jako Nové", good:"Dobré", fair:"Uspokojivé", detecting:"Stále zjišťujeme váš blok... počkejte 2 s", micBlocked:"Mikrofon zablokován - zkontrolujte oprávnění" },
  hu: { general:"Általános", faith:"Hit", safety:"Biztonság", for_sale:"Eladó", free:"Ingyen", lost_pet:"Elveszett Kisállat", event:"Esemény", help:"Segítség", recommend:"Ajánlás", job:"Munka", postTo:"Posztolás {zip} - One Stop", tapMic:"Érints mikrofont - működik {zip} - bármilyen telefon", postingAs:"Posztolás mint • {zip} • {icon} {cat} • Univerzális Mikrofon", postBtn:"Posztolás {zip} 🚀", addressPh:"📍 Cím - Privát", pricePh:"Ár $", freePh:"Ingyen (0)", new:"Új", likeNew:"Újszerű", good:"Jó", fair:"Megfelelő", detecting:"Még mindig észleljük a blokkod... várj 2 mp", micBlocked:"Mikrofon blokkolva - ellenőrizd engedélyek" },
  fi: { general:"Yleinen", faith:"Usko", safety:"Turvallisuus", for_sale:"Myynnissä", free:"Ilmainen", lost_pet:"Kadonnut Lemmikki", event:"Tapahtuma", help:"Apua", recommend:"Suosittele", job:"Työ", postTo:"Julkaise {zip} - One Stop", tapMic:"Napauta mikkiä - toimii {zip} - mikä tahansa puhelin", postingAs:"Julkaistaan • {zip} • {icon} {cat} • Universaali Mikki", postBtn:"Julkaise {zip} 🚀", addressPh:"📍 Osoite - Yksityinen", pricePh:"Hinta $", freePh:"Ilmainen (0)", new:"Uusi", likeNew:"Kuin Uusi", good:"Hyvä", fair:"Kohtalainen", detecting:"Vielä tunnistetaan lohkoasi... odota 2 s", micBlocked:"Mikki estetty - tarkista oikeudet" },
  no: { general:"Generelt", faith:"Tro", safety:"Sikkerhet", for_sale:"Til Salgs", free:"Gratis", lost_pet:"Savnet Kjæledyr", event:"Arrangement", help:"Hjelp", recommend:"Anbefal", job:"Jobb", postTo:"Post til {zip} - One Stop", tapMic:"Trykk mic - fungerer i {zip} - hvilken som helst telefon", postingAs:"Poster som • {zip} • {icon} {cat} • Universal Mic", postBtn:"Post til {zip} 🚀", addressPh:"📍 Adresse - Privat", pricePh:"Pris $", freePh:"Gratis (0)", new:"Ny", likeNew:"Som Ny", good:"Bra", fair:"Greit", detecting:"Oppdager fortsatt blokken din... vent 2 sek", micBlocked:"Mic blokkert - sjekk tillatelser" },
  da: { general:"Generelt", faith:"Tro", safety:"Sikkerhed", for_sale:"Til Salg", free:"Gratis", lost_pet:"Savnet Kæledyr", event:"Begivenhed", help:"Hjælp", recommend:"Anbefal", job:"Job", postTo:"Post til {zip} - One Stop", tapMic:"Tryk mic - virker i {zip} - enhver telefon", postingAs:"Poster som • {zip} • {icon} {cat} • Universal Mic", postBtn:"Post til {zip} 🚀", addressPh:"📍 Adresse - Privat", pricePh:"Pris $", freePh:"Gratis (0)", new:"Ny", likeNew:"Som Ny", good:"God", fair:"Ok", detecting:"Registrerer stadig din blok... vent 2 sek", micBlocked:"Mic blokeret - tjek tilladelser" },
  bg: { general:"Общо", faith:"Вяра", safety:"Безопасност", for_sale:"За Продажба", free:"Безплатно", lost_pet:"Изгубен Любимец", event:"Събитие", help:"Помощ", recommend:"Препоръчай", job:"Работа", postTo:"Публикувай в {zip} - One Stop", tapMic:"Натисни микрофон - работи в {zip} - всеки телефон", postingAs:"Публикуване като • {zip} • {icon} {cat} • Универсален Микрофон", postBtn:"Публикувай в {zip} 🚀", addressPh:"📍 Адрес - Личен", pricePh:"Цена $", freePh:"Безплатно (0)", new:"Нов", likeNew:"Като Нов", good:"Добро", fair:"Задоволително", detecting:"Все още откриваме вашия блок... изчакайте 2 сек", micBlocked:"Микрофон блокиран - проверете разрешения" },
  hr: { general:"Općenito", faith:"Vjera", safety:"Sigurnost", for_sale:"Na Prodaju", free:"Besplatno", lost_pet:"Izgubljen Ljubimac", event:"Događaj", help:"Pomoć", recommend:"Preporuči", job:"Posao", postTo:"Objavi u {zip} - One Stop", tapMic:"Dodirni mikro - radi u {zip} - bilo koji telefon", postingAs:"Objava kao • {zip} • {icon} {cat} • Univerzalni Mikrofon", postBtn:"Objavi u {zip} 🚀", addressPh:"📍 Adresa - Privatno", pricePh:"Cijena $", freePh:"Besplatno (0)", new:"Novo", likeNew:"Kao Novo", good:"Dobro", fair:"Zadovoljavajuće", detecting:"Još uvijek otkrivamo vaš blok... pričekajte 2 sek", micBlocked:"Mikrofon blokiran - provjerite dozvole" },
  sr: { general:"Опште", faith:"Вера", safety:"Безбедност", for_sale:"На Продају", free:"Бесплатно", lost_pet:"Изгубљен Љубимац", event:"Догађај", help:"Помоћ", recommend:"Препоручи", job:"Посао", postTo:"Објави у {zip} - One Stop", tapMic:"Додирни микро - ради у {zip} - било који телефон", postingAs:"Објава као • {zip} • {icon} {cat} • Универзални Микрофон", postBtn:"Објави у {zip} 🚀", addressPh:"📍 Адреса - Приватно", pricePh:"Цена $", freePh:"Бесплатно (0)", new:"Ново", likeNew:"Као Ново", good:"Добро", fair:"Задовољавајуће", detecting:"Још увек откривамо ваш блок... сачекајте 2 сек", micBlocked:"Микрофон блокиран - проверите дозволе" },
  sk: { general:"Všeobecné", faith:"Viera", safety:"Bezpečnosť", for_sale:"Na Predaj", free:"Zadarmo", lost_pet:"Stratený Miláčik", event:"Udalosť", help:"Pomoc", recommend:"Odporučiť", job:"Práca", postTo:"Publikovať do {zip} - One Stop", tapMic:"Klepni mikrofón - funguje v {zip} - akýkoľvek telefón", postingAs:"Publikovanie ako • {zip} • {icon} {cat} • Univerzálny Mikrofón", postBtn:"Publikovať do {zip} 🚀", addressPh:"📍 Adresa - Súkromná", pricePh:"Cena $", freePh:"Zadarmo (0)", new:"Nové", likeNew:"Ako Nové", good:"Dobré", fair:"Uspokojivé", detecting:"Stále zisťujeme váš blok... počkajte 2 s", micBlocked:"Mikrofón zablokovaný - skontrolujte oprávnenia" },
  sl: { general:"Splošno", faith:"Vera", safety:"Varnost", for_sale:"Naprodaj", free:"Brezplačno", lost_pet:"Izgubljen Ljubljenček", event:"Dogodek", help:"Pomoč", recommend:"Priporoči", job:"Delo", postTo:"Objavi v {zip} - One Stop", tapMic:"Tapni mikro - deluje v {zip} - kateri koli telefon", postingAs:"Objava kot • {zip} • {icon} {cat} • Univerzalni Mikrofon", postBtn:"Objavi v {zip} 🚀", addressPh:"📍 Naslov - Zasebno", pricePh:"Cena $", freePh:"Brezplačno (0)", new:"Novo", likeNew:"Kot Novo", good:"Dobro", fair:"Zadovoljivo", detecting:"Še vedno zaznavamo vaš blok... počakajte 2 sek", micBlocked:"Mikrofon blokiran - preverite dovoljenja" },
  et: { general:"Üldine", faith:"Usk", safety:"Turvalisus", for_sale:"Müügil", free:"Tasuta", lost_pet:"Kadunud Lemmik", event:"Sündmus", help:"Abi", recommend:"Soovita", job:"Töö", postTo:"Postita {zip} - One Stop", tapMic:"Puuduta mikrofoni - töötab {zip} - iga telefon", postingAs:"Postitamine kui • {zip} • {icon} {cat} • Universaalne Mikrofon", postBtn:"Postita {zip} 🚀", addressPh:"📍 Aadress - Privaatne", pricePh:"Hind $", freePh:"Tasuta (0)", new:"Uus", likeNew:"Uusväärne", good:"Hea", fair:"Rahuldav", detecting:"Ikka tuvastame teie plokki... oodake 2 sek", micBlocked:"Mikrofon blokeeritud - kontrolli õigusi" },
  lv: { general:"Vispārīgi", faith:"Ticība", safety:"Drošība", for_sale:"Pārdošanā", free:"Bezmaksas", lost_pet:"Pazudis Mīlulis", event:"Pasākums", help:"Palīdzība", recommend:"Ieteikt", job:"Darbs", postTo:"Publicēt {zip} - One Stop", tapMic:"Pieskaries mikro - darbojas {zip} - jebkurš tālrunis", postingAs:"Publicē kā • {zip} • {icon} {cat} • Universāls Mikrofons", postBtn:"Publicēt {zip} 🚀", addressPh:"📍 Adrese - Privāta", pricePh:"Cena $", freePh:"Bezmaksas (0)", new:"Jauns", likeNew:"Kā Jauns", good:"Labs", fair:"Apmierinošs", detecting:"Joprojām nosaka jūsu bloku... pagaidiet 2 sek", micBlocked:"Mikrofons bloķēts - pārbaudiet atļaujas" },
  lt: { general:"Bendra", faith:"Tikėjimas", safety:"Saugumas", for_sale:"Parduodama", free:"Nemokamai", lost_pet:"Dingęs Augintinis", event:"Renginys", help:"Pagalba", recommend:"Rekomenduoti", job:"Darbas", postTo:"Paskelbti į {zip} - One Stop", tapMic:"Palieskite mikro - veikia {zip} - bet koks telefonas", postingAs:"Skelbiama kaip • {zip} • {icon} {cat} • Universalus Mikrofonas", postBtn:"Paskelbti į {zip} 🚀", addressPh:"📍 Adresas - Privatus", pricePh:"Kaina $", freePh:"Nemokamai (0)", new:"Naujas", likeNew:"Kaip Naujas", good:"Geras", fair:"Patenkinamas", detecting:"Vis dar aptinkame jūsų bloką... palaukite 2 sek", micBlocked:"Mikrofonas užblokuotas - patikrinkite leidimus" },
  be: { general:"Агульнае", faith:"Вера", safety:"Бяспека", for_sale:"На Продаж", free:"Бясплатна", lost_pet:"Згублены Гадаванец", event:"Падзея", help:"Дапамога", recommend:"Рэкамендаваць", job:"Праца", postTo:"Апублікаваць у {zip} - One Stop", tapMic:"Націсні мікра - працуе ў {zip} - любы тэлефон", postingAs:"Публікацыя як • {zip} • {icon} {cat} • Універсальны Мікрафон", postBtn:"Апублікаваць у {zip} 🚀", addressPh:"📍 Адрас - Прыватны", pricePh:"Цана $", freePh:"Бясплатна (0)", new:"Новы", likeNew:"Як Новы", good:"Добра", fair:"Здавальняюча", detecting:"Усё яшчэ вызначаем ваш блок... пачакайце 2 сек", micBlocked:"Мікрафон заблакаваны - праверце дазволы" },
  ka: { general:"ზოგადი", faith:"რწმენა", safety:"უსაფრთხოება", for_sale:"იყიდება", free:"უფასო", lost_pet:"დაკარგული შინაური", event:"ღონისძიება", help:"დახმარება", recommend:"რეკომენდაცია", job:"სამსახური", postTo:"გამოქვეყნება {zip} - One Stop", tapMic:"შეეხე მიკროფონს - მუშაობს {zip}-ში - ნებისმიერი ტელეფონი", postingAs:"გამოქვეყნება როგორც • {zip} • {icon} {cat} • უნივერსალური მიკროფონი", postBtn:"გამოქვეყნება {zip} 🚀", addressPh:"📍 მისამართი - პირადი", pricePh:"ფასი $", freePh:"უფასო (0)", new:"ახალი", likeNew:"ახალივით", good:"კარგი", fair:"დამაკმაყოფილებელი", detecting:"ჯერ კიდევ ვადგენთ თქვენს ბლოკს... დაელოდეთ 2 წმ", micBlocked:"მიკროფონი დაბლოკილია - შეამოწმეთ ნებართვები" },
  hy: { general:"Ընդհանուր", faith:"Հավատ", safety:"Անվտանգություն", for_sale:"Վաճառվում է", free:"Անվճար", lost_pet:"Կորած Ընտանի կենդանի", event:"Իրադարձություն", help:"Օգնություն", recommend:"Առաջարկել", job:"Աշխատանք", postTo:"Հրապարակել {zip}-ում - One Stop", tapMic:"Հպեք խոսափողին - աշխատում է {zip}-ում - ցանկացած հեռախոս", postingAs:"Հրապարակում որպես • {zip} • {icon} {cat} • Ունիվերսալ խոսափող", postBtn:"Հրապարակել {zip} 🚀", addressPh:"📍 Հասցե - Անձնական", pricePh:"Գին $", freePh:"Անվճար (0)", new:"Նոր", likeNew:"Նորի պես", good:"Լավ", fair:"Բավարար", detecting:"Դեռ հայտնաբերում ենք ձեր բլոկը... սպասեք 2 վրկ", micBlocked:"Խոսափողը արգելափակված է - ստուգեք թույլտվությունները" },
  az: { general:"Ümumi", faith:"İnam", safety:"Təhlükəsizlik", for_sale:"Satılır", free:"Pulsuz", lost_pet:"İtmiş Heyvan", event:"Tədbir", help:"Kömək", recommend:"Tövsiyə et", job:"İş", postTo:"{zip}-ə post et - One Stop", tapMic:"Mikrofona toxun - {zip}-də işləyir - hər hansı telefon", postingAs:"Post kimi • {zip} • {icon} {cat} • Universal Mikrofon", postBtn:"{zip}-ə post et 🚀", addressPh:"📍 Ünvan - Şəxsi", pricePh:"Qiymət $", freePh:"Pulsuz (0)", new:"Yeni", likeNew:"Yeni Kimi", good:"Yaxşı", fair:"Qənaətbəxş", detecting:"Hələ də blokunuzu aşkarlayırıq... 2 san gözləyin", micBlocked:"Mikrofon bloklandı - icazələri yoxlayın" },
  kk: { general:"Жалпы", faith:"Сенім", safety:"Қауіпсіздік", for_sale:"Сатылады", free:"Тегін", lost_pet:"Жоғалған Үй Жануары", event:"Оқиға", help:"Көмек", recommend:"Ұсыну", job:"Жұмыс", postTo:"{zip}-ға жариялау - One Stop", tapMic:"Микрофонды түртіңіз - {zip}-да жұмыс істейді - кез келген телефон", postingAs:"Жариялау ретінде • {zip} • {icon} {cat} • Әмбебап Микрофон", postBtn:"{zip}-ға жариялау 🚀", addressPh:"📍 Мекенжай - Жеке", pricePh:"Баға $", freePh:"Тегін (0)", new:"Жаңа", likeNew:"Жаңа Сияқты", good:"Жақсы", fair:"Қанағаттанарлық", detecting:"Блок әлі анықталуда... 2 сек күтіңіз", micBlocked:"Микрофон бұғатталған - рұқсаттарды тексеріңіз" },
  ky: { general:"Жалпы", faith:"Ишеним", safety:"Коопсуздук", for_sale:"Сатылат", free:"Акысыз", lost_pet:"Жоголгон Үй Жаныбары", event:"Иш-чара", help:"Жардам", recommend:"Сунуштоо", job:"Жумуш", postTo:"{zip}-га жарыялоо - One Stop", tapMic:"Микрофонду таптап - {zip}-да иштейт - каалаган телефон", postingAs:"Жарыялоо катары • {zip} • {icon} {cat} • Универсал Микрофон", postBtn:"{zip}-га жарыялоо 🚀", addressPh:"📍 Дарек - Жеке", pricePh:"Баа $", freePh:"Акысыз (0)", new:"Жаңы", likeNew:"Жаңы Сыяктуу", good:"Жакшы", fair:"Канааттандырарлык", detecting:"Блок дагы аныкталууда... 2 сек күтө туруңуз", micBlocked:"Микрофон бөгөттөлдү - уруксаттарды текшериңиз" },
  uz: { general:"Umumiy", faith:"E'tiqod", safety:"Xavfsizlik", for_sale:"Sotiladi", free:"Bepul", lost_pet:"Yo'qolgan Uy Hayvoni", event:"Tadbir", help:"Yordam", recommend:"Tavsiya", job:"Ish", postTo:"{zip} ga joylash - One Stop", tapMic:"Mikrofonga teging - {zip} da ishlaydi - har qanday telefon", postingAs:"Joylash sifatida • {zip} • {icon} {cat} • Universal Mikrofon", postBtn:"{zip} ga joylash 🚀", addressPh:"📍 Manzil - Shaxsiy", pricePh:"Narx $", freePh:"Bepul (0)", new:"Yangi", likeNew:"Yangi Kabi", good:"Yaxshi", fair:"Qoniqarli", detecting:"Blokingiz hali aniqlanmoqda... 2 soniya kuting", micBlocked:"Mikrofon bloklangan - ruxsatlarni tekshiring" },
  tg: { general:"Умумӣ", faith:"Эътиқод", safety:"Беҳатарӣ", for_sale:"Барои фурӯш", free:"Ройгон", lost_pet:"Ҳайвони гумшуда", event:"Чорабинӣ", help:"Кӯмак", recommend:"Тавсия", job:"Кор", postTo:"Ба {zip} интишор кунед - One Stop", tapMic:"Микрофонро ламс кунед - дар {zip} кор мекунад - ҳар телефон", postingAs:"Интишор ҳамчун • {zip} • {icon} {cat} • Микрофони универсалӣ", postBtn:"Ба {zip} интишор 🚀", addressPh:"📍 Суроға - Хусусӣ", pricePh:"Нарх $", freePh:"Ройгон (0)", new:"Нав", likeNew:"Мисли нав", good:"Хуб", fair:"Қаноатбахш", detecting:"Ҳоло ҳам блоки шуморо муайян мекунем... 2 сония интизор шавед", micBlocked:"Микрофон баста шуд - иҷозатҳоро санҷед" },
  mn: { general:"Ерөнхий", faith:"Итгэл", safety:"Аюулгүй байдал", for_sale:"Зарна", free:"Үнэгүй", lost_pet:"Төөрсөн Тэжээвэр", event:"Арга хэмжээ", help:"Тусламж", recommend:"Зөвлөмж", job:"Ажил", postTo:"{zip} руу нийтлэх - One Stop", tapMic:"Микрофоныг дар - {zip} дотор ажиллана - ямар ч утас", postingAs:"Нийтлэх хэлбэрээр • {zip} • {icon} {cat} • Универсал Микрофон", postBtn:"{zip} руу нийтлэх 🚀", addressPh:"📍 Хаяг - Хувийн", pricePh:"Үнэ $", freePh:"Үнэгүй (0)", new:"Шинэ", likeNew:"Шинэ Шиг", good:"Сайн", fair:"Дунд", detecting:"Таны блокыг одоо хүртэл илрүүлж байна... 2 сек хүлээнэ үү", micBlocked:"Микрофон блоклогдсон - зөвшөөрлийг шалгана уу" },
  km: { general:"ទូទៅ", faith:"ជំនឿ", safety:"សុវត្ថិភាព", for_sale:"លក់", free:"ឥតគិតថ្លៃ", lost_pet:"សត្វចិញ្ចឹមបាត់", event:"ព្រឹត្តិការណ៍", help:"ជំនួយ", recommend:"ណែនាំ", job:"ការងារ", postTo:"បង្ហោះទៅ {zip} - One Stop", tapMic:"ចុចមីក្រូ - ដំណើរការនៅ {zip} - ទូរស័ព្ទណាមួយ", postingAs:"បង្ហោះជា • {zip} • {icon} {cat} • មីក្រូសកល", postBtn:"បង្ហោះទៅ {zip} 🚀", addressPh:"📍 អាសយដ្ឋាន - ឯកជន", pricePh:"តម្លៃ $", freePh:"ឥតគិតថ្លៃ (0)", new:"ថ្មី", likeNew:"ដូចថ្មី", good:"ល្អ", fair:"មធ្យម", detecting:"នៅតែរកឃើញប្លុករបស់អ្នក...រង់ចាំ 2 វិនាទី", micBlocked:"មីក្រូត្រូវបានប្លុក - ពិនិត្យការអនុញ្ញាត" },
  lo: { general:"ທົ່ວໄປ", faith:"ຄວາມເຊື່ອ", safety:"ຄວາມປອດໄພ", for_sale:"ຂາຍ", free:"ຟຣີ", lost_pet:"ສັດລ້ຽງຫາຍ", event:"ເຫດການ", help:"ຊ່ວຍເຫຼືອ", recommend:"ແນະນຳ", job:"ວຽກ", postTo:"ໂພສໄປ {zip} - One Stop", tapMic:"ແຕະໄມ - ເຮັດວຽກໃນ {zip} - ໂທລະສັບໃດກໍໄດ້", postingAs:"ໂພສເປັນ • {zip} • {icon} {cat} • ໄມສາກົນ", postBtn:"ໂພສໄປ {zip} 🚀", addressPh:"📍 ທີ່ຢູ່ - ສ່ວນຕົວ", pricePh:"ລາຄາ $", freePh:"ຟຣີ (0)", new:"ໃໝ່", likeNew:"ຄືໃໝ່", good:"ດີ", fair:"ພໍໃຊ້", detecting:"ຍັງກວດຈັບບລັອກຂອງທ່ານ...ລໍຖ້າ 2 ວິ", micBlocked:"ໄມຖືກບລັອກ - ກວດສອບສິດ" },
  my: { general:"အထွေထွေ", faith:"ယုံကြည်မှု", safety:"ဘေးကင်းရေး", for_sale:"ရောင်းရန်", free:"အခမဲ့", lost_pet:"ပျောက်ဆုံးအိမ်မွေးတိရစ္ဆာန်", event:"ပွဲ", help:"အကူအညီ", recommend:"အကြံပြုရန်", job:"အလုပ်", postTo:"{zip} သို့ တင်ရန် - One Stop", tapMic:"မိုက်ကိုနှိပ်ပါ - {zip} တွင်အလုပ်လုပ်သည် - မည်သည့်ဖုန်းမဆို", postingAs:"တင်ခြင်းအဖြစ် • {zip} • {icon} {cat} • ယူနီဗာဆယ်မိုက်", postBtn:"{zip} သို့ တင်ရန် 🚀", addressPh:"📍 လိပ်စာ - ကိုယ်ပိုင်", pricePh:"ဈေးနှုန်း $", freePh:"အခမဲ့ (0)", new:"အသစ်", likeNew:"အသစ်လိုလို", good:"ကောင်းသော", fair:"သင့်", detecting:"သင့်ဘလောက်ကိုရှာဖွေနေဆဲ...2 စက္ကန့်စောင့်ပါ", micBlocked:"မိုက်ပိတ်ထားသည် - ခွင့်ပြုချက်စစ်ပါ" },
}

function makeLegible(text: string){ try { if(!text) return text; let t = text.trim().replace(/\s+/g,' '); if(!t) return t; const isQuestion = (s:string)=> /^(who|what|where|when|why|how|how many|do you|does|did|are you|isn'?t|is this|are we|will|can you|is it|will it|would you|should|did you)/i.test(s.trim()); let parts = t.split(/(?<=[.!?])\s+/); if(parts.length === 1){ parts = t.split(/(?=\bhow many\b|\bhow\b|\bwhat\b|\bwhere\b|\bwhen\b|\bwhy\b|\bdo you\b|\bare you\b|\bis it\b|\bwill it\b)/i) }; parts = parts.map(s=>{ s = s.trim(); if(!s) return s; s = s.charAt(0).toUpperCase() + s.slice(1); if(!/[?.!]$/.test(s)) s += isQuestion(s)? '?' : '.'; return s }); return parts.join(' ').replace(/\s+([?.!])/g,'$1').replace(/\s{2,}/g,' ') } catch { return text } }

export default function CreatePost({ onPosted }: { onPosted?: () => void }){
  const { zip } = useLocation()
  const { language } = useLanguage()
  const d = D[language] || D.en
  const [body, setBody] = useState('')
  const [category, setCategory] = useState('general')
  const [price, setPrice] = useState('')
  const [condition, setCondition] = useState('good')
  const [address, setAddress] = useState('')
  const [posting, setPosting] = useState(false)
  const [listening, setListening] = useState(false)
  const recRef = useRef<any>(null)
  const mediaRef = useRef<MediaRecorder | null>(null)
  const finalRef = useRef('')
  const killedRef = useRef(false)

  const CATEGORIES = [
    { id: 'general', label: d.general, icon: '😊', needsAddress: false },
    { id: 'faith', label: d.faith, icon: '✝', needsAddress: false },
    { id: 'safety', label: d.safety, icon: '🚨', needsAddress: true },
    { id: 'for_sale', label: d.for_sale, icon: '💰', needsAddress: true },
    { id: 'free', label: d.free, icon: '🎁', needsAddress: true },
    { id: 'lost_pet', label: d.lost_pet, icon: '🐶', needsAddress: true },
    { id: 'event', label: d.event, icon: '🎉', needsAddress: true },
    { id: 'help', label: d.help, icon: '🤝', needsAddress: false },
    { id: 'recommend', label: d.recommend, icon: '🌮', needsAddress: false },
    { id: 'job', label: d.job, icon: '💼', needsAddress: true },
  ]
  const currentCat = CATEGORIES.find(c=>c.id===category)

  const stopMic = () => {
    killedRef.current = true
    try{ if(recRef.current){ recRef.current.onresult = null; recRef.current.onend = null; recRef.current.onerror = null; recRef.current.stop() } }catch{}
    try{ if(mediaRef.current){ mediaRef.current.ondataavailable = null; mediaRef.current.onstop = null; mediaRef.current.stop() } }catch{}
    try{ const s = (mediaRef.current as any)?.stream; if(s) s.getTracks().forEach((tr:any)=>tr.stop()) }catch{}
    recRef.current = null; mediaRef.current = null; setListening(false)
  }
  useEffect(()=>{ return ()=> { try { stopMic() } catch {} } },[])

  const toggleMic = async () => {
    if(listening){ try { stopMic(); if(finalRef.current) setBody(makeLegible(finalRef.current)) } catch {}; return }
    killedRef.current = false
    const SR: any = typeof window!== 'undefined'? (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition : null
    const userLang = typeof window!== 'undefined'? navigator.language || 'en-US' : 'en-US'
    if(SR && SR.available){ try{ const status = await SR.available({ langs: [userLang], processLocally: true }); if(status === "unavailable"){ startRecordingFallback(); return } }catch{} }
    if(SR){
      try{
        const rec = new SR(); rec.continuous = true; rec.interimResults = true; rec.lang = userLang; recRef.current = rec; finalRef.current = body? body + ' ' : ''
        rec.onstart = () => { if(!killedRef.current) setListening(true) }
        rec.onend = () => { setListening(false); if(!killedRef.current && finalRef.current) setBody(makeLegible(finalRef.current)) }
        rec.onresult = (e:any)=>{ if(killedRef.current) return; let interim = ''; for(let i=e.resultIndex; i<e.results.length; i++){ const t = e.results[i][0].transcript; if(!t) continue; if(e.results[i].isFinal){ const clean = t.trim(); if(clean &&!finalRef.current.toLowerCase().endsWith(clean.toLowerCase())){ finalRef.current = (finalRef.current + ' ' + clean).trim() + ' ' } } else { interim = t.trim() } }; const display = (finalRef.current + ' ' + interim).trim(); if(display) setBody(display) }
        rec.onerror = () => { if(!killedRef.current){ try{ rec.stop() }catch{}; startRecordingFallback() } }
        rec.start(); return
      }catch{}
    }
    startRecordingFallback()
  }
  const startRecordingFallback = async () => {
    try{
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true })
      const mr = new MediaRecorder(stream); mediaRef.current = mr; const chunks: BlobPart[] = []
      mr.ondataavailable = e=> { if(!killedRef.current) chunks.push(e.data) }
      mr.onstop = async ()=>{ if(killedRef.current){ stopMic(); return }; stopMic(); const blob = new Blob(chunks, { type: 'audio/webm' }); try{ const fd = new FormData(); fd.append('audio', blob); const res = await fetch('/api/transcribe-elevenlabs', { method: 'POST', body: fd }); const data = await res.json(); if(data.text &&!killedRef.current){ const legible = makeLegible(data.text); setBody(prev=> makeLegible((prev? prev+' ':'') + legible)) } }catch{} }
      mr.start(); setListening(true); finalRef.current = body? body + ' ' : ''
    }catch{ try { alert(d.micBlocked) } catch {} }
  }

  const handlePost = async () => {
    try { stopMic() } catch {}
    if(!body.trim()) return
    setPosting(true)
    try {
      const supabase = createClient() as any
      const { data: { user } } = await supabase.auth.getUser()
      const finalBody = makeLegible(body.trim())
      const effectiveZip = zip || (typeof window!== 'undefined'? localStorage.getItem('user_zip') : '') || ''
      if (!effectiveZip || effectiveZip === 'YOUR BLOCK') { alert(d.detecting); setPosting(false); return }
      const payload: any = { body: finalBody, tag: category, category, zip_code: effectiveZip, user_id: user?.id, location_address: address || null }
      if(price) payload.price = parseFloat(price) || null
      if(category==='for_sale') payload.condition = condition
      const { error } = await supabase.from('posts').insert(payload)
      if(!error){ setBody(''); setPrice(''); setAddress(''); setCategory('general'); finalRef.current=''; try { onPosted?.() } catch {} } else { try { alert(error.message) } catch {} }
    } catch(e:any){ try { alert(e?.message || 'Post failed') } catch {} } finally { setPosting(false) }
  }

  const displayZip = zip || (typeof window!== 'undefined'? (()=>{ try { return localStorage.getItem('user_zip') } catch { return '' } })() : '') || 'YOUR BLOCK'

  return (
    <div className="w-full max-w-full min-w-0 overflow-hidden bg-black/40 backdrop-blur-xl rounded-2xl p-5 border border-white/10 text-white mb-4">
      <p className="font-bold mb-3">📝 {d.postTo.replace('{zip}', displayZip)}</p>
      <div className="flex flex-wrap gap-2 mb-4 w-full max-w-full min-w-0">{CATEGORIES.map(c => (<button key={c.id} onClick={()=>{ try { setCategory(c.id) } catch {} }} className={`px-3 py-1.5 rounded-full text-xs font-bold border transition ${category===c.id? 'bg-white text-black border-white' : 'bg-white/10 border-white/20 text-white/70'}`}>{c.icon} {c.label}</button>))}</div>
      <div className="flex gap-2 w-full max-w-full min-w-0"><textarea value={body} onChange={e=>{ try { setBody(e.target.value) } catch {} }} placeholder={d.tapMic.replace('{zip}', displayZip)} className="w-full max-w-full min-w-0 bg-white rounded-xl p-3 text-black placeholder:text-black/40 flex-1 resize-none outline-none border" /><button onClick={()=>{ try { toggleMic() } catch {} }} className={`h-12 w-12 rounded-full flex items-center justify-center border-2 border-white shrink-0 ${listening? 'bg-red-600 animate-pulse' : 'bg-black'}`}>🎤</button></div>
      {currentCat?.needsAddress && (<div className="mt-3 bg-white/10 rounded-xl p-3 border border-white/10 w-full max-w-full min-w-0 overflow-hidden"><div className="flex gap-2 w-full max-w-full min-w-0 flex-wrap"><input value={price} onChange={e=>{ try { setPrice(e.target.value) } catch {} }} placeholder={category==='free'? d.freePh : category==='for_sale'? d.pricePh : ' '} className={`bg-white rounded-xl p-2.5 text-sm text-black ${category==='event' || category==='job'? 'hidden' : 'w-24'}`} />{category==='for_sale' && <select value={condition} onChange={e=>{ try { setCondition(e.target.value) } catch {} }} className="bg-white rounded-xl p-2.5 text-sm text-black"><option value="new">{d.new}</option><option value="like_new">{d.likeNew}</option><option value="good">{d.good}</option><option value="fair">{d.fair}</option></select>}<input value={address} onChange={e=>{ try { setAddress(e.target.value) } catch {} }} placeholder={d.addressPh} className="flex-1 min-w-0 bg-white rounded-xl p-2.5 text-sm text-black" /></div></div>)}
      <div className="flex justify-between items-center mt-3 w-full max-w-full min-w-0"><p className="text-xs text-white/40">{d.postingAs.replace('{zip}', displayZip).replace('{icon}', currentCat?.icon||'').replace('{cat}', CATEGORIES.find(c=>c.id===category)?.label||category)}</p><button onClick={()=>{ try { handlePost() } catch {} }} disabled={posting ||!body.trim()} className="bg-white text-black font-bold px-5 py-2 rounded-full text-sm disabled:opacity-40">{d.postBtn.replace('{zip}', displayZip)}</button></div>
    </div>
  )
}
