'use client'
import Link from 'next/link'
import { useLanguage } from '@/lib/language-context'

const D: Record<string, any> = {
  en: { verify:"Verify", verification:"Verification", security:"Security • SSL Secured", trust:"Trust Meter • LIVE", legal:"Legal", terms:"Terms of Use", privacy:"Privacy Policy", legalDmca:"Legal • DMCA", guarantees:"Guarantees", ourGuarantees:"Our Guarantees", faith:"Faith Policy", failsafe:"Failsafe", contact:"Contact", contactUs:"Contact Us", about:"About", support:"Support • LIVE", platform:"Platform", tagline:"LOCAL TO YOUR NEIGHBORHOOD • LIVE • INDEPENDENT • FAILSAFE • SSL SECURED • 100% VERIFIED • PRIVATE WITHIN 10 MILES", copy:"© 2026 Sweet Social Space" },
  es: { verify:"Verificar", verification:"Verificación", security:"Seguridad • SSL Seguro", trust:"Medidor Confianza • VIVO", legal:"Legal", terms:"Términos de Uso", privacy:"Política Privacidad", legalDmca:"Legal • DMCA", guarantees:"Garantías", ourGuarantees:"Nuestras Garantías", faith:"Política de Fe", failsafe:"A Prueba Fallos", contact:"Contacto", contactUs:"Contáctanos", about:"Acerca", support:"Soporte • VIVO", platform:"Plataforma", tagline:"LOCAL A TU VECINDARIO • VIVO • INDEPENDIENTE • A PRUEBA FALLOS • SSL SEGURO • 100% VERIFICADO • PRIVADO EN 10 MILLAS", copy:"© 2026 Sweet Social Space" },
  fr: { verify:"Vérifier", verification:"Vérification", security:"Sécurité • SSL Sécurisé", trust:"Compteur Confiance • LIVE", legal:"Légal", terms:"Conditions d'Utilisation", privacy:"Politique Confidentialité", legalDmca:"Légal • DMCA", guarantees:"Garanties", ourGuarantees:"Nos Garanties", faith:"Politique Foi", failsafe:"À l'Épreuve", contact:"Contact", contactUs:"Nous Contacter", about:"À Propos", support:"Support • LIVE", platform:"Plateforme", tagline:"LOCAL À VOTRE QUARTIER • LIVE • INDÉPENDANT • FAILSAFE • SSL SÉCURISÉ • 100% VÉRIFIÉ • PRIVÉ DANS 10 MILES", copy:"© 2026 Sweet Social Space" },
  de: { verify:"Verifizieren", verification:"Verifizierung", security:"Sicherheit • SSL Gesichert", trust:"Vertrauensmesser • LIVE", legal:"Rechtliches", terms:"Nutzungsbedingungen", privacy:"Datenschutz", legalDmca:"Recht • DMCA", guarantees:"Garantien", ourGuarantees:"Unsere Garantien", faith:"Glaubensrichtlinie", failsafe:"Ausfallsicher", contact:"Kontakt", contactUs:"Kontaktieren Sie Uns", about:"Über", support:"Support • LIVE", platform:"Plattform", tagline:"LOKAL FÜR DEINE NACHBARSCHAFT • LIVE • UNABHÄNGIG • AUSFALLSICHER • SSL GESICHERT • 100% VERIFIZIERT • PRIVAT IN 10 MEILEN", copy:"© 2026 Sweet Social Space" },
  zh: { verify:"验证", verification:"验证", security:"安全 • SSL 安全", trust:"信任度 • 直播", legal:"法律", terms:"使用条款", privacy:"隐私政策", legalDmca:"法律 • DMCA", guarantees:"保证", ourGuarantees:"我们的保证", faith:"信仰政策", failsafe:"故障安全", contact:"联系", contactUs:"联系我们", about:"关于", support:"支持 • 直播", platform:"平台", tagline:"本地到你的社区 • 直播 • 独立 • 故障安全 • SSL 安全 • 100% 已验证 • 10英里内私密", copy:"© 2026 Sweet Social Space" },
  ja: { verify:"検証", verification:"検証", security:"セキュリティ • SSL保護", trust:"信頼メーター • ライブ", legal:"法的", terms:"利用規約", privacy:"プライバシーポリシー", legalDmca:"法的 • DMCA", guarantees:"保証", ourGuarantees:"私たちの保証", faith:"信仰ポリシー", failsafe:"フェイルセーフ", contact:"お問い合わせ", contactUs:"お問い合わせ", about:"私たちについて", support:"サポート • ライブ", platform:"プラットフォーム", tagline:"あなたの近所にローカル • ライブ • 独立 • フェイルセーフ • SSL保護 • 100%検証済み • 10マイル以内プライベート", copy:"© 2026 Sweet Social Space" },
  ko: { verify:"검증", verification:"검증", security:"보안 • SSL 보안", trust:"신뢰 미터 • 라이브", legal:"법적", terms:"이용 약관", privacy:"개인정보 보호정책", legalDmca:"법적 • DMCA", guarantees:"보증", ourGuarantees:"우리의 보증", faith:"신앙 정책", failsafe:"페일세이프", contact:"연락처", contactUs:"문의하기", about:"소개", support:"지원 • 라이브", platform:"플랫폼", tagline:"동네에 로컬 • 라이브 • 독립 • 페일세이프 • SSL 보안 • 100% 검증 • 10마일 내 비공개", copy:"© 2026 Sweet Social Space" },
  pt: { verify:"Verificar", verification:"Verificação", security:"Segurança • SSL Seguro", trust:"Medidor Confiança • AO VIVO", legal:"Legal", terms:"Termos de Uso", privacy:"Política Privacidade", legalDmca:"Legal • DMCA", guarantees:"Garantias", ourGuarantees:"Nossas Garantias", faith:"Política de Fé", failsafe:"À Prova Falhas", contact:"Contato", contactUs:"Fale Conosco", about:"Sobre", support:"Suporte • AO VIVO", platform:"Plataforma", tagline:"LOCAL DO SEU BAIRRO • AO VIVO • INDEPENDENTE • À PROVA FALHAS • SSL SEGURO • 100% VERIFICADO • PRIVADO EM 10 MILHAS", copy:"© 2026 Sweet Social Space" },
  ru: { verify:"Проверка", verification:"Верификация", security:"Безопасность • SSL Защищено", trust:"Измеритель Доверия • LIVE", legal:"Юридич.", terms:"Условия Использования", privacy:"Политика Конфиденциальности", legalDmca:"Юридич. • DMCA", guarantees:"Гарантии", ourGuarantees:"Наши Гарантии", faith:"Политика Веры", failsafe:"Отказоустойчивость", contact:"Контакт", contactUs:"Связаться", about:"О Нас", support:"Поддержка • LIVE", platform:"Платформа", tagline:"ЛОКАЛЬНО ДЛЯ ВАШЕГО РАЙОНА • LIVE • НЕЗАВИСИМО • ОТКАЗОУСТОЙЧИВО • SSL ЗАЩИЩЕНО • 100% ПРОВЕРЕНО • ПРИВАТНО В 10 МИЛЯХ", copy:"© 2026 Sweet Social Space" },
  ar: { verify:"تحقق", verification:"التحقق", security:"الأمان • SSL مؤمن", trust:"مقياس الثقة • مباشر", legal:"قانوني", terms:"شروط الاستخدام", privacy:"سياسة الخصوصية", legalDmca:"قانوني • DMCA", guarantees:"ضمانات", ourGuarantees:"ضماناتنا", faith:"سياسة الإيمان", failsafe:"آمن من الفشل", contact:"اتصال", contactUs:"اتصل بنا", about:"حول", support:"دعم • مباشر", platform:"منصة", tagline:"محلي لحيك • مباشر • مستقل • آمن من الفشل • SSL مؤمن • 100% موثق • خاص ضمن 10 أميال", copy:"© 2026 Sweet Social Space" },
  hi: { verify:"सत्यापन", verification:"सत्यापन", security:"सुरक्षा • SSL सुरक्षित", trust:"विश्वास मीटर • लाइव", legal:"कानूनी", terms:"उपयोग शर्तें", privacy:"गोपनीयता नीति", legalDmca:"कानूनी • DMCA", guarantees:"गारंटी", ourGuarantees:"हमारी गारंटी", faith:"आस्था नीति", failsafe:"फेलसेफ", contact:"संपर्क", contactUs:"हमसे संपर्क", about:"हमारे बारे में", support:"सहायता • लाइव", platform:"प्लेटफ़ॉर्म", tagline:"आपके पड़ोस के लिए स्थानीय • लाइव • स्वतंत्र • फेलसेफ • SSL सुरक्षित • 100% सत्यापित • 10 मील में निजी", copy:"© 2026 Sweet Social Space" },
  it: { verify:"Verifica", verification:"Verifica", security:"Sicurezza • SSL Sicuro", trust:"Misuratore Fiducia • LIVE", legal:"Legale", terms:"Termini d'Uso", privacy:"Privacy Policy", legalDmca:"Legale • DMCA", guarantees:"Garanzie", ourGuarantees:"Le Nostre Garanzie", faith:"Politica Fede", failsafe:"Failsafe", contact:"Contatto", contactUs:"Contattaci", about:"Chi Siamo", support:"Supporto • LIVE", platform:"Piattaforma", tagline:"LOCALE AL TUO QUARTIERE • LIVE • INDIPENDENTE • FAILSAFE • SSL SICURO • 100% VERIFICATO • PRIVATO ENTRO 10 MIGLIA", copy:"© 2026 Sweet Social Space" },
  nl: { verify:"Verifiëren", verification:"Verificatie", security:"Beveiliging • SSL Beveiligd", trust:"Vertrouwensmeter • LIVE", legal:"Juridisch", terms:"Gebruiksvoorwaarden", privacy:"Privacybeleid", legalDmca:"Juridisch • DMCA", guarantees:"Garanties", ourGuarantees:"Onze Garanties", faith:"Geloofsbeleid", failsafe:"Failsafe", contact:"Contact", contactUs:"Contact Ons", about:"Over", support:"Support • LIVE", platform:"Platform", tagline:"LOKAAL VOOR JE BUURT • LIVE • ONAFHANKELIJK • FAILSAFE • SSL BEVEILIGD • 100% GEVERIFIEERD • PRIVÉ BINNEN 10 MIJL", copy:"© 2026 Sweet Social Space" },
  tl: { verify:"I-verify", verification:"Verification", security:"Security • SSL Secured", trust:"Trust Meter • LIVE", legal:"Legal", terms:"Terms of Use", privacy:"Privacy Policy", legalDmca:"Legal • DMCA", guarantees:"Garantiya", ourGuarantees:"Aming Garantiya", faith:"Faith Policy", failsafe:"Failsafe", contact:"Contact", contactUs:"Contact Us", about:"About", support:"Support • LIVE", platform:"Platform", tagline:"LOCAL SA IYONG KAPITBAHAYAN • LIVE • INDEPENDENT • FAILSAFE • SSL SECURED • 100% VERIFIED • PRIVATE WITHIN 10 MILES", copy:"© 2026 Sweet Social Space" },
  bn: { verify:"যাচাই", verification:"যাচাইকরণ", security:"নিরাপত্তা • SSL সুরক্ষিত", trust:"বিশ্বাস মিটার • লাইভ", legal:"আইনি", terms:"ব্যবহারের শর্তাবলী", privacy:"গোপনীয়তা নীতি", legalDmca:"আইনি • DMCA", guarantees:"গ্যারান্টি", ourGuarantees:"আমাদের গ্যারান্টি", faith:"বিশ্বাস নীতি", failsafe:"ফেইলসেফ", contact:"যোগাযোগ", contactUs:"আমাদের সাথে যোগাযোগ", about:"সম্পর্কে", support:"সহায়তা • লাইভ", platform:"প্ল্যাটফর্ম", tagline:"আপনার পাড়ার জন্য স্থানীয় • লাইভ • স্বাধীন • ফেইলসেফ • SSL সুরক্ষিত • 100% যাচাইকৃত • 10 মাইলের মধ্যে ব্যক্তিগত", copy:"© 2026 Sweet Social Space" },
  id: { verify:"Verifikasi", verification:"Verifikasi", security:"Keamanan • SSL Aman", trust:"Meter Kepercayaan • LIVE", legal:"Hukum", terms:"Syarat Penggunaan", privacy:"Kebijakan Privasi", legalDmca:"Hukum • DMCA", guarantees:"Jaminan", ourGuarantees:"Jaminan Kami", faith:"Kebijakan Iman", failsafe:"Failsafe", contact:"Kontak", contactUs:"Hubungi Kami", about:"Tentang", support:"Dukungan • LIVE", platform:"Platform", tagline:"LOKAL UNTUK LINGKUNGAN ANDA • LIVE • INDEPENDEN • FAILSAFE • SSL AMAN • 100% TERVERIFIKASI • PRIVAT DALAM 10 MIL", copy:"© 2026 Sweet Social Space" },
  vi: { verify:"Xác Minh", verification:"Xác Minh", security:"Bảo Mật • SSL An Toàn", trust:"Thước Đo Tin Cậy • TRỰC TIẾP", legal:"Pháp Lý", terms:"Điều Khoản Sử Dụng", privacy:"Chính Sách Bảo Mật", legalDmca:"Pháp Lý • DMCA", guarantees:"Bảo Đảm", ourGuarantees:"Bảo Đảm Của Chúng Tôi", faith:"Chính Sách Đức Tin", failsafe:"An Toàn Thất Bại", contact:"Liên Hệ", contactUs:"Liên Hệ Chúng Tôi", about:"Giới Thiệu", support:"Hỗ Trợ • TRỰC TIẾP", platform:"Nền Tảng", tagline:"ĐỊA PHƯƠNG CHO KHU PHỐ CỦA BẠN • TRỰC TIẾP • ĐỘC LẬP • AN TOÀN • SSL BẢO MẬT • 100% ĐÃ XÁC MINH • RIÊNG TƯ TRONG 10 DẶM", copy:"© 2026 Sweet Social Space" },
  th: { verify:"ยืนยัน", verification:"การยืนยัน", security:"ความปลอดภัย • SSL ปลอดภัย", trust:"มิเตอร์ความเชื่อถือ • สด", legal:"กฎหมาย", terms:"ข้อกำหนดการใช้งาน", privacy:"นโยบายความเป็นส่วนตัว", legalDmca:"กฎหมาย • DMCA", guarantees:"การรับประกัน", ourGuarantees:"การรับประกันของเรา", faith:"นโยบายความเชื่อ", failsafe:"ปลอดภัยล้มเหลว", contact:"ติดต่อ", contactUs:"ติดต่อเรา", about:"เกี่ยวกับ", support:"สนับสนุน • สด", platform:"แพลตฟอร์ม", tagline:"ท้องถิ่นสำหรับละแวกของคุณ • สด • อิสระ • ปลอดภัยล้มเหลว • SSL ปลอดภัย • 100% ยืนยันแล้ว • ส่วนตัวภายใน 10 ไมล์", copy:"© 2026 Sweet Social Space" },
  sv: { verify:"Verifiera", verification:"Verifiering", security:"Säkerhet • SSL Säkrad", trust:"Förtroendemätare • LIVE", legal:"Juridik", terms:"Användarvillkor", privacy:"Integritetspolicy", legalDmca:"Juridik • DMCA", guarantees:"Garantier", ourGuarantees:"Våra Garantier", faith:"Tros Policy", failsafe:"Felsäker", contact:"Kontakt", contactUs:"Kontakta Oss", about:"Om", support:"Support • LIVE", platform:"Plattform", tagline:"LOKAL FÖR DITT GRANNAR • LIVE • OBEROENDE • FELSAKER • SSL SÄKRAD • 100% VERIFIERAD • PRIVAT INOM 10 MILES", copy:"© 2026 Sweet Social Space" },
  pl: { verify:"Weryfikuj", verification:"Weryfikacja", security:"Bezpieczeństwo • SSL Zabezpieczone", trust:"Miernik Zaufania • LIVE", legal:"Prawne", terms:"Warunki Użytkowania", privacy:"Polityka Prywatności", legalDmca:"Prawne • DMCA", guarantees:"Gwarancje", ourGuarantees:"Nasze Gwarancje", faith:"Polityka Wiary", failsafe:"Niezawodny", contact:"Kontakt", contactUs:"Skontaktuj się", about:"O Nas", support:"Wsparcie • LIVE", platform:"Platforma", tagline:"LOKALNIE DLA TWOJEJ OKOLICY • LIVE • NIEZALEŻNY • NIEZAWODNY • SSL ZABEZPIECZONY • 100% ZWERYFIKOWANY • PRYWATNY W 10 MILACH", copy:"© 2026 Sweet Social Space" },
  tr: { verify:"Doğrula", verification:"Doğrulama", security:"Güvenlik • SSL Güvenli", trust:"Güven Ölçer • CANLI", legal:"Yasal", terms:"Kullanım Şartları", privacy:"Gizlilik Politikası", legalDmca:"Yasal • DMCA", guarantees:"Garantiler", ourGuarantees:"Garantilerimiz", faith:"İnanç Politikası", failsafe:"Güvenli Arıza", contact:"İletişim", contactUs:"Bize Ulaşın", about:"Hakkında", support:"Destek • CANLI", platform:"Platform", tagline:"MAHALLENİZ İÇİN YEREL • CANLI • BAĞIMSIZ • GÜVENLİ • SSL GÜVENLİ • %100 DOĞRULANMIŞ • 10 MİL İÇİNDE ÖZEL", copy:"© 2026 Sweet Social Space" },
  uk: { verify:"Перевірка", verification:"Верифікація", security:"Безпека • SSL Захищено", trust:"Вимірювач Довіри • LIVE", legal:"Юридичне", terms:"Умови Використання", privacy:"Політика Конфіденційності", legalDmca:"Юридичне • DMCA", guarantees:"Гарантії", ourGuarantees:"Наші Гарантії", faith:"Політика Віри", failsafe:"Відмовостійкий", contact:"Контакт", contactUs:"Зв'язатися", about:"Про Нас", support:"Підтримка • LIVE", platform:"Платформа", tagline:"ЛОКАЛЬНО ДЛЯ ВАШОГО РАЙОНУ • LIVE • НЕЗАЛЕЖНИЙ • ВІДМОВОСТІЙКИЙ • SSL ЗАХИЩЕНО • 100% ПЕРЕВІРЕНО • ПРИВАТНО В МЕЖАХ 10 МИЛЬ", copy:"© 2026 Sweet Social Space" },
  el: { verify:"Επαλήθευση", verification:"Επαλήθευση", security:"Ασφάλεια • SSL Ασφαλές", trust:"Μετρητής Εμπιστοσύνης • ΖΩΝΤΑΝΑ", legal:"Νομικά", terms:"Όροι Χρήσης", privacy:"Πολιτική Απορρήτου", legalDmca:"Νομικά • DMCA", guarantees:"Εγγυήσεις", ourGuarantees:"Οι Εγγυήσεις Μας", faith:"Πολιτική Πίστης", failsafe:"Ασφαλές", contact:"Επικοινωνία", contactUs:"Επικοινωνήστε Μαζί Μας", about:"Σχετικά", support:"Υποστήριξη • ΖΩΝΤΑΝΑ", platform:"Πλατφόρμα", tagline:"ΤΟΠΙΚΟ ΓΙΑ ΤΗ ΓΕΙΤΟΝΙΑ ΣΑΣ • ΖΩΝΤΑΝΑ • ΑΝΕΞΑΡΤΗΤΟ • ΑΣΦΑΛΕΣ • SSL ΑΣΦΑΛΕΣ • 100% ΕΠΑΛΗΘΕΥΜΕΝΟ • ΙΔΙΩΤΙΚΟ ΕΝΤΟΣ 10 ΜΙΛΙΩΝ", copy:"© 2026 Sweet Social Space" },
  he: { verify:"אמת", verification:"אימות", security:"אבטחה • SSL מאובטח", trust:"מד אמון • חי", legal:"משפטי", terms:"תנאי שימוש", privacy:"מדיניות פרטיות", legalDmca:"משפטי • DMCA", guarantees:"ערבויות", ourGuarantees:"הערבויות שלנו", faith:"מדיניות אמונה", failsafe:"חסין תקלות", contact:"צור קשר", contactUs:"צור קשר", about:"אודות", support:"תמיכה • חי", platform:"פלטפורמה", tagline:"מקומי לשכונה שלך • חי • עצמאי • חסין תקלות • SSL מאובטח • 100% מאומת • פרטי בתוך 10 מייל", copy:"© 2026 Sweet Social Space" },
  ur: { verify:"تصدیق", verification:"تصدیق", security:"سیکیورٹی • SSL محفوظ", trust:"اعتماد میٹر • لائیو", legal:"قانونی", terms:"استعمال کی شرائط", privacy:"پرائیویسی پالیسی", legalDmca:"قانونی • DMCA", guarantees:"ضمانتیں", ourGuarantees:"ہماری ضمانتیں", faith:"ایمان پالیسی", failsafe:"فیل سیف", contact:"رابطہ", contactUs:"ہم سے رابطہ کریں", about:"ہمارے بارے میں", support:"سپورٹ • لائیو", platform:"پلیٹ فارم", tagline:"آپ کے محلے کے لیے مقامی • لائیو • آزاد • فیل سیف • SSL محفوظ • 100% تصدیق شدہ • 10 میل کے اندر نجی", copy:"© 2026 Sweet Social Space" },
  fa: { verify:"تأیید", verification:"تأیید", security:"امنیت • SSL امن", trust:"سنجش اعتماد • زنده", legal:"قانونی", terms:"شرایط استفاده", privacy:"سیاست حریم خصوصی", legalDmca:"قانونی • DMCA", guarantees:"ضمانت ها", ourGuarantees:"ضمانت های ما", faith:"سیاست ایمان", failsafe:"ایمن از خرابی", contact:"تماس", contactUs:"تماس با ما", about:"درباره", support:"پشتیبانی • زنده", platform:"پلتفرم", tagline:"محلی برای محله شما • زنده • مستقل • ایمن از خرابی • SSL امن • 100% تأیید شده • خصوصی در 10 مایل", copy:"© 2026 Sweet Social Space" },
  ms: { verify:"Sahkan", verification:"Pengesahan", security:"Keselamatan • SSL Selamat", trust:"Meter Kepercayaan • LANGSUNG", legal:"Undang-undang", terms:"Syarat Penggunaan", privacy:"Dasar Privasi", legalDmca:"Undang-undang • DMCA", guarantees:"Jaminan", ourGuarantees:"Jaminan Kami", faith:"Dasar Kepercayaan", failsafe:"Selamat Gagal", contact:"Hubungi", contactUs:"Hubungi Kami", about:"Tentang", support:"Sokongan • LANGSUNG", platform:"Platform", tagline:"TEMPATAN UNTUK KEJIRANAN ANDA • LANGSUNG • BEBAS • SELAMAT GAGAL • SSL SELAMAT • 100% DISAHKAN • PERIBADI DALAM 10 BATU", copy:"© 2026 Sweet Social Space" },
  ro: { verify:"Verifică", verification:"Verificare", security:"Securitate • SSL Securizat", trust:"Contor Încredere • LIVE", legal:"Legal", terms:"Termeni de Utilizare", privacy:"Politica Confidențialitate", legalDmca:"Legal • DMCA", guarantees:"Garanții", ourGuarantees:"Garanțiile Noastre", faith:"Politica Credință", failsafe:"Failsafe", contact:"Contact", contactUs:"Contactează-ne", about:"Despre", support:"Suport • LIVE", platform:"Platformă", tagline:"LOCAL PENTRU CARTIERUL TĂU • LIVE • INDEPENDENT • FAILSAFE • SSL SECURIZAT • 100% VERIFICAT • PRIVAT PE 10 MILE", copy:"© 2026 Sweet Social Space" },
  cs: { verify:"Ověřit", verification:"Ověření", security:"Zabezpečení • SSL Zabezpečeno", trust:"Měřič Důvěry • ŽIVĚ", legal:"Právní", terms:"Podmínky Používání", privacy:"Zásady Ochrany Osobních Údajů", legalDmca:"Právní • DMCA", guarantees:"Záruky", ourGuarantees:"Naše Záruky", faith:"Zásady Víry", failsafe:"Odolný proti selhání", contact:"Kontakt", contactUs:"Kontaktujte Nás", about:"O Nás", support:"Podpora • ŽIVĚ", platform:"Platforma", tagline:"LOKÁLNĚ PRO VAŠE SOUSEDSTVÍ • ŽIVĚ • NEZÁVISLÝ • ODOLNÝ • SSL ZABEZPEČENO • 100% OVĚŘENO • SOUKROMÉ DO 10 MIL", copy:"© 2026 Sweet Social Space" },
  hu: { verify:"Ellenőrzés", verification:"Ellenőrzés", security:"Biztonság • SSL Biztonságos", trust:"Bizalommérő • ÉLŐ", legal:"Jogi", terms:"Használati Feltételek", privacy:"Adatvédelmi Irányelvek", legalDmca:"Jogi • DMCA", guarantees:"Garanciák", ourGuarantees:"Garanciáink", faith:"Hit Irányelv", failsafe:"Hibatűrő", contact:"Kapcsolat", contactUs:"Kapcsolatfelvétel", about:"Rólunk", support:"Támogatás • ÉLŐ", platform:"Platform", tagline:"HELYI A KÖRNYÉKEDNEK • ÉLŐ • FÜGGETLEN • HIBATŰRŐ • SSL BIZTONSÁGOS • 100% ELLENŐRZÖTT • PRIVÁT 10 MÉRFÖLDÖN BELÜL", copy:"© 2026 Sweet Social Space" },
  fi: { verify:"Vahvista", verification:"Vahvistus", security:"Turvallisuus • SSL Suojattu", trust:"Luottamusmittari • LIVE", legal:"Lakiasiat", terms:"Käyttöehdot", privacy:"Tietosuojakäytäntö", legalDmca:"Lakiasiat • DMCA", guarantees:"Takuut", ourGuarantees:"Takuumme", faith:"Uskon Käytäntö", failsafe:"Vikasietoinen", contact:"Yhteystiedot", contactUs:"Ota Yhteyttä", about:"Tietoa", support:"Tuki • LIVE", platform:"Alusta", tagline:"PAIKALLINEN NAAPURUSTOLLESI • LIVE • RIIPPUMATON • VIKASIETOINEN • SSL SUOJATTU • 100% VAHVISTETTU • YKSITYINEN 10 MAILIN SISÄLLÄ", copy:"© 2026 Sweet Social Space" },
  no: { verify:"Verifiser", verification:"Verifisering", security:"Sikkerhet • SSL Sikret", trust:"Tillitsmåler • LIVE", legal:"Juridisk", terms:"Vilkår for Bruk", privacy:"Personvern", legalDmca:"Juridisk • DMCA", guarantees:"Garantier", ourGuarantees:"Våre Garantier", faith:"Tros Policy", failsafe:"Failsafe", contact:"Kontakt", contactUs:"Kontakt Oss", about:"Om", support:"Support • LIVE", platform:"Plattform", tagline:"LOKALT FOR NABOLAGET DITT • LIVE • UAVHENGIG • FAILSAFE • SSL SIKRET • 100% VERIFISERT • PRIVAT INNEN 10 MILES", copy:"© 2026 Sweet Social Space" },
  da: { verify:"Bekræft", verification:"Bekræftelse", security:"Sikkerhed • SSL Sikret", trust:"Tillidsmåler • LIVE", legal:"Juridisk", terms:"Brugsbetingelser", privacy:"Privatlivspolitik", legalDmca:"Juridisk • DMCA", guarantees:"Garantier", ourGuarantees:"Vores Garantier", faith:"Tros Politik", failsafe:"Failsafe", contact:"Kontakt", contactUs:"Kontakt Os", about:"Om", support:"Support • LIVE", platform:"Platform", tagline:"LOKALT FOR DIT KVARTER • LIVE • UAFHÆNGIG • FAILSAFE • SSL SIKRET • 100% BEKRÆFTET • PRIVAT INDEN FOR 10 MILES", copy:"© 2026 Sweet Social Space" },
  bg: { verify:"Проверка", verification:"Верификация", security:"Сигурност • SSL Защитено", trust:"Измерител на Доверие • НА ЖИВО", legal:"Правни", terms:"Условия за Ползване", privacy:"Политика за Поверителност", legalDmca:"Правни • DMCA", guarantees:"Гаранции", ourGuarantees:"Нашите Гаранции", faith:"Политика за Вяра", failsafe:"Устойчив", contact:"Контакт", contactUs:"Свържете се с Нас", about:"За Нас", support:"Поддръжка • НА ЖИВО", platform:"Платформа", tagline:"ЛОКАЛНО ЗА ВАШИЯ КВАРТАЛ • НА ЖИВО • НЕЗАВИСИМ • УСТОЙЧИВ • SSL ЗАЩИТЕНО • 100% ВЕРИФИЦИРАН • ЧАСТНО В РАМКИТЕ НА 10 МИЛИ", copy:"© 2026 Sweet Social Space" },
  hr: { verify:"Provjeri", verification:"Verifikacija", security:"Sigurnost • SSL Osigurano", trust:"Mjerač Povjerenja • UŽIVO", legal:"Pravno", terms:"Uvjeti Korištenja", privacy:"Politika Privatnosti", legalDmca:"Pravno • DMCA", guarantees:"Jamstva", ourGuarantees:"Naša Jamstva", faith:"Politika Vjere", failsafe:"Otporan na Kvar", contact:"Kontakt", contactUs:"Kontaktirajte Nas", about:"O Nama", support:"Podrška • UŽIVO", platform:"Platforma", tagline:"LOKALNO ZA VAŠE SUSJEDSTVO • UŽIVO • NEOVISNO • OTPORNO NA KVAR • SSL OSIGURANO • 100% VERIFICIRANO • PRIVATNO UNUTAR 10 MILJA", copy:"© 2026 Sweet Social Space" },
  sr: { verify:"Провери", verification:"Верификација", security:"Безбедност • SSL Обезбеђено", trust:"Мерач Поверења • УЖИВО", legal:"Правно", terms:"Услови Коришћења", privacy:"Политика Приватности", legalDmca:"Правно • DMCA", guarantees:"Гаранције", ourGuarantees:"Наше Гаранције", faith:"Политика Вере", failsafe:"Отпоран на Квар", contact:"Контакт", contactUs:"Контактирајте Нас", about:"О Нама", support:"Подршка • УЖИВО", platform:"Платформа", tagline:"ЛОКАЛНО ЗА ВАШЕ КОМШИЛСТВО • УЖИВО • НЕЗАВИСНО • ОТПОРНО НА КВАР • SSL ОБЕЗБЕЂЕНО • 100% ВЕРИФИКОВАНО • ПРИВАТНО УНУТАР 10 МИЉА", copy:"© 2026 Sweet Social Space" },
  sk: { verify:"Overiť", verification:"Overenie", security:"Zabezpečenie • SSL Zabezpečené", trust:"Merač Dôvery • NAŽIVO", legal:"Právne", terms:"Podmienky Používania", privacy:"Zásady Ochrany Osobných Údajov", legalDmca:"Právne • DMCA", guarantees:"Záruky", ourGuarantees:"Naše Záruky", faith:"Politika Viery", failsafe:"Odolný voči zlyhaniu", contact:"Kontakt", contactUs:"Kontaktujte Nás", about:"O Nás", support:"Podpora • NAŽIVO", platform:"Platforma", tagline:"LOKÁLNE PRE VAŠE SUSEDSTVO • NAŽIVO • NEZÁVISLÉ • ODOLNÉ • SSL ZABEZPEČENÉ • 100% OVERENÉ • SÚKROMNÉ DO 10 MÍĽ", copy:"© 2026 Sweet Social Space" },
  sl: { verify:"Preveri", verification:"Preverjanje", security:"Varnost • SSL Zaščiteno", trust:"Merilnik Zaupanja • V ŽIVO", legal:"Pravno", terms:"Pogoji Uporabe", privacy:"Politika Zasebnosti", legalDmca:"Pravno • DMCA", guarantees:"Jamstva", ourGuarantees:"Naša Jamstva", faith:"Politika Vere", failsafe:"Varno", contact:"Kontakt", contactUs:"Kontaktirajte Nas", about:"O Nas", support:"Podpora • V ŽIVO", platform:"Platforma", tagline:"LOKALNO ZA VAŠO SOSESKO • V ŽIVO • NEODVISNO • VARNO • SSL ZAŠČITENO • 100% PREVERJENO • ZASEBNO V 10 MILJAH", copy:"© 2026 Sweet Social Space" },
  et: { verify:"Kinnita", verification:"Kinnitamine", security:"Turvalisus • SSL Turvatud", trust:"Usaldusmõõtur • OTSE", legal:"Juriidiline", terms:"Kasutustingimused", privacy:"Privaatsuspoliitika", legalDmca:"Juriidiline • DMCA", guarantees:"Garantiid", ourGuarantees:"Meie Garantiid", faith:"Usu Poliitika", failsafe:"Tõrkekindel", contact:"Kontakt", contactUs:"Võtke Meiega Ühendust", about:"Meist", support:"Tugi • OTSE", platform:"Platvorm", tagline:"KOHALIK TEIE NAABRUSKONNALE • OTSE • SÕLTUMATU • TÕRKEKINDEL • SSL TURVATUD • 100% KINNITATUD • PRIVAATNE 10 MIILI RAADIOSES", copy:"© 2026 Sweet Social Space" },
  lv: { verify:"Verificēt", verification:"Verifikācija", security:"Drošība • SSL Aizsargāts", trust:"Uzticības Mērītājs • TIEŠRAIDE", legal:"Juridiskais", terms:"Lietošanas Noteikumi", privacy:"Privātuma Politika", legalDmca:"Juridiskais • DMCA", guarantees:"Garantijas", ourGuarantees:"Mūsu Garantijas", faith:"Ticības Politika", failsafe:"Drošs pret kļūmēm", contact:"Kontakti", contactUs:"Sazinieties ar Mums", about:"Par Mums", support:"Atbalsts • TIEŠRAIDE", platform:"Platforma", tagline:"VIETĒJS JŪSU APKĀRTNEI • TIEŠRAIDE • NEATKARĪGS • DROŠS • SSL AIZSARGĀTS • 100% VERIFICĒTS • PRIVĀTS 10 JŪDŽU RĀDIUSĀ", copy:"© 2026 Sweet Social Space" },
  lt: { verify:"Patikrinti", verification:"Patvirtinimas", security:"Saugumas • SSL Apsaugotas", trust:"Pasitikėjimo Matuoklis • GYVAI", legal:"Teisinis", terms:"Naudojimo Sąlygos", privacy:"Privatumo Politika", legalDmca:"Teisinis • DMCA", guarantees:"Garantijos", ourGuarantees:"Mūsų Garantijos", faith:"Tikėjimo Politika", failsafe:"Atsparus Gedimams", contact:"Kontaktas", contactUs:"Susisiekite", about:"Apie Mus", support:"Pagalba • GYVAI", platform:"Platforma", tagline:"VIETINIS JŪSŲ KAIMYNYSTĖJE • GYVAI • NEPRIKLAUSOMAS • ATSPARUS • SSL APSAUGOTAS • 100% PATVIRTINTAS • PRIVATUS 10 MYLIŲ SPINDULIU", copy:"© 2026 Sweet Social Space" },
  be: { verify:"Праверыць", verification:"Верыфікацыя", security:"Бяспека • SSL Абаронены", trust:"Вымяральнік Даверу • ЖЫВА", legal:"Юрыдычнае", terms:"Умовы Выкарыстання", privacy:"Палітыка Прыватнасці", legalDmca:"Юрыдычнае • DMCA", guarantees:"Гарантыі", ourGuarantees:"Нашы Гарантыі", faith:"Палітыка Веры", failsafe:"Адмоваўстойлівы", contact:"Кантакт", contactUs:"Звязацца з Нами", about:"Пра Нас", support:"Падтрымка • ЖЫВА", platform:"Платформа", tagline:"ЛАКАЛЬНА ДЛЯ ВАШАГА РАЁНА • ЖЫВА • НЕЗАЛЕЖНАЯ • АДМОВАЎСТОЙЛІВАЯ • SSL АБАРОНЕНА • 100% ПРАВЕРАНА • ПРЫВАТНА Ў МЕЖАХ 10 МІЛЬ", copy:"© 2026 Sweet Social Space" },
  ka: { verify:"გადამოწმება", verification:"ვერიფიკაცია", security:"უსაფრთხოება • SSL დაცული", trust:"ნდობის მრიცხველი • LIVE", legal:"იურიდიული", terms:"გამოყენების პირობები", privacy:"კონფიდენციალურობის პოლიტიკა", legalDmca:"იურიდიული • DMCA", guarantees:"გარანტიები", ourGuarantees:"ჩვენი გარანტიები", faith:"რწმენის პოლიტიკა", failsafe:"შეცდომაგამძლე", contact:"კონტაქტი", contactUs:"დაგვიკავშირდით", about:"ჩვენ შესახებ", support:"მხარდაჭერა • LIVE", platform:"პლატფორმა", tagline:"ლოკალური თქვენი სამეზობლოსთვის • LIVE • დამოუკიდებელი • შეცდომაგამძლე • SSL დაცული • 100% დადასტურებული • პირადი 10 მილის ფარგლებში", copy:"© 2026 Sweet Social Space" },
  hy: { verify:"Ստուգել", verification:"Վերիֆիկացում", security:"Անվտանգություն • SSL Պաշտպանված", trust:"Վստահության Չափիչ • ՈՒՂԻՂ", legal:"Իրավական", terms:"Օգտագործման Պայմաններ", privacy:"Գաղտնիության Քաղաքականություն", legalDmca:"Իրավական • DMCA", guarantees:"Երաշխիքներ", ourGuarantees:"Մեր Երաշխիքները", faith:"Հավատքի Քաղաքականություն", failsafe:"Խափանակայուն", contact:"Կապ", contactUs:"Կապ մեզ հետ", about:"Մեր մասին", support:"Աջակցություն • ՈՒՂԻՂ", platform:"Հարթակ", tagline:"ՏԵՂԱԿԱՆ ՁԵՐ ԹԱՂԱՄԱՍԻ ՀԱՄԱՐ • ՈՒՂԻՂ • ԱՆԿԱԽ • ԽԱՓԱՆԱԿԱՅՈՒՆ • SSL ՊԱՇՏՊԱՆՎԱԾ • 100% ՍՏՈՒԳՎԱԾ • ՄԱՍՆԱՎՈՐ 10 ՄՂՈՆՈՎ", copy:"© 2026 Sweet Social Space" },
  az: { verify:"Doğrula", verification:"Doğrulama", security:"Təhlükəsizlik • SSL Təhlükəsiz", trust:"Etibar Ölçer • CANLI", legal:"Hüquqi", terms:"İstifadə Şərtləri", privacy:"Məxfilik Siyasəti", legalDmca:"Hüquqi • DMCA", guarantees:"Zəmanətlər", ourGuarantees:"Zəmanətlərimiz", faith:"İnam Siyasəti", failsafe:"Xətadan Qorunan", contact:"Əlaqə", contactUs:"Bizimlə Əlaqə", about:"Haqqımızda", support:"Dəstək • CANLI", platform:"Platforma", tagline:"MƏHƏLLƏNİZ ÜÇÜN YERLİ • CANLI • MÜSTƏQİL • XƏTADAN QORUNAN • SSL TƏHLÜKƏSİZ • 100% DOĞRULANMIŞ • 10 MİL DAXİLİNDƏ ŞƏXSİ", copy:"© 2026 Sweet Social Space" },
  kk: { verify:"Тексеру", verification:"Тексеру", security:"Қауіпсіздік • SSL Қорғалған", trust:"Сенім Өлшегіш • ТІКЕЛЕЙ", legal:"Заңды", terms:"Пайдалану Шарттары", privacy:"Құпиялылық Саясаты", legalDmca:"Заңды • DMCA", guarantees:"Кепілдіктер", ourGuarantees:"Біздің Кепілдіктер", faith:"Сенім Саясаты", failsafe:"Ақауға Төзімді", contact:"Байланыс", contactUs:"Бізбен Байланысыңыз", about:"Біз Туралы", support:"Қолдау • ТІКЕЛЕЙ", platform:"Платформа", tagline:"КӨРШІЛЕСТІГІҢІЗ ҮШІН ЖЕРГІЛІКТІ • ТІКЕЛЕЙ • ТӘУЕЛСІЗ • АҚАУҒА ТӨЗІМДІ • SSL ҚОРҒАЛҒАН • 100% ТЕКСЕРІЛГЕН • 10 МИЛЬ ІШІНДЕ ЖЕКЕ", copy:"© 2026 Sweet Social Space" },
  ky: { verify:"Текшерүү", verification:"Текшерүү", security:"Коопсуздук • SSL Корголгон", trust:"Ишеним Өлчөгүч • ТҮЗ", legal:"Юридикалык", terms:"Колдонуу Шарттары", privacy:"Купуялык Саясаты", legalDmca:"Юридикалык • DMCA", guarantees:"Кепилдиктер", ourGuarantees:"Биздин Кепилдиктер", faith:"Ишеним Саясаты", failsafe:"Катага Чыдамдуу", contact:"Байланыш", contactUs:"Биз менен Байланышыңыз", about:"Биз Жөнүндө", support:"Колдоо • ТҮЗ", platform:"Платформа", tagline:"КООМЧУЛУГУҢУЗ ҮЧҮН ЖЕРГИЛИКТҮҮ • ТҮЗ • КӨЗ КАРАНДЫСЫЗ • КАТАГА ЧЫДАМДУУ • SSL КОРГОЛГОН • 100% ТЕКШЕРИЛГЕН • 10 МИЛЬ ИЧИНДЕ ЖЕКЕ", copy:"© 2026 Sweet Social Space" },
  uz: { verify:"Tasdiqlash", verification:"Tasdiqlash", security:"Xavfsizlik • SSL Xavfsiz", trust:"Ishonch O'lchagich • JONLI", legal:"Huquqiy", terms:"Foydalanish Shartlari", privacy:"Maxfiylik Siyosati", legalDmca:"Huquqiy • DMCA", guarantees:"Kafolatlar", ourGuarantees:"Kafolatlarimiz", faith:"E'tiqod Siyosati", failsafe:"Xatoga Chidamli", contact:"Aloqa", contactUs:"Biz Bilan Bog'laning", about:"Biz Haqimizda", support:"Qo'llab-quvvatlash • JONLI", platform:"Platforma", tagline:"MAHALLANGIZ UCHUN MAHALLIY • JONLI • MUSTAQIL • XATOGA CHIDAMLI • SSL XAVFSIZ • 100% TASDIQLANGAN • 10 MIL ICHIDA XUSUSIY", copy:"© 2026 Sweet Social Space" },
  tg: { verify:"Тасдиқ", verification:"Тасдиқ", security:"Амният • SSL Амну", trust:"Андозаи эътимод • ЗИНДА", legal:"Ҳуқуқӣ", terms:"Шартҳои истифода", privacy:"Сиёсати махфият", legalDmca:"Ҳуқуқӣ • DMCA", guarantees:"Кафолатҳо", ourGuarantees:"Кафолатҳои мо", faith:"Сиёсати эътиқод", failsafe:"Бехатар", contact:"Тамос", contactUs:"Бо мо тамос гиред", about:"Дар бораи мо", support:"Дастгирӣ • ЗИНДА", platform:"Платформа", tagline:"МАҲАЛЛӢ БАРОИ МАҲАЛЛАИ ШУМО • ЗИНДА • МУСТАҚИЛ • БЕХАТАР • SSL АМН • 100% ТАСДИҚШУДА • ХУСУСӢ ДАР 10 МИЛ", copy:"© 2026 Sweet Social Space" },
  mn: { verify:"Баталгаажуулах", verification:"Баталгаажуулалт", security:"Аюулгүй байдал • SSL Хамгаалагдсан", trust:"Итгэлийн Хэмжигч • ШУУД", legal:"Хуулийн", terms:"Хэрэглэх Нөхцөл", privacy:"Нууцлалын Бодлого", legalDmca:"Хуулийн • DMCA", guarantees:"Баталгаа", ourGuarantees:"Манай Баталгаа", faith:"Итгэлийн Бодлого", failsafe:"Алдаанд Тэсвэртэй", contact:"Холбоо барих", contactUs:"Бидэнтэй Холбогдоно уу", about:"Бидний Тухай", support:"Дэмжлэг • ШУУД", platform:"Платформ", tagline:"ТАНЫ ХӨРШИД ОРОН НУТАГТ • ШУУД • ХАРААТ БУС • АЛДААНД ТЭСВЭРТЭЙ • SSL ХАМГААЛАГДСАН • 100% БАТАЛГААЖСАН • 10 МИЛИЙН ДОТОР ХУВИЙН", copy:"© 2026 Sweet Social Space" },
  km: { verify:"ផ្ទៀងផ្ទាត់", verification:"ការផ្ទៀងផ្ទាត់", security:"សុវត្ថិភាព • SSL មានសុវត្ថិភាព", trust:"រង្វាស់ទំនុកចិត្ត • ផ្ទាល់", legal:"ច្បាប់", terms:"លក្ខខណ្ឌប្រើប្រាស់", privacy:"គោលការណ៍ឯកជនភាព", legalDmca:"ច្បាប់ • DMCA", guarantees:"ការធានា", ourGuarantees:"ការធានារបស់យើង", faith:"គោលការណ៍ជំនឿ", failsafe:"សុវត្ថិភាពបរាជ័យ", contact:"ទំនាក់ទំនង", contactUs:"ទាក់ទងមកយើង", about:"អំពី", support:"ជំនួយ • ផ្ទាល់", platform:"វេទិកា", tagline:"មូលដ្ឋានសម្រាប់សង្កាត់របស់អ្នក • ផ្ទាល់ • ឯករាជ្យ • សុវត្ថិភាពបរាជ័យ • SSL មានសុវត្ថិភាព • 100% បានផ្ទៀងផ្ទាត់ • ឯកជនក្នុងរង្វង់ 10 ម៉ាយ", copy:"© 2026 Sweet Social Space" },
  lo: { verify:"ຢືນຢັນ", verification:"ການຢືນຢັນ", security:"ຄວາມປອດໄພ • SSL ປອດໄພ", trust:"ເຄື່ອງວັດແທກຄວາມໄວ້ວາງໃຈ • ສົດ", legal:"ກົດໝາຍ", terms:"ເງື່ອນໄຂການໃຊ້", privacy:"ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ", legalDmca:"ກົດໝາຍ • DMCA", guarantees:"ການຮັບປະກັນ", ourGuarantees:"ການຮັບປະກັນຂອງພວກເຮົາ", faith:"ນະໂຍບາຍຄວາມເຊື່ອ", failsafe:"ປອດໄພລົ້ມເຫຼວ", contact:"ຕິດຕໍ່", contactUs:"ຕິດຕໍ່ພວກເຮົາ", about:"ກ່ຽວກັບ", support:"ສະໜັບສະໜູນ • ສົດ", platform:"ແພລະຕະຟອມ", tagline:"ທ້ອງຖິ່ນສຳລັບບ້ານຂອງທ່ານ • ສົດ • ເປັນເອກະລາດ • ປອດໄພລົ້ມເຫຼວ • SSL ປອດໄພ • 100% ຢືນຢັນແລ້ວ • ສ່ວນຕົວພາຍໃນ 10 ໄມ", copy:"© 2026 Sweet Social Space" },
  my: { verify:"အတည်ပြုရန်", verification:"အတည်ပြုခြင်း", security:"လုံခြုံရေး • SSL လုံခြုံသည်", trust:"ယုံကြည်မှုမီတာ • တိုက်ရိုက်", legal:"ဥပဒေရေး", terms:"အသုံးပြုမှုစည်းမျဉ်းများ", privacy:"ကိုယ်ရေးကိုယ်တာမူဝါဒ", legalDmca:"ဥပဒေရေး • DMCA", guarantees:"အာမခံချက်များ", ourGuarantees:"ကျွန်ုပ်တို့၏အာမခံချက်များ", faith:"ယုံကြည်မှုမူဝါဒ", failsafe:"ပျက်ကွက်မှုလုံခြုံ", contact:"ဆက်သွယ်ရန်", contactUs:"ကျွန်ုပ်တို့ကိုဆက်သွယ်ပါ", about:"အကြောင်း", support:"ပံ့ပိုးမှု • တိုက်ရိုက်", platform:"ပလက်ဖောင်း", tagline:"သင့်ရပ်ကွက်အတွက် ဒေသခံ • တိုက်ရိုက် • လွတ်လပ်သော • ပျက်ကွက်မှုလုံခြုံ • SSL လုံခြုံသည် • 100% အတည်ပြုပြီး • 10 မိုင်အတွင်းသီးသန့်", copy:"© 2026 Sweet Social Space" },
}

export default function GlobalFooter() {
  const { language } = useLanguage()
  const d = D[language] || D.en
  return (
    <footer className="w-full bg-black/80 backdrop-blur border-t border-white/10 mt-10 py-8 px-6">
      <div className="max-w-7xl mx-auto grid grid-cols-2 md:grid-cols-5 gap-8 text-sm">
        <div>
          <h4 className="font-black text-white uppercase tracking-widest mb-3">{d.verify}</h4>
          <ul className="space-y-2 text-white/60">
            <li><Link href="/verification" className="hover:text-white">{d.verification}</Link></li>
            <li><Link href="/security" className="hover:text-white">{d.security}</Link></li>
            <li><Link href="/trust" className="hover:text-white">{d.trust}</Link></li>
          </ul>
        </div>
        <div>
          <h4 className="font-black text-white uppercase tracking-widest mb-3">{d.legal}</h4>
          <ul className="space-y-2 text-white/60">
            <li><Link href="/terms" className="hover:text-white">{d.terms}</Link></li>
            <li><Link href="/privacy" className="hover:text-white">{d.privacy}</Link></li>
            <li><Link href="/legal" className="hover:text-white">{d.legalDmca}</Link></li>
          </ul>
        </div>
        <div>
          <h4 className="font-black text-white uppercase tracking-widest mb-3">{d.guarantees}</h4>
          <ul className="space-y-2 text-white/60">
            <li><Link href="/guarantees" className="hover:text-white">{d.ourGuarantees}</Link></li>
            <li><Link href="/faith" className="hover:text-white">{d.faith}</Link></li>
            <li><Link href="/failsafe" className="hover:text-white">{d.failsafe}</Link></li>
          </ul>
        </div>
        <div>
          <h4 className="font-black text-white uppercase tracking-widest mb-3">{d.contact}</h4>
          <ul className="space-y-2 text-white/60">
            <li><Link href="/contact" className="hover:text-white">{d.contactUs}</Link></li>
            <li><Link href="/about" className="hover:text-white">{d.about}</Link></li>
            <li><Link href="/support" className="hover:text-white">{d.support}</Link></li>
          </ul>
        </div>
        <div>
          <h4 className="font-black text-white uppercase tracking-widest mb-3">{d.platform}</h4>
          <p className="text-white/40 text-xs leading-relaxed">{d.tagline}</p>
          <p className="mt-3 text-white/20 text-xs">{d.copy}</p>
        </div>
      </div>
    </footer>
  )
}
