'use client'
import Link from 'next/link'
import { useLanguage } from '@/lib/language-context'

const D: Record<string, any> = {
  en: { verify:"Verify", verification:"Verification", security:"Security • SSL Secured", trust:"Trust Meter", legal:"Legal", terms:"Terms of Use", privacy:"Privacy Policy", legalDmca:"Legal • DMCA", guarantees:"Guarantees", ourGuar:"Our Guarantees", faith:"Faith Corner", failsafe:"Failsafe", contact:"Contact", contactUs:"Contact Us", about:"About", support:"Support", platform:"Platform", tagline:"INDEPENDENT • FAILSAFE • SSL SECURED • 100% VERIFIED • We care about your privacy" },
  es: { verify:"Verificar", verification:"Verificación", security:"Seguridad • SSL Seguro", trust:"Medidor Confianza", legal:"Legal", terms:"Términos de Uso", privacy:"Política Privacidad", legalDmca:"Legal • DMCA", guarantees:"Garantías", ourGuar:"Nuestras Garantías", faith:"Rincón Fe", failsafe:"A Prueba Fallos", contact:"Contacto", contactUs:"Contáctanos", about:"Acerca", support:"Soporte", platform:"Plataforma", tagline:"INDEPENDIENTE • A PRUEBA FALLOS • SSL SEGURO • 100% VERIFICADO • Nos importa tu privacidad" },
  fr: { verify:"Vérifier", verification:"Vérification", security:"Sécurité • SSL Sécurisé", trust:"Compteur Confiance", legal:"Légal", terms:"Conditions Utilisation", privacy:"Politique Confidentialité", legalDmca:"Légal • DMCA", guarantees:"Garanties", ourGuar:"Nos Garanties", faith:"Coin Foi", failsafe:"Sécurité Intégrée", contact:"Contact", contactUs:"Contactez-nous", about:"À propos", support:"Support", platform:"Plateforme", tagline:"INDÉPENDANT • SÉCURITÉ INTÉGRÉE • SSL SÉCURISÉ • 100% VÉRIFIÉ • Votre vie privée compte" },
  de: { verify:"Verifizieren", verification:"Verifizierung", security:"Sicherheit • SSL Gesichert", trust:"Vertrauensmesser", legal:"Rechtliches", terms:"Nutzungsbedingungen", privacy:"Datenschutzrichtlinie", legalDmca:"Rechtliches • DMCA", guarantees:"Garantien", ourGuar:"Unsere Garantien", faith:"Glaubens-Ecke", failsafe:"Ausfallsicher", contact:"Kontakt", contactUs:"Kontaktiere Uns", about:"Über", support:"Support", platform:"Plattform", tagline:"UNABHÄNGIG • AUSFALLSICHER • SSL GESICHERT • 100% VERIFIZIERT • Datenschutz wichtig" },
  zh: { verify:"验证", verification:"验证", security:"安全 • SSL 安全", trust:"信任计", legal:"法律", terms:"使用条款", privacy:"隐私政策", legalDmca:"法律 • DMCA", guarantees:"保证", ourGuar:"我们的保证", faith:"信仰角落", failsafe:"故障安全", contact:"联系", contactUs:"联系我们", about:"关于", support:"支持", platform:"平台", tagline:"独立 • 故障安全 • SSL 安全 • 100% 已验证 • 我们关心您的隐私" },
  ja: { verify:"認証", verification:"認証", security:"セキュリティ • SSL保護", trust:"信頼メーター", legal:"法的", terms:"利用規約", privacy:"プライバシーポリシー", legalDmca:"法的 • DMCA", guarantees:"保証", ourGuar:"私たちの保証", faith:"信仰コーナー", failsafe:"フェイルセーフ", contact:"連絡先", contactUs:"お問い合わせ", about:"約", support:"サポート", platform:"プラットフォーム", tagline:"独立 • フェイルセーフ • SSL保護 • 100%認証済み • プライバシーを大切に" },
  ko: { verify:"인증", verification:"인증", security:"보안 • SSL 보안", trust:"신뢰 미터", legal:"법률", terms:"이용 약관", privacy:"개인정보 처리방침", legalDmca:"법률 • DMCA", guarantees:"보증", ourGuar:"우리의 보증", faith:"신앙 코너", failsafe:"안전장치", contact:"연락처", contactUs:"문의하기", about:"소개", support:"지원", platform:"플랫폼", tagline:"독립 • 안전장치 • SSL 보안 • 100% 인증됨 • 개인정보 보호 중요" },
  pt: { verify:"Verificar", verification:"Verificação", security:"Segurança • SSL Seguro", trust:"Medidor Confiança", legal:"Legal", terms:"Termos de Uso", privacy:"Política Privacidade", legalDmca:"Legal • DMCA", guarantees:"Garantias", ourGuar:"Nossas Garantias", faith:"Canto Fé", failsafe:"À Prova Falhas", contact:"Contato", contactUs:"Fale Conosco", about:"Sobre", support:"Suporte", platform:"Plataforma", tagline:"INDEPENDENTE • À PROVA FALHAS • SSL SEGURO • 100% VERIFICADO • Sua privacidade importa" },
  ru: { verify:"Проверить", verification:"Верификация", security:"Безопасность • SSL Защищено", trust:"Измеритель Доверия", legal:"Юридич.", terms:"Условия Использования", privacy:"Политика Конфиденц.", legalDmca:"Юридич. • DMCA", guarantees:"Гарантии", ourGuar:"Наши Гарантии", faith:"Уголок Веры", failsafe:"Безотказность", contact:"Контакт", contactUs:"Свяжитесь с Нами", about:"О Нас", support:"Поддержка", platform:"Платформа", tagline:"НЕЗАВИСИМЫЙ • БЕЗОТКАЗНЫЙ • SSL ЗАЩИЩЕНО • 100% ПРОВЕРЕНО • Ваша приватность важна" },
  ar: { verify:"تحقق", verification:"التحقق", security:"الأمان • SSL آمن", trust:"مقياس الثقة", legal:"قانوني", terms:"شروط الاستخدام", privacy:"سياسة الخصوصية", legalDmca:"قانوني • DMCA", guarantees:"ضمانات", ourGuar:"ضماناتنا", faith:"ركن الإيمان", failsafe:"آمن من الفشل", contact:"اتصل", contactUs:"اتصل بنا", about:"حول", support:"دعم", platform:"منصة", tagline:"مستقل • آمن من الفشل • SSL آمن • 100% موثق • خصوصيتك تهمنا" },
  hi: { verify:"सत्यापित", verification:"सत्यापन", security:"सुरक्षा • SSL सुरक्षित", trust:"विश्वास मीटर", legal:"कानूनी", terms:"उपयोग शर्तें", privacy:"गोपनीयता नीति", legalDmca:"कानूनी • DMCA", guarantees:"गारंटी", ourGuar:"हमारी गारंटी", faith:"विश्वास कोना", failsafe:"फेलसेफ", contact:"संपर्क", contactUs:"संपर्क करें", about:"बारे में", support:"सहायता", platform:"प्लेटफॉर्म", tagline:"स्वतंत्र • फेलसेफ • SSL सुरक्षित • 100% सत्यापित • आपकी गोपनीयता महत्वपूर्ण" },
  it: { verify:"Verifica", verification:"Verifica", security:"Sicurezza • SSL Sicuro", trust:"Misuratore Fiducia", legal:"Legale", terms:"Termini d'Uso", privacy:"Informativa Privacy", legalDmca:"Legale • DMCA", guarantees:"Garanzie", ourGuar:"Nostre Garanzie", faith:"Angolo Fede", failsafe:"Failsafe", contact:"Contatto", contactUs:"Contattaci", about:"Chi Siamo", support:"Supporto", platform:"Piattaforma", tagline:"INDIPENDENTE • FAILSAFE • SSL SICURO • 100% VERIFICATO • Privacy importante" },
  nl: { verify:"Verifiëren", verification:"Verificatie", security:"Beveiliging • SSL Beveiligd", trust:"Vertrouwensmeter", legal:"Juridisch", terms:"Gebruiksvoorwaarden", privacy:"Privacybeleid", legalDmca:"Juridisch • DMCA", guarantees:"Garanties", ourGuar:"Onze Garanties", faith:"Geloofshoek", failsafe:"Failsafe", contact:"Contact", contactUs:"Contacteer Ons", about:"Over", support:"Support", platform:"Platform", tagline:"ONAFHANKELIJK • FAILSAFE • SSL BEVEILIGD • 100% GEVERIFIEERD • Privacy belangrijk" },
  tl: { verify:"I-verify", verification:"Beripikasyon", security:"Seguridad • SSL Secured", trust:"Trust Meter", legal:"Legal", terms:"Tuntunin ng Paggamit", privacy:"Patakaran sa Privacy", legalDmca:"Legal • DMCA", guarantees:"Garantiya", ourGuar:"Aming Garantiya", faith:"Sulok ng Pananampalataya", failsafe:"Failsafe", contact:"Contact", contactUs:"Makipag-ugnayan", about:"Tungkol", support:"Suporta", platform:"Platform", tagline:"INDEPENDENT • FAILSAFE • SSL SECURED • 100% VERIFIED • Mahalaga privacy mo" },
  bn: { verify:"যাচাই", verification:"যাচাইকরণ", security:"নিরাপত্তা • SSL সুরক্ষিত", trust:"বিশ্বাস মিটার", legal:"আইনি", terms:"ব্যবহারের শর্ত", privacy:"গোপনীয়তা নীতি", legalDmca:"আইনি • DMCA", guarantees:"গ্যারান্টি", ourGuar:"আমাদের গ্যারান্টি", faith:"বিশ্বাস কোণ", failsafe:"ফেলসেফ", contact:"যোগাযোগ", contactUs:"যোগাযোগ করুন", about:"সম্পর্কে", support:"সহায়তা", platform:"প্ল্যাটফর্ম", tagline:"স্বাধীন • ফেলসেফ • SSL সুরক্ষিত • ১০০% যাচাইকৃত • আপনার গোপনীয়তা গুরুত্বপূর্ণ" },
  id: { verify:"Verifikasi", verification:"Verifikasi", security:"Keamanan • SSL Aman", trust:"Pengukur Kepercayaan", legal:"Legal", terms:"Syarat Penggunaan", privacy:"Kebijakan Privasi", legalDmca:"Legal • DMCA", guarantees:"Jaminan", ourGuar:"Jaminan Kami", faith:"Sudut Iman", failsafe:"Failsafe", contact:"Kontak", contactUs:"Hubungi Kami", about:"Tentang", support:"Dukungan", platform:"Platform", tagline:"INDEPENDEN • FAILSAFE • SSL AMAN • 100% TERVERIFIKASI • Privasi penting" },
  vi: { verify:"Xác minh", verification:"Xác minh", security:"Bảo mật • SSL An toàn", trust:"Thước Đo Tin Cậy", legal:"Pháp lý", terms:"Điều khoản Sử dụng", privacy:"Chính sách Riêng tư", legalDmca:"Pháp lý • DMCA", guarantees:"Bảo đảm", ourGuar:"Bảo đảm Chúng tôi", faith:"Góc Đức tin", failsafe:"An toàn", contact:"Liên hệ", contactUs:"Liên hệ Chúng tôi", about:"Về", support:"Hỗ trợ", platform:"Nền tảng", tagline:"ĐỘC LẬP • AN TOÀN • SSL AN TOÀN • 100% ĐÃ XÁC MINH • Quyền riêng tư quan trọng" },
  th: { verify:"ยืนยัน", verification:"การยืนยัน", security:"ความปลอดภัย • SSL ปลอดภัย", trust:"เครื่องวัดความไว้วางใจ", legal:"กฎหมาย", terms:"ข้อกำหนดการใช้งาน", privacy:"นโยบายความเป็นส่วนตัว", legalDmca:"กฎหมาย • DMCA", guarantees:"การรับประกัน", ourGuar:"การรับประกันของเรา", faith:"มุมศรัทธา", failsafe:"ปลอดภัย", contact:"ติดต่อ", contactUs:"ติดต่อเรา", about:"เกี่ยวกับ", support:"สนับสนุน", platform:"แพลตฟอร์ม", tagline:"อิสระ • ปลอดภัย • SSL ปลอดภัย • 100% ยืนยันแล้ว • ความเป็นส่วนตัวสำคัญ" },
  sv: { verify:"Verifiera", verification:"Verifiering", security:"Säkerhet • SSL Säker", trust:"Förtroendemätare", legal:"Juridiskt", terms:"Användarvillkor", privacy:"Integritetspolicy", legalDmca:"Juridiskt • DMCA", guarantees:"Garantier", ourGuar:"Våra Garantier", faith:"Troshörna", failsafe:"Felsäker", contact:"Kontakt", contactUs:"Kontakta Oss", about:"Om", support:"Support", platform:"Plattform", tagline:"OBEROENDE • FELSÄKER • SSL SÄKER • 100% VERIFIERAD • Integritet viktig" },
  pl: { verify:"Weryfikuj", verification:"Weryfikacja", security:"Bezpieczeństwo • SSL Zabezpieczone", trust:"Miernik Zaufania", legal:"Prawne", terms:"Warunki Użytkowania", privacy:"Polityka Prywatności", legalDmca:"Prawne • DMCA", guarantees:"Gwarancje", ourGuar:"Nasze Gwarancje", faith:"Kącik Wiary", failsafe:"Zabezpieczenie", contact:"Kontakt", contactUs:"Skontaktuj się", about:"O Nas", support:"Wsparcie", platform:"Platforma", tagline:"NIEZALEŻNY • ZABEZPIECZONY • SSL ZABEZPIECZONE • 100% ZWERYFIKOWANY • Prywatność ważna" },
  tr: { verify:"Doğrula", verification:"Doğrulama", security:"Güvenlik • SSL Güvenli", trust:"Güven Ölçer", legal:"Yasal", terms:"Kullanım Şartları", privacy:"Gizlilik Politikası", legalDmca:"Yasal • DMCA", guarantees:"Garantiler", ourGuar:"Garantilerimiz", faith:"İnanç Köşesi", failsafe:"Güvenli", contact:"İletişim", contactUs:"Bize Ulaşın", about:"Hakkında", support:"Destek", platform:"Platform", tagline:"BAĞIMSIZ • GÜVENLİ • SSL GÜVENLİ • %100 DOĞRULANMIŞ • Gizliliğiniz önemli" },
  uk: { verify:"Перевірити", verification:"Верифікація", security:"Безпека • SSL Захищено", trust:"Вимірювач Довіри", legal:"Юридично", terms:"Умови Використання", privacy:"Політика Конфід.", legalDmca:"Юридично • DMCA", guarantees:"Гарантії", ourGuar:"Наші Гарантії", faith:"Куточок Віри", failsafe:"Безвідмовність", contact:"Контакт", contactUs:"Зв'яжіться з Нами", about:"Про Нас", support:"Підтримка", platform:"Платформа", tagline:"НЕЗАЛЕЖНИЙ • БЕЗВІДМОВНИЙ • SSL ЗАХИЩЕНО • 100% ПЕРЕВІРЕНО • Конфіденційність важлива" },
  el: { verify:"Επαλήθευση", verification:"Επαλήθευση", security:"Ασφάλεια • SSL Ασφαλές", trust:"Μετρητής Εμπιστοσύνης", legal:"Νομικά", terms:"Όροι Χρήσης", privacy:"Πολιτική Απορρήτου", legalDmca:"Νομικά • DMCA", guarantees:"Εγγυήσεις", ourGuar:"Εγγυήσεις Μας", faith:"Γωνιά Πίστης", failsafe:"Ασφαλές", contact:"Επικοινωνία", contactUs:"Επικοινωνήστε", about:"Σχετικά", support:"Υποστήριξη", platform:"Πλατφόρμα", tagline:"ΑΝΕΞΑΡΤΗΤΟ • ΑΣΦΑΛΕΣ • SSL ΑΣΦΑΛΕΣ • 100% ΕΠΑΛΗΘΕΥΜΕΝΟ • Ιδιωτικότητα σημαντική" },
  he: { verify:"אמת", verification:"אימות", security:"אבטחה • SSL מאובטח", trust:"מד אמון", legal:"משפטי", terms:"תנאי שימוש", privacy:"מדיניות פרטיות", legalDmca:"משפטי • DMCA", guarantees:"ערבויות", ourGuar:"הערבויות שלנו", faith:"פינת אמונה", failsafe:"מוגן כשל", contact:"צור קשר", contactUs:"צור קשר איתנו", about:"אודות", support:"תמיכה", platform:"פלטפורמה", tagline:"עצמאי • מוגן כשל • SSL מאובטח • 100% מאומת • פרטיות חשובה" },
  ur: { verify:"تصدیق", verification:"تصدیق", security:"سیکیورٹی • SSL محفوظ", trust:"اعتماد میٹر", legal:"قانونی", terms:"استعمال کی شرائط", privacy:"رازداری کی پالیسی", legalDmca:"قانونی • DMCA", guarantees:"ضمانتیں", ourGuar:"ہماری ضمانتیں", faith:"ایمان کونہ", failsafe:"فیل سیف", contact:"رابطہ", contactUs:"ہم سے رابطہ کریں", about:"ہمارے بارے میں", support:"سپورٹ", platform:"پلیٹ فارم", tagline:"آزاد • فیل سیف • SSL محفوظ • 100% تصدیق شدہ • آپ کی رازداری اہم" },
  fa: { verify:"تأیید", verification:"تأیید", security:"امنیت • SSL امن", trust:"سنجش اعتماد", legal:"حقوقی", terms:"شرایط استفاده", privacy:"سیاست حریم خصوصی", legalDmca:"حقوقی • DMCA", guarantees:"ضمانت‌ها", ourGuar:"ضمانت‌های ما", faith:"گوشه ایمان", failsafe:"ایمن از خرابی", contact:"تماس", contactUs:"با ما تماس بگیرید", about:"درباره", support:"پشتیبانی", platform:"پلتفرم", tagline:"مستقل • ایمن از خرابی • SSL امن • 100% تأیید شده • حریم خصوصی مهم است" },
  ms: { verify:"Sahkan", verification:"Pengesahan", security:"Keselamatan • SSL Selamat", trust:"Meter Kepercayaan", legal:"Undang-undang", terms:"Terma Penggunaan", privacy:"Dasar Privasi", legalDmca:"Undang-undang • DMCA", guarantees:"Jaminan", ourGuar:"Jaminan Kami", faith:"Sudut Iman", failsafe:"Selamat Gagal", contact:"Hubungi", contactUs:"Hubungi Kami", about:"Tentang", support:"Sokongan", platform:"Platform", tagline:"BEBAS • SELAMAT GAGAL • SSL SELAMAT • 100% DISAHKAN • Privasi penting" },
  ro: { verify:"Verifică", verification:"Verificare", security:"Securitate • SSL Securizat", trust:"Contor Încredere", legal:"Legal", terms:"Termeni Utilizare", privacy:"Politică Confidențialitate", legalDmca:"Legal • DMCA", guarantees:"Garanții", ourGuar:"Garanțiile Noastre", faith:"Colț Credință", failsafe:"Siguranță", contact:"Contact", contactUs:"Contactează-ne", about:"Despre", support:"Suport", platform:"Platformă", tagline:"INDEPENDENT • SIGUR • SSL SECURIZAT • 100% VERIFICAT • Confidențialitate importantă" },
  cs: { verify:"Ověřit", verification:"Ověření", security:"Zabezpečení • SSL Zabezpečeno", trust:"Měřič Důvěry", legal:"Právní", terms:"Podmínky Používání", privacy:"Zásady Ochrany", legalDmca:"Právní • DMCA", guarantees:"Záruky", ourGuar:"Naše Záruky", faith:"Koutek Víry", failsafe:"Zabezpečení", contact:"Kontakt", contactUs:"Kontaktujte Nás", about:"O Nás", support:"Podpora", platform:"Platforma", tagline:"NEZÁVISLÝ • ZABEZPEČENÝ • SSL ZABEZPEČENO • 100% OVĚŘENO • Soukromí důležité" },
  hu: { verify:"Ellenőriz", verification:"Ellenőrzés", security:"Biztonság • SSL Védett", trust:"Bizalmi Mérő", legal:"Jogi", terms:"Használati Feltételek", privacy:"Adatvédelmi Irányelvek", legalDmca:"Jogi • DMCA", guarantees:"Garanciák", ourGuar:"Garanciáink", faith:"Hit Sarok", failsafe:"Biztonságos", contact:"Kapcsolat", contactUs:"Lépj Velünk Kapcsolatba", about:"Rólunk", support:"Támogatás", platform:"Platform", tagline:"FÜGGETLEN • BIZTONSÁGOS • SSL VÉDETT • 100% ELLENŐRZÖTT • Adatvédelem fontos" },
  fi: { verify:"Vahvista", verification:"Vahvistus", security:"Turvallisuus • SSL Suojattu", trust:"Luottamusmittari", legal:"Juridinen", terms:"Käyttöehdot", privacy:"Tietosuojakäytäntö", legalDmca:"Juridinen • DMCA", guarantees:"Takuut", ourGuar:"Takuumme", faith:"Uskonurkka", failsafe:"Vikasietoinen", contact:"Yhteys", contactUs:"Ota Yhteyttä", about:"Meistä", support:"Tuki", platform:"Alusta", tagline:"RIIPPUMATON • VIKASIETOINEN • SSL SUOJATTU • 100% VAHVISTETTU • Yksityisyys tärkeä" },
  no: { verify:"Bekreft", verification:"Verifisering", security:"Sikkerhet • SSL Sikret", trust:"Tillitsmåler", legal:"Juridisk", terms:"Bruksvilkår", privacy:"Personvernerklæring", legalDmca:"Juridisk • DMCA", guarantees:"Garantier", ourGuar:"Våre Garantier", faith:"Troshjørne", failsafe:"Feilsikker", contact:"Kontakt", contactUs:"Kontakt Oss", about:"Om", support:"Støtte", platform:"Plattform", tagline:"UAVHENGIG • FEILSIKKER • SSL SIKRET • 100% VERIFISERT • Personvern viktig" },
  da: { verify:"Bekræft", verification:"Verifikation", security:"Sikkerhed • SSL Sikret", trust:"Tillidsmåler", legal:"Juridisk", terms:"Brugsbetingelser", privacy:"Privatlivspolitik", legalDmca:"Juridisk • DMCA", guarantees:"Garantier", ourGuar:"Vores Garantier", faith:"Troshjørne", failsafe:"Fejlsikker", contact:"Kontakt", contactUs:"Kontakt Os", about:"Om", support:"Support", platform:"Platform", tagline:"UAFHÆNGIG • FEJLSIKKER • SSL SIKRET • 100% VERIFICERET • Privatliv vigtigt" },
  bg: { verify:"Потвърди", verification:"Верификация", security:"Сигурност • SSL Защитено", trust:"Измервател Доверие", legal:"Правно", terms:"Условия за Ползване", privacy:"Политика Поверителност", legalDmca:"Правно • DMCA", guarantees:"Гаранции", ourGuar:"Нашите Гаранции", faith:"Кът Вяра", failsafe:"Безопасност", contact:"Контакт", contactUs:"Свържете се с Нас", about:"За Нас", support:"Поддръжка", platform:"Платформа", tagline:"НЕЗАВИСИМ • БЕЗОПАСЕН • SSL ЗАЩИТЕНО • 100% ВЕРИФИЦИРАН • Поверителността важна" },
  hr: { verify:"Potvrdi", verification:"Verifikacija", security:"Sigurnost • SSL Osigurano", trust:"Mjerač Povjerenja", legal:"Pravno", terms:"Uvjeti Korištenja", privacy:"Pravila Privatnosti", legalDmca:"Pravno • DMCA", guarantees:"Jamstva", ourGuar:"Naša Jamstva", faith:"Kutak Vjere", failsafe:"Sigurnosno", contact:"Kontakt", contactUs:"Kontaktirajte Nas", about:"O Nama", support:"Podrška", platform:"Platforma", tagline:"NEOVISAN • SIGURNOSNI • SSL OSIGURANO • 100% VERIFICIRANO • Privatnost važna" },
  sr: { verify:"Потврди", verification:"Верификација", security:"Безбедност • SSL Обезбеђено", trust:"Мерач Поверења", legal:"Правно", terms:"Услови Коришћења", privacy:"Политика Приватности", legalDmca:"Правно • DMCA", guarantees:"Гаранције", ourGuar:"Наше Гаранције", faith:"Кутак Вере", failsafe:"Сигурносно", contact:"Контакт", contactUs:"Контактирајте Нас", about:"О Нама", support:"Подршка", platform:"Платформа", tagline:"НЕЗАВИСАН • СИГУРНОСНИ • SSL ОБЕЗБЕЂЕНО • 100% ВЕРИФИКОВАНО • Приватност важна" },
  sk: { verify:"Overiť", verification:"Overenie", security:"Zabezpečenie • SSL Zabezpečené", trust:"Merač Dôvery", legal:"Právne", terms:"Podmienky Používania", privacy:"Zásady Ochrany", legalDmca:"Právne • DMCA", guarantees:"Záruky", ourGuar:"Naše Záruky", faith:"Kútik Viery", failsafe:"Bezpečnostné", contact:"Kontakt", contactUs:"Kontaktujte Nás", about:"O Nás", support:"Podpora", platform:"Platforma", tagline:"NEZÁVISLÝ • BEZPEČNOSTNÝ • SSL ZABEZPEČENÉ • 100% OVERENÉ • Súkromie dôležité" },
  sl: { verify:"Preveri", verification:"Preverjanje", security:"Varnost • SSL Zavarovano", trust:"Merilnik Zaupanja", legal:"Pravno", terms:"Pogoji Uporabe", privacy:"Politika Zasebnosti", legalDmca:"Pravno • DMCA", guarantees:"Jamstva", ourGuar:"Naša Jamstva", faith:"Kotiček Vere", failsafe:"Varno", contact:"Kontakt", contactUs:"Kontaktirajte Nas", about:"O Nas", support:"Podpora", platform:"Platforma", tagline:"NEODVISEN • VAREN • SSL ZAVAROVANO • 100% PREVERJENO • Zasebnost pomembna" },
  et: { verify:"Kinnita", verification:"Kinnitamine", security:"Turvalisus • SSL Kaitstud", trust:"Usaldusmõõdik", legal:"Juriidiline", terms:"Kasutustingimused", privacy:"Privaatsuspoliitika", legalDmca:"Juriidiline • DMCA", guarantees:"Garantiid", ourGuar:"Meie Garantiid", faith:"Usunurk", failsafe:"Tõrkekindel", contact:"Kontakt", contactUs:"Võta Ühendust", about:"Meist", support:"Tugi", platform:"Platvorm", tagline:"SÕLTUMATU • TÕRKEKINDEL • SSL KAITSTUD • 100% KINNITATUD • Privaatsus oluline" },
  lv: { verify:"Apstiprināt", verification:"Verifikācija", security:"Drošība • SSL Aizsargāts", trust:"Uzticības Mērītājs", legal:"Juridiska", terms:"Lietošanas Noteikumi", privacy:"Privātuma Politika", legalDmca:"Juridiska • DMCA", guarantees:"Garantijas", ourGuar:"Mūsu Garantijas", faith:"Ticības Stūris", failsafe:"Drošs", contact:"Kontakts", contactUs:"Sazinieties ar Mums", about:"Par Mums", support:"Atbalsts", platform:"Platforma", tagline:"NEATKARĪGS • DROŠS • SSL AIZSARGĀTS • 100% VERIFICĒTS • Privātums svarīgs" },
  lt: { verify:"Patvirtinti", verification:"Patvirtinimas", security:"Saugumas • SSL Apsaugota", trust:"Pasitikėjimo Matuoklis", legal:"Teisinė", terms:"Naudojimo Sąlygos", privacy:"Privatumo Politika", legalDmca:"Teisinė • DMCA", guarantees:"Garantijos", ourGuar:"Mūsų Garantijos", faith:"Tikėjimo Kampelis", failsafe:"Apsauga", contact:"Kontaktas", contactUs:"Susisiekite Su Mumis", about:"Apie Mus", support:"Pagalba", platform:"Platforma", tagline:"NEPRIKLAUSOMA • APSAUGA • SSL APSAUGOTA • 100% PATVIRTINTA • Privatumas svarbus" },
  be: { verify:"Пацвердзіць", verification:"Верыфікацыя", security:"Бяспека • SSL Абаронена", trust:"Вымяральнік Даверу", legal:"Юрыдычна", terms:"Умовы Выкарыстання", privacy:"Палітыка Прыватнасці", legalDmca:"Юрыдычна • DMCA", guarantees:"Гарантыі", ourGuar:"Нашы Гарантыі", faith:"Куток Веры", failsafe:"Бяспека", contact:"Кантакт", contactUs:"Звяжыцеся з Нами", about:"Пра Нас", support:"Падтрымка", platform:"Платформа", tagline:"НЕЗАЛЕЖНЫ • БЯСПЕКА • SSL АБАРОНЕНА • 100% ВЕРЫФІКАВАНА • Прыватнасць важная" },
  ka: { verify:"დადასტურება", verification:"ვერიფიკაცია", security:"უსაფრთხოება • SSL დაცული", trust:"ნდობის მრიცხველი", legal:"იურიდიული", terms:"გამოყენების წესები", privacy:"კონფიდენციალურობის პოლიტიკა", legalDmca:"იურიდიული • DMCA", guarantees:"გარანტიები", ourGuar:"ჩვენი გარანტიები", faith:"რწმენის კუთხე", failsafe:"უსაფრთხო", contact:"კონტაქტი", contactUs:"დაგვიკავშირდით", about:"ჩვენ შესახებ", support:"მხარდაჭერა", platform:"პლატფორმა", tagline:"დამოუკიდებელი • უსაფრთხო • SSL დაცული • 100% ვერიფიცირებული • კონფიდენციალურობა მნიშვნელოვანია" },
  hy: { verify:"Հաստատել", verification:"Ստուգում", security:"Անվտանգություն • SSL Պաշտպանված", trust:"Վստահության Չափիչ", legal:"Իրավական", terms:"Օգտագործման Պայմաններ", privacy:"Գաղտնիության Քաղաքականություն", legalDmca:"Իրավական • DMCA", guarantees:"Երաշխիքներ", ourGuar:"Մեր Երաշխիքները", faith:"Հավատի Անկյուն", failsafe:"Անվտանգ", contact:"Կապ", contactUs:"Կապվեք Մեզ Հետ", about:"Մեր Մասին", support:"Աջակցություն", platform:"Հարթակ", tagline:"ԱՆԿԱԽ • ԱՆՎՏԱՆԳ • SSL ՊԱՇՏՊԱՆՎԱԾ • 100% ՍՏՈՒԳՎԱԾ • Գաղտնիությունը կարևոր է" },
  az: { verify:"Təsdiqlə", verification:"Doğrulama", security:"Təhlükəsizlik • SSL Qorunur", trust:"Etibar Ölçən", legal:"Hüquqi", terms:"İstifadə Şərtləri", privacy:"Məxfilik Siyasəti", legalDmca:"Hüquqi • DMCA", guarantees:"Zəmanətlər", ourGuar:"Zəmanətlərimiz", faith:"İnam Küncü", failsafe:"Təhlükəsiz", contact:"Əlaqə", contactUs:"Bizimlə Əlaqə Saxlayın", about:"Haqqımızda", support:"Dəstək", platform:"Platforma", tagline:"MÜSTƏQİL • TƏHLÜKƏSİZ • SSL QORUNUR • 100% DOĞRULANMIŞ • Məxfilik vacibdir" },
  kk: { verify:"Растау", verification:"Тексеру", security:"Қауіпсіздік • SSL Қорғалған", trust:"Сенім Өлшегіш", legal:"Заңды", terms:"Пайдалану Шарттары", privacy:"Құпиялылық Саясаты", legalDmca:"Заңды • DMCA", guarantees:"Кепілдіктер", ourGuar:"Біздің Кепілдіктер", faith:"Сенім Бұрышы", failsafe:"Қауіпсіз", contact:"Байланыс", contactUs:"Бізбен Байланысыңыз", about:"Біз Туралы", support:"Қолдау", platform:"Платформа", tagline:"ТӘУЕЛСІЗ • ҚАУІПСІЗ • SSL ҚОРҒАЛҒАН • 100% РАСТАЛҒАН • Құпиялылық маңызды" },
  ky: { verify:"Тастыктоо", verification:"Текшерүү", security:"Коопсуздук • SSL Корголгон", trust:"Ишеним Өлчөгүч", legal:"Юридикалык", terms:"Колдонуу Шарттары", privacy:"Купуялуулук Саясаты", legalDmca:"Юридикалык • DMCA", guarantees:"Кепилдиктер", ourGuar:"Биздин Кепилдиктер", faith:"Ишеним Бурчу", failsafe:"Коопсуз", contact:"Байланыш", contactUs:"Биз Менен Байланышыңыз", about:"Биз Жөнүндө", support:"Колдоо", platform:"Платформа", tagline:"КӨЗ КАРАНДЫСЫЗ • КООПСУЗ • SSL КОРГОЛГОН • 100% ТАСТЫКТАЛГАН • Купуялуулук маанилүү" },
  uz: { verify:"Tasdiqlash", verification:"Tasdiqlash", security:"Xavfsizlik • SSL Himoyalangan", trust:"Ishonch O'lchagich", legal:"Yuridik", terms:"Foydalanish Shartlari", privacy:"Maxfiylik Siyosati", legalDmca:"Yuridik • DMCA", guarantees:"Kafolatlar", ourGuar:"Kafolatlarimiz", faith:"Iymon Burchagi", failsafe:"Xavfsiz", contact:"Aloqa", contactUs:"Biz Bilan Bog'laning", about:"Biz Haqimizda", support:"Qo'llab-quvvatlash", platform:"Platforma", tagline:"MUSTAQIL • XAVFSIZ • SSL HIMOYALANGAN • 100% TASDIQLANGAN • Maxfiylik muhim" },
  tg: { verify:"Тасдиқ", verification:"Тасдиқ", security:"Амният • SSL Ҳифз Шуда", trust:"Андозаи Боварӣ", legal:"Ҳуқуқӣ", terms:"Шартҳои Истифода", privacy:"Сиёсати Махфият", legalDmca:"Ҳуқуқӣ • DMCA", guarantees:"Кафолатҳо", ourGuar:"Кафолатҳои Мо", faith:"Гӯшаи Имон", failsafe:"Беэътимод", contact:"Тамос", contactUs:"Бо Мо Тамос Гиред", about:"Дар Бораи Мо", support:"Дастгирӣ", platform:"Платформа", tagline:"МУСТАҚИЛ • БЕЭЪТИМОД • SSL ҲИФЗ ШУДА • 100% ТАСДИҚ ШУДА • Махфият муҳим" },
  mn: { verify:"Баталгаажуулах", verification:"Баталгаажуулалт", security:"Аюулгүй Байдал • SSL Хамгаалагдсан", trust:"Итгэлцлийн Хэмжигч", legal:"Хууль", terms:"Хэрэглэх Нөхцөл", privacy:"Нууцлалын Бодлого", legalDmca:"Хууль • DMCA", guarantees:"Баталгаа", ourGuar:"Манай Баталгаа", faith:"Итгэлийн Булан", failsafe:"Аюулгүй", contact:"Холбоо барих", contactUs:"Бидэнтэй Холбогдоно уу", about:"Бидний Тухай", support:"Дэмжлэг", platform:"Платформ", tagline:"ХАРААТ БУС • АЮУЛГҮЙ • SSL ХАМГААЛАГДСАН • 100% БАТАЛГААЖСАН • Нууцлал чухал" },
  km: { verify:"ផ្ទៀងផ្ទាត់", verification:"ផ្ទៀងផ្ទាត់", security:"សុវត្ថិភាព • SSL មានសុវត្ថិភាព", trust:"ម៉ែត្រទំនុកចិត្ត", legal:"ច្បាប់", terms:"លក្ខខណ្ឌប្រើប្រាស់", privacy:"គោលការណ៍ឯកជនភាព", legalDmca:"ច្បាប់ • DMCA", guarantees:"ការធានា", ourGuar:"ការធានារបស់យើង", faith:"ជ្រុងជំនឿ", failsafe:"សុវត្ថិភាព", contact:"ទំនាក់ទំនង", contactUs:"ទាក់ទងមកយើង", about:"អំពី", support:"គាំទ្រ", platform:"វេទិកា", tagline:"ឯករាជ្យ • សុវត្ថិភាព • SSL មានសុវត្ថិភាព • 100% ផ្ទៀងផ្ទាត់ • ឯកជនភាពសំខាន់" },
  lo: { verify:"ຢືນຢັນ", verification:"ການຢືນຢັນ", security:"ຄວາມປອດໄພ • SSL ປອດໄພ", trust:"ເຄື່ອງວັດແທກຄວາມໄວ້ວາງໃຈ", legal:"ກົດໝາຍ", terms:"ເງື່ອນໄຂການໃຊ້", privacy:"ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ", legalDmca:"ກົດໝາຍ • DMCA", guarantees:"ການຮັບປະກັນ", ourGuar:"ການຮັບປະກັນຂອງພວກເຮົາ", faith:"ມຸມສັດທາ", failsafe:"ປອດໄພ", contact:"ຕິດຕໍ່", contactUs:"ຕິດຕໍ່ພວກເຮົາ", about:"ກ່ຽວກັບ", support:"ສະໜັບສະໜູນ", platform:"ແພລດຟອມ", tagline:"ເອກະລາດ • ປອດໄພ • SSL ປອດໄພ • 100% ຢືນຢັນແລ້ວ • ຄວາມເປັນສ່ວນຕົວສຳຄັນ" },
  my: { verify:"အတည်ပြုပါ", verification:"အတည်ပြုခြင်း", security:"လုံခြုံရေး • SSL လုံခြုံသည်", trust:"ယုံကြည်မှုမီတာ", legal:"ဥပဒေရေး", terms:"အသုံးပြုမှုစည်းမျဉ်းများ", privacy:"ကိုယ်ရေးကိုယ်တာမူဝါဒ", legalDmca:"ဥပဒေရေး • DMCA", guarantees:"အာမခံချက်များ", ourGuar:"ကျွန်ုပ်တို့၏အာမခံချက်များ", faith:"ယုံကြည်ခြင်းထောင့်", failsafe:"လုံခြုံမှု", contact:"ဆက်သွယ်ရန်", contactUs:"ကျွန်ုပ်တို့ကိုဆက်သွယ်ပါ", about:"အကြောင်း", support:"အကူအညီ", platform:"ပလက်ဖောင်း", tagline:"လွတ်လပ်သော • လုံခြုံမှု • SSL လုံခြုံသည် • 100% အတည်ပြုပြီး • ကိုယ်ရေးကိုယ်တာအရေးကြီးသည်" },
}

export default function LocalFooter() {
  const { language } = useLanguage()
  const d = D[language] || D.en
  return (
    <footer className="w-full bg-black/80 backdrop-blur border-t border-white/10 mt-10 py-8 px-6">
      <div className="max-w-7xl mx-auto grid grid-cols-2 md:grid-cols-5 gap-8 text-sm">
        <div>
          <h4 className="font-black text-white uppercase tracking-widest mb-3">{d.verify}</h4>
          <ul className="space-y-2 text-white/60">
            <li><Link href="/apply-verification" className="hover:text-white">{d.verification}</Link></li>
            <li><Link href="/legal/security" className="hover:text-white">{d.security}</Link></li>
            <li><Link href="/trust" className="hover:text-white">{d.trust}</Link></li>
          </ul>
        </div>
        <div>
          <h4 className="font-black text-white uppercase tracking-widest mb-3">{d.legal}</h4>
          <ul className="space-y-2 text-white/60">
            <li><Link href="/legal/terms" className="hover:text-white">{d.terms}</Link></li>
            <li><Link href="/legal/privacy" className="hover:text-white">{d.privacy}</Link></li>
            <li><Link href="/legal/legal" className="hover:text-white">{d.legalDmca}</Link></li>
          </ul>
        </div>
        <div>
          <h4 className="font-black text-white uppercase tracking-widest mb-3">{d.guarantees}</h4>
          <ul className="space-y-2 text-white/60">
            <li><Link href="/legal/guarantees" className="hover:text-white">{d.ourGuar}</Link></li>
            <li><Link href="/faith" className="hover:text-white">{d.faith}</Link></li>
            <li><Link href="/failsafe" className="hover:text-white">{d.failsafe}</Link></li>
          </ul>
        </div>
        <div>
          <h4 className="font-black text-white uppercase tracking-widest mb-3">{d.contact}</h4>
          <ul className="space-y-2 text-white/60">
            <li><Link href="/contact" className="hover:text-white">{d.contactUs}</Link></li>
            <li><Link href="/about" className="hover:text-white">{d.about}</Link></li>
            <li><Link href="/support" className="hover:text-white">{d.support}</Link></li>
          </ul>
        </div>
        <div>
          <h4 className="font-black text-white uppercase tracking-widest mb-3">{d.platform}</h4>
          <p className="text-white/40 text-xs leading-relaxed">
           {d.tagline}
          </p>
          <p className="mt-3 text-white/20 text-xs">© 2026 Sweet Social Space</p>
        </div>
      </div>
    </footer>
  )
}
