'use client'
import { useEffect, useState } from 'react'
import { useLanguage } from '@/lib/language-context'

const D: Record<string, any> = {
  en: { title:"Enable permissions to unlock your block", location:"📍 Location required", locDesc:"We need your location to show posts near you, your Block Map, and The Drop in your zip.", notif:"🔔 Notifications", notifDesc:"Get alerted when The Drop lands at 10AM and when neighbors go live near you.", enableLoc:"Enable Location", enableNotif:"Enable Notifications", skip:"Skip for now", granted:"Granted", denied:"Denied — enable in browser settings", prompt:"Tap to enable", why:"Why we ask:", why1:"• Location = shows only your zip + radius, not exact address", why2:"• Notifications = only for Drop + Live, no spam", why3:"• Faith welcome. Respect required. No shadowbans.", checking:"Checking permissions..." },
  es: { title:"Activa permisos para desbloquear tu bloque", location:"📍 Ubicación requerida", locDesc:"Necesitamos tu ubicación para mostrar posts cerca, tu Mapa y El Drop en tu zip.", notif:"🔔 Notificaciones", notifDesc:"Recibe alertas cuando El Drop llega a las 10AM y cuando vecinos salen en vivo.", enableLoc:"Activar Ubicación", enableNotif:"Activar Notificaciones", skip:"Omitir por ahora", granted:"Concedido", denied:"Denegado — activa en ajustes del navegador", prompt:"Toca para activar", why:"Por qué preguntamos:", why1:"• Ubicación = solo tu zip + radio, no dirección exacta", why2:"• Notificaciones = solo para Drop + Live, sin spam", why3:"• Fe bienvenida. Respeto requerido.", checking:"Verificando permisos..." },
  fr: { title:"Activez les permissions pour débloquer votre bloc", location:"📍 Localisation requise", locDesc:"Nous avons besoin de votre position pour afficher les posts près de vous.", notif:"🔔 Notifications", notifDesc:"Soyez alerté quand Le Drop arrive à 10H.", enableLoc:"Activer Localisation", enableNotif:"Activer Notifications", skip:"Passer", granted:"Accordé", denied:"Refusé — activez dans les paramètres", prompt:"Appuyez pour activer", why:"Pourquoi nous demandons:", why1:"• Localisation = seulement votre zip + rayon", why2:"• Notifications = seulement Drop + Live", why3:"• Foi bienvenue. Respect requis.", checking:"Vérification..." },
  de: { title:"Berechtigungen aktivieren um Block freizuschalten", location:"📍 Standort erforderlich", locDesc:"Wir brauchen deinen Standort für Posts in deiner Nähe.", notif:"🔔 Benachrichtigungen", notifDesc:"Werde benachrichtigt wenn Der Drop um 10Uhr landet.", enableLoc:"Standort Aktivieren", enableNotif:"Benachrichtigungen Aktivieren", skip:"Vorläufig überspringen", granted:"Erteilt", denied:"Verweigert — in Browsereinstellungen aktivieren", prompt:"Zum Aktivieren tippen", why:"Warum wir fragen:", why1:"• Standort = nur PLZ + Radius", why2:"• Benachrichtigungen = nur Drop + Live", why3:"• Glaube willkommen. Respekt erforderlich.", checking:"Berechtigungen prüfen..." },
  zh: { title:"启用权限以解锁你的街区", location:"📍 需要位置", locDesc:"我们需要你的位置来显示附近的帖子、街区地图和投放。", notif:"🔔 通知", notifDesc:"当投放上午10点到达时提醒你。", enableLoc:"启用位置", enableNotif:"启用通知", skip:"暂时跳过", granted:"已授予", denied:"已拒绝 — 在浏览器设置中启用", prompt:"点击启用", why:"为什么我们要请求：", why1:"• 位置 = 仅邮编 + 半径", why2:"• 通知 = 仅投放 + 直播", why3:"• 欢迎信仰。需要尊重。", checking:"正在检查权限..." },
  ja: { title:"ブロックを解除するには権限を有効にしてください", location:"📍 位置情報が必要", locDesc:"近くの投稿、ブロックマップ、ドロップを表示するために位置が必要です。", notif:"🔔 通知", notifDesc:"ドロップが午前10時に到着したときに通知します。", enableLoc:"位置情報を有効化", enableNotif:"通知を有効化", skip:"今はスキップ", granted:"許可済み", denied:"拒否 — ブラウザ設定で有効化", prompt:"タップして有効化", why:"なぜ尋ねるのか：", why1:"• 位置 = 郵便番号 + 半径のみ", why2:"• 通知 = ドロップ + ライブのみ", why3:"• 信仰歓迎。敬意必須。", checking:"権限を確認中..." },
  ko: { title:"블록을 해제하려면 권한을 활성화하세요", location:"📍 위치 필요", locDesc:"근처 게시물, 블록 맵, 드롭을 표시하려면 위치가 필요합니다.", notif:"🔔 알림", notifDesc:"드롭이 오전 10시에 도착하면 알림을 받습니다.", enableLoc:"위치 활성화", enableNotif:"알림 활성화", skip:"지금 건너뛰기", granted:"허용됨", denied:"거부됨 — 브라우저 설정에서 활성화", prompt:"탭하여 활성화", why:"왜 묻나요:", why1:"• 위치 = 우편번호 + 반경만", why2:"• 알림 = 드롭 + 라이브만", why3:"• 신앙 환영. 존중 필수.", checking:"권한 확인 중..." },
  pt: { title:"Ative permissões para desbloquear seu bloco", location:"📍 Localização necessária", locDesc:"Precisamos da sua localização para mostrar posts perto.", notif:"🔔 Notificações", notifDesc:"Seja alertado quando O Drop chega às 10H.", enableLoc:"Ativar Localização", enableNotif:"Ativar Notificações", skip:"Pular por enquanto", granted:"Concedido", denied:"Negado — ative nas configurações", prompt:"Toque para ativar", why:"Por que pedimos:", why1:"• Localização = só seu cep + raio", why2:"• Notificações = só Drop + Live", why3:"• Fé bem-vinda. Respeito obrigatório.", checking:"Verificando permissões..." },
  ru: { title:"Включите разрешения чтобы разблокировать блок", location:"📍 Требуется местоположение", locDesc:"Нам нужно местоположение для постов рядом.", notif:"🔔 Уведомления", notifDesc:"Получайте оповещения когда Дроп в 10 утра.", enableLoc:"Включить Местоположение", enableNotif:"Включить Уведомления", skip:"Пропустить пока", granted:"Разрешено", denied:"Запрещено — включите в настройках браузера", prompt:"Нажмите чтобы включить", why:"Почему мы спрашиваем:", why1:"• Местоположение = только zip + радиус", why2:"• Уведомления = только Дроп + Live", why3:"• Вера приветствуется. Уважение обязательно.", checking:"Проверка разрешений..." },
  ar: { title:"فعّل الأذونات لفتح البلوك الخاص بك", location:"📍 الموقع مطلوب", locDesc:"نحتاج موقعك لعرض المنشورات القريبة.", notif:"🔔 الإشعارات", notifDesc:"احصل على تنبيه عند وصول الإسقاط.", enableLoc:"تفعيل الموقع", enableNotif:"تفعيل الإشعارات", skip:"تخطي الآن", granted:"ممنوح", denied:"مرفوض — فعّل في إعدادات المتصفح", prompt:"اضغط للتفعيل", why:"لماذا نسأل:", why1:"• الموقع = فقط الرمز + نصف القطر", why2:"• الإشعارات = فقط الإسقاط + مباشر", why3:"• الإيمان مرحب. الاحترام مطلوب.", checking:"فحص الأذونات..." },
  hi: { title:"अपने ब्लॉक को अनलॉक करने के लिए अनुमतियाँ सक्षम करें", location:"📍 स्थान आवश्यक", locDesc:"आस-पास के पोस्ट दिखाने के लिए हमें आपका स्थान चाहिए।", notif:"🔔 सूचनाएं", notifDesc:"जब ड्रॉप सुबह 10 बजे आता है तो अलर्ट पाएं।", enableLoc:"स्थान सक्षम करें", enableNotif:"सूचनाएं सक्षम करें", skip:"अभी छोड़ें", granted:"स्वीकृत", denied:"अस्वीकृत — ब्राउज़र सेटिंग में सक्षम करें", prompt:"सक्षम करने के लिए टैप करें", why:"हम क्यों पूछते हैं:", why1:"• स्थान = केवल ज़िप + दायरा", why2:"• सूचनाएं = केवल ड्रॉप + लाइव", why3:"• विश्वास स्वागत। सम्मान आवश्यक।", checking:"अनुमतियाँ जाँच रहा है..." },
  it: { title:"Abilita permessi per sbloccare il tuo blocco", location:"📍 Posizione richiesta", locDesc:"Abbiamo bisogno della tua posizione per mostrare i post vicini.", notif:"🔔 Notifiche", notifDesc:"Ricevi avvisi quando Il Drop arriva alle 10.", enableLoc:"Abilita Posizione", enableNotif:"Abilita Notifiche", skip:"Salta per ora", granted:"Concesso", denied:"Negato — abilita nelle impostazioni", prompt:"Tocca per abilitare", why:"Perché chiediamo:", why1:"• Posizione = solo zip + raggio", why2:"• Notifiche = solo Drop + Live", why3:"• Fede benvenuta. Rispetto richiesto.", checking:"Verifica permessi..." },
  nl: { title:"Schakel machtigingen in om je blok te ontgrendelen", location:"📍 Locatie vereist", locDesc:"We hebben je locatie nodig voor posts dichtbij.", notif:"🔔 Meldingen", notifDesc:"Krijg melding wanneer De Drop om 10U landt.", enableLoc:"Locatie Inschakelen", enableNotif:"Meldingen Inschakelen", skip:"Voor nu overslaan", granted:"Toegestaan", denied:"Geweigerd — inschakelen in browserinstellingen", prompt:"Tik om in te schakelen", why:"Waarom we vragen:", why1:"• Locatie = alleen zip + straal", why2:"• Meldingen = alleen Drop + Live", why3:"• Geloof welkom. Respect vereist.", checking:"Machtigingen controleren..." },
  tl: { title:"I-enable ang permissions para ma-unlock ang block", location:"📍 Kailangan ng Lokasyon", locDesc:"Kailangan namin ang lokasyon mo para sa malapit na posts.", notif:"🔔 Notifications", notifDesc:"Ma-alert kapag dumating ang Drop ng 10AM.", enableLoc:"I-enable Lokasyon", enableNotif:"I-enable Notifications", skip:"Laktawan muna", granted:"Pinayagan", denied:"Tinanggihan — i-enable sa browser settings", prompt:"I-tap para i-enable", why:"Bakit kami nagtatanong:", why1:"• Lokasyon = zip + radius lang", why2:"• Notifications = Drop + Live lang", why3:"• Faith welcome. Respect required.", checking:"Tine-check permissions..." },
  bn: { title:"আপনার ব্লক আনলক করতে অনুমতি সক্ষম করুন", location:"📍 অবস্থান প্রয়োজন", locDesc:"কাছাকাছি পোস্ট দেখাতে আমাদের আপনার অবস্থান প্রয়োজন।", notif:"🔔 বিজ্ঞপ্তি", notifDesc:"ড্রপ সকাল 10টায় এলে সতর্কতা পান।", enableLoc:"অবস্থান সক্ষম করুন", enableNotif:"বিজ্ঞপ্তি সক্ষম করুন", skip:"এখন এড়িয়ে যান", granted:"মঞ্জুর", denied:"অস্বীকৃত — ব্রাউজার সেটিংসে সক্ষম করুন", prompt:"সক্ষম করতে ট্যাপ করুন", why:"আমরা কেন জিজ্ঞাসা করি:", why1:"• অবস্থান = শুধু জিপ + ব্যাসার্ধ", why2:"• বিজ্ঞপ্তি = শুধু ড্রপ + লাইভ", why3:"• বিশ্বাস স্বাগত। সম্মান প্রয়োজন।", checking:"অনুমতি পরীক্ষা..." },
  id: { title:"Aktifkan izin untuk membuka blok Anda", location:"📍 Lokasi diperlukan", locDesc:"Kami butuh lokasi Anda untuk menampilkan postingan dekat.", notif:"🔔 Notifikasi", notifDesc:"Dapatkan peringatan saat The Drop mendarat jam 10 pagi.", enableLoc:"Aktifkan Lokasi", enableNotif:"Aktifkan Notifikasi", skip:"Lewati dulu", granted:"Diizinkan", denied:"Ditolak — aktifkan di pengaturan browser", prompt:"Ketuk untuk aktifkan", why:"Mengapa kami bertanya:", why1:"• Lokasi = hanya zip + radius", why2:"• Notifikasi = hanya Drop + Live", why3:"• Iman diterima. Hormat diperlukan.", checking:"Memeriksa izin..." },
  vi: { title:"Bật quyền để mở khóa khối của bạn", location:"📍 Yêu cầu vị trí", locDesc:"Chúng tôi cần vị trí của bạn để hiển thị bài đăng gần.", notif:"🔔 Thông báo", notifDesc:"Nhận cảnh báo khi The Drop đến lúc 10AM.", enableLoc:"Bật Vị trí", enableNotif:"Bật Thông báo", skip:"Bỏ qua bây giờ", granted:"Đã cấp", denied:"Bị từ chối — bật trong cài đặt trình duyệt", prompt:"Nhấn để bật", why:"Tại sao chúng tôi hỏi:", why1:"• Vị trí = chỉ zip + bán kính", why2:"• Thông báo = chỉ Drop + Live", why3:"• Đức tin được chào đón. Yêu cầu tôn trọng.", checking:"Đang kiểm tra quyền..." },
  th: { title:"เปิดใช้งานสิทธิ์เพื่อปลดล็อกบล็อกของคุณ", location:"📍 ต้องการตำแหน่ง", locDesc:"เราต้องการตำแหน่งของคุณเพื่อแสดงโพสต์ใกล้ๆ", notif:"🔔 การแจ้งเตือน", notifDesc:"รับการแจ้งเตือนเมื่อ The Drop มาถึง 10โมง", enableLoc:"เปิดใช้งานตำแหน่ง", enableNotif:"เปิดใช้งานการแจ้งเตือน", skip:"ข้ามตอนนี้", granted:"ได้รับอนุญาต", denied:"ถูกปฏิเสธ — เปิดในตั้งค่าเบราว์เซอร์", prompt:"แตะเพื่อเปิดใช้งาน", why:"ทำไมเราถาม:", why1:"• ตำแหน่ง = เพียง zip + รัศมี", why2:"• การแจ้งเตือน = เพียง Drop + Live", why3:"• ยินดีต้อนรับศรัทธา ต้องเคารพ", checking:"กำลังตรวจสอบสิทธิ์..." },
  sv: { title:"Aktivera behörigheter för att låsa upp ditt block", location:"📍 Plats krävs", locDesc:"Vi behöver din plats för inlägg nära dig.", notif:"🔔 Notiser", notifDesc:"Få larm när The Drop landar 10AM.", enableLoc:"Aktivera Plats", enableNotif:"Aktivera Notiser", skip:"Hoppa över nu", granted:"Beviljad", denied:"Nekad — aktivera i webbläsarinställningar", prompt:"Tryck för att aktivera", why:"Varför vi frågar:", why1:"• Plats = endast zip + radie", why2:"• Notiser = endast Drop + Live", why3:"• Tro välkommen. Respekt krävs.", checking:"Kontrollerar behörigheter..." },
  pl: { title:"Włącz uprawnienia aby odblokować swój blok", location:"📍 Lokalizacja wymagana", locDesc:"Potrzebujemy Twojej lokalizacji dla postów w pobliżu.", notif:"🔔 Powiadomienia", notifDesc:"Dostawaj alert gdy The Drop ląduje o 10 rano.", enableLoc:"Włącz Lokalizację", enableNotif:"Włącz Powiadomienia", skip:"Pomiń na razie", granted:"Przyznane", denied:"Odmówiono — włącz w ustawieniach przeglądarki", prompt:"Dotknij aby włączyć", why:"Dlaczego pytamy:", why1:"• Lokalizacja = tylko zip + promień", why2:"• Powiadomienia = tylko Drop + Live", why3:"• Wiara mile widziana. Szacunek wymagany.", checking:"Sprawdzanie uprawnień..." },
  tr: { title:"Blokunuzu açmak için izinleri etkinleştirin", location:"📍 Konum gerekli", locDesc:"Yakınınızdaki gönderileri göstermek için konumunuza ihtiyacımız var.", notif:"🔔 Bildirimler", notifDesc:"The Drop saat 10'da geldiğinde uyarı alın.", enableLoc:"Konumu Etkinleştir", enableNotif:"Bildirimleri Etkinleştir", skip:"Şimdilik atla", granted:"Verildi", denied:"Reddedildi — tarayıcı ayarlarında etkinleştir", prompt:"Etkinleştirmek için dokun", why:"Neden soruyoruz:", why1:"• Konum = sadece zip + yarıçap", why2:"• Bildirimler = sadece Drop + Live", why3:"• İnanç hoş. Saygı şart.", checking:"İzinler kontrol ediliyor..." },
  uk: { title:"Увімкніть дозволи щоб розблокувати блок", location:"📍 Потрібне місцезнаходження", locDesc:"Нам потрібне ваше місцезнаходження для постів поруч.", notif:"🔔 Сповіщення", notifDesc:"Отримуйте сповіщення коли Дроп о 10 ранку.", enableLoc:"Увімкнути Місцезнаходження", enableNotif:"Увімкнути Сповіщення", skip:"Пропустити зараз", granted:"Надано", denied:"Відхилено — увімкніть в налаштуваннях браузера", prompt:"Натисніть щоб увімкнути", why:"Чому ми питаємо:", why1:"• Місцезнаходження = лише zip + радіус", why2:"• Сповіщення = лише Дроп + Live", why3:"• Віра вітається. Повага обов'язкова.", checking:"Перевірка дозволів..." },
  el: { title:"Ενεργοποιήστε δικαιώματα για ξεκλείδωμα block", location:"📍 Απαιτείται τοποθεσία", locDesc:"Χρειαζόμαστε την τοποθεσία σας για κοντινές αναρτήσεις.", notif:"🔔 Ειδοποιήσεις", notifDesc:"Λάβετε ειδοποίηση όταν το Drop φτάνει 10πμ.", enableLoc:"Ενεργοποίηση Τοποθεσίας", enableNotif:"Ενεργοποίηση Ειδοποιήσεων", skip:"Παράλειψη προς το παρόν", granted:"Εγκρίθηκε", denied:"Απορρίφθηκε — ενεργοποιήστε στις ρυθμίσεις", prompt:"Πατήστε για ενεργοποίηση", why:"Γιατί ρωτάμε:", why1:"• Τοποθεσία = μόνο zip + ακτίνα", why2:"• Ειδοποιήσεις = μόνο Drop + Live", why3:"• Πίστη ευπρόσδεκτη. Σεβασμός απαιτείται.", checking:"Έλεγχος δικαιωμάτων..." },
  he: { title:"הפעל הרשאות כדי לפתוח את הבלוק שלך", location:"📍 נדרש מיקום", locDesc:"אנחנו צריכים את המיקום שלך כדי להציג פוסטים קרובים.", notif:"🔔 התראות", notifDesc:"קבל התראה כשה-Drop נוחת ב-10 בבוקר.", enableLoc:"הפעל מיקום", enableNotif:"הפעל התראות", skip:"דלג לעת עתה", granted:"אושר", denied:"נדחה — הפעל בהגדרות דפדפן", prompt:"הקש כדי להפעיל", why:"למה אנחנו שואלים:", why1:"• מיקום = רק zip + רדיוס", why2:"• התראות = רק Drop + Live", why3:"• אמונה ברוכה. כבוד נדרש.", checking:"בודק הרשאות..." },
  ro: { title:"Activează permisiuni pentru a debloca blocul", location:"📍 Locație necesară", locDesc:"Avem nevoie de locația ta pentru postări din apropiere.", notif:"🔔 Notificări", notifDesc:"Primești alertă când The Drop aterizează la 10AM.", enableLoc:"Activează Locația", enableNotif:"Activează Notificările", skip:"Sari peste acum", granted:"Acordat", denied:"Refuzat — activează în setările browserului", prompt:"Atinge pentru a activa", why:"De ce întrebăm:", why1:"• Locație = doar zip + rază", why2:"• Notificări = doar Drop + Live", why3:"• Credință binevenită. Respect obligatoriu.", checking:"Verificare permisiuni..." },
  cs: { title:"Povolte oprávnění pro odemknutí bloku", location:"📍 Vyžadována poloha", locDesc:"Potřebujeme vaši polohu pro příspěvky poblíž.", notif:"🔔 Oznámení", notifDesc:"Dostaňte upozornění když Drop přistane v 10AM.", enableLoc:"Povolit Polohu", enableNotif:"Povolit Oznámení", skip:"Přeskočit prozatím", granted:"Uděleno", denied:"Odepřeno — povolte v nastavení prohlížeče", prompt:"Klepněte pro povolení", why:"Proč se ptáme:", why1:"• Poloha = pouze zip + poloměr", why2:"• Oznámení = pouze Drop + Live", why3:"• Víra vítána. Respekt vyžadován.", checking:"Kontrola oprávnění..." },
  hu: { title:"Engedélyezze a jogosultságokat blokk feloldásához", location:"📍 Hely szükséges", locDesc:"Szükségünk van a tartózkodási helyedre a közeli posztokhoz.", notif:"🔔 Értesítések", notifDesc:"Értesítést kapsz amikor A Drop 10-kor landol.", enableLoc:"Hely Engedélyezése", enableNotif:"Értesítések Engedélyezése", skip:"Kihagyás most", granted:"Megadva", denied:"Megtagadva — engedélyezd böngésző beállításokban", prompt:"Koppints az engedélyezéshez", why:"Miért kérdezzük:", why1:"• Hely = csak zip + sugár", why2:"• Értesítések = csak Drop + Live", why3:"• Hit üdvözölve. Tisztelet kötelező.", checking:"Jogosultságok ellenőrzése..." },
  fi: { title:"Ota käyttöoikeudet käyttöön blokin avaamiseksi", location:"📍 Sijainti vaaditaan", locDesc:"Tarvitsemme sijaintisi lähellä oleviin postauksiin.", notif:"🔔 Ilmoitukset", notifDesc:"Saat hälytyksen kun Drop laskeutuu klo 10.", enableLoc:"Ota Sijainti Käyttöön", enableNotif:"Ota Ilmoitukset Käyttöön", skip:"Ohita toistaiseksi", granted:"Myönnetty", denied:"Estetty — ota käyttöön selaimen asetuksissa", prompt:"Napauta ottaaksesi käyttöön", why:"Miksi kysymme:", why1:"• Sijainti = vain zip + säde", why2:"• Ilmoitukset = vain Drop + Live", why3:"• Usko tervetullut. Kunnioitus vaaditaan.", checking:"Tarkistetaan käyttöoikeuksia..." },
  no: { title:"Aktiver tillatelser for å låse opp blokken", location:"📍 Posisjon kreves", locDesc:"Vi trenger posisjonen din for innlegg i nærheten.", notif:"🔔 Varsler", notifDesc:"Få varsel når The Drop lander kl 10.", enableLoc:"Aktiver Posisjon", enableNotif:"Aktiver Varsler", skip:"Hopp over for nå", granted:"Innvilget", denied:"Nektet — aktiver i nettleserinnstillinger", prompt:"Trykk for å aktivere", why:"Hvorfor vi spør:", why1:"• Posisjon = kun zip + radius", why2:"• Varsler = kun Drop + Live", why3:"• Tro velkommen. Respekt kreves.", checking:"Sjekker tillatelser..." },
  da: { title:"Aktiver tilladelser for at låse op for din blok", location:"📍 Placering påkrævet", locDesc:"Vi har brug for din placering til opslag i nærheden.", notif:"🔔 Notifikationer", notifDesc:"Få alarm når The Drop lander kl 10.", enableLoc:"Aktiver Placering", enableNotif:"Aktiver Notifikationer", skip:"Spring over nu", granted:"Givet", denied:"Afvist — aktiver i browserindstillinger", prompt:"Tryk for at aktivere", why:"Hvorfor vi spørger:", why1:"• Placering = kun zip + radius", why2:"• Notifikationer = kun Drop + Live", why3:"• Tro velkommen. Respekt påkrævet.", checking:"Tjekker tilladelser..." },
  bg: { title:"Активирайте разрешения за отключване на блока", location:"📍 Изисква се местоположение", locDesc:"Нуждаем се от местоположението ви за близки публикации.", notif:"🔔 Известия", notifDesc:"Получавайте известие когато Drop кацне в 10 сутринта.", enableLoc:"Активирай Местоположение", enableNotif:"Активирай Известия", skip:"Пропусни засега", granted:"Разрешено", denied:"Отказано — активирайте в настройките на браузъра", prompt:"Докоснете за активиране", why:"Защо питаме:", why1:"• Местоположение = само zip + радиус", why2:"• Известия = само Drop + Live", why3:"• Вярата добре дошла. Уважение изисква.", checking:"Проверка на разрешения..." },
  hr: { title:"Omogućite dozvole za otključavanje bloka", location:"📍 Lokacija obavezna", locDesc:"Trebamo vašu lokaciju za objave u blizini.", notif:"🔔 Obavijesti", notifDesc:"Primajte obavijest kad Drop sleti u 10 ujutro.", enableLoc:"Omogući Lokaciju", enableNotif:"Omogući Obavijesti", skip:"Preskoči za sada", granted:"Odobreno", denied:"Odbijeno — omogućite u postavkama preglednika", prompt:"Dodirnite za omogućavanje", why:"Zašto pitamo:", why1:"• Lokacija = samo zip + radijus", why2:"• Obavijesti = samo Drop + Live", why3:"• Vjera dobrodošla. Poštovanje obavezno.", checking:"Provjera dozvola..." },
  sr: { title:"Омогућите дозволе за откључавање блока", location:"📍 Локација обавезна", locDesc:"Треба нам ваша локација за објаве у близини.", notif:"🔔 Обавештења", notifDesc:"Примајте обавештење кад Дроп слети у 10 ујутру.", enableLoc:"Омогући Локацију", enableNotif:"Омогући Обавештења", skip:"Прескочи за сада", granted:"Одобрено", denied:"Одбијено — омогућите у подешавањима претраживача", prompt:"Додирните за омогућавање", why:"Зашто питамо:", why1:"• Локација = само zip + радијус", why2:"• Обавештења = само Дроп + Live", why3:"• Вера добродошла. Поштовање обавезно.", checking:"Провера дозвола..." },
  sk: { title:"Povoľte oprávnenia na odomknutie bloku", location:"📍 Vyžaduje sa poloha", locDesc:"Potrebujeme vašu polohu pre príspevky v blízkosti.", notif:"🔔 Oznámenia", notifDesc:"Dostávajte upozornenie keď Drop pristane o 10 ráno.", enableLoc:"Povoliť Polohu", enableNotif:"Povoliť Oznámenia", skip:"Preskočiť teraz", granted:"Udelené", denied:"Odmietnuté — povoľte v nastaveniach prehliadača", prompt:"Klepnite pre povolenie", why:"Prečo sa pýtame:", why1:"• Poloha = iba zip + polomer", why2:"• Oznámenia = iba Drop + Live", why3:"• Viera vítaná. Rešpekt vyžadovaný.", checking:"Kontrola oprávnení..." },
  sl: { title:"Omogočite dovoljenja za odklepanje bloka", location:"📍 Lokacija obvezna", locDesc:"Potrebujemo vašo lokacijo za objave v bližini.", notif:"🔔 Obvestila", notifDesc:"Prejmite obvestilo ko Drop pristane ob 10h.", enableLoc:"Omogoči Lokacijo", enableNotif:"Omogoči Obvestila", skip:"Preskoči za zdaj", granted:"Odobreno", denied:"Zavrnjeno — omogočite v nastavitvah brskalnika", prompt:"Dotaknite za omogočanje", why:"Zakaj sprašujemo:", why1:"• Lokacija = samo zip + radij", why2:"• Obvestila = samo Drop + Live", why3:"• Vera dobrodošla. Spoštovanje zahtevano.", checking:"Preverjanje dovoljenj..." },
  et: { title:"Lubage load bloki avamiseks", location:"📍 Asukoht nõutav", locDesc:"Vajame teie asukohta lähedal olevate postituste jaoks.", notif:"🔔 Teated", notifDesc:"Saate teate kui Drop maandub kell 10.", enableLoc:"Luba Asukoht", enableNotif:"Luba Teated", skip:"Jäta vahele", granted:"Lubatud", denied:"Keelatud — lubage brauseri seadetes", prompt:"Puudutage lubamiseks", why:"Miks küsime:", why1:"• Asukoht = ainult zip + raadius", why2:"• Teated = ainult Drop + Live", why3:"• Usk teretulnud. Austus nõutud.", checking:"Lubade kontroll..." },
  lv: { title:"Iespējojiet atļaujas lai atbloķētu bloku", location:"📍 Nepieciešama atrašanās vieta", locDesc:"Mums vajag jūsu atrašanās vietu tuvumā esošiem ierakstiem.", notif:"🔔 Paziņojumi", notifDesc:"Saņemiet brīdinājumu kad Drop nolaižas 10 no rīta.", enableLoc:"Iespējot Atrašanās vietu", enableNotif:"Iespējot Paziņojumus", skip:"Izlaist pagaidām", granted:"Piešķirts", denied:"Noraidīts — iespējojiet pārlūka iestatījumos", prompt:"Pieskarieties lai iespējotu", why:"Kāpēc mēs jautājam:", why1:"• Atrašanās vieta = tikai zip + rādiuss", why2:"• Paziņojumi = tikai Drop + Live", why3:"• Ticība laipni gaidīta. Cieņa nepieciešama.", checking:"Atļauju pārbaude..." },
  lt: { title:"Įgalinkite leidimus atrakinti bloką", location:"📍 Reikalinga vieta", locDesc:"Mums reikia jūsų vietos netoliese įrašams.", notif:"🔔 Pranešimai", notifDesc:"Gaukite įspėjimą kai Drop nusileidžia 10 ryto.", enableLoc:"Įgalinti Vietą", enableNotif:"Įgalinti Pranešimus", skip:"Praleisti dabar", granted:"Suteikta", denied:"Atmesta — įgalinkite naršyklės nustatymuose", prompt:"Palieskite kad įgalintumėte", why:"Kodėl klausiame:", why1:"• Vieta = tik zip + spindulys", why2:"• Pranešimai = tik Drop + Live", why3:"• Tikėjimas laukiamas. Pagarba privaloma.", checking:"Tikrinami leidimai..." },
  be: { title:"Уключыце дазволы каб разблакаваць блок", location:"📍 Патрабуецца месцазнаходжанне", locDesc:"Нам патрэбна ваша месцазнаходжанне для пастоў побач.", notif:"🔔 Апавяшчэнні", notifDesc:"Атрымлівайце апавяшчэнне калі Дроп у 10 раніцы.", enableLoc:"Уключыць Месцазнаходжанне", enableNotif:"Уключыць Апавяшчэнні", skip:"Прапусціць зараз", granted:"Нададзена", denied:"Адхілена — уключыце ў наладах браўзэра", prompt:"Націсніце каб уключыць", why:"Чаму мы пытаем:", why1:"• Месцазнаходжанне = толькі zip + радыус", why2:"• Апавяшчэнні = толькі Дроп + Live", why3:"• Вера вітаецца. Павага абавязковая.", checking:"Праверка дазволаў..." },
  ka: { title:"ბლოკის განსაბლოკად ნებართვების ჩართვა", location:"📍 მდებარეობა საჭიროა", locDesc:"ახლომდებარე პოსტებისთვის გვჭირდება თქვენი მდებარეობა.", notif:"🔔 შეტყობინებები", notifDesc:"მიიღეთ გაფრთხილება როცა Drop 10 საათზე ჩამოდის.", enableLoc:"მდებარეობის ჩართვა", enableNotif:"შეტყობინებების ჩართვა", skip:"ახლა გამოტოვება", granted:"მინიჭებული", denied:"უარყოფილი — ჩართეთ ბრაუზერის პარამეტრებში", prompt:"შეეხე ჩასართავად", why:"რატომ ვკითხულობთ:", why1:"• მდებარეობა = მხოლოდ zip + რადიუსი", why2:"• შეტყობინებები = მხოლოდ Drop + Live", why3:"• რწმენა მისასალმებელი. პატივისცემა საჭირო.", checking:"ნებართვების შემოწმება..." },
  hy: { title:"Միացրեք թույլտվությունները բլոկը ապակողպելու համար", location:"📍 Պահանջվում է գտնվելու վայրը", notif:"🔔 Ծանուցումներ", notifDesc:"Ստացեք զգուշացում երբ Դրոպը վայրէջք է կատարում 10-ին:", enableLoc:"Միացնել Գտնվելու վայրը", enableNotif:"Միացնել Ծանուցումները", skip:"Բաց թողնել հիմա", granted:"Տրված է", denied:"Մերժված է — միացրեք դիտարկիչի կարգավորումներում", prompt:"Հպեք միացնելու համար", why:"Ինչու ենք հարցնում:", why1:"• Գտնվելու վայրը = միայն zip + շառավիղ", why2:"• Ծանուցումները = միայն Դրոպ + Live", why3:"• Հավատը ողջունելի է: Հարգանքը պարտադիր է:", checking:"Թույլտվությունների ստուգում..." },
  az: { title:"Bloku açmaq üçün icazələri aktivləşdirin", location:"📍 Məkan tələb olunur", locDesc:"Yaxınlıqdakı paylaşımlar üçün məkanınıza ehtiyacımız var.", notif:"🔔 Bildirişlər", notifDesc:"Drop saat 10-da enəndə xəbərdarlıq alın.", enableLoc:"Məkanı Aktivləşdir", enableNotif:"Bildirişləri Aktivləşdir", skip:"Hələlik keç", granted:"Verildi", denied:"Rədd edildi — brauzer parametrlərində aktivləşdirin", prompt:"Aktivləşdirmək üçün toxunun", why:"Niyə soruşuruq:", why1:"• Məkan = yalnız zip + radius", why2:"• Bildirişlər = yalnız Drop + Live", why3:"• İnanc xoşdur. Hörmət tələb olunur.", checking:"İcazələr yoxlanılır..." },
  kk: { title:"Блокты ашу үшін рұқсаттарды қосыңыз", location:"📍 Орналасқан жер қажет", locDesc:"Жақын маңдағы жазбалар үшін орналасқан жеріңіз қажет.", notif:"🔔 Хабарландырулар", notifDesc:"Drop таңғы 10-да қонғанда ескерту алыңыз.", enableLoc:"Орналасқан жерді Қосу", enableNotif:"Хабарландыруларды Қосу", skip:"Әзірге өткізіп жіберу", granted:"Берілді", denied:"Қабылданбады — браузер параметрлерінде қосыңыз", prompt:"Қосу үшін түртіңіз", why:"Неге сұраймыз:", why1:"• Орналасқан жер = тек zip + радиус", why2:"• Хабарландырулар = тек Drop + Live", why3:"• Сенім қош келеді. Құрмет қажет.", checking:"Рұқсаттар тексерілуде..." },
  ky: { title:"Блокту ачуу үчүн уруксаттарды иштетиңиз", location:"📍 Жайгашкан жер талап кылынат", locDesc:"Жакынкы посттор үчүн жайгашкан жериңиз керек.", notif:"🔔 Билдирмелер", notifDesc:"Drop саат 10до конгондо эскертүү алыңыз.", enableLoc:"Жайгашкан жерди Иштетүү", enableNotif:"Билдирмелерди Иштетүү", skip:"Азырынча өткөрүп жиберүү", granted:"Берилди", denied:"Четке кагылды — браузер жөндөөлөрүндө иштетиңиз", prompt:"Иштетүү үчүн таптап коюңуз", why:"Эмне үчүн сурайбыз:", why1:"• Жайгашкан жер = zip + радиус гана", why2:"• Билдирмелер = Drop + Live гана", why3:"• Ишеним кош келиңиз. Урмат талап кылынат.", checking:"Уруксаттар текшерилүүдө..." },
  uz: { title:"Blokni ochish uchun ruxsatlarni yoqing", location:"📍 Joylashuv talab qilinadi", locDesc:"Yaqin atrofdagi postlar uchun joylashuvingiz kerak.", notif:"🔔 Bildirishnomalar", notifDesc:"Drop soat 10 da qo'nganda ogohlantirish oling.", enableLoc:"Joylashuvni Yoqish", enableNotif:"Bildirishnomalarni Yoqish", skip:"Hozircha o'tkazib yuborish", granted:"Berildi", denied:"Rad etildi — brauzer sozlamalarida yoqing", prompt:"Yoqish uchun bosing", why:"Nega so'raymiz:", why1:"• Joylashuv = faqat zip + radius", why2:"• Bildirishnomalar = faqat Drop + Live", why3:"• Imon xush kelibsiz. Hurmat talab qilinadi.", checking:"Ruxsatlar tekshirilmoqda..." },
  tg: { title:"Иҷозатҳоро барои кушодани блок фаъол кунед", location:"📍 Ҷойгиршавӣ талаб карда мешавад", locDesc:"Барои паёмҳои наздик ҷойгиршавии шумо лозим аст.", notif:"🔔 Огоҳиҳо", notifDesc:"Вақте ки Дроп соати 10 мефарояд огоҳӣ гиред.", enableLoc:"Ҷойгиршавиро Фаъол кардан", enableNotif:"Огоҳиҳоро Фаъол кардан", skip:"Ҳоло гузаронидан", granted:"Дода шуд", denied:"Рад карда шуд — дар танзимоти браузер фаъол кунед", prompt:"Барои фаъол кардан ламс кунед", why:"Чаро мепурсем:", why1:"• Ҷойгиршавӣ = танҳо zip + радиус", why2:"• Огоҳиҳо = танҳо Дроп + Live", why3:"• Имон хуш омадед. Эҳтиром зарур аст.", checking:"Санҷиши иҷозатҳо..." },
  mn: { title:"Блокоо нээхийн тулд зөвшөөрлийг идэвхжүүлнэ үү", location:"📍 Байршил шаардлагатай", locDesc:"Ойролцоох постуудад таны байршил хэрэгтэй.", notif:"🔔 Мэдэгдэл", notifDesc:"Drop өглөө 10 цагт буух үед сэрэмжлүүлэг аваарай.", enableLoc:"Байршил Идэвхжүүлэх", enableNotif:"Мэдэгдэл Идэвхжүүлэх", skip:"Одоохондоо алгасах", granted:"Олгосон", denied:"Татгалзсан — хөтчийн тохиргоонд идэвхжүүлнэ үү", prompt:"Идэвхжүүлэхийн тулд дарна уу", why:"Яагаад асууж байна:", why1:"• Байршил = зөвхөн zip + радиус", why2:"• Мэдэгдэл = зөвхөн Drop + Live", why3:"• Итгэл тавтай морилно уу. Хүндэтгэл шаардлагатай.", checking:"Зөвшөөрөл шалгаж байна..." },
  km: { title:"បើកការអនុញ្ញាតដើម្បីដោះសោប្លុករបស់អ្នក", location:"📍 ត្រូវការទីតាំង", locDesc:"យើងត្រូវការទីតាំងរបស់អ្នកសម្រាប់ការបង្ហោះនៅក្បែរ។", notif:"🔔 การแจ้งเตือน", notifDesc:"ទទួលការជូនដំណឹងនៅពេល The Drop ចុះចតម៉ោង 10ព្រឹក។", enableLoc:"បើកទីតាំង", enableNotif:"បើកការជូនដំណឹង", skip:"រំលងឥឡូវ", granted:"បានផ្តល់", denied:"បានបដិសេធ — បើកនៅក្នុងការកំណត់កម្មវិធីរុករក", prompt:"ប៉ះដើម្បីបើក", why:"ហេតុអ្វីយើងសួរ:", why1:"• ទីតាំង = តែ zip + កាំ", why2:"• ការជូនដំណឹង = តែ Drop + Live", why3:"• សូមស្វាគមន៍ជំនឿ។ ត្រូវការការគោរព។", checking:"កំពុងពិនិត្យការអនុញ្ញាត..." },
  lo: { title:"ເປີດໃຊ້ສິດເພື່ອປົດລັອກບລັອກຂອງທ່ານ", location:"📍 ຕ້ອງການສະຖານທີ່", locDesc:"ພວກເຮົາຕ້ອງການສະຖານທີ່ຂອງທ່ານເພື່ອສະແດງໂພສໃກ້ໆ", notif:"🔔 ການແຈ້ງເຕືອນ", notifDesc:"ຮັບການແຈ້ງເຕືອນເມື່ອ The Drop ລົງຈອດ 10ໂມງ", enableLoc:"ເປີດໃຊ້ສະຖານທີ່", enableNotif:"ເປີດໃຊ້ການແຈ້ງເຕືອນ", skip:"ຂ້າມຕອນນີ້", granted:"ອະນຸຍາດແລ້ວ", denied:"ຖືກປະຕິເສດ — ເປີດໃນຕັ້ງຄ່າເບຣາວເຊີ", prompt:"ແຕະເພື່ອເປີດໃຊ້", why:"ເປັນຫຍັງພວກເຮົາຖາມ:", why1:"• ສະຖານທີ່ = ພຽງ zip + ລັດສະໝີ", why2:"• ການແຈ້ງເຕືອນ = ພຽງ Drop + Live", why3:"• ຍິນດີຕ້ອນຮັບຄວາມເຊື່ອ ຕ້ອງການເຄົາລົບ", checking:"ກຳລັງກວດສອບສິດ..." },
  my: { title:"သင့်ဘလောက်ကိုဖွင့်ရန် ခွင့်ပြုချက်များကို ဖွင့်ပါ", location:"📍 တည်နေရာ လိုအပ်သည်", locDesc:"အနီးနားရှိ ပို့စ်များအတွက် သင့်တည်နေရာ လိုအပ်ပါသည်။", notif:"🔔 အသိပေးချက်များ", notifDesc:"The Drop မနက် 10 နာရီတွင် ဆင်းသက်သောအခါ သတိပေးချက် ရယူပါ။", enableLoc:"တည်နေရာ ဖွင့်ပါ", enableNotif:"အသိပေးချက်များ ဖွင့်ပါ", skip:"ယခုကျော်ပါ", granted:"ခွင့်ပြုပြီး", denied:"ငြင်းပယ်သည် — ဘရောက်ဆာ ဆက်တင်တွင် ဖွင့်ပါ", prompt:"ဖွင့်ရန် နှိပ်ပါ", why:"ဘာကြောင့်မေးသနည်း:", why1:"• တည်နေရာ = zip + အချင်းဝက်သာ", why2:"• အသိပေးချက်များ = Drop + Live သာ", why3:"• ယုံကြည်မှု ကြိုဆိုသည်။ လေးစားမှု လိုအပ်သည်။", checking:"ခွင့်ပြုချက်များ စစ်ဆေးနေသည်..." },
  ms: { title:"Dayakan kebenaran untuk buka kunci blok anda", location:"📍 Lokasi diperlukan", locDesc:"Kami perlukan lokasi anda untuk siaran berdekatan.", notif:"🔔 Pemberitahuan", notifDesc:"Dapatkan amaran apabila The Drop mendarat jam 10 pagi.", enableLoc:"Dayakan Lokasi", enableNotif:"Dayakan Pemberitahuan", skip:"Langkau buat sekarang", granted:"Diberikan", denied:"Ditolak — dayakan dalam tetapan pelayar", prompt:"Ketik untuk dayakan", why:"Mengapa kami bertanya:", why1:"• Lokasi = hanya zip + jejari", why2:"• Pemberitahuan = hanya Drop + Live", why3:"• Kepercayaan dialu-alukan. Hormat diperlukan.", checking:"Memeriksa kebenaran..." },
  fa: { title:"مجوزها را برای باز کردن بلوک خود فعال کنید", location:"📍 موقعیت لازم است", locDesc:"برای نمایش پست‌های نزدیک به موقعیت شما نیاز داریم.", notif:"🔔 اعلان‌ها", notifDesc:"وقتی دراپ ساعت ۱۰ فرود می‌آید هشدار بگیرید.", enableLoc:"فعال‌سازی موقعیت", enableNotif:"فعال‌سازی اعلان‌ها", skip:"رد شدن برای الان", granted:"اعطا شد", denied:"رد شد — در تنظیمات مرورگر فعال کنید", prompt:"برای فعال‌سازی ضربه بزنید", why:"چرا می‌پرسیم:", why1:"• موقعیت = فقط زیپ + شعاع", why2:"• اعلان‌ها = فقط دراپ + لایو", why3:"• ایمان خوش آمد. احترام لازم است.", checking:"در حال بررسی مجوزها..." },
  ur: { title:"اپنے بلاک کو انلاک کرنے کے لیے اجازتیں فعال کریں", location:"📍 مقام درکار ہے", locDesc:"قریبی پوسٹس دکھانے کے لیے ہمیں آپ کا مقام چاہیے۔", notif:"🔔 اطلاعات", notifDesc:"جب ڈراپ صبح 10 بجے آئے تو الرٹ حاصل کریں۔", enableLoc:"مقام فعال کریں", enableNotif:"اطلاعات فعال کریں", skip:"ابھی چھوڑیں", granted:"منظور شدہ", denied:"مسترد — براؤزر سیٹنگ میں فعال کریں", prompt:"فعال کرنے کے لیے ٹیپ کریں", why:"ہم کیوں پوچھتے ہیں:", why1:"• مقام = صرف زپ + رداس", why2:"• اطلاعات = صرف ڈراپ + لائیو", why3:"• ایمان خوش آمدید۔ احترام ضروری۔", checking:"اجازتیں چیک ہو رہی ہیں..." },
}

export default function PermissionsGate() {
  const { language } = useLanguage()
  const d = D[language] || D.en
  const [locStatus, setLocStatus] = useState<'granted'|'denied'|'prompt'|'checking'>('checking')
  const [notifStatus, setNotifStatus] = useState<'granted'|'denied'|'prompt'|'checking'>('checking')
  const [show, setShow] = useState(false)

  useEffect(() => {
    const check = async () => {
      try {
        if (navigator.permissions) {
          const geo = await navigator.permissions.query({ name: 'geolocation' as any })
          setLocStatus(geo.state as any)
          geo.onchange = () => setLocStatus(geo.state as any)
        } else setLocStatus('prompt')
      } catch { setLocStatus('prompt') }

      if ('Notification' in window) {
        const n = Notification.permission
        if (n === 'granted') setNotifStatus('granted')
        else if (n === 'denied') setNotifStatus('denied')
        else setNotifStatus('prompt')
      } else setNotifStatus('granted')
    }
    check()
  }, [])

  useEffect(() => {
    // Show gate if any permission not granted
    if (locStatus === 'checking' || notifStatus === 'checking') return
    if (locStatus!== 'granted' || notifStatus!== 'granted') setShow(true)
    else setShow(false)
  }, [locStatus, notifStatus])

  const requestLocation = () => {
    navigator.geolocation.getCurrentPosition(
      () => { setLocStatus('granted'); setShow(notifStatus!== 'granted') },
      () => setLocStatus('denied'),
      { enableHighAccuracy: false, timeout: 10000 }
    )
  }

  const requestNotif = async () => {
    try {
      const r = await Notification.requestPermission()
      if (r === 'granted') setNotifStatus('granted')
      else setNotifStatus('denied')
    } catch { setNotifStatus('denied') }
  }

  if (!show) return null

  return (
    <div className="bg-black/80 backdrop-blur-2xl border border-amber-500/20 rounded-2xl p-5 space-y-4">
      <h3 className="text-white font-black text-sm tracking-wider">{d.title}</h3>

      <div className="space-y-3">
        <div className="flex justify-between items-start gap-3 bg-white/[0.05] rounded-xl p-3 border border-white/10">
          <div className="flex-1">
            <p className="text-white font-bold text-xs">{d.location}</p>
            <p className="text-white/60 text- mt-1 leading-tight">{d.locDesc}</p>
            <p className="text-amber-300 text- mt-1 font-bold">
              {locStatus === 'granted'? d.granted : locStatus === 'denied'? d.denied : d.prompt}
            </p>
          </div>
          {locStatus!== 'granted' && (
            <button onClick={requestLocation} className="bg-white text-black text- font-black px-3 py-2 rounded-full hover:bg-white/90 shrink-0">
              {d.enableLoc}
            </button>
          )}
        </div>

        <div className="flex justify-between items-start gap-3 bg-white/[0.05] rounded-xl p-3 border border-white/10">
          <div className="flex-1">
            <p className="text-white font-bold text-xs">{d.notif}</p>
            <p className="text-white/60 text- mt-1 leading-tight">{d.notifDesc}</p>
            <p className="text-amber-300 text- mt-1 font-bold">
              {notifStatus === 'granted'? d.granted : notifStatus === 'denied'? d.denied : d.prompt}
            </p>
          </div>
          {notifStatus!== 'granted' && (
            <button onClick={requestNotif} className="bg-white text-black text- font-black px-3 py-2 rounded-full hover:bg-white/90 shrink-0">
              {d.enableNotif}
            </button>
          )}
        </div>
      </div>

      <div className="bg-amber-500/10 rounded-xl p-3 border border-amber-500/20">
        <p className="text-amber-200 text- font-black">{d.why}</p>
        <p className="text-white/60 text- mt-1">{d.why1}</p>
        <p className="text-white/60 text-">{d.why2}</p>
        <p className="text-white/60 text-">{d.why3}</p>
      </div>

      <button onClick={() => setShow(false)} className="w-full bg-white/5 border border-white/10 text-white/50 text-xs py-2 rounded-xl hover:bg-white/10">
        {d.skip}
      </button>
    </div>
  )
}
