'use client'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useLanguage } from '@/lib/language-context'

const D: Record<string, any> = {
  en: { cms:"Posts CMS", search:"Search post body...", posts:"Posts", loading:"Loading...", noMatch:"No posts match this filter.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Mark draft", del:"Delete", delTitle:"Delete this post?", delDesc:"Permanently removes from feed. Audit log remains.", audit:"Audit log", noAct:"No actions yet.", empty:"Body cannot be empty", updated:"Post updated", deleted:"Post deleted", marked:"Marked" },
  es: { cms:"CMS de Posts", search:"Buscar cuerpo...", posts:"Posts", loading:"Cargando...", noMatch:"Sin coincidencias.", pub:"Publicado", draft:"Borrador", unpub:"No publicado", bot:"Bot", zip:"CP", tag:"Etiqueta", body:"Cuerpo", save:"Guardar", cancel:"Cancelar", edit:"Editar", publish:"Publicar", unpublish:"Despublicar", markDraft:"Marcar borrador", del:"Eliminar", delTitle:"Eliminar post?", delDesc:"Elimina permanente del feed.", audit:"Auditoria", noAct:"Sin acciones.", empty:"Cuerpo vacio", updated:"Post actualizado", deleted:"Post eliminado", marked:"Marcado" },
  fr: { cms:"CMS Posts", search:"Rechercher...", posts:"Posts", loading:"Chargement...", noMatch:"Aucun post.", pub:"Publie", draft:"Brouillon", unpub:"Non publie", bot:"Bot", zip:"CP", tag:"Tag", body:"Corps", save:"Enregistrer", cancel:"Annuler", edit:"Editer", publish:"Publier", unpublish:"Depublier", markDraft:"Brouillon", del:"Supprimer", delTitle:"Supprimer?", delDesc:"Supprime definitivement.", audit:"Journal", noAct:"Aucune action.", empty:"Corps vide", updated:"Post mis a jour", deleted:"Post supprime", marked:"Marque" },
  de: { cms:"Posts CMS", search:"Suche...", posts:"Posts", loading:"Laden...", noMatch:"Keine Treffer.", pub:"Veroffentlicht", draft:"Entwurf", unpub:"Unveroffentlicht", bot:"Bot", zip:"PLZ", tag:"Tag", body:"Inhalt", save:"Speichern", cancel:"Abbrechen", edit:"Bearbeiten", publish:"Veroffentlichen", unpublish:"Zuruckziehen", markDraft:"Entwurf", del:"Loschen", delTitle:"Loschen?", delDesc:"Entfernt permanent.", audit:"Protokoll", noAct:"Keine Aktionen.", empty:"Inhalt leer", updated:"Aktualisiert", deleted:"Geloscht", marked:"Markiert" },
  zh: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  ja: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  ko: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  pt: { cms:"CMS Posts", search:"Buscar corpo...", posts:"Posts", loading:"Carregando...", noMatch:"Sem correspondencia.", pub:"Publicado", draft:"Rascunho", unpub:"Nao publicado", bot:"Bot", zip:"CEP", tag:"Tag", body:"Corpo", save:"Salvar", cancel:"Cancelar", edit:"Editar", publish:"Publicar", unpublish:"Despublicar", markDraft:"Marcar rascunho", del:"Deletar", delTitle:"Deletar post?", delDesc:"Remove permanente.", audit:"Log auditoria", noAct:"Sem acoes.", empty:"Corpo vazio", updated:"Atualizado", deleted:"Deletado", marked:"Marcado" },
  ru: { cms:"CMS Posts", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  ar: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  hi: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  it: { cms:"CMS Post", search:"Cerca...", posts:"Post", loading:"Caricamento...", noMatch:"Nessun match.", pub:"Pubblicato", draft:"Bozza", unpub:"Non pubblicato", bot:"Bot", zip:"CAP", tag:"Tag", body:"Corpo", save:"Salva", cancel:"Annulla", edit:"Modifica", publish:"Pubblica", unpublish:"Ritira", markDraft:"Bozza", del:"Elimina", delTitle:"Eliminare?", delDesc:"Rimuove permanente.", audit:"Log", noAct:"Nessuna azione.", empty:"Corpo vuoto", updated:"Aggiornato", deleted:"Eliminato", marked:"Segnato" },
  nl: { cms:"Posts CMS", search:"Zoeken...", posts:"Posts", loading:"Laden...", noMatch:"Geen match.", pub:"Gepubliceerd", draft:"Concept", unpub:"Niet gepubl.", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Opslaan", cancel:"Annuleren", edit:"Bewerken", publish:"Publiceren", unpublish:"Depubliceren", markDraft:"Concept", del:"Verwijderen", delTitle:"Verwijderen?", delDesc:"Verwijdert permanent.", audit:"Log", noAct:"Geen acties.", empty:"Body leeg", updated:"Bijgewerkt", deleted:"Verwijderd", marked:"Gemarkeerd" },
  tl: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  bn: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  id: { cms:"CMS Post", search:"Cari...", posts:"Post", loading:"Memuat...", noMatch:"Tidak cocok.", pub:"Diterbitkan", draft:"Draf", unpub:"Tidak terbit", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Isi", save:"Simpan", cancel:"Batal", edit:"Edit", publish:"Terbitkan", unpublish:"Batal terbit", markDraft:"Tandai draf", del:"Hapus", delTitle:"Hapus?", delDesc:"Hapus permanen.", audit:"Log audit", noAct:"Belum ada aksi.", empty:"Isi kosong", updated:"Diperbarui", deleted:"Dihapus", marked:"Ditandai" },
  vi: { cms:"CMS Bai", search:"Tim...", posts:"Bai viet", loading:"Dang tai...", noMatch:"Khong khop.", pub:"Da dang", draft:"Nhap", unpub:"Chua dang", bot:"Bot", zip:"ZIP", tag:"The", body:"Noi dung", save:"Luu", cancel:"Huy", edit:"Sua", publish:"Dang", unpublish:"Go dang", markDraft:"Nhap", del:"Xoa", delTitle:"Xoa?", delDesc:"Xoa vinh vien.", audit:"Nhat ky", noAct:"Chua co hanh dong.", empty:"Noi dung rong", updated:"Da cap nhat", deleted:"Da xoa", marked:"Da danh dau" },
  th: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  sv: { cms:"Posts CMS", search:"Sok...", posts:"Inlagg", loading:"Laddar...", noMatch:"Ingen match.", pub:"Publicerad", draft:"Utkast", unpub:"Opublicerad", bot:"Bot", zip:"ZIP", tag:"Tagg", body:"Text", save:"Spara", cancel:"Avbryt", edit:"Redigera", publish:"Publicera", unpublish:"Avpublicera", markDraft:"Utkast", del:"Radera", delTitle:"Radera?", delDesc:"Tar bort permanent.", audit:"Logg", noAct:"Inga atgarder.", empty:"Text tom", updated:"Uppdaterad", deleted:"Raderad", marked:"Markerad" },
  pl: { cms:"CMS Postow", search:"Szukaj...", posts:"Posty", loading:"Ladowanie...", noMatch:"Brak dopasowan.", pub:"Opublikowano", draft:"Szkic", unpub:"Nieopublik.", bot:"Bot", zip:"Kod", tag:"Tag", body:"Tresc", save:"Zapisz", cancel:"Anuluj", edit:"Edytuj", publish:"Publikuj", unpublish:"Cofnij", markDraft:"Szkic", del:"Usun", delTitle:"Usunac?", delDesc:"Usuwa trwale.", audit:"Dziennik", noAct:"Brak akcji.", empty:"Tresc pusta", updated:"Zaktualizowano", deleted:"Usunieto", marked:"Oznaczono" },
  tr: { cms:"Gonderi CMS", search:"Ara...", posts:"Gonderiler", loading:"Yukleniyor...", noMatch:"Eslestirme yok.", pub:"Yayinlandi", draft:"Taslak", unpub:"Yayinlanmadi", bot:"Bot", zip:"Posta", tag:"Etiket", body:"Icerik", save:"Kaydet", cancel:"Iptal", edit:"Duzenle", publish:"Yayinla", unpublish:"Kaldir", markDraft:"Taslak", del:"Sil", delTitle:"Sil?", delDesc:"Kalici siler.", audit:"Denetim", noAct:"Islem yok.", empty:"Icerik bos", updated:"Guncellendi", deleted:"Silindi", marked:"Isaretlendi" },
  uk: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  el: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  he: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  ur: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  fa: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  ms: { cms:"CMS Pos", search:"Cari...", posts:"Pos", loading:"Memuat...", noMatch:"Tiada padanan.", pub:"Diterbit", draft:"Draf", unpub:"Tidak diterbit", bot:"Bot", zip:"Poskod", tag:"Tag", body:"Isi", save:"Simpan", cancel:"Batal", edit:"Edit", publish:"Terbit", unpublish:"Nyahterbit", markDraft:"Draf", del:"Padam", delTitle:"Padam?", delDesc:"Padam kekal.", audit:"Log audit", noAct:"Tiada tindakan.", empty:"Isi kosong", updated:"Dikemas kini", deleted:"Dipadam", marked:"Ditanda" },
  ro: { cms:"CMS Postari", search:"Cauta...", posts:"Postari", loading:"Se incarca...", noMatch:"Fara potrivire.", pub:"Publicat", draft:"Ciorna", unpub:"Nepublicat", bot:"Bot", zip:"Cod", tag:"Eticheta", body:"Corp", save:"Salveaza", cancel:"Anuleaza", edit:"Editeaza", publish:"Publica", unpublish:"Retrage", markDraft:"Ciorna", del:"Sterge", delTitle:"Sterge?", delDesc:"Sterge permanent.", audit:"Jurnal", noAct:"Nicio actiune.", empty:"Corp gol", updated:"Actualizat", deleted:"Sters", marked:"Marcat" },
  cs: { cms:"CMS Prispevku", search:"Hledat...", posts:"Prispevky", loading:"Nacitani...", noMatch:"Zadna shoda.", pub:"Publikovano", draft:"Koncept", unpub:"Nepublikovano", bot:"Bot", zip:"PSC", tag:"Stitek", body:"Text", save:"Ulozit", cancel:"Zrusit", edit:"Upravit", publish:"Publikovat", unpublish:"Zrusit publ.", markDraft:"Koncept", del:"Smazat", delTitle:"Smazat?", delDesc:"Trvale odstrani.", audit:"Audit log", noAct:"Zadne akce.", empty:"Text prazdny", updated:"Aktualizovano", deleted:"Smazano", marked:"Oznaceno" },
  hu: { cms:"Poszt CMS", search:"Keres...", posts:"Posztok", loading:"Betoltes...", noMatch:"Nincs talalat.", pub:"Kozzetett", draft:"Vazlat", unpub:"Nem kozzetett", bot:"Bot", zip:"Iranyito", tag:"Cimke", body:"Szoveg", save:"Mentes", cancel:"Megse", edit:"Szerkeszt", publish:"Kozzetesz", unpublish:"Visszavon", markDraft:"Vazlat", del:"Torles", delTitle:"Torol?", delDesc:"Veglegesen torol.", audit:"Naplo", noAct:"Nincs muvelet.", empty:"Szoveg ures", updated:"Frissitve", deleted:"Torolve", marked:"Jelolve" },
  fi: { cms:"Post CMS", search:"Hae...", posts:"Postaukset", loading:"Ladataan...", noMatch:"Ei osumia.", pub:"Julkaistu", draft:"Luonnos", unpub:"Ei julkaistu", bot:"Bot", zip:"Posti", tag:"Tagi", body:"Sisalto", save:"Tallenna", cancel:"Peruuta", edit:"Muokkaa", publish:"Julkaise", unpublish:"Peru julkaisu", markDraft:"Luonnos", del:"Poista", delTitle:"Poista?", delDesc:"Poistaa pysyvasti.", audit:"Loki", noAct:"Ei toimia.", empty:"Sisalto tyhja", updated:"Paivitetty", deleted:"Poistettu", marked:"Merkitty" },
  no: { cms:"Posts CMS", search:"Sok...", posts:"Innlegg", loading:"Laster...", noMatch:"Ingen treff.", pub:"Publisert", draft:"Utkast", unpub:"Upublisert", bot:"Bot", zip:"Postnr", tag:"Tagg", body:"Tekst", save:"Lagre", cancel:"Avbryt", edit:"Rediger", publish:"Publiser", unpublish:"Avpubliser", markDraft:"Utkast", del:"Slett", delTitle:"Slette?", delDesc:"Fjerner permanent.", audit:"Logg", noAct:"Ingen handlinger.", empty:"Tekst tom", updated:"Oppdatert", deleted:"Slettet", marked:"Markert" },
  da: { cms:"Posts CMS", search:"Sog...", posts:"Opslag", loading:"Indlaeser...", noMatch:"Ingen match.", pub:"Udgivet", draft:"Kladde", unpub:"Ikke udgivet", bot:"Bot", zip:"Postnr", tag:"Tag", body:"Tekst", save:"Gem", cancel:"Annuller", edit:"Rediger", publish:"Udgiv", unpublish:"Afpublicer", markDraft:"Kladde", del:"Slet", delTitle:"Slette?", delDesc:"Fjerner permanent.", audit:"Log", noAct:"Ingen handlinger.", empty:"Tekst tom", updated:"Opdateret", deleted:"Slettet", marked:"Markeret" },
  bg: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  hr: { cms:"CMS Objava", search:"Trazi...", posts:"Objave", loading:"Ucitavanje...", noMatch:"Nema podudaranja.", pub:"Objavljeno", draft:"Nacrt", unpub:"Neobjavljeno", bot:"Bot", zip:"Posta", tag:"Oznaka", body:"Tijelo", save:"Spremi", cancel:"Otkazi", edit:"Uredi", publish:"Objavi", unpublish:"Povuci", markDraft:"Nacrt", del:"Izbrisi", delTitle:"Izbrisati?", delDesc:"Trajno uklanja.", audit:"Dnevnik", noAct:"Nema akcija.", empty:"Tijelo prazno", updated:"Azurirano", deleted:"Izbrisano", marked:"Oznaceno" },
  sr: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  sk: { cms:"CMS Prispevkov", search:"Hladat...", posts:"Prispevky", loading:"Nacitanie...", noMatch:"Ziadna zhoda.", pub:"Publikovane", draft:"Koncept", unpub:"Nepublikovane", bot:"Bot", zip:"PSC", tag:"Znacka", body:"Text", save:"Ulozit", cancel:"Zrusit", edit:"Upravit", publish:"Publikovat", unpublish:"Zrusit publ.", markDraft:"Koncept", del:"Zmazat", delTitle:"Zmazat?", delDesc:"Trvalo odstrani.", audit:"Audit log", noAct:"Ziadne akcie.", empty:"Text prazdny", updated:"Aktualizovane", deleted:"Zmazane", marked:"Oznacene" },
  sl: { cms:"CMS Objav", search:"Isci...", posts:"Objave", loading:"Nalaganje...", noMatch:"Ni ujemanja.", pub:"Objavljeno", draft:"Osnutek", unpub:"Neobjavljeno", bot:"Bot", zip:"Posta", tag:"Oznaka", body:"Vsebina", save:"Shrani", cancel:"Preklici", edit:"Uredi", publish:"Objavi", unpublish:"Preklici obj.", markDraft:"Osnutek", del:"Izbrisi", delTitle:"Izbrisati?", delDesc:"Trajno odstrani.", audit:"Dnevnik", noAct:"Ni dejanj.", empty:"Vsebina prazna", updated:"Posodobljeno", deleted:"Izbrisano", marked:"Oznaceno" },
  et: { cms:"Postituste CMS", search:"Otsi...", posts:"Postitused", loading:"Laadimine...", noMatch:"Vastet pole.", pub:"Avaldatud", draft:"Mustand", unpub:"Avaldamata", bot:"Bot", zip:"Sihtnr", tag:"Silt", body:"Sisu", save:"Salvesta", cancel:"Katkesta", edit:"Muuda", publish:"Avalda", unpublish:"Eemalda", markDraft:"Mustand", del:"Kustuta", delTitle:"Kustutada?", delDesc:"Eemaldab jaadavalt.", audit:"Audit", noAct:"Tegevusi pole.", empty:"Sisu tuhi", updated:"Uuendatud", deleted:"Kustutatud", marked:"Margitud" },
  lv: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  lt: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  be: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  ka: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  hy: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  az: { cms:"Post CMS", search:"Axtar...", posts:"Postlar", loading:"Yuklenir...", noMatch:"Uyğunluq yoxdur.", pub:"Yayimlandi", draft:"Qaralama", unpub:"Yayimlanmadi", bot:"Bot", zip:"Indeks", tag:"Teq", body:"Metn", save:"Saxla", cancel:"Legv et", edit:"Redakte", publish:"Yayimla", unpublish:"Geri al", markDraft:"Qaralama", del:"Sil", delTitle:"Sil?", delDesc:"Həmişəlik silir.", audit:"Jurnal", noAct:"Fəaliyyət yoxdur.", empty:"Metn boş", updated:"Yeniləndi", deleted:"Silindi", marked:"İşarələndi" },
  kk: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  ky: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  uz: { cms:"Post CMS", search:"Qidirish...", posts:"Postlar", loading:"Yuklanmoqda...", noMatch:"Moslik yoq.", pub:"Nashr etildi", draft:"Qoralama", unpub:"Nashr etilmadi", bot:"Bot", zip:"Indeks", tag:"Teg", body:"Matn", save:"Saqlash", cancel:"Bekor", edit:"Tahrirlash", publish:"Nashr etish", unpublish:"Olib tashlash", markDraft:"Qoralama", del:"Ochirish", delTitle:"Ochirilsin?", delDesc:"Doimiy ochiradi.", audit:"Jurnal", noAct:"Harakat yoq.", empty:"Matn bosh", updated:"Yangilandi", deleted:"Ochirildi", marked:"Belgilandi" },
  tg: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  mn: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  km: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  lo: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  my: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
}

type AdminPostDTO = { id: string; body: string; tag: string | null; zip_code: string | null; visibility: 'published' | 'draft' | 'unpublished'; author_is_bot: boolean; author_name: string | null; user_id: string; created_at: string }
type PostVisibility = 'published' | 'draft' | 'unpublished'

async function listAdminPosts(filter: any): Promise<AdminPostDTO[]> {
  try {
    const supabase = createClient() as any
    let query = supabase.from('posts').select('*, profiles(full_name, is_bot)').order('created_at', { ascending: false }).limit(50)
    if (filter.user_id) query = query.eq('user_id', filter.user_id)
    if (filter.user_ids) query = query.in('user_id', filter.user_ids)
    if (filter.zip_code) query = query.eq('zip_code', filter.zip_code)
    if (filter.search) { const safe = String(filter.search).slice(0,80).replace(/[%_]/g,''); if (safe) query = query.ilike('body', `%${safe}%`) }
    const { data, error } = await query
    if (error) throw error
    return (data || []).map((p: any) => ({...p, author_name: p.profiles?.full_name, author_is_bot: p.profiles?.is_bot || false }))
  } catch { return [] }
}
async function updateAdminPost({ id, body, tag }: any) { const supabase = createClient() as any; const { error } = await supabase.from('posts').update({ body, tag }).eq('id', id); if (error) throw error }
async function deleteAdminPost({ id }: any) { const supabase = createClient() as any; const { error } = await supabase.from('posts').delete().eq('id', id); if (error) throw error }
async function setAdminPostVisibility({ id, visibility }: any) { const supabase = createClient() as any; const { error } = await supabase.from('posts').update({ visibility }).eq('id', id); if (error) throw error }
async function listPostAuditLog(filter: any): Promise<any[]> {
  try {
    const supabase = createClient() as any
    let q = supabase.from('post_audit_log').select('*').order('created_at', { ascending: false }).limit(filter.limit || 200)
    const { data, error } = await q
    if (error) throw error
    return data || []
  } catch { return [] }
}

function Button({ size, variant, onClick, disabled, children,...props }: any) {
  const base = 'rounded-md px-3 py-2 text-sm font-medium disabled:opacity-50'
  const variants: any = { default: 'bg-primary text-primary-foreground hover:bg-primary/90', outline: 'border border-border bg-background hover:bg-secondary', secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80', ghost: 'hover:bg-secondary', destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90' }
  return <button onClick={(e)=>{ try { onClick?.(e) } catch {} }} disabled={disabled} className={`${base} ${variants[variant] || variants.default}`} {...props}>{children}</button>
}
function Input(props: any) { return <input {...props} className="w-full rounded-xl border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary" /> }
function Textarea(props: any) { return <textarea {...props} className="w-full rounded-xl border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary" /> }
function Badge({ className, variant, children }: any) {
  const base = 'inline-flex items-center rounded-full px-2 py-0.5 text-xs font-semibold'
  const variants: any = { default: 'bg-primary/10 text-primary', secondary: 'bg-secondary text-secondary-foreground', outline: 'border border-border' }
  return <span className={`${base} ${variants[variant] || variants.default} ${className || ''}`}>{children}</span>
}
function AlertDialog({ children }: any) { return <>{children}</> }
function AlertDialogTrigger({ children }: any) { return children }
function AlertDialogContent({ children }: any) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"><div className="rounded-2xl bg-card p-6 max-w-md">{children}</div></div> }
function AlertDialogHeader({ children }: any) { return <div className="mb-4">{children}</div> }
function AlertDialogTitle({ children }: any) { return <h3 className="text-lg font-semibold">{children}</h3> }
function AlertDialogDescription({ children }: any) { return <p className="text-sm text-muted-foreground">{children}</p> }
function AlertDialogFooter({ children }: any) { return <div className="mt-4 flex justify-end gap-2">{children}</div> }
function AlertDialogCancel({ children }: any) { return <Button variant="ghost">{children}</Button> }
function AlertDialogAction({ onClick, children }: any) { return <Button variant="destructive" onClick={onClick}>{children}</Button> }
const toast = { success: (msg: string) => { try { console.log(`✓ ${msg}`) } catch {} }, error: (msg: string) => { try { console.log(`✗ ${msg}`) } catch {} } }

type Props = { title?: string; description?: string; userId?: string; userIds?: string[]; scope: string; zip_code?: string; showSearch?: boolean }
function visibilityBadge(v: PostVisibility, d: any) { if (v === 'published') return <Badge className="bg-green-600">{d.pub}</Badge>; if (v === 'draft') return <Badge variant="secondary">{d.draft}</Badge>; return <Badge variant="outline">{d.unpub}</Badge> }

export function PostsCmsPanel({ title, description, userId, userIds, scope, zip_code, showSearch = true }: Props) {
  const { language } = useLanguage()
  const d = D[language] || D.en
  const [search, setSearch] = useState('')
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editBody, setEditBody] = useState('')
  const [editTag, setEditTag] = useState('')
  const [busy, setBusy] = useState(false)
  const [posts, setPosts] = useState<AdminPostDTO[]>([])
  const [audit, setAudit] = useState<any[]>([])
  const [isLoading, setIsLoading] = useState(true)

  const refresh = async () => {
    try { setIsLoading(true); const filter = { user_id: userId, user_ids: userIds, zip_code: zip_code, search: search || undefined }; const [p, a] = await Promise.all([listAdminPosts(filter), listPostAuditLog({ user_id: userId, user_ids: userIds, limit: 200 })]); setPosts(p); setAudit(a) } catch (err: any) { toast.error(err?.message?? 'Failed to load') } finally { try { setIsLoading(false) } catch {} }
  }

  useEffect(() => { refresh() }, [search, userId, zip_code])
  const invalidate = () => { try { refresh() } catch {} }
  const beginEdit = (p: AdminPostDTO) => { setEditingId(p.id); setEditBody(p.body); setEditTag(p.tag?? '') }
  const saveEdit = async () => {
    if (!editingId) return; if (!editBody.trim()) { toast.error(d.empty); return }
    setBusy(true)
    try { await updateAdminPost({ id: editingId, body: editBody.trim(), tag: editTag.trim() }); toast.success(d.updated); setEditingId(null); invalidate() } catch (err: any) { toast.error(err?.message?? 'Failed') } finally { try { setBusy(false) } catch {} }
  }
  const onDelete = async (id: string) => { try { await deleteAdminPost({ id }); toast.success(d.deleted); if (editingId === id) setEditingId(null); invalidate() } catch (err: any) { toast.error(err?.message?? 'Failed') } }
  const onSetVis = async (id: string, visibility: PostVisibility) => { try { await setAdminPostVisibility({ id, visibility }); toast.success(`${d.marked} ${visibility}`); invalidate() } catch (err: any) { toast.error(err?.message?? 'Failed') } }

  return (
    <section className="space-y-6">
      <header><h2 className="font-display text-xl font-semibold">{title || d.cms}</h2>{description && (<p className="mt-1 text-sm text-muted-foreground">{description}</p>)}</header>
      {showSearch && (<Input placeholder={d.search} value={search} onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSearch(e.target.value)} maxLength={120} />)}
      <div className="space-y-3">
        <h3 className="text-sm font-semibold">{d.posts} ({posts.length}) {zip_code? `• ${zip_code}`:''}</h3>
        {isLoading && <p className="text-sm text-muted-foreground">{d.loading}</p>}
        {!isLoading && posts.length === 0 && (<p className="rounded-xl border border-dashed border-border p-4 text-sm text-muted-foreground">{d.noMatch}</p>)}
        {posts.map((p) => {
          const isEditing = editingId === p.id
          return (
            <article key={p.id} className="rounded-xl border border-border bg-card p-4">
              <div className="flex flex-wrap items-center gap-2">{visibilityBadge(p.visibility, d)}{p.author_is_bot && <Badge variant="outline">{d.bot}</Badge>}{p.tag && <Badge variant="outline">{p.tag}</Badge>}{p.zip_code && (<Badge variant="outline">{d.zip} {p.zip_code}</Badge>)}<span className="text-xs text-muted-foreground">{p.author_name?? p.user_id.slice(0, 8)}</span><span className="ml-auto text-xs text-muted-foreground">{new Date(p.created_at).toLocaleString()}</span></div>
              {isEditing? (
                <div className="mt-3 space-y-3"><label className="block text-sm"><span className="text-muted-foreground">{d.tag}</span><Input value={editTag} onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEditTag(e.target.value)} maxLength={40} /></label><label className="block text-sm"><span className="text-muted-foreground">{d.body} ({editBody.length}/2000)</span><Textarea value={editBody} onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setEditBody(e.target.value)} maxLength={2000} rows={6} /></label><div className="flex gap-2"><Button size="sm" onClick={saveEdit} disabled={busy}>{d.save}</Button><Button size="sm" variant="ghost" onClick={() => setEditingId(null)}>{d.cancel}</Button></div></div>
              ) : (<pre className="mt-2 whitespace-pre-wrap text-sm">{p.body}</pre>)}
              {!isEditing && (<div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => beginEdit(p)}>{d.edit}</Button>{p.visibility!== 'published' && (<Button size="sm" onClick={() => onSetVis(p.id, 'published')}>{d.publish}</Button>)}{p.visibility === 'published' && (<Button size="sm" variant="secondary" onClick={() => onSetVis(p.id, 'unpublished')}>{d.unpublish}</Button>)}{p.visibility!== 'draft' && (<Button size="sm" variant="ghost" onClick={() => onSetVis(p.id, 'draft')}>{d.markDraft}</Button>)}<AlertDialog><AlertDialogTrigger><Button size="sm" variant="destructive">{d.del}</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{d.delTitle}</AlertDialogTitle><AlertDialogDescription>{d.delDesc}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{d.cancel}</AlertDialogCancel><AlertDialogAction onClick={() => onDelete(p.id)}>{d.del}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>)}
            </article>
          )
        })}
      </div>
      <div className="space-y-3"><h3 className="text-sm font-semibold">{d.audit} ({audit.length})</h3><div className="rounded-xl border border-border bg-card">{audit.length === 0 && (<p className="p-4 text-sm text-muted-foreground">{d.noAct}</p>)}{audit.map((row) => (<div key={row.id} className="border-b border-border p-3 text-sm last:border-b-0"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className="text-xs uppercase">{row.action}</Badge><span className="font-medium">{row.actor_is_bot? '🤖 ' : ''}{row.actor_name?? row.actor_id?.slice(0, 8)?? 'system'}</span><span className="text-xs text-muted-foreground">{new Date(row.created_at).toLocaleString()}</span>{row.post_id && (<span className="ml-auto font-mono text-xs text-muted-foreground">{row.post_id.slice(0, 8)}</span>)}</div>{row.snapshot?.body && (<p className="mt-1 line-clamp-2 text-xs text-muted-foreground">"{String(row.snapshot.body).slice(0, 160)}"</p>)}</div>))}</div></div>
    </section>
  )
}
