'use client'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useLanguage } from '@/lib/language-context'

const D: Record<string, any> = {
  en: { cms:"Posts CMS", search:"Search post body...", posts:"Posts", loading:"Loading...", noMatch:"No posts match this filter.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Mark draft", del:"Delete", delTitle:"Delete this post?", delDesc:"Permanently removes from feed. Audit log remains.", audit:"Audit log", noAct:"No actions yet.", empty:"Body cannot be empty", updated:"Post updated", deleted:"Post deleted", marked:"Marked" },
  es: { cms:"CMS de Posts", search:"Buscar cuerpo...", posts:"Posts", loading:"Cargando...", noMatch:"Sin coincidencias.", pub:"Publicado", draft:"Borrador", unpub:"No publicado", bot:"Bot", zip:"CP", tag:"Etiqueta", body:"Cuerpo", save:"Guardar", cancel:"Cancelar", edit:"Editar", publish:"Publicar", unpublish:"Despublicar", markDraft:"Marcar borrador", del:"Eliminar", delTitle:"Eliminar post?", delDesc:"Elimina permanente del feed.", audit:"Auditoria", noAct:"Sin acciones.", empty:"Cuerpo vacio", updated:"Post actualizado", deleted:"Post eliminado", marked:"Marcado" },
  fr: { cms:"CMS Posts", search:"Rechercher...", posts:"Posts", loading:"Chargement...", noMatch:"Aucun post.", pub:"Publie", draft:"Brouillon", unpub:"Non publie", bot:"Bot", zip:"CP", tag:"Tag", body:"Corps", save:"Enregistrer", cancel:"Annuler", edit:"Editer", publish:"Publier", unpublish:"Depublier", markDraft:"Brouillon", del:"Supprimer", delTitle:"Supprimer?", delDesc:"Supprime definitivement.", audit:"Journal", noAct:"Aucune action.", empty:"Corps vide", updated:"Post mis a jour", deleted:"Post supprime", marked:"Marque" },
  de: { cms:"Posts CMS", search:"Suche...", posts:"Posts", loading:"Laden...", noMatch:"Keine Treffer.", pub:"Veroffentlicht", draft:"Entwurf", unpub:"Unveroffentlicht", bot:"Bot", zip:"PLZ", tag:"Tag", body:"Inhalt", save:"Speichern", cancel:"Abbrechen", edit:"Bearbeiten", publish:"Veroffentlichen", unpublish:"Zuruckziehen", markDraft:"Entwurf", del:"Loschen", delTitle:"Loschen?", delDesc:"Entfernt permanent.", audit:"Protokoll", noAct:"Keine Aktionen.", empty:"Inhalt leer", updated:"Aktualisiert", deleted:"Geloscht", marked:"Markiert" },
  zh: { cms:"帖子管理", search:"搜索正文...", posts:"帖子", loading:"加载中...", noMatch:"无匹配帖子。", pub:"已发布", draft:"草稿", unpub:"未发布", bot:"机器人", zip:"邮编", tag:"标签", body:"正文", save:"保存", cancel:"取消", edit:"编辑", publish:"发布", unpublish:"取消发布", markDraft:"标为草稿", del:"删除", delTitle:"删除此帖?", delDesc:"从信息流永久删除。", audit:"审计日志", noAct:"暂无操作。", empty:"正文不能为空", updated:"已更新", deleted:"已删除", marked:"已标记" },
  ja: { cms:"投稿CMS", search:"本文を検索...", posts:"投稿", loading:"読み込み中...", noMatch:"一致なし。", pub:"公開", draft:"下書き", unpub:"未公開", bot:"Bot", zip:"郵便", tag:"タグ", body:"本文", save:"保存", cancel:"キャンセル", edit:"編集", publish:"公開", unpublish:"非公開", markDraft:"下書き化", del:"削除", delTitle:"削除しますか?", delDesc:"フィードから永久削除。", audit:"監査ログ", noAct:"操作なし。", empty:"本文空", updated:"更新済み", deleted:"削除済み", marked:"マーク済み" },
  ko: { cms:"게시물 CMS", search:"본문 검색...", posts:"게시물", loading:"로딩중...", noMatch:"일치 없음。", pub:"게시됨", draft:"초안", unpub:"미게시", bot:"봇", zip:"우편", tag:"태그", body:"본문", save:"저장", cancel:"취소", edit:"편집", publish:"게시", unpublish:"게시 취소", markDraft:"초안 표시", del:"삭제", delTitle:"삭제할까요?", delDesc:"피드에서 영구 삭제。", audit:"감사 로그", noAct:"작업 없음。", empty:"본문 비어있음", updated:"업데이트됨", deleted:"삭제됨", marked:"표시됨" },
  pt: { cms:"CMS Posts", search:"Buscar corpo...", posts:"Posts", loading:"Carregando...", noMatch:"Sem correspondencia.", pub:"Publicado", draft:"Rascunho", unpub:"Nao publicado", bot:"Bot", zip:"CEP", tag:"Tag", body:"Corpo", save:"Salvar", cancel:"Cancelar", edit:"Editar", publish:"Publicar", unpublish:"Despublicar", markDraft:"Marcar rascunho", del:"Deletar", delTitle:"Deletar post?", delDesc:"Remove permanente.", audit:"Log auditoria", noAct:"Sem acoes.", empty:"Corpo vazio", updated:"Atualizado", deleted:"Deletado", marked:"Marcado" },
  ru: { cms:"CMS Постов", search:"Поиск...", posts:"Посты", loading:"Загрузка...", noMatch:"Нет совпадений.", pub:"Опубликовано", draft:"Черновик", unpub:"Неопубликовано", bot:"Бот", zip:"Индекс", tag:"Тег", body:"Текст", save:"Сохранить", cancel:"Отмена", edit:"Редакт", publish:"Опубликовать", unpublish:"Снять", markDraft:"В черновик", del:"Удалить", delTitle:"Удалить?", delDesc:"Удаляет навсегда.", audit:"Журнал", noAct:"Нет действий.", empty:"Текст пуст", updated:"Обновлено", deleted:"Удалено", marked:"Отмечено" },
  ar: { cms:"ادارة المنشورات", search:"بحث...", posts:"منشورات", loading:"تحميل...", noMatch:"لا تطابق.", pub:"منشور", draft:"مسودة", unpub:"غير منشور", bot:"بوت", zip:"رمز", tag:"وسم", body:"نص", save:"حفظ", cancel:"الغاء", edit:"تعديل", publish:"نشر", unpublish:"الغاء نشر", markDraft:"مسودة", del:"حذف", delTitle:"حذف؟", delDesc:"يزيل نهائيا.", audit:"سجل", noAct:"لا اجراءات.", empty:"النص فارغ", updated:"تم التحديث", deleted:"تم الحذف", marked:"تم" },
  hi: { cms:"Posts CMS", search:"खोजें...", posts:"पोस्ट", loading:"लोड हो रहा...", noMatch:"कोई मेल नहीं।", pub:"प्रकाशित", draft:"ड्राफ्ट", unpub:"अप्रकाशित", bot:"बॉट", zip:"पिन", tag:"टैग", body:"बॉडी", save:"सेव", cancel:"रद्द", edit:"एडिट", publish:"प्रकाशित", unpublish:"अप्रकाशित", markDraft:"ड्राफ्ट", del:"हटाएं", delTitle:"हटाएं?", delDesc:"फीड से हटाता है।", audit:"ऑडिट", noAct:"कोई कार्रवाई नहीं।", empty:"बॉडी खाली", updated:"अपडेट", deleted:"हटाया", marked:"चिह्नित" },
  it: { cms:"CMS Post", search:"Cerca...", posts:"Post", loading:"Caricamento...", noMatch:"Nessun match.", pub:"Pubblicato", draft:"Bozza", unpub:"Non pubblicato", bot:"Bot", zip:"CAP", tag:"Tag", body:"Corpo", save:"Salva", cancel:"Annulla", edit:"Modifica", publish:"Pubblica", unpublish:"Ritira", markDraft:"Bozza", del:"Elimina", delTitle:"Eliminare?", delDesc:"Rimuove permanente.", audit:"Log", noAct:"Nessuna azione.", empty:"Corpo vuoto", updated:"Aggiornato", deleted:"Eliminato", marked:"Segnato" },
  nl: { cms:"Posts CMS", search:"Zoeken...", posts:"Posts", loading:"Laden...", noMatch:"Geen match.", pub:"Gepubliceerd", draft:"Concept", unpub:"Niet gepubl.", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Opslaan", cancel:"Annuleren", edit:"Bewerken", publish:"Publiceren", unpublish:"Depubliceren", markDraft:"Concept", del:"Verwijderen", delTitle:"Verwijderen?", delDesc:"Verwijdert permanent.", audit:"Log", noAct:"Geen acties.", empty:"Body leeg", updated:"Bijgewerkt", deleted:"Verwijderd", marked:"Gemarkeerd" },
  tl: { cms:"Posts CMS", search:"Hanapin...", posts:"Posts", loading:"Naglo-load...", noMatch:"Walang tugma.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Mark draft", del:"Delete", delTitle:"Delete?", delDesc:"Tanggalin permanente.", audit:"Audit log", noAct:"Walang aksyon.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  bn: { cms:"Posts CMS", search:"খুজুন...", posts:"পোস্ট", loading:"লোড হচ্ছে...", noMatch:"মিল নেই।", pub:"প্রকাশিত", draft:"খসড়া", unpub:"অপ্রকাশিত", bot:"বট", zip:"জিপ", tag:"ট্যাগ", body:"বডি", save:"সেভ", cancel:"বাতিল", edit:"এডিট", publish:"প্রকাশ", unpublish:"অপ্রকাশ", markDraft:"খসড়া", del:"মুছুন", delTitle:"মুছবেন?", delDesc:"স্থায়ীভাবে মুছে।", audit:"অডিট", noAct:"কোনো কাজ নেই।", empty:"বডি খালি", updated:"আপডেট", deleted:"মুছেছে", marked:"চিহ্নিত" },
  id: { cms:"CMS Post", search:"Cari...", posts:"Post", loading:"Memuat...", noMatch:"Tidak cocok.", pub:"Diterbitkan", draft:"Draf", unpub:"Tidak terbit", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Isi", save:"Simpan", cancel:"Batal", edit:"Edit", publish:"Terbitkan", unpublish:"Batal terbit", markDraft:"Tandai draf", del:"Hapus", delTitle:"Hapus?", delDesc:"Hapus permanen.", audit:"Log audit", noAct:"Belum ada aksi.", empty:"Isi kosong", updated:"Diperbarui", deleted:"Dihapus", marked:"Ditandai" },
  vi: { cms:"CMS Bai", search:"Tim...", posts:"Bai viet", loading:"Dang tai...", noMatch:"Khong khop.", pub:"Da dang", draft:"Nhap", unpub:"Chua dang", bot:"Bot", zip:"ZIP", tag:"The", body:"Noi dung", save:"Luu", cancel:"Huy", edit:"Sua", publish:"Dang", unpublish:"Go dang", markDraft:"Nhap", del:"Xoa", delTitle:"Xoa?", delDesc:"Xoa vinh vien.", audit:"Nhat ky", noAct:"Chua co hanh dong.", empty:"Noi dung rong", updated:"Da cap nhat", deleted:"Da xoa", marked:"Da danh dau" },
  th: { cms:"CMS โพสต์", search:"ค้นหา...", posts:"โพสต์", loading:"โหลด...", noMatch:"ไม่ตรงกัน", pub:"เผยแพร่แล้ว", draft:"ฉบับร่าง", unpub:"ไม่เผยแพร่", bot:"บอท", zip:"รหัส", tag:"แท็ก", body:"เนื้อหา", save:"บันทึก", cancel:"ยกเลิก", edit:"แก้ไข", publish:"เผยแพร่", unpublish:"ยกเลิกเผยแพร่", markDraft:"ร่าง", del:"ลบ", delTitle:"ลบ?", delDesc:"ลบถาวร", audit:"บันทึก", noAct:"ยังไม่มี", empty:"เนื้อหาว่าง", updated:"อัปเดตแล้ว", deleted:"ลบแล้ว", marked:"ทำเครื่องหมาย" },
  sv: { cms:"Posts CMS", search:"Sok...", posts:"Inlagg", loading:"Laddar...", noMatch:"Ingen match.", pub:"Publicerad", draft:"Utkast", unpub:"Opublicerad", bot:"Bot", zip:"ZIP", tag:"Tagg", body:"Text", save:"Spara", cancel:"Avbryt", edit:"Redigera", publish:"Publicera", unpublish:"Avpublicera", markDraft:"Utkast", del:"Radera", delTitle:"Radera?", delDesc:"Tar bort permanent.", audit:"Logg", noAct:"Inga atgarder.", empty:"Text tom", updated:"Uppdaterad", deleted:"Raderad", marked:"Markerad" },
  pl: { cms:"CMS Postow", search:"Szukaj...", posts:"Posty", loading:"Ladowanie...", noMatch:"Brak dopasowan.", pub:"Opublikowano", draft:"Szkic", unpub:"Nieopublik.", bot:"Bot", zip:"Kod", tag:"Tag", body:"Tresc", save:"Zapisz", cancel:"Anuluj", edit:"Edytuj", publish:"Publikuj", unpublish:"Cofnij", markDraft:"Szkic", del:"Usun", delTitle:"Usunac?", delDesc:"Usuwa trwale.", audit:"Dziennik", noAct:"Brak akcji.", empty:"Tresc pusta", updated:"Zaktualizowano", deleted:"Usunieto", marked:"Oznaczono" },
  tr: { cms:"Gonderi CMS", search:"Ara...", posts:"Gonderiler", loading:"Yukleniyor...", noMatch:"Eslestirme yok.", pub:"Yayinlandi", draft:"Taslak", unpub:"Yayinlanmadi", bot:"Bot", zip:"Posta", tag:"Etiket", body:"Icerik", save:"Kaydet", cancel:"Iptal", edit:"Duzenle", publish:"Yayinla", unpublish:"Kaldir", markDraft:"Taslak", del:"Sil", delTitle:"Sil?", delDesc:"Kalıcı siler.", audit:"Denetim", noAct:"Islem yok.", empty:"Icerik bos", updated:"Guncellendi", deleted:"Silindi", marked:"Isaretlendi" },
  uk: { cms:"CMS Постив", search:"Пошук...", posts:"Пости", loading:"Завантаження...", noMatch:"Нема збігів.", pub:"Опубліковано", draft:"Чернетка", unpub:"Неопубліковано", bot:"Бот", zip:"Індекс", tag:"Тег", body:"Текст", save:"Зберегти", cancel:"Скасувати", edit:"Редагувати", publish:"Опублікувати", unpublish:"Зняти", markDraft:"Чернетка", del:"Видалити", delTitle:"Видалити?", delDesc:"Видаляє назавжди.", audit:"Журнал", noAct:"Нема дій.", empty:"Текст порожній", updated:"Оновлено", deleted:"Видалено", marked:"Позначено" },
  el: { cms:"CMS Αναρτησεων", search:"Αναζήτηση...", posts:"Αναρτήσεις", loading:"Φορτωση...", noMatch:"Καμια αντιστοιχια.", pub:"Δημοσιευμενο", draft:"Προχειρο", unpub:"Μη δημοσιευμενο", bot:"Bot", zip:"ΤΚ", tag:"Ετικετα", body:"Σωμα", save:"Αποθηκευση", cancel:"Ακυρωση", edit:"Επεξεργασια", publish:"Δημοσιευση", unpublish:"Αποδημοσιευση", markDraft:"Προχειρο", del:"Διαγραφη", delTitle:"Διαγραφη;", delDesc:"Διαγραφει μονιμα.", audit:"Αρχειο", noAct:"Καμια ενεργεια.", empty:"Σωμα κενο", updated:"Ενημερωθηκε", deleted:"Διαγραφηκε", marked:"Σημειωθηκε" },
  he: { cms:"ניהול פוסטים", search:"חיפוש...", posts:"פוסטים", loading:"טוען...", noMatch:"אין התאמה.", pub:"פורסם", draft:"טיוטה", unpub:"לא פורסם", bot:"בוט", zip:"מיקוד", tag:"תג", body:"גוף", save:"שמור", cancel:"ביטול", edit:"ערוך", publish:"פרסם", unpublish:"בטל פרסום", markDraft:"טיוטה", del:"מחק", delTitle:"למחוק?", delDesc:"מוחק לצמיתות.", audit:"יומן", noAct:"אין פעולות.", empty:"גוף ריק", updated:"עודכן", deleted:"נמחק", marked:"סומן" },
  ur: { cms:"Posts CMS", search:"تلاش...", posts:"پوسٹس", loading:"لوڈ ہو رہا...", noMatch:"کوئی مماثلت نہیں۔", pub:"شائع", draft:"مسودہ", unpub:"غیر شائع", bot:"بوٹ", zip:"زپ", tag:"ٹیگ", body:"باڈی", save:"محفوظ", cancel:"منسوخ", edit:"ترمیم", publish:"شائع", unpublish:"غیر شائع", markDraft:"مسودہ", del:"حذف", delTitle:"حذف؟", delDesc:"مستقل ہٹاتا ہے۔", audit:"آڈٹ", noAct:"کوئی کارروائی نہیں۔", empty:"باڈی خالی", updated:"اپ ڈیٹ", deleted:"حذف", marked:"نشان زد" },
  fa: { cms:"مدیریت پست", search:"جستجو...", posts:"پست ها", loading:"بارگذاری...", noMatch:"تطابقی نیست.", pub:"منتشر شده", draft:"پیش نویس", unpub:"منتشر نشده", bot:"ربات", zip:"کد پستی", tag:"برچسب", body:"متن", save:"ذخیره", cancel:"لغو", edit:"ویرایش", publish:"انتشار", unpublish:"لغو انتشار", markDraft:"پیش نویس", del:"حذف", delTitle:"حذف؟", delDesc:"برای همیشه حذف.", audit:"گزارش", noAct:"اقدامی نیست.", empty:"متن خالی", updated:"بهروز شد", deleted:"حذف شد", marked:"علامت" },
  ms: { cms:"CMS Pos", search:"Cari...", posts:"Pos", loading:"Memuat...", noMatch:"Tiada padanan.", pub:"Diterbit", draft:"Draf", unpub:"Tidak diterbit", bot:"Bot", zip:"Poskod", tag:"Tag", body:"Isi", save:"Simpan", cancel:"Batal", edit:"Edit", publish:"Terbit", unpublish:"Nyahterbit", markDraft:"Draf", del:"Padam", delTitle:"Padam?", delDesc:"Padam kekal.", audit:"Log audit", noAct:"Tiada tindakan.", empty:"Isi kosong", updated:"Dikemas kini", deleted:"Dipadam", marked:"Ditanda" },
  ro: { cms:"CMS Postari", search:"Cauta...", posts:"Postari", loading:"Se incarca...", noMatch:"Fara potrivire.", pub:"Publicat", draft:"Ciorna", unpub:"Nepublicat", bot:"Bot", zip:"Cod", tag:"Eticheta", body:"Corp", save:"Salveaza", cancel:"Anuleaza", edit:"Editeaza", publish:"Publica", unpublish:"Retrage", markDraft:"Ciorna", del:"Sterge", delTitle:"Sterge?", delDesc:"Sterge permanent.", audit:"Jurnal", noAct:"Nicio actiune.", empty:"Corp gol", updated:"Actualizat", deleted:"Sters", marked:"Marcat" },
  cs: { cms:"CMS Prispevku", search:"Hledat...", posts:"Prispevky", loading:"Nacitani...", noMatch:"Zadna shoda.", pub:"Publikovano", draft:"Koncept", unpub:"Nepublikovano", bot:"Bot", zip:"PSC", tag:"Stitek", body:"Text", save:"Ulozit", cancel:"Zrusit", edit:"Upravit", publish:"Publikovat", unpublish:"Zrusit publ.", markDraft:"Koncept", del:"Smazat", delTitle:"Smazat?", delDesc:"Trvale odstrani.", audit:"Audit log", noAct:"Zadne akce.", empty:"Text prazdny", updated:"Aktualizovano", deleted:"Smazano", marked:"Oznaceno" },
  hu: { cms:"Poszt CMS", search:"Keres...", posts:"Posztok", loading:"Betoltes...", noMatch:"Nincs talalat.", pub:"Kozzetett", draft:"Vazlat", unpub:"Nem kozzetett", bot:"Bot", zip:"Iranyito", tag:"Cimke", body:"Szoveg", save:"Mentes", cancel:"Megse", edit:"Szerkeszt", publish:"Kozzetesz", unpublish:"Visszavon", markDraft:"Vazlat", del:"Torles", delTitle:"Torol?", delDesc:"Veglegesen torol.", audit:"Naplo", noAct:"Nincs muvelet.", empty:"Szoveg ures", updated:"Frissitve", deleted:"Torolve", marked:"Jelolve" },
  fi: { cms:"Post CMS", search:"Hae...", posts:"Postaukset", loading:"Ladataan...", noMatch:"Ei osumia.", pub:"Julkaistu", draft:"Luonnos", unpub:"Ei julkaistu", bot:"Bot", zip:"Posti", tag:"Tagi", body:"Sisalto", save:"Tallenna", cancel:"Peruuta", edit:"Muokkaa", publish:"Julkaise", unpublish:"Peru julkaisu", markDraft:"Luonnos", del:"Poista", delTitle:"Poista?", delDesc:"Poistaa pysyvasti.", audit:"Loki", noAct:"Ei toimia.", empty:"Sisalto tyhja", updated:"Paivitetty", deleted:"Poistettu", marked:"Merkitty" },
  no: { cms:"Posts CMS", search:"Sok...", posts:"Innlegg", loading:"Laster...", noMatch:"Ingen treff.", pub:"Publisert", draft:"Utkast", unpub:"Upublisert", bot:"Bot", zip:"Postnr", tag:"Tagg", body:"Tekst", save:"Lagre", cancel:"Avbryt", edit:"Rediger", publish:"Publiser", unpublish:"Avpubliser", markDraft:"Utkast", del:"Slett", delTitle:"Slette?", delDesc:"Fjerner permanent.", audit:"Logg", noAct:"Ingen handlinger.", empty:"Tekst tom", updated:"Oppdatert", deleted:"Slettet", marked:"Markert" },
  da: { cms:"Posts CMS", search:"Sog...", posts:"Opslag", loading:"Indlaeser...", noMatch:"Ingen match.", pub:"Udgivet", draft:"Kladde", unpub:"Ikke udgivet", bot:"Bot", zip:"Postnr", tag:"Tag", body:"Tekst", save:"Gem", cancel:"Annuller", edit:"Rediger", publish:"Udgiv", unpublish:"Afpublicer", markDraft:"Kladde", del:"Slet", delTitle:"Slette?", delDesc:"Fjerner permanent.", audit:"Log", noAct:"Ingen handlinger.", empty:"Tekst tom", updated:"Opdateret", deleted:"Slettet", marked:"Markeret" },
  bg: { cms:"CMS Публикации", search:"Търси...", posts:"Публикации", loading:"Зареждане...", noMatch:"Няма съвпадение.", pub:"Публикувано", draft:"Чернова", unpub:"Непубликувано", bot:"Бот", zip:"Код", tag:"Етикет", body:"Тяло", save:"Запази", cancel:"Отказ", edit:"Редактирай", publish:"Публикувай", unpublish:"Свали", markDraft:"Чернова", del:"Изтрий", delTitle:"Изтриване?", delDesc:"Изтрива за постоянно.", audit:"Дневник", noAct:"Няма действия.", empty:"Тяло празно", updated:"Обновено", deleted:"Изтрито", marked:"Маркирано" },
  hr: { cms:"CMS Objava", search:"Trazi...", posts:"Objave", loading:"Ucitavanje...", noMatch:"Nema podudaranja.", pub:"Objavljeno", draft:"Nacrt", unpub:"Neobjavljeno", bot:"Bot", zip:"Posta", tag:"Oznaka", body:"Tijelo", save:"Spremi", cancel:"Otkazi", edit:"Uredi", publish:"Objavi", unpublish:"Povuci", markDraft:"Nacrt", del:"Izbrisi", delTitle:"Izbrisati?", delDesc:"Trajno uklanja.", audit:"Dnevnik", noAct:"Nema akcija.", empty:"Tijelo prazno", updated:"Azurirano", deleted:"Izbrisano", marked:"Oznaceno" },
  sr: { cms:"CMS Објава", search:"Тражи...", posts:"Објаве", loading:"Учитавање...", noMatch:"Нема поклапања.", pub:"Објављено", draft:"Нацрт", unpub:"Необјављено", bot:"Бот", zip:"Пошта", tag:"Ознака", body:"Тело", save:"Сачувај", cancel:"Откажи", edit:"Уреди", publish:"Објави", unpublish:"Повуци", markDraft:"Нацрт", del:"Обриши", delTitle:"Обрисати?", delDesc:"Трајно уклања.", audit:"Дневник", noAct:"Нема акција.", empty:"Тело празно", updated:"Ажурирано", deleted:"Обрисано", marked:"Означено" },
  sk: { cms:"CMS Prispevkov", search:"Hladat...", posts:"Prispevky", loading:"Nacitanie...", noMatch:"Ziadna zhoda.", pub:"Publikovane", draft:"Koncept", unpub:"Nepublikovane", bot:"Bot", zip:"PSC", tag:"Znacka", body:"Text", save:"Ulozit", cancel:"Zrusit", edit:"Upravit", publish:"Publikovat", unpublish:"Zrusit publ.", markDraft:"Koncept", del:"Zmazat", delTitle:"Zmazat?", delDesc:"Trvalo odstrani.", audit:"Audit log", noAct:"Ziadne akcie.", empty:"Text prazdny", updated:"Aktualizovane", deleted:"Zmazane", marked:"Oznacene" },
  sl: { cms:"CMS Objav", search:"Isci...", posts:"Objave", loading:"Nalaganje...", noMatch:"Ni ujemanja.", pub:"Objavljeno", draft:"Osnutek", unpub:"Neobjavljeno", bot:"Bot", zip:"Posta", tag:"Oznaka", body:"Vsebina", save:"Shrani", cancel:"Preklici", edit:"Uredi", publish:"Objavi", unpublish:"Preklici obj.", markDraft:"Osnutek", del:"Izbrisi", delTitle:"Izbrisati?", delDesc:"Trajno odstrani.", audit:"Dnevnik", noAct:"Ni dejanj.", empty:"Vsebina prazna", updated:"Posodobljeno", deleted:"Izbrisano", marked:"Oznaceno" },
  et: { cms:"Postituste CMS", search:"Otsi...", posts:"Postitused", loading:"Laadimine...", noMatch:"Vastet pole.", pub:"Avaldatud", draft:"Mustand", unpub:"Avaldamata", bot:"Bot", zip:"Sihtnr", tag:"Silt", body:"Sisu", save:"Salvesta", cancel:"Katkesta", edit:"Muuda", publish:"Avalda", unpublish:"Eemalda", markDraft:"Mustand", del:"Kustuta", delTitle:"Kustutada?", delDesc:"Eemaldab jaadavalt.", audit:"Audit", noAct:"Tegevusi pole.", empty:"Sisu tuhi", updated:"Uuendatud", deleted:"Kustutatud", marked:"Margitud" },
  lv: { cms:"Ierakstu CMS", search:"Meklet...", posts:"Ieraksti", loading:"Ielade...", noMatch:"Nav atbilstibas.", pub:"Publicets", draft:"Melnraksts", unpub:"Nepublicets", bot:"Bots", zip:"Indekss", tag:"Tags", body:"Saturs", save:"Saglabat", cancel:"Atcelt", edit:"Reditget", publish:"Publicet", unpublish:"Atpublicet", markDraft:"Melnraksts", del:"Dzest", delTitle:"Dzest?", delDesc:"Dzest pastavigi.", audit:"Zurnals", noAct:"Nav darbibas.", empty:"Saturs tukss", updated:"Atjauninats", deleted:"Dzests", marked:"Atzimets" },
  lt: { cms:"Irasu CMS", search:"Ieskoti...", posts:"Irasai", loading:"Kraunama...", noMatch:"Atitikmenu nera.", pub:"Paskelbta", draft:"Juodrastis", unpub:"Nepaskelbta", bot:"Botas", zip:"Kod", tag:"Zyma", body:"Turinys", save:"Issaugoti", cancel:"Atsaukti", edit:"Redaguoti", publish:"Paskelbti", unpublish:"Atpaskelbti", markDraft:"Juodrastis", del:"Istrinti", delTitle:"Istrinti?", delDesc:"Pasalinama visam.", audit:"Zurnalas", noAct:"Veiksmu nera.", empty:"Turinys tuscias", updated:"Atnaujinta", deleted:"Istrinta", marked:"Pazymeta" },
  be: { cms:"CMS Постаў", search:"Пошук...", posts:"Посты", loading:"Загрузка...", noMatch:"Супадзенняў няма.", pub:"Апублікавана", draft:"Чарнавік", unpub:"Неапублікавана", bot:"Бот", zip:"Індэкс", tag:"Тэг", body:"Тэкст", save:"Захаваць", cancel:"Скасаваць", edit:"Рэдагаваць", publish:"Апублікаваць", unpublish:"Зняць", markDraft:"Чарнавік", del:"Выдаліць", delTitle:"Выдаліць?", delDesc:"Выдаляе назаўжды.", audit:"Журнал", noAct:"Дзеянняў няма.", empty:"Тэкст пусты", updated:"Абноўлена", deleted:"Выдалена", marked:"Пазначана" },
  ka: { cms:"პოსტების CMS", search:"ძიება...", posts:"პოსტები", loading:"იტვირთება...", noMatch:"დამთხვევა არ არის.", pub:"გამოქვეყნებული", draft:"მონახაზი", unpub:"გამოუქვეყნებელი", bot:"ბოტი", zip:"ინდექსი", tag:"ტეგი", body:"ტექსტი", save:"შენახვა", cancel:"გაუქმება", edit:"რედაქტირება", publish:"გამოქვეყნება", unpublish:"მოხსნა", markDraft:"მონახაზი", del:"წაშლა", delTitle:"წაშლა?", delDesc:"სამუდამოდ შლის.", audit:"ჟურნალი", noAct:"მოქმედება არ არის.", empty:"ტექსტი ცარიელი", updated:"განახლდა", deleted:"წაიშალა", marked:"მონიშნული" },
  hy: { cms:"Posts CMS", search:"Search...", posts:"Posts", loading:"Loading...", noMatch:"No match.", pub:"Published", draft:"Draft", unpub:"Unpublished", bot:"Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"Save", cancel:"Cancel", edit:"Edit", publish:"Publish", unpublish:"Unpublish", markDraft:"Draft", del:"Delete", delTitle:"Delete?", delDesc:"Removes permanently.", audit:"Audit log", noAct:"No actions.", empty:"Body empty", updated:"Updated", deleted:"Deleted", marked:"Marked" },
  az: { cms:"Post CMS", search:"Axtar...", posts:"Postlar", loading:"Yuklenir...", noMatch:"Uyğunluq yoxdur.", pub:"Yayimlandi", draft:"Qaralama", unpub:"Yayimlanmadi", bot:"Bot", zip:"Indeks", tag:"Teq", body:"Metn", save:"Saxla", cancel:"Legv et", edit:"Redakte", publish:"Yayimla", unpublish:"Geri al", markDraft:"Qaralama", del:"Sil", delTitle:"Sil?", delDesc:"Həmişəlik silir.", audit:"Jurnal", noAct:"Fəaliyyət yoxdur.", empty:"Metn boş", updated:"Yeniləndi", deleted:"Silindi", marked:"İşarələndi" },
  kk: { cms:"Post CMS", search:"Izdeu...", posts:"Posttar", loading:"Juktelude...", noMatch:"Saiykestik jok.", pub:"Jariyalandi", draft:"Joba", unpub:"Jariyalanbadi", bot:"Bot", zip:"Indeks", tag:"Teg", body:"Matin", save:"Saqtau", cancel:"Boldyrmau", edit:"Redaktirlau", publish:"Jariyalau", unpublish:"Alip tastau", markDraft:"Joba", del:"Oshiru", delTitle:"Oshiru?", delDesc:"Mangi oshiredi.", audit:"Jurnal", noAct:"Areket jok.", empty:"Matin bos", updated:"Jangartyldy", deleted:"Oshirildi", marked:"Belgilen" },
  ky: { cms:"Post CMS", search:"Izdoo...", posts:"Posttor", loading:"Juktoluu...", noMatch:"Dal keluu jok.", pub:"Jaryyalandi", draft:"Dolboor", unpub:"Jaryyalanbadi", bot:"Bot", zip:"Indeks", tag:"Teg", body:"Tekst", save:"Saqtash", cancel:"Jokko chygaru", edit:"Ondoo", publish:"Jaryyala", unpublish:"Alip saluu", markDraft:"Dolboor", del:"Ochuruu", delTitle:"Ochuruu?", delDesc:"Bi-rotolo ochurot.", audit:"Jurnal", noAct:"Araket jok.", empty:"Tekst bosh", updated:"Janylandy", deleted:"Ochuruldu", marked:"Belgilen" },
  uz: { cms:"Post CMS", search:"Qidirish...", posts:"Postlar", loading:"Yuklanmoqda...", noMatch:"Moslik yoq.", pub:"Nashr etildi", draft:"Qoralama", unpub:"Nashr etilmadi", bot:"Bot", zip:"Indeks", tag:"Teg", body:"Matn", save:"Saqlash", cancel:"Bekor", edit:"Tahrirlash", publish:"Nashr etish", unpublish:"Olib tashlash", markDraft:"Qoralama", del:"Ochirish", delTitle:"Ochirilsin?", delDesc:"Doimiy ochiradi.", audit:"Jurnal", noAct:"Harakat yoq.", empty:"Matn bosh", updated:"Yangilandi", deleted:"Ochirildi", marked:"Belgilandi" },
  tg: { cms:"CMS Пост", search:"Чустучу...", posts:"Постхо", loading:"Боркунӣ...", noMatch:"Мутобиқат нест.", pub:"Нашр шуд", draft:"Пешнавис", unpub:"Нашр нашудааст", bot:"Бот", zip:"Индекс", tag:"Тег", body:"Матн", save:"Захира", cancel:"Бекор", edit:"Таҳрир", publish:"Нашр", unpublish:"Бозхонд", markDraft:"Пешнавис", del:"Ҳазф", delTitle:"Ҳазф?", delDesc:"Доимӣ ҳазф.", audit:"Журнал", noAct:"Амале нест.", empty:"Матн холӣ", updated:"Нав шуд", deleted:"Ҳазф шуд", marked:"Нишон" },
  mn: { cms:"Post CMS", search:"Haiх...", posts:"Postууд", loading:"Achaalj baina...", noMatch:"Taarahgui.", pub:"Niitlegdsen", draft:"Noorog", unpub:"Niitleegdeegui", bot:"Bot", zip:"Zip", tag:"Tag", body:"Text", save:"Hadgalah", cancel:"Tsutslah", edit:"Zasah", publish:"Niitleh", unpublish:"Tat", markDraft:"Noorog", del:"Ustgah", delTitle:"Ustgah uu?", delDesc:"Bainga ustgana.", audit:"Log", noAct:"Uildel baihgui.", empty:"Text hooson", updated:"Shinechlegdlee", deleted:"Ustgasan", marked:"Temdeglesen" },
  km: { cms:"CMS Post", search:"ស្វែងរក...", posts:"Post", loading:"កំពុងផ្ទុក...", noMatch:"គ្មានការផ្គូផ្គង។", pub:"បានផ្សាយ", draft:"ព្រាង", unpub:"មិនបានផ្សាយ", bot:"Bot", zip:"ZIP", tag:"Tag", body:"តួ", save:"រក្សាទុក", cancel:"បោះបង់", edit:"កែ", publish:"ផ្សាយ", unpublish:"ដកផ្សាយ", markDraft:"ព្រាង", del:"លុប", delTitle:"លុប?", delDesc:"លុបជាអចិន្ត្រៃយ៍។", audit:"កំណត់ហេតុ", noAct:"គ្មានសកម្មភាព។", empty:"តួទទេ", updated:"បានអាប់ដេត", deleted:"បានលុប", marked:"បានសម្គាល់" },
  lo: { cms:"CMS Post", search:"ຄົ້ນຫາ...", posts:"Post", loading:"ກຳລັງໂຫຼດ...", noMatch:"ບໍ່ມີການຈັບຄູ່。", pub:"ເຜີຍແຜ່ແລ້ວ", draft:"ສະບັບຮ່າງ", unpub:"ບໍ່ໄດ້ເຜີຍແຜ່", bot:"Bot", zip:"ZIP", tag:"ແທັກ", body:"ເນື້ອຫາ", save:"ບັນທຶກ", cancel:"ຍົກເລີກ", edit:"ແກ້ໄຂ", publish:"ເຜີຍແຜ່", unpublish:"ຍົກເລີກເຜີຍແຜ່", markDraft:"ຮ່າງ", del:"ລຶບ", delTitle:"ລຶບ?", delDesc:"ລຶບຖາວອນ。", audit:"ບັນທຶກ", noAct:"ບໍ່ມີການກະທຳ。", empty:"ເນື້ອຫາຫວ່າງ", updated:"ອັບເດແລ້ວ", deleted:"ລຶບແລ້ວ", marked:"ໝາຍໄວ້" },
  my: { cms:"Post CMS", search:"ရှာရန်...", posts:"Post", loading:"တင်နေသည်...", noMatch:"ကိုက်ညီမှုမရှိ။", pub:"ထုတ်ဝေပြီး", draft:"မူကြမ်း", unpub:"မထုတ်ဝေရ", bot:"Bot", zip:"ZIP", tag:"Tag", body:"ကိုယ်ထည်", save:"သိမ်းမည်", cancel:"ပယ်ဖျက်", edit:"တည်းဖြတ်", publish:"ထုတ်ဝေ", unpublish:"ထုတ်ဝေမှုဖျက်", markDraft:"မူကြမ်း", del:"ဖျက်", delTitle:"ဖျက်မလား?", delDesc:"အမြဲတမ်းဖျက်သည်။", audit:"မှတ်တမ်း", noAct:"လုပ်ဆောင်ချက်မရှိ။", empty:"ကိုယ်ထည်ဗလာ", updated:"အပ်ဒိတ်လုပ်ပြီး", deleted:"ဖျက်ပြီး", marked:"အမှတ်အသားပြု" },
}

type AdminPostDTO = { id: string; body: string; tag: string | null; zip_code: string | null; visibility: 'published' | 'draft' | 'unpublished'; author_is_bot: boolean; author_name: string | null; user_id: string; created_at: string }
type PostVisibility = 'published' | 'draft' | 'unpublished'

async function listAdminPosts(filter: any): Promise<AdminPostDTO[]> {
  try {
    const supabase = createClient() as any
    let query = supabase.from('posts').select('*, profiles(full_name, is_bot)').order('created_at', { ascending: false }).limit(50)
    if (filter.user_id) query = query.eq('user_id', filter.user_id)
    if (filter.user_ids) query = query.in('user_id', filter.user_ids)
    if (filter.zip_code) query = query.eq('zip_code', filter.zip_code)
    if (filter.search) { const safe = String(filter.search).slice(0,80).replace(/[%_]/g,''); if (safe) query = query.ilike('body', `%${safe}%`) }
    const { data, error } = await query
    if (error) throw error
    return (data || []).map((p: any) => ({...p, author_name: p.profiles?.full_name, author_is_bot: p.profiles?.is_bot || false }))
  } catch { return [] }
}
async function updateAdminPost({ id, body, tag }: any) { const supabase = createClient() as any; const { error } = await supabase.from('posts').update({ body, tag }).eq('id', id); if (error) throw error }
async function deleteAdminPost({ id }: any) { const supabase = createClient() as any; const { error } = await supabase.from('posts').delete().eq('id', id); if (error) throw error }
async function setAdminPostVisibility({ id, visibility }: any) { const supabase = createClient() as any; const { error } = await supabase.from('posts').update({ visibility }).eq('id', id); if (error) throw error }
async function listPostAuditLog(filter: any): Promise<any[]> {
  try {
    const supabase = createClient() as any
    let q = supabase.from('post_audit_log').select('*').order('created_at', { ascending: false }).limit(filter.limit || 200)
    const { data, error } = await q
    if (error) throw error
    return data || []
  } catch { return [] }
}

function Button({ size, variant, onClick, disabled, children,...props }: any) {
  const base = 'rounded-md px-3 py-2 text-sm font-medium disabled:opacity-50'
  const variants: any = { default: 'bg-primary text-primary-foreground hover:bg-primary/90', outline: 'border border-border bg-background hover:bg-secondary', secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80', ghost: 'hover:bg-secondary', destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90' }
  return <button onClick={(e)=>{ try { onClick?.(e) } catch {} }} disabled={disabled} className={`${base} ${variants[variant] || variants.default}`} {...props}>{children}</button>
}
function Input(props: any) { return <input {...props} className="w-full rounded-xl border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary" /> }
function Textarea(props: any) { return <textarea {...props} className="w-full rounded-xl border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary" /> }
function Badge({ className, variant, children }: any) {
  const base = 'inline-flex items-center rounded-full px-2 py-0.5 text-xs font-semibold'
  const variants: any = { default: 'bg-primary/10 text-primary', secondary: 'bg-secondary text-secondary-foreground', outline: 'border border-border' }
  return <span className={`${base} ${variants[variant] || variants.default} ${className || ''}`}>{children}</span>
}
function AlertDialog({ children }: any) { return <>{children}</> }
function AlertDialogTrigger({ children }: any) { return children }
function AlertDialogContent({ children }: any) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"><div className="rounded-2xl bg-card p-6 max-w-md">{children}</div></div> }
function AlertDialogHeader({ children }: any) { return <div className="mb-4">{children}</div> }
function AlertDialogTitle({ children }: any) { return <h3 className="text-lg font-semibold">{children}</h3> }
function AlertDialogDescription({ children }: any) { return <p className="text-sm text-muted-foreground">{children}</p> }
function AlertDialogFooter({ children }: any) { return <div className="mt-4 flex justify-end gap-2">{children}</div> }
function AlertDialogCancel({ children }: any) { return <Button variant="ghost">{children}</Button> }
function AlertDialogAction({ onClick, children }: any) { return <Button variant="destructive" onClick={onClick}>{children}</Button> }
const toast = { success: (msg: string) => { try { console.log(`✓ ${msg}`) } catch {} }, error: (msg: string) => { try { console.log(`✗ ${msg}`) } catch {} } }

type Props = { title?: string; description?: string; userId?: string; userIds?: string[]; scope: string; zip_code?: string; showSearch?: boolean }
function visibilityBadge(v: PostVisibility, d: any) { if (v === 'published') return <Badge className="bg-green-600">{d.pub}</Badge>; if (v === 'draft') return <Badge variant="secondary">{d.draft}</Badge>; return <Badge variant="outline">{d.unpub}</Badge> }

export function PostsCmsPanel({ title, description, userId, userIds, scope, zip_code, showSearch = true }: Props) {
  const { language } = useLanguage()
  const d = D[language] || D.en
  const [search, setSearch] = useState('')
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editBody, setEditBody] = useState('')
  const [editTag, setEditTag] = useState('')
  const [busy, setBusy] = useState(false)
  const [posts, setPosts] = useState<AdminPostDTO[]>([])
  const [audit, setAudit] = useState<any[]>([])
  const [isLoading, setIsLoading] = useState(true)

  const refresh = async () => {
    try { setIsLoading(true); const filter = { user_id: userId, user_ids: userIds, zip_code: zip_code, search: search || undefined }; const [p, a] = await Promise.all([listAdminPosts(filter), listPostAuditLog({ user_id: userId, user_ids: userIds, limit: 200 })]); setPosts(p); setAudit(a) } catch (err: any) { toast.error(err?.message?? 'Failed to load') } finally { try { setIsLoading(false) } catch {} }
  }

  useEffect(() => { refresh() }, [search, userId, zip_code])
  const invalidate = () => { try { refresh() } catch {} }
  const beginEdit = (p: AdminPostDTO) => { setEditingId(p.id); setEditBody(p.body); setEditTag(p.tag?? '') }
  const saveEdit = async () => {
    if (!editingId) return; if (!editBody.trim()) { toast.error(d.empty); return }
    setBusy(true)
    try { await updateAdminPost({ id: editingId, body: editBody.trim(), tag: editTag.trim() }); toast.success(d.updated); setEditingId(null); invalidate() } catch (err: any) { toast.error(err?.message?? 'Failed') } finally { try { setBusy(false) } catch {} }
  }
  const onDelete = async (id: string) => { try { await deleteAdminPost({ id }); toast.success(d.deleted); if (editingId === id) setEditingId(null); invalidate() } catch (err: any) { toast.error(err?.message?? 'Failed') } }
  const onSetVis = async (id: string, visibility: PostVisibility) => { try { await setAdminPostVisibility({ id, visibility }); toast.success(`${d.marked} ${visibility}`); invalidate() } catch (err: any) { toast.error(err?.message?? 'Failed') } }

  return (
    <section className="space-y-6">
      <header><h2 className="font-display text-xl font-semibold">{title || d.cms}</h2>{description && (<p className="mt-1 text-sm text-muted-foreground">{description}</p>)}</header>
      {showSearch && (<Input placeholder={d.search} value={search} onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSearch(e.target.value)} maxLength={120} />)}
      <div className="space-y-3">
        <h3 className="text-sm font-semibold">{d.posts} ({posts.length}) {zip_code? `• ${zip_code}`:''}</h3>
        {isLoading && <p className="text-sm text-muted-foreground">{d.loading}</p>}
        {!isLoading && posts.length === 0 && (<p className="rounded-xl border border-dashed border-border p-4 text-sm text-muted-foreground">{d.noMatch}</p>)}
        {posts.map((p) => {
          const isEditing = editingId === p.id
          return (
            <article key={p.id} className="rounded-xl border border-border bg-card p-4">
              <div className="flex flex-wrap items-center gap-2">{visibilityBadge(p.visibility, d)}{p.author_is_bot && <Badge variant="outline">{d.bot}</Badge>}{p.tag && <Badge variant="outline">{p.tag}</Badge>}{p.zip_code && (<Badge variant="outline">{d.zip} {p.zip_code}</Badge>)}<span className="text-xs text-muted-foreground">{p.author_name?? p.user_id.slice(0, 8)}</span><span className="ml-auto text-xs text-muted-foreground">{new Date(p.created_at).toLocaleString()}</span></div>
              {isEditing? (
                <div className="mt-3 space-y-3"><label className="block text-sm"><span className="text-muted-foreground">{d.tag}</span><Input value={editTag} onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEditTag(e.target.value)} maxLength={40} /></label><label className="block text-sm"><span className="text-muted-foreground">{d.body} ({editBody.length}/2000)</span><Textarea value={editBody} onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setEditBody(e.target.value)} maxLength={2000} rows={6} /></label><div className="flex gap-2"><Button size="sm" onClick={saveEdit} disabled={busy}>{d.save}</Button><Button size="sm" variant="ghost" onClick={() => setEditingId(null)}>{d.cancel}</Button></div></div>
              ) : (<pre className="mt-2 whitespace-pre-wrap text-sm">{p.body}</pre>)}
              {!isEditing && (<div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => beginEdit(p)}>{d.edit}</Button>{p.visibility!== 'published' && (<Button size="sm" onClick={() => onSetVis(p.id, 'published')}>{d.publish}</Button>)}{p.visibility === 'published' && (<Button size="sm" variant="secondary" onClick={() => onSetVis(p.id, 'unpublished')}>{d.unpublish}</Button>)}{p.visibility!== 'draft' && (<Button size="sm" variant="ghost" onClick={() => onSetVis(p.id, 'draft')}>{d.markDraft}</Button>)}<AlertDialog><AlertDialogTrigger><Button size="sm" variant="destructive">{d.del}</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{d.delTitle}</AlertDialogTitle><AlertDialogDescription>{d.delDesc}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{d.cancel}</AlertDialogCancel><AlertDialogAction onClick={() => onDelete(p.id)}>{d.del}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>)}
            </article>
          )
        })}
      </div>
      <div className="space-y-3"><h3 className="text-sm font-semibold">{d.audit} ({audit.length})</h3><div className="rounded-xl border border-border bg-card">{audit.length === 0 && (<p className="p-4 text-sm text-muted-foreground">{d.noAct}</p>)}{audit.map((row) => (<div key={row.id} className="border-b border-border p-3 text-sm last:border-b-0"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className="text-xs uppercase">{row.action}</Badge><span className="font-medium">{row.actor_is_bot? '🤖 ' : ''}{row.actor_name?? row.actor_id?.slice(0, 8)?? 'system'}</span><span className="text-xs text-muted-foreground">{new Date(row.created_at).toLocaleString()}</span>{row.post_id && (<span className="ml-auto font-mono text-xs text-muted-foreground">{row.post_id.slice(0, 8)}</span>)}</div>{row.snapshot?.body && (<p className="mt-1 line-clamp-2 text-xs text-muted-foreground">"{String(row.snapshot.body).slice(0, 160)}"</p>)}</div>))}</div></div>
    </section>
  )
}
