'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useLanguage } from '@/lib/language-context'

const D: Record<string, any> = {
  en: { postsCms:"Posts CMS", searchBody:"Search post body…", posts:"Posts", loading:"Loading…", noMatch:"No posts match this filter.", published:"Published", draft:"Draft", unpublished:"Unpublished", bot:"🤖 Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"💾 Save", cancel:"Cancel", edit:"✏ Edit", publish:"📢 Publish", unpublish:"🙈 Unpublish", markDraft:"📝 Mark as draft", delete:"🗑 Delete", deleteTitle:"Delete this post?", deleteDesc:"This permanently removes the post from the feed. The audit log entry remains.", audit:"Audit log", noActions:"No actions yet.", cannotEmpty:"Body cannot be empty", updated:"Post updated", deleted:"Post deleted", marked:"Marked", failed:"Failed", failedLoad:"Failed to load", failedUpdate:"Failed to update", failedDelete:"Failed to delete" },
  es: { postsCms:"CMS Publicaciones", searchBody:"Buscar cuerpo…", posts:"Publicaciones", loading:"Cargando…", noMatch:"Ninguna publicación coincide.", published:"Publicado", draft:"Borrador", unpublished:"No publicado", bot:"🤖 Bot", zip:"CP", tag:"Etiqueta", body:"Cuerpo", save:"💾 Guardar", cancel:"Cancelar", edit:"✏ Editar", publish:"📢 Publicar", unpublish:"🙈 Despublicar", markDraft:"📝 Marcar borrador", delete:"🗑 Eliminar", deleteTitle:"¿Eliminar publicación?", deleteDesc:"Esto elimina permanentemente la publicación. El registro auditoría permanece.", audit:"Registro auditoría", noActions:"Sin acciones aún.", cannotEmpty:"Cuerpo no puede estar vacío", updated:"Publicación actualizada", deleted:"Publicación eliminada", marked:"Marcado", failed:"Falló", failedLoad:"Error al cargar", failedUpdate:"Error al actualizar", failedDelete:"Error al eliminar" },
  fr: { postsCms:"CMS Publications", searchBody:"Rechercher corps…", posts:"Publications", loading:"Chargement…", noMatch:"Aucune publication correspond.", published:"Publié", draft:"Brouillon", unpublished:"Non publié", bot:"🤖 Bot", zip:"CP", tag:"Tag", body:"Corps", save:"💾 Enregistrer", cancel:"Annuler", edit:"✏ Modifier", publish:"📢 Publier", unpublish:"🙈 Dépublier", markDraft:"📝 Marquer brouillon", delete:"🗑 Supprimer", deleteTitle:"Supprimer ce post?", deleteDesc:"Supprime définitivement le post. Le journal audit reste.", audit:"Journal audit", noActions:"Aucune action.", cannotEmpty:"Corps vide interdit", updated:"Post mis à jour", deleted:"Post supprimé", marked:"Marqué", failed:"Échec", failedLoad:"Échec chargement", failedUpdate:"Échec mise à jour", failedDelete:"Échec suppression" },
  de: { postsCms:"Posts CMS", searchBody:"Post-Inhalt suchen…", posts:"Posts", loading:"Laden…", noMatch:"Keine Posts passen.", published:"Veröffentlicht", draft:"Entwurf", unpublished:"Unveröffentlicht", bot:"🤖 Bot", zip:"PLZ", tag:"Tag", body:"Inhalt", save:"💾 Speichern", cancel:"Abbrechen", edit:"✏ Bearbeiten", publish:"📢 Veröffentlichen", unpublish:"🙈 Zurückziehen", markDraft:"📝 Als Entwurf", delete:"🗑 Löschen", deleteTitle:"Diesen Post löschen?", deleteDesc:"Entfernt Post dauerhaft. Audit-Log bleibt.", audit:"Audit-Log", noActions:"Noch keine Aktionen.", cannotEmpty:"Inhalt darf nicht leer sein", updated:"Post aktualisiert", deleted:"Post gelöscht", marked:"Markiert", failed:"Fehlgeschlagen", failedLoad:"Laden fehlgeschlagen", failedUpdate:"Update fehlgeschlagen", failedDelete:"Löschen fehlgeschlagen" },
  zh: { postsCms:"帖子管理", searchBody:"搜索帖子内容…", posts:"帖子", loading:"加载中…", noMatch:"无匹配帖子。", published:"已发布", draft:"草稿", unpublished:"未发布", bot:"🤖 机器人", zip:"邮编", tag:"标签", body:"内容", save:"💾 保存", cancel:"取消", edit:"✏ 编辑", publish:"📢 发布", unpublish:"🙈 取消发布", markDraft:"📝 标为草稿", delete:"🗑 删除", deleteTitle:"删除此帖子？", deleteDesc:"这将永久删除该帖子。审计日志保留。", audit:"审计日志", noActions:"暂无操作。", cannotEmpty:"内容不能为空", updated:"帖子已更新", deleted:"帖子已删除", marked:"已标记", failed:"失败", failedLoad:"加载失败", failedUpdate:"更新失败", failedDelete:"删除失败" },
  ja: { postsCms:"投稿CMS", searchBody:"本文を検索…", posts:"投稿", loading:"読み込み中…", noMatch:"一致する投稿なし。", published:"公開済み", draft:"下書き", unpublished:"未公開", bot:"🤖 ボット", zip:"郵便番号", tag:"タグ", body:"本文", save:"💾 保存", cancel:"キャンセル", edit:"✏ 編集", publish:"📢 公開", unpublish:"🙈 非公開", markDraft:"📝 下書きにする", delete:"🗑 削除", deleteTitle:"この投稿を削除？", deleteDesc:"フィードから完全に削除。監査ログは残ります。", audit:"監査ログ", noActions:"まだ操作なし。", cannotEmpty:"本文は空にできません", updated:"投稿更新", deleted:"投稿削除", marked:"マーク済み", failed:"失敗", failedLoad:"読み込み失敗", failedUpdate:"更新失敗", failedDelete:"削除失敗" },
  ko: { postsCms:"게시물 CMS", searchBody:"본문 검색…", posts:"게시물", loading:"로딩 중…", noMatch:"일치하는 게시물 없음.", published:"게시됨", draft:"임시", unpublished:"미게시", bot:"🤖 봇", zip:"우편", tag:"태그", body:"본문", save:"💾 저장", cancel:"취소", edit:"✏ 편집", publish:"📢 게시", unpublish:"🙈 게시 취소", markDraft:"📝 임시로 표시", delete:"🗑 삭제", deleteTitle:"이 게시물 삭제?", deleteDesc:"피드에서 영구 삭제. 감사 로그는 남음.", audit:"감사 로그", noActions:"아직 작업 없음.", cannotEmpty:"본문 비울 수 없음", updated:"게시물 업데이트됨", deleted:"게시물 삭제됨", marked:"표시됨", failed:"실패", failedLoad:"로드 실패", failedUpdate:"업데이트 실패", failedDelete:"삭제 실패" },
  pt: { postsCms:"CMS de Posts", searchBody:"Buscar corpo…", posts:"Posts", loading:"Carregando…", noMatch:"Nenhum post corresponde.", published:"Publicado", draft:"Rascunho", unpublished:"Despublicado", bot:"🤖 Bot", zip:"CEP", tag:"Tag", body:"Corpo", save:"💾 Salvar", cancel:"Cancelar", edit:"✏ Editar", publish:"📢 Publicar", unpublish:"🙈 Despublicar", markDraft:"📝 Marcar rascunho", delete:"🗑 Deletar", deleteTitle:"Deletar este post?", deleteDesc:"Remove permanentemente do feed. Log auditoria permanece.", audit:"Log auditoria", noActions:"Nenhuma ação ainda.", cannotEmpty:"Corpo não pode ser vazio", updated:"Post atualizado", deleted:"Post deletado", marked:"Marcado", failed:"Falhou", failedLoad:"Falha ao carregar", failedUpdate:"Falha ao atualizar", failedDelete:"Falha ao deletar" },
  ru: { postsCms:"CMS Постов", searchBody:"Поиск по телу…", posts:"Посты", loading:"Загрузка…", noMatch:"Нет подходящих постов.", published:"Опубликовано", draft:"Черновик", unpublished:"Неопубликовано", bot:"🤖 Бот", zip:"Индекс", tag:"Тег", body:"Тело", save:"💾 Сохранить", cancel:"Отмена", edit:"✏ Редактировать", publish:"📢 Опубликовать", unpublish:"🙈 Снять", markDraft:"📝 В черновики", delete:"🗑 Удалить", deleteTitle:"Удалить пост?", deleteDesc:"Навсегда удаляет пост. Лог аудита остается.", audit:"Журнал аудита", noActions:"Действий пока нет.", cannotEmpty:"Тело не может быть пустым", updated:"Пост обновлен", deleted:"Пост удален", marked:"Отмечено", failed:"Ошибка", failedLoad:"Ошибка загрузки", failedUpdate:"Ошибка обновления", failedDelete:"Ошибка удаления" },
  ar: { postsCms:"نظام المنشورات", searchBody:"ابحث في النص…", posts:"منشورات", loading:"جاري التحميل…", noMatch:"لا منشورات مطابقة.", published:"منشور", draft:"مسودة", unpublished:"غير منشور", bot:"🤖 بوت", zip:"رمز بريدي", tag:"وسم", body:"نص", save:"💾 حفظ", cancel:"إلغاء", edit:"✏ تعديل", publish:"📢 نشر", unpublish:"🙈 إلغاء نشر", markDraft:"📝 وضع مسودة", delete:"🗑 حذف", deleteTitle:"حذف هذا المنشور؟", deleteDesc:"يزيل المنشور نهائيا. سجل التدقيق يبقى.", audit:"سجل التدقيق", noActions:"لا إجراءات بعد.", cannotEmpty:"النص لا يمكن أن يكون فارغا", updated:"تم تحديث المنشور", deleted:"تم حذف المنشور", marked:"تم وضع علامة", failed:"فشل", failedLoad:"فشل التحميل", failedUpdate:"فشل التحديث", failedDelete:"فشل الحذف" },
  hi: { postsCms:"पोस्ट CMS", searchBody:"बॉडी खोजें…", posts:"पोस्ट", loading:"लोड हो रहा…", noMatch:"कोई पोस्ट मेल नहीं।", published:"प्रकाशित", draft:"ड्राफ्ट", unpublished:"अप्रकाशित", bot:"🤖 बॉट", zip:"पिन", tag:"टैग", body:"बॉडी", save:"💾 सेव", cancel:"रद्द", edit:"✏ संपादित", publish:"📢 प्रकाशित", unpublish:"🙈 अप्रकाशित", markDraft:"📝 ड्राफ्ट चिह्नित", delete:"🗑 हटाएं", deleteTitle:"यह पोस्ट हटाएं?", deleteDesc:"फ़ीड से स्थायी रूप से हटाता है। ऑडिट लॉग रहता है।", audit:"ऑडिट लॉग", noActions:"अभी कोई कार्रवाई नहीं।", cannotEmpty:"बॉडी खाली नहीं", updated:"पोस्ट अपडेट", deleted:"पोस्ट हटाया", marked:"चिह्नित", failed:"विफल", failedLoad:"लोड विफल", failedUpdate:"अपडेट विफल", failedDelete:"हटाना विफल" },
  it: { postsCms:"CMS Post", searchBody:"Cerca corpo…", posts:"Post", loading:"Caricamento…", noMatch:"Nessun post corrisponde.", published:"Pubblicato", draft:"Bozza", unpublished:"Non pubblicato", bot:"🤖 Bot", zip:"CAP", tag:"Tag", body:"Corpo", save:"💾 Salva", cancel:"Annulla", edit:"✏ Modifica", publish:"📢 Pubblica", unpublish:"🙈 Annulla pubblicazione", markDraft:"📝 Segna bozza", delete:"🗑 Elimina", deleteTitle:"Eliminare questo post?", deleteDesc:"Rimuove permanentemente dal feed. Log audit rimane.", audit:"Log audit", noActions:"Nessuna azione.", cannotEmpty:"Corpo non vuoto", updated:"Post aggiornato", deleted:"Post eliminato", marked:"Segnato", failed:"Fallito", failedLoad:"Caricamento fallito", failedUpdate:"Aggiornamento fallito", failedDelete:"Eliminazione fallita" },
  nl: { postsCms:"Posts CMS", searchBody:"Zoek body…", posts:"Posts", loading:"Laden…", noMatch:"Geen posts gevonden.", published:"Gepubliceerd", draft:"Concept", unpublished:"Niet gepubliceerd", bot:"🤖 Bot", zip:"Postcode", tag:"Tag", body:"Body", save:"💾 Opslaan", cancel:"Annuleren", edit:"✏ Bewerken", publish:"📢 Publiceren", unpublish:"🙈 Depubliceren", markDraft:"📝 Als concept", delete:"🗑 Verwijderen", deleteTitle:"Deze post verwijderen?", deleteDesc:"Verwijdert permanent. Auditlog blijft.", audit:"Auditlog", noActions:"Nog geen acties.", cannotEmpty:"Body mag niet leeg", updated:"Post bijgewerkt", deleted:"Post verwijderd", marked:"Gemarkeerd", failed:"Mislukt", failedLoad:"Laden mislukt", failedUpdate:"Update mislukt", failedDelete:"Verwijderen mislukt" },
  tl: { postsCms:"Posts CMS", searchBody:"Hanapin body…", posts:"Posts", loading:"Naglo-load…", noMatch:"Walang tugmang posts.", published:"Nai-publish", draft:"Draft", unpublished:"Hindi nai-publish", bot:"🤖 Bot", zip:"ZIP", tag:"Tag", body:"Body", save:"💾 I-save", cancel:"Kansela", edit:"✏ I-edit", publish:"📢 I-publish", unpublish:"🙈 I-unpublish", markDraft:"📝 Mark draft", delete:"🗑 Burahin", deleteTitle:"Burahin post na ito?", deleteDesc:"Permanenteng aalisin sa feed. Audit log nananatili.", audit:"Audit log", noActions:"Wala pang aksyon.", cannotEmpty:"Body hindi pwedeng blangko", updated:"Post na-update", deleted:"Post nabura", marked:"Na-mark", failed:"Nabigo", failedLoad:"Load nabigo", failedUpdate:"Update nabigo", failedDelete:"Delete nabigo" },
  bn: { postsCms:"পোস্ট CMS", searchBody:"বডি খুঁজুন…", posts:"পোস্ট", loading:"লোড হচ্ছে…", noMatch:"কোন পোস্ট মেলেনি।", published:"প্রকাশিত", draft:"খসড়া", unpublished:"অপ্রকাশিত", bot:"🤖 বট", zip:"জিপ", tag:"ট্যাগ", body:"বডি", save:"💾 সংরক্ষণ", cancel:"বাতিল", edit:"✏ সম্পাদনা", publish:"📢 প্রকাশ", unpublish:"🙈 অপ্রকাশ", markDraft:"📝 খসড়া চিহ্নিত", delete:"🗑 মুছুন", deleteTitle:"এই পোস্ট মুছবেন?", deleteDesc:"ফিড থেকে স্থায়ীভাবে মুছে দেয়। অডিট লগ থাকে।", audit:"অডিট লগ", noActions:"এখনো কোনো কাজ নেই।", cannotEmpty:"বডি খালি নয়", updated:"পোস্ট আপডেট", deleted:"পোস্ট মুছেছে", marked:"চিহ্নিত", failed:"ব্যর্থ", failedLoad:"লোড ব্যর্থ", failedUpdate:"আপডেট ব্যর্থ", failedDelete:"মুছা ব্যর্থ" },
  id: { postsCms:"CMS Postingan", searchBody:"Cari isi…", posts:"Postingan", loading:"Memuat…", noMatch:"Tidak ada postingan cocok.", published:"Diterbitkan", draft:"Draf", unpublished:"Tidak diterbitkan", bot:"🤖 Bot", zip:"Kode Pos", tag:"Tag", body:"Isi", save:"💾 Simpan", cancel:"Batal", edit:"✏ Edit", publish:"📢 Terbitkan", unpublish:"🙈 Batal terbit", markDraft:"📝 Tandai draf", delete:"🗑 Hapus", deleteTitle:"Hapus postingan ini?", deleteDesc:"Menghapus permanen dari feed. Log audit tetap.", audit:"Log audit", noActions:"Belum ada aksi.", cannotEmpty:"Isi tidak boleh kosong", updated:"Postingan diperbarui", deleted:"Postingan dihapus", marked:"Ditandai", failed:"Gagal", failedLoad:"Gagal memuat", failedUpdate:"Gagal memperbarui", failedDelete:"Gagal menghapus" },
  vi: { postsCms:"CMS Bài viết", searchBody:"Tìm nội dung…", posts:"Bài viết", loading:"Đang tải…", noMatch:"Không có bài khớp.", published:"Đã xuất bản", draft:"Nháp", unpublished:"Chưa xuất bản", bot:"🤖 Bot", zip:"ZIP", tag:"Thẻ", body:"Nội dung", save:"💾 Lưu", cancel:"Hủy", edit:"✏ Sửa", publish:"📢 Xuất bản", unpublish:"🙈 Gỡ xuất bản", markDraft:"📝 Đánh dấu nháp", delete:"🗑 Xóa", deleteTitle:"Xóa bài này?", deleteDesc:"Xóa vĩnh viễn khỏi feed. Nhật ký kiểm toán vẫn còn.", audit:"Nhật ký kiểm toán", noActions:"Chưa có hành động.", cannotEmpty:"Nội dung không được trống", updated:"Đã cập nhật bài", deleted:"Đã xóa bài", marked:"Đã đánh dấu", failed:"Thất bại", failedLoad:"Tải thất bại", failedUpdate:"Cập nhật thất bại", failedDelete:"Xóa thất bại" },
  th: { postsCms:"CMS โพสต์", searchBody:"ค้นหาเนื้อหา…", posts:"โพสต์", loading:"กำลังโหลด…", noMatch:"ไม่มีโพสต์ที่ตรงกัน", published:"เผยแพร่แล้ว", draft:"ฉบับร่าง", unpublished:"ไม่ได้เผยแพร่", bot:"🤖 บอท", zip:"รหัสไปรษณีย์", tag:"แท็ก", body:"เนื้อหา", save:"💾 บันทึก", cancel:"ยกเลิก", edit:"✏ แก้ไข", publish:"📢 เผยแพร่", unpublish:"🙈 ยกเลิกเผยแพร่", markDraft:"📝 ทำเครื่องหมายร่าง", delete:"🗑 ลบ", deleteTitle:"ลบโพสต์นี้?", deleteDesc:"ลบโพสต์ออกจากฟีดถาวร บันทึกการตรวจสอบยังคงอยู่", audit:"บันทึกการตรวจสอบ", noActions:"ยังไม่มีการดำเนินการ", cannotEmpty:"เนื้อหาต้องไม่ว่าง", updated:"อัปเดตโพสต์แล้ว", deleted:"ลบโพสต์แล้ว", marked:"ทำเครื่องหมายแล้ว", failed:"ล้มเหลว", failedLoad:"โหลดล้มเหลว", failedUpdate:"อัปเดตล้มเหลว", failedDelete:"ลบล้มเหลว" },
  sv: { postsCms:"Inlägg CMS", searchBody:"Sök innehåll…", posts:"Inlägg", loading:"Laddar…", noMatch:"Inga inlägg matchar.", published:"Publicerad", draft:"Utkast", unpublished:"Opublicerad", bot:"🤖 Bot", zip:"Postnr", tag:"Tagg", body:"Innehåll", save:"💾 Spara", cancel:"Avbryt", edit:"✏ Redigera", publish:"📢 Publicera", unpublish:"🙈 Avpublicera", markDraft:"📝 Markera utkast", delete:"🗑 Radera", deleteTitle:"Radera inlägg?", deleteDesc:"Tar bort permanent från flödet. Auditlogg kvarstår.", audit:"Auditlogg", noActions:"Inga åtgärder ännu.", cannotEmpty:"Innehåll får ej tomt", updated:"Inlägg uppdaterat", deleted:"Inlägg raderat", marked:"Markerat", failed:"Misslyckades", failedLoad:"Laddning misslyckades", failedUpdate:"Uppdatering misslyckades", failedDelete:"Radering misslyckades" },
  pl: { postsCms:"CMS Postów", searchBody:"Szukaj treści…", posts:"Posty", loading:"Ładowanie…", noMatch:"Brak pasujących postów.", published:"Opublikowany", draft:"Szkic", unpublished:"Nieopublikowany", bot:"🤖 Bot", zip:"Kod", tag:"Tag", body:"Treść", save:"💾 Zapisz", cancel:"Anuluj", edit:"✏ Edytuj", publish:"📢 Opublikuj", unpublish:"🙈 Cofnij publikację", markDraft:"📝 Oznacz jako szkic", delete:"🗑 Usuń", deleteTitle:"Usunąć ten post?", deleteDesc:"Trwale usuwa z feeda. Log audytu pozostaje.", audit:"Log audytu", noActions:"Brak działań.", cannotEmpty:"Treść nie może być pusta", updated:"Post zaktualizowany", deleted:"Post usunięty", marked:"Oznaczony", failed:"Niepowodzenie", failedLoad:"Błąd ładowania", failedUpdate:"Błąd aktualizacji", failedDelete:"Błąd usuwania" },
  tr: { postsCms:"Gönderi CMS", searchBody:"İçerik ara…", posts:"Gönderiler", loading:"Yükleniyor…", noMatch:"Eşleşen gönderi yok.", published:"Yayınlandı", draft:"Taslak", unpublished:"Yayınlanmadı", bot:"🤖 Bot", zip:"Posta Kodu", tag:"Etiket", body:"İçerik", save:"💾 Kaydet", cancel:"İptal", edit:"✏ Düzenle", publish:"📢 Yayınla", unpublish:"🙈 Yayından kaldır", markDraft:"📝 Taslak işaretle", delete:"🗑 Sil", deleteTitle:"Bu gönderiyi sil?", deleteDesc:"Akıştan kalıcı siler. Denetim günlüğü kalır.", audit:"Denetim günlüğü", noActions:"Henüz işlem yok.", cannotEmpty:"İçerik boş olamaz", updated:"Gönderi güncellendi", deleted:"Gönderi silindi", marked:"İşaretlendi", failed:"Başarısız", failedLoad:"Yükleme başarısız", failedUpdate:"Güncelleme başarısız", failedDelete:"Silme başarısız" },
  uk: { postsCms:"CMS Постів", searchBody:"Пошук по тілу…", posts:"Пости", loading:"Завантаження…", noMatch:"Немає відповідних постів.", published:"Опубліковано", draft:"Чернетка", unpublished:"Неопубліковано", bot:"🤖 Бот", zip:"Індекс", tag:"Тег", body:"Тіло", save:"💾 Зберегти", cancel:"Скасувати", edit:"✏ Редагувати", publish:"📢 Опублікувати", unpublish:"🙈 Зняти", markDraft:"📝 В чернетки", delete:"🗑 Видалити", deleteTitle:"Видалити пост?", deleteDesc:"Назавжди видаляє з стрічки. Лог аудиту залишається.", audit:"Журнал аудиту", noActions:"Дій поки немає.", cannotEmpty:"Тіло не може бути порожнім", updated:"Пост оновлено", deleted:"Пост видалено", marked:"Позначено", failed:"Помилка", failedLoad:"Помилка завантаження", failedUpdate:"Помилка оновлення", failedDelete:"Помилка видалення" },
  el: { postsCms:"CMS Αναρτήσεων", searchBody:"Αναζήτηση σώματος…", posts:"Αναρτήσεις", loading:"Φόρτωση…", noMatch:"Καμία ανάρτηση δεν ταιριάζει.", published:"Δημοσιευμένο", draft:"Πρόχειρο", unpublished:"Μη δημοσιευμένο", bot:"🤖 Bot", zip:"ΤΚ", tag:"Ετικέτα", body:"Σώμα", save:"💾 Αποθήκευση", cancel:"Ακύρωση", edit:"✏ Επεξεργασία", publish:"📢 Δημοσίευση", unpublish:"🙈 Από-δημοσίευση", markDraft:"📝 Σήμανση προχείρου", delete:"🗑 Διαγραφή", deleteTitle:"Διαγραφή ανάρτησης;", deleteDesc:"Διαγράφει μόνιμα από τη ροή. Το αρχείο ελέγχου παραμένει.", audit:"Αρχείο ελέγχου", noActions:"Καμία ενέργεια ακόμα.", cannotEmpty:"Σώμα δεν μπορεί κενό", updated:[STRIPPED 45 bytes], deleted:[STRIPPED 43 bytes], marked:"Σημειωμένο", failed:"Αποτυχία", failedLoad:"Αποτυχία φόρτωσης", failedUpdate:"Αποτυχία ενημέρωσης", failedDelete:"Αποτυχία διαγραφής" },
  he: { postsCms:"ניהול פוסטים", searchBody:"חיפוש גוף…", posts:"פוסטים", loading:"טוען…", noMatch:"אין פוסטים תואמים.", published:"פורסם", draft:"טיוטה", unpublished:"לא פורסם", bot:"🤖 בוט", zip:"מיקוד", tag:"תג", body:"גוף", save:"💾 שמור", cancel:"ביטול", edit:"✏ ערוך", publish:"📢 פרסם", unpublish:"🙈 בטל פרסום", markDraft:"📝 סמן כטיוטה", delete:"🗑 מחק", deleteTitle:"למחוק פוסט זה?", deleteDesc:"מוחק לצמיתות מהפיד. יומן ביקורת נשאר.", audit:"יומן ביקורת", noActions:"אין פעולות עדיין.", cannotEmpty:"גוף לא יכול להיות ריק", updated:"פוסט עודכן", deleted:"פוסט נמחק", marked:"סומן", failed:"נכשל", failedLoad:"טעינה נכשלה", failedUpdate:"עדכון נכשל", failedDelete:"מחיקה נכשלה" },
  ur: { postsCms:"پوسٹس CMS", searchBody:"باڈی تلاش…", posts:"پوسٹس", loading:"لوڈ ہو رہا…", noMatch:"کوئی پوسٹ مماثل نہیں۔", published:"شائع شدہ", draft:"مسودہ", unpublished:"غیر شائع شدہ", bot:"🤖 بوٹ", zip:"زپ", tag:"ٹیگ", body:"باڈی", save:"💾 محفوظ", cancel:"منسوخ", edit:"✏ ترمیم", publish:"📢 شائع کریں", unpublish:"🙈 غیر شائع", markDraft:"📝 مسودہ نشان", delete:"🗑 حذف", deleteTitle:"یہ پوسٹ حذف کریں؟", deleteDesc:"فیڈ سے مستقل ہٹاتا ہے۔ آڈٹ لاگ رہتا ہے۔", audit:"آڈٹ لاگ", noActions:"ابھی کوئی کارروائی نہیں۔", cannotEmpty:"باڈی خالی نہیں", updated:"پوسٹ اپ ڈیٹ", deleted:"پوسٹ حذف", marked:"نشان زد", failed:"ناکام", failedLoad:"لوڈ ناکام", failedUpdate:"اپ ڈیٹ ناکام", failedDelete:"حذف ناکام" },
  fa: { postsCms:"CMS پست‌ها", searchBody:"جستجوی بدنه…", posts:"پست‌ها", loading:"در حال بارگذاری…", noMatch:"هیچ پستی مطابقت ندارد.", published:"منتشر شده", draft:"پیش‌نویس", unpublished:"منتشر نشده", bot:"🤖 ربات", zip:"کد پستی", tag:"برچسب", body:"بدنه", save:"💾 ذخیره", cancel:"لغو", edit:"✏ ویرایش", publish:"📢 انتشار", unpublish:"🙈 لغو انتشار", markDraft:"📝 علامت پیش‌نویس", delete:"🗑 حذف", deleteTitle:"حذف این پست؟", deleteDesc:"پست را برای همیشه از فید حذف می‌کند. لاگ حسابرسی می‌ماند.", audit:"لاگ حسابرسی", noActions:"هنوز اقدامی نیست.", cannotEmpty:"بدنه نمی‌تواند خالی باشد", updated:"پست به‌روز شد", deleted:"پست حذف شد", marked:"علامت‌گذاری شد", failed:"ناموفق", failedLoad:"بارگذاری ناموفق", failedUpdate:"به‌روزرسانی ناموفق", failedDelete:"حذف ناموفق" },
  ms: { postsCms:"CMS Pos", searchBody:"Cari badan…", posts:"Pos", loading:"Memuatkan…", noMatch:"Tiada pos sepadan.", published:"Diterbitkan", draft:"Draf", unpublished:"Tidak diterbitkan", bot:"🤖 Bot", zip:"Poskod", tag:"Tag", body:"Badan", save:"💾 Simpan", cancel:"Batal", edit:"✏ Sunting", publish:"📢 Terbitkan", unpublish:"🙈 Nyahterbit", markDraft:"📝 Tandakan draf", delete:"🗑 Padam", deleteTitle:"Padam pos ini?", deleteDesc:"Membuang secara kekal dari suapan. Log audit kekal.", audit:"Log audit", noActions:"Tiada tindakan lagi.", cannotEmpty:"Badan tidak boleh kosong", updated:"Pos dikemas kini", deleted:"Pos dipadam", marked:"Ditandakan", failed:"Gagal", failedLoad:"Gagal memuat", failedUpdate:"Gagal mengemas kini", failedDelete:"Gagal memadam" },
  ro: { postsCms:"CMS Postări", searchBody:"Caută corp…", posts:"Postări", loading:"Se încarcă…", noMatch:"Nicio postare potrivită.", published:"Publicat", draft:"Ciornă", unpublished:"Nepublicat", bot:"🤖 Bot", zip:"Cod poștal", tag:"Etichetă", body:"Corp", save:"💾 Salvează", cancel:"Anulează", edit:"✏ Editează", publish:"📢 Publică", unpublish:"🙈 Depublică", markDraft:"📝 Marchează ciornă", delete:"🗑 Șterge", deleteTitle:"Ștergi această postare?", deleteDesc:"Șterge permanent din flux. Jurnal audit rămâne.", audit:"Jurnal audit", noActions:"Nicio acțiune încă.", cannotEmpty:"Corpul nu poate fi gol", updated:"Postare actualizată", deleted:"Postare ștearsă", marked:"Marcat", failed:"Eșuat", failedLoad:"Încărcare eșuată", failedUpdate:"Actualizare eșuată", failedDelete:"Ștergere eșuată" },
  cs: { postsCms:"CMS Příspěvků", searchBody:"Hledat tělo…", posts:"Příspěvky", loading:"Načítání…", noMatch:"Žádné příspěvky neodpovídají.", published:"Publikováno", draft:"Koncept", unpublished:"Nepublikováno", bot:"🤖 Bot", zip:"PSČ", tag:"Tag", body:"Tělo", save:"💾 Uložit", cancel:"Zrušit", edit:"✏ Upravit", publish:"📢 Publikovat", unpublish:"🙈 Zrušit publikaci", markDraft:"📝 Označit koncept", delete:"🗑 Smazat", deleteTitle:"Smazat příspěvek?", deleteDesc:"Trvale odstraní z feedu. Audit log zůstává.", audit:"Audit log", noActions:"Zatím žádné akce.", cannotEmpty:"Tělo nesmí být prázdné", updated:"Příspěvek aktualizován", deleted:"Příspěvek smazán", marked:"Označeno", failed:"Selhalo", failedLoad:"Načtení selhalo", failedUpdate:"Aktualizace selhala", failedDelete:"Mazání selhalo" },
  hu: { postsCms:"Bejegyzés CMS", searchBody:"Törzs keresése…", posts:"Bejegyzések", loading:"Betöltés…", noMatch:"Nincs egyező bejegyzés.", published:"Közzétéve", draft:"Vázlat", unpublished:"Nem közzétett", bot:"🤖 Bot", zip:"Irányítószám", tag:"Címke", body:"Törzs", save:"💾 Mentés", cancel:"Mégse", edit:"✏ Szerkesztés", publish:"📢 Közzététel", unpublish:"🙈 Visszavonás", markDraft:"📝 Vázlat jelölés", delete:"🗑 Törlés", deleteTitle:"Törli ezt a bejegyzést?", deleteDesc:"Véglegesen eltávolítja a hírfolyamból. Napló megmarad.", audit:"Napló", noActions:"Még nincs művelet.", cannotEmpty:"Törzs nem lehet üres", updated:"Bejegyzés frissítve", deleted:"Bejegyzés törölve", marked:"Megjelölve", failed:"Sikertelen", failedLoad:"Betöltés sikertelen", failedUpdate:"Frissítés sikertelen", failedDelete:"Törlés sikertelen" },
  fi: { postsCms:"Julkaisujen CMS", searchBody:"Hae runkoa…", posts:"Julkaisut", loading:"Ladataan…", noMatch:"Ei vastaavia julkaisuja.", published:"Julkaistu", draft:"Luonnos", unpublished:"Julkaisematon", bot:"🤖 Botti", zip:"Postinumero", tag:"Tagi", body:"Runko", save:"💾 Tallenna", cancel:"Peruuta", edit:"✏ Muokkaa", publish:"📢 Julkaise", unpublish:"🙈 Poista julkaisu", markDraft:"📝 Merkitse luonnos", delete:"🗑 Poista", deleteTitle:"Poistetaanko julkaisu?", deleteDesc:"Poistaa pysyvästi syötteestä. Audit-loki säilyy.", audit:"Audit-loki", noActions:"Ei toimia vielä.", cannotEmpty:"Runko ei tyhjä", updated:"Julkaisu päivitetty", deleted:"Julkaisu poistettu", marked:"Merkitty", failed:"Epäonnistui", failedLoad:"Lataus epäonnistui", failedUpdate:"Päivitys epäonnistui", failedDelete:"Poisto epäonnistui" },
  no: { postsCms:"Innlegg CMS", searchBody:"Søk innhold…", posts:"Innlegg", loading:"Laster…", noMatch:"Ingen innlegg matcher.", published:"Publisert", draft:"Utkast", unpublished:"Upublisert", bot:"🤖 Bot", zip:"Postnr", tag:"Tagg", body:"Innhold", save:"💾 Lagre", cancel:"Avbryt", edit:"✏ Rediger", publish:"📢 Publiser", unpublish:"🙈 Avpubliser", markDraft:"📝 Marker som utkast", delete:"🗑 Slett", deleteTitle:"Slette innlegg?", deleteDesc:"Fjerner permanent fra feed. Revisjonslogg beholdes.", audit:"Revisjonslogg", noActions:"Ingen handlinger ennå.", cannotEmpty:"Innhold kan ikke være tomt", updated:"Innlegg oppdatert", deleted:"Innlegg slettet", marked:"Markert", failed:"Mislyktes", failedLoad:"Lasting mislyktes", failedUpdate:"Oppdatering mislyktes", failedDelete:"Sletting mislyktes" },
  da: { postsCms:"Opslag CMS", searchBody:"Søg brødtekst…", posts:"Opslag", loading:"Indlæser…", noMatch:"Ingen opslag matcher.", published:"Publiceret", draft:"Kladde", unpublished:"Upubliceret", bot:"🤖 Bot", zip:"Postnr", tag:"Tag", body:"Brødtekst", save:"💾 Gem", cancel:"Annuller", edit:"✏ Rediger", publish:"📢 Publicer", unpublish:"🙈 Afpublicer", markDraft:"📝 Markér kladde", delete:"🗑 Slet", deleteTitle:"Slet opslag?", deleteDesc:"Fjerner permanent fra feed. Auditlog forbliver.", audit:"Auditlog", noActions:"Ingen handlinger endnu.", cannotEmpty:"Brødtekst må ikke tom", updated:"Opslag opdateret", deleted:"Opslag slettet", marked:"Markeret", failed:"Mislykkedes", failedLoad:"Indlæsning mislykkedes", failedUpdate:"Opdatering mislykkedes", failedDelete:"Sletning mislykkedes" },
  bg: { postsCms:"CMS Публикации", searchBody:"Търсене тяло…", posts:"Публикации", loading:"Зареждане…", noMatch:"Няма съвпадащи публикации.", published:"Публикувано", draft:"Чернова", unpublished:"Непубликувано", bot:"🤖 Бот", zip:"Пощ. код", tag:"Таг", body:"Тяло", save:"💾 Запази", cancel:"Отказ", edit:"✏ Редактирай", publish:"📢 Публикувай", unpublish:"🙈 Спри публикуване", markDraft:"📝 Маркирай чернова", delete:"🗑 Изтрий", deleteTitle:"Изтриване публикация?", deleteDesc:"Премахва завинаги от емисията. Одит лог остава.", audit:"Одит лог", noActions:"Няма действия още.", cannotEmpty:"Тялото не може празно", updated:"Публикация обновена", deleted:"Публикация изтрита", marked:"Маркирано", failed:"Неуспех", failedLoad:"Зареждане неуспешно", failedUpdate:"Обновяване неуспешно", failedDelete:"Изтриване неуспешно" },
  hr: { postsCms:"CMS Objava", searchBody:"Traži tijelo…", posts:"Objave", loading:"Učitavanje…", noMatch:"Nema podudarnih objava.", published:"Objavljeno", draft:"Nacrt", unpublished:"Neobjavljeno", bot:"🤖 Bot", zip:"Pošt. broj", tag:"Oznaka", body:"Tijelo", save:"💾 Spremi", cancel:"Otkaži", edit:"✏ Uredi", publish:"📢 Objavi", unpublish:"🙈 Poništi objavu", markDraft:"📝 Označi nacrt", delete:"🗑 Izbriši", deleteTitle:"Izbrisati objavu?", deleteDesc:"Trajno uklanja iz feeda. Audit log ostaje.", audit:"Audit log", noActions:"Još nema akcija.", cannotEmpty:"Tijelo ne smije prazno", updated:"Objava ažurirana", deleted:"Objava izbrisana", marked:"Označeno", failed:"Neuspjeh", failedLoad:"Učitavanje neuspjelo", failedUpdate:"Ažuriranje neuspjelo", failedDelete:"Brisanje neuspjelo" },
  sr: { postsCms:"CMS Објава", searchBody:"Тражи тело…", posts:"Објаве", loading:"Учитавање…", noMatch:"Нема подударних објава.", published:"Објављено", draft:"Нацрт", unpublished:"Необјављено", bot:"🤖 Бот", zip:"Пош. број", tag:"Ознака", body:"Тело", save:"💾 Сачувај", cancel:"Откажи", edit:"✏ Уреди", publish:"📢 Објави", unpublish:"🙈 Повуци објаву", markDraft:"📝 Означи нацрт", delete:"🗑 Обриши", deleteTitle:"Обрисати објаву?", deleteDesc:"Трајно уклања из фида. Лог ревизије остаје.", audit:"Лог ревизије", noActions:"Још нема акција.", cannotEmpty:"Тело не сме празно", updated:"Објава ажурирана", deleted:"Објава обрисана", marked:"Означено", failed:"Неуспех", failedLoad:"Учитавање неуспешно", failedUpdate:"Ажурирање неуспешно", failedDelete:"Брисање неуспешно" },
  sk: { postsCms:"CMS Príspevkov", searchBody:"Hľadať telo…", posts:"Príspevky", loading:"Načítanie…", noMatch:"Žiadne príspevky nezodpovedajú.", published:"Publikované", draft:"Koncept", unpublished:"Nepublikované", bot:"🤖 Bot", zip:"PSČ", tag:"Tag", body:"Telo", save:"💾 Uložiť", cancel:"Zrušiť", edit:"✏ Upraviť", publish:"📢 Publikovať", unpublish:"🙈 Zrušiť publikáciu", markDraft:"📝 Označiť koncept", delete:"🗑 Vymazať", deleteTitle:"Vymazať príspevok?", deleteDesc:"Trvalo odstráni z feedu. Audit log zostáva.", audit:"Audit log", noActions:"Zatiaľ žiadne akcie.", cannotEmpty:"Telo nesmie byť prázdne", updated:"Príspevok aktualizovaný", deleted:"Príspevok vymazaný", marked:"Označené", failed:"Zlyhalo", failedLoad:"Načítanie zlyhalo", failedUpdate:"Aktualizácia zlyhala", failedDelete:"Mazanie zlyhalo" },
  sl: { postsCms:"CMS Objav", searchBody:"Išči telo…", posts:"Objave", loading:"Nalaganje…", noMatch:"Ni ujemajočih objav.", published:"Objavljeno", draft:"Osnutek", unpublished:"Neobjavljeno", bot:"🤖 Bot", zip:"Poštna št", tag:"Oznaka", body:"Telo", save:"💾 Shrani", cancel:"Prekliči", edit:"✏ Uredi", publish:"📢 Objavi", unpublish:"🙈 Prekliči objavo", markDraft:"📝 Označi osnutek", delete:"🗑 Izbriši", deleteTitle:"Izbrisati objavo?", deleteDesc:"Trajno odstrani iz vira. Dnevnik revizije ostane.", audit:"Dnevnik revizije", noActions:"Še ni dejanj.", cannotEmpty:"Telo ne sme prazno", updated:"Objava posodobljena", deleted:"Objava izbrisana", marked:"Označeno", failed:"Spodletelo", failedLoad:"Nalaganje spodletelo", failedUpdate:"Posodobitev spodletela", failedDelete:"Brisanje spodletelo" },
  et: { postsCms:"Postituste CMS", searchBody:"Otsi sisu…", posts:"Postitused", loading:"Laadimine…", noMatch:"Ükski postitus ei vasta.", published:"Avaldatud", draft:"Mustand", unpublished:"Avaldamata", bot:"🤖 Bot", zip:"Postiindeks", tag:"Silt", body:"Sisu", save:"💾 Salvesta", cancel:"Tühista", edit:"✏ Muuda", publish:"📢 Avalda", unpublish:"🙈 Tühista avaldamine", markDraft:"📝 Märgi mustandiks", delete:"🗑 Kustuta", deleteTitle:"Kustutada postitus?", deleteDesc:"Eemaldab jäädavalt voost. Auditilogi jääb.", audit:"Auditilogi", noActions:"Tegevusi veel pole.", cannotEmpty:"Sisu ei tohi tühi olla", updated:"Postitus uuendatud", deleted:"Postitus kustutatud", marked:"Märgitud", failed:"Ebaõnnestus", failedLoad:"Laadimine ebaõnnestus", failedUpdate:"Uuendamine ebaõnnestus", failedDelete:"Kustutamine ebaõnnestus" },
  lv: { postsCms:"Ziņu CMS", searchBody:"Meklēt saturu…", posts:"Ziņas", loading:"Ielāde…", noMatch:"Neviena ziņa neatbilst.", published:"Publicēts", draft:"Melnraksts", unpublished:"Nepublicēts", bot:"🤖 Bots", zip:"Pasta indekss", tag:"Tags", body:"Saturs", save:"💾 Saglabāt", cancel:"Atcelt", edit:"✏ Rediģēt", publish:"📢 Publicēt", unpublish:"🙈 Atcelt publicēšanu", markDraft:"📝 Atzīmēt melnraksts", delete:"🗑 Dzēst", deleteTitle:"Dzēst ziņu?", deleteDesc:"Neatgriezeniski noņem no plūsmas. Audita žurnāls paliek.", audit:"Audita žurnāls", noActions:"Vēl nav darbību.", cannotEmpty:"Saturs nedrīkst tukšs", updated:"Ziņa atjaunināta", deleted:"Ziņa dzēsta", marked:"Atzīmēts", failed:"Neizdevās", failedLoad:"Ielāde neizdevās", failedUpdate:"Atjaunināšana neizdevās", failedDelete:"Dzēšana neizdevās" },
  lt: { postsCms:"Įrašų CMS", searchBody:"Ieškoti turinio…", posts:"Įrašai", loading:"Įkeliama…", noMatch:"Nėra atitinkančių įrašų.", published:"Paskelbta", draft:"Juodraštis", unpublished:"Nepaskelbta", bot:"🤖 Botas", zip:"Pašto kodas", tag:"Žyma", body:"Turinys", save:"💾 Išsaugoti", cancel:"Atšaukti", edit:"✏ Redaguoti", publish:"📢 Paskelbti", unpublish:"🙈 Atšaukti paskelbimą", markDraft:"📝 Žymėti juodraštį", delete:"🗑 Ištrinti", deleteTitle:"Ištrinti įrašą?", deleteDesc:"Visam laikui pašalina iš srauto. Audito žurnalas lieka.", audit:"Audito žurnalas", noActions:"Veiksmų dar nėra.", cannotEmpty:"Turinys negali būti tuščias", updated:"Įrašas atnaujintas", deleted:"Įrašas ištrintas", marked:"Pažymėta", failed:"Nepavyko", failedLoad:"Įkėlimas nepavyko", failedUpdate:"Atnaujinimas nepavyko", failedDelete:"Ištrynimas nepavyko" },
  be: { postsCms:"CMS Постаў", searchBody:"Пошук па целе…", posts:"Посты", loading:"Загрузка…", noMatch:"Няма адпаведных постаў.", published:"Апублікавана", draft:"Чарнавік", unpublished:"Неапублікавана", bot:"🤖 Бот", zip:"Індэкс", tag:"Тэг", body:"Цела", save:"💾 Захаваць", cancel:"Скасаваць", edit:"✏ Рэдагаваць", publish:"📢 Апублікаваць", unpublish:"🙈 Зняць", markDraft:"📝 У чарнавікі", delete:"🗑 Выдаліць", deleteTitle:"Выдаліць пост?", deleteDesc:"Назаўсёды выдаляе са стужкі. Лог аўдыту застаецца.", audit:"Журнал аўдыту", noActions:"Дзеянняў пакуль няма.", cannotEmpty:"Цела не можа быць пустым", updated:"Пост абноўлены", deleted:"Пост выдалены", marked:"Пазначана", failed:"Памылка", failedLoad:"Памылка загрузкі", failedUpdate:"Памылка абнаўлення", failedDelete:"Памылка выдалення" },
  ka: { postsCms:"პოსტების CMS", searchBody:"ძიება სხეულში…", posts:"პოსტები", loading:"იტვირთება…", noMatch:"შესაბამისი პოსტი არ არის.", published:"გამოქვეყნებული", draft:"მონახაზი", unpublished:"გამოუქვეყნებელი", bot:"🤖 ბოტი", zip:"საფოსტო", tag:"ტეგი", body:"სხეული", save:"💾 შენახვა", cancel:"გაუქმება", edit:"✏ რედაქტირება", publish:"📢 გამოქვეყნება", unpublish:"🙈 გამოქვეყნების გაუქმება", markDraft:"📝 მონახაზად მონიშვნა", delete:"🗑 წაშლა", deleteTitle:"წაიშალოს პოსტი?", deleteDesc:"სამუდამოდ შლის ფიდიდან. აუდიტის ჟურნალი რჩება.", audit:"აუდიტის ჟურნალი", noActions:"ჯერ ქმედება არ არის.", cannotEmpty:"სხეული არ შეიძლება ცარიელი", updated:"პოსტი განახლდა", deleted:"პოსტი წაიშალა", marked:"მონიშნული", failed:"ვერ მოხერხდა", failedLoad:"ჩატვირთვა ვერ მოხერხდა", failedUpdate:"განახლება ვერ მოხერხდა", failedDelete:"წაშლა ვერ მოხერხდა" },
  hy: { postsCms:"Գրառումների CMS", searchBody:"Որոնել մարմնում…", posts:"Գրառումներ", loading:"Բեռնում…", noMatch:"Համապատասխան գրառում չկա։", published:"Հրապարակված", draft:"Սևագիր", unpublished:"Չհրապարակված", bot:"🤖 Բոտ", zip:"Փոստային", tag:"Պիտակ", body:"Մարմին", save:"💾 Պահպանել", cancel:"Չեղարկել", edit:"✏ Խմբագրել", publish:"📢 Հրապարակել", unpublish:"🙈 Հանել հրապարակումից", markDraft:"📝 Նշել սևագիր", delete:"🗑 Ջնջել", deleteTitle:"Ջնջել գրառումը՞", deleteDesc:"Ընդմիշտ հեռացնում է հոսքից։ Աուդիտի մատյանը մնում է։", audit:"Աուդիտի մատյան", noActions:"Գործողություններ դեռ չկան։", cannotEmpty:"Մարմինը չի կարող դատարկ լինել", updated:"Գրառումը թարմացվեց", deleted:"Գրառումը ջնջվեց", marked:"Նշված", failed:"Ձախողվեց", failedLoad:"Բեռնումը ձախողվեց", failedUpdate:"Թարմացումը ձախողվեց", failedDelete:"Ջնջումը ձախողվեց" },
  az: { postsCms:"Post CMS", searchBody:"Məzmun axtar…", posts:"Postlar", loading:"Yüklənir…", noMatch:"Uyğun post yoxdur.", published:"Dərc edildi", draft:"Qaralama", unpublished:"Dərc edilməyib", bot:"🤖 Bot", zip:"Poçt kodu", tag:"Teq", body:"Məzmun", save:"💾 Saxla", cancel:"Ləğv et", edit:"✏ Redaktə et", publish:"📢 Dərc et", unpublish:"🙈 Dərcdən çıxar", markDraft:"📝 Qaralama işarələ", delete:"🗑 Sil", deleteTitle:"Bu postu sil?", deleteDesc:"Feeddən həmişəlik silir. Audit jurnalı qalır.", audit:"Audit jurnalı", noActions:"Hələ hərəkət yoxdur.", cannotEmpty:"Məzmun boş ola bilməz", updated:"Post yeniləndi", deleted:"Post silindi", marked:"İşarələndi", failed:"Uğursuz", failedLoad:"Yükləmə uğursuz", failedUpdate:"Yeniləmə uğursuz", failedDelete:"Silmə uğursuz" },
  kk: { postsCms:"Посттар CMS", searchBody:"Денеден іздеу…", posts:"Посттар", loading:"Жүктелуде…", noMatch:"Сәйкес пост жоқ.", published:"Жарияланды", draft:"Жоба", unpublished:"Жарияланбаған", bot:"🤖 Бот", zip:"Пошта индексі", tag:"Тег", body:"Дене", save:"💾 Сақтау", cancel:"Болдырмау", edit:"✏ Өңдеу", publish:"📢 Жариялау", unpublish:"🙈 Жариялаудан алу", markDraft:"📝 Жоба ретінде белгілеу", delete:"🗑 Жою", deleteTitle:"Бұл постты жою?", deleteDesc:"Лентадан біржола жояды. Аудит журналы қалады.", audit:"Аудит журналы", noActions:"Әзірге әрекет жоқ.", cannotEmpty:"Дене бос болмауы керек", updated:"Пост жаңартылды", deleted:"Пост жойылды", marked:"Белгіленді", failed:"Сәтсіз", failedLoad:"Жүктеу сәтсіз", failedUpdate:"Жаңарту сәтсіз", failedDelete:"Жою сәтсіз" },
  ky: { postsCms:"Посттор CMS", searchBody:"Денеден издөө…", posts:"Посттор", loading:"Жүктөлүүдө…", noMatch:"Туура келген пост жок.", published:"Жарыяланды", draft:"Долбоор", unpublished:"Жарыяланбаган", bot:"🤖 Бот", zip:"Почта индекси", tag:"Тег", body:"Дене", save:"💾 Сактоо", cancel:"Жокко чыгаруу", edit:"✏ Түзөтүү", publish:"📢 Жарыялоо", unpublish:"🙈 Жарыялоону алып салуу", markDraft:"📝 Долбоор белгилөө", delete:"🗑 Өчүрүү", deleteTitle:"Бул постту өчүрүү?", deleteDesc:"Лентадан биротоло өчүрөт. Аудит журналы калат.", audit:"Аудит журналы", noActions:"Азырынча аракет жок.", cannotEmpty:"Дене бош болбошу керек", updated:"Пост жаңыртылды", deleted:"Пост өчүрүлдү", marked:"Белгиленди", failed:"Ийгиликсиз", failedLoad:"Жүктөө ийгиликсиз", failedUpdate:"Жаңыртуу ийгиликсиз", failedDelete:"Өчүрүү ийгиликсиз" },
  uz: { postsCms:"Postlar CMS", searchBody:"Tana bo'ylab qidirish…", posts:"Postlar", loading:"Yuklanmoqda…", noMatch:"Mos post yo'q.", published:"Nashr etildi", draft:"Qoralama", unpublished:"Nashr etilmagan", bot:"🤖 Bot", zip:"Pochta indeksi", tag:"Teg", body:"Tana", save:"💾 Saqlash", cancel:"Bekor", edit:"✏ Tahrirlash", publish:"📢 Nashr etish", unpublish:"🙈 Nashrdan olib tashlash", markDraft:"📝 Qoralama belgilash", delete:"🗑 O'chirish", deleteTitle:"Bu postni o'chirish?", deleteDesc:"Lentadan butunlay o'chiradi. Audit jurnali qoladi.", audit:"Audit jurnali", noActions:"Hali harakat yo'q.", cannotEmpty:"Tana bo'sh bo'lmasligi kerak", updated:"Post yangilandi", deleted:"Post o'chirildi", marked:"Belgilandi", failed:"Muvaffaqiyatsiz", failedLoad:"Yuklash muvaffaqiyatsiz", failedUpdate:"Yangilash muvaffaqiyatsiz", failedDelete:"O'chirish muvaffaqiyatsiz" },
  tg: { postsCms:"CMS Паёмҳо", searchBody:"Ҷустуҷӯ дар бадан…", posts:"Паёмҳо", loading:"Боркунӣ…", noMatch:"Паёми мувофиқ нест.", published:"Нашр шуд", draft:"Пешнавис", unpublished:"Нашр нашуда", bot:"🤖 Бот", zip:"Индекси почта", tag:"Тег", body:"Бадан", save:"💾 Захира", cancel:"Бекор", edit:"✏ Таҳрир", publish:"📢 Нашр", unpublish:"🙈 Бекор кардани нашр", markDraft:"📝 Нишони пешнавис", delete:"🗑 Ҳазф", deleteTitle:"Ин паёмро ҳазф кунед?", deleteDesc:"Аз навор доимӣ ҳазф мекунад. Сабти аудит мемонад.", audit:"Сабти аудит", noActions:"Ҳанӯз амале нест.", cannotEmpty:"Бадан холӣ буда наметавонад", updated:"Паём нав шуд", deleted:"Паём ҳазф шуд", marked:"Нишон дода шуд", failed:"Ноком", failedLoad:"Боркунӣ ноком", failedUpdate:"Навсозӣ ноком", failedDelete:"Ҳазф ноком" },
  mn: { postsCms:"Постууд CMS", searchBody:"Бие хайх…", posts:"Постууд", loading:"Ачаалж байна…", noMatch:"Тохирох пост алга.", published:"Нийтлэгдсэн", draft:"Ноорог", unpublished:"Нийтлэгдээгүй", bot:"🤖 Бот", zip:"Шуудан", tag:"Шошго", body:"Бие", save:"💾 Хадгалах", cancel:"Цуцлах", edit:"✏ Засах", publish:"📢 Нийтлэх", unpublish:"🙈 Нийтлэл цуцлах", markDraft:"📝 Ноорог тэмдэглэх", delete:"🗑 Устгах", deleteTitle:"Энэ постыг устгах уу?", deleteDesc:"Feed-ээс бүрмөсөн устгана. Аудитын лог үлдэнэ.", audit:"Аудитын лог", noActions:"Одоогоор үйлдэл алга.", cannotEmpty:"Бие хоосон байж болохгүй", updated:"Пост шинэчлэгдсэн", deleted:"Пост устгагдсан", marked:"Тэмдэглэгдсэн", failed:"Амжилтгүй", failedLoad:"Ачаалал амжилтгүй", failedUpdate:"Шинэчлэл амжилтгүй", failedDelete:"Устгал амжилтгүй" },
  km: { postsCms:"CMS ប្រកាស", searchBody:"ស្វែងរកតួ…", posts:"ប្រកាស", loading:"កំពុងផ្ទុក…", noMatch:"គ្មានប្រកាសត្រូវគ្នា។", published:"បានផ្សាយ", draft:"សេចក្តីព្រាង", unpublished:"មិនបានផ្សាយ", bot:"🤖 Bot", zip:"លេខប្រៃ", tag:"ស្លាក", body:"តួ", save:"💾 រក្សាទុក", cancel:"បោះបង់", edit:"✏ កែសម្រួល", publish:"📢 ផ្សាយ", unpublish:"🙈 ដកផ្សាយ", markDraft:"📝 សម្គាល់ព្រាង", delete:"🗑 លុប", deleteTitle:"លុបប្រកាសនេះ?", deleteDesc:"លុបជាអចិន្ត្រៃយ៍ចេញពី feed។ កំណត់ហេតុសវនកម្មនៅសល់។", audit:"កំណត់ហេតុសវនកម្ម", noActions:"មិនទាន់មានសកម្មភាព។", cannotEmpty:"តួមិនអាចទទេ", updated:"ប្រកាសបានធ្វើបច្ចុប្បន្នភាព", deleted:"ប្រកាសបានលុប", marked:"បានសម្គាល់", failed:"បរាជ័យ", failedLoad:"ផ្ទុកបរាជ័យ", failedUpdate:"ធ្វើបច្ចុប្បន្នភាពបរាជ័យ", failedDelete:"លុបបរាជ័យ" },
  lo: { postsCms:"CMS ໂພສ", searchBody:"ຄົ້ນຫາເນື້ອໃນ…", posts:"ໂພສ", loading:"ກຳລັງໂຫລດ…", noMatch:"ບໍ່ມີໂພສກົງກັນ", published:"ເຜີຍແຜ່ແລ້ວ", draft:"ສະບັບຮ່າງ", unpublished:"ບໍ່ໄດ້ເຜີຍແຜ່", bot:"🤖 ບອທ", zip:"ລະຫັດໄປສະນີ", tag:"ແທັກ", body:"ເນື້ອໃນ", save:"💾 ບັນທຶກ", cancel:"ຍົກເລີກ", edit:"✏ ແກ້ໄຂ", publish:"📢 ເຜີຍແຜ່", unpublish:"🙈 ຍົກເລີກເຜີຍແຜ່", markDraft:"📝 ໝາຍວ່າຮ່າງ", delete:"🗑 ລຶບ", deleteTitle:"ລຶບໂພສນີ້?", deleteDesc:"ລຶບຖາວອນຈາກຟີດ. ບັນທຶກການກວດສອບຍັງຄົງຢູ່", audit:"ບັນທຶກການກວດສອບ", noActions:"ຍັງບໍ່ມີການກະທຳ", cannotEmpty:"ເນື້ອໃນຕ້ອງບໍ່ຫວ່າງ", updated:"ອັບເດດໂພສແລ້ວ", deleted:"ລຶບໂພສແລ້ວ", marked:"ໝາຍແລ້ວ", failed:"ລົ້ມເຫລວ", failedLoad:"ໂຫລດລົ້ມເຫລວ", failedUpdate:"ອັບເດດລົ້ມເຫລວ", failedDelete:"ລຶບລົ້ມເຫລວ" },
  my: { postsCms:"ပို့စ် CMS", searchBody:"ကိုယ်ထည်ရှာရန်…", posts:"ပို့စ်များ", loading:"တင်နေသည်…", noMatch:"ကိုက်ညီသောပို့စ်မရှိ။", published:"ထုတ်ဝေပြီး", draft:"မူကြမ်း", unpublished:"မထုတ်ဝေရသေး", bot:"🤖 ဘော့", zip:"စာတိုက်ကုဒ်", tag:"တဂ်", body:"ကိုယ်ထည်", save:"💾 သိမ်းဆည်း", cancel:"ပယ်ဖျက်", edit:"✏ တည်းဖြတ်", publish:"📢 ထုတ်ဝေ", unpublish:"🙈 ထုတ်ဝေမှုဖျက်", markDraft:"📝 မူကြမ်းအဖြစ်သတ်မှတ်", delete:"🗑 ဖျက်", deleteTitle:"ဤပို့စ်ဖျက်မလား?", deleteDesc:"ဖိဒ်မှ အပြီးဖျက်မည်။ စာရင်းစစ်မှတ်တမ်းကျန်မည်။", audit:"စာရင်းစစ်မှတ်တမ်း", noActions:"လုပ်ဆောင်ချက်မရှိသေး။", cannotEmpty:"ကိုယ်ထည်အလွတ်မရပါ", updated:"ပို့စ်အပ်ဒိတ်လုပ်ပြီး", deleted:"ပို့စ်ဖျက်ပြီး", marked:"အမှတ်အသားပြုပြီး", failed:"ကျရှုံး", failedLoad:"တင်မှုကျရှုံး", failedUpdate:"အပ်ဒိတ်ကျရှုံး", failedDelete:"ဖျက်မှုကျရှုံး" },
}

type AdminPostDTO = { id: string; body: string; tag: string | null; zip_code: string | null; visibility: 'published' | 'draft' | 'unpublished'; author_is_bot: boolean; author_name: string | null; user_id: string; created_at: string }
type PostVisibility = 'published' | 'draft' | 'unpublished'

async function listAdminPosts(filter: any): Promise<AdminPostDTO[]> {
  try {
    const supabase = createClient() as any
    let query = supabase.from('posts').select('*, profiles(full_name, is_bot)').order('created_at', { ascending: false }).limit(50)
    if (filter.user_id) query = query.eq('user_id', filter.user_id)
    if (filter.user_ids) query = query.in('user_id', filter.user_ids)
    if (filter.zip_code) query = query.eq('zip_code', filter.zip_code)
    if (filter.search) { const safe = String(filter.search).slice(0,80).replace(/[%_]/g,''); if (safe) query = query.ilike('body', `%${safe}%`) }
    const { data, error } = await query
    if (error) throw error
    return (data || []).map((p: any) => ({...p, author_name: p.profiles?.full_name, author_is_bot: p.profiles?.is_bot || false }))
  } catch { return [] }
}
async function updateAdminPost({ id, body, tag }: any) { const supabase = createClient() as any; const { error } = await supabase.from('posts').update({ body, tag }).eq('id', id); if (error) throw error }
async function deleteAdminPost({ id }: any) { const supabase = createClient() as any; const { error } = await supabase.from('posts').delete().eq('id', id); if (error) throw error }
async function setAdminPostVisibility({ id, visibility }: any) { const supabase = createClient() as any; const { error } = await supabase.from('posts').update({ visibility }).eq('id', id); if (error) throw error }
async function listPostAuditLog(filter: any): Promise<any[]> {
  try {
    const supabase = createClient() as any
    let q = supabase.from('post_audit_log').select('*').order('created_at', { ascending: false }).limit(filter.limit || 200)
    const { data, error } = await q
    if (error) throw error
    return data || []
  } catch { return [] }
}

function Button({ size, variant, onClick, disabled, children,...props }: any) {
  const base = 'rounded-md px-3 py-2 text-sm font-medium disabled:opacity-50'
  const variants: any = { default: 'bg-primary text-primary-foreground hover:bg-primary/90', outline: 'border border-border bg-background hover:bg-secondary', secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80', ghost: 'hover:bg-secondary', destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90' }
  return <button onClick={(e)=>{ try { onClick?.(e) } catch {} }} disabled={disabled} className={`${base} ${variants[variant] || variants.default}`} {...props}>{children}</button>
}
function Input(props: any) { return <input {...props} className="w-full rounded-xl border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary" /> }
function Textarea(props: any) { return <textarea {...props} className="w-full rounded-xl border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary" /> }
function Badge({ className, variant, children }: any) {
  const base = 'inline-flex items-center rounded-full px-2 py-0.5 text-xs font-semibold'
  const variants: any = { default: 'bg-primary/10 text-primary', secondary: 'bg-secondary text-secondary-foreground', outline: 'border border-border' }
  return <span className={`${base} ${variants[variant] || variants.default} ${className || ''}`}>{children}</span>
}
function AlertDialog({ children }: any) { return <>{children}</> }
function AlertDialogTrigger({ children }: any) { return children }
function AlertDialogContent({ children }: any) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"><div className="rounded-2xl bg-card p-6 max-w-md">{children}</div></div> }
function AlertDialogHeader({ children }: any) { return <div className="mb-4">{children}</div> }
function AlertDialogTitle({ children }: any) { return <h3 className="text-lg font-semibold">{children}</h3> }
function AlertDialogDescription({ children }: any) { return <p className="text-sm text-muted-foreground">{children}</p> }
function AlertDialogFooter({ children }: any) { return <div className="mt-4 flex justify-end gap-2">{children}</div> }
function AlertDialogCancel({ children }: any) { return <Button variant="ghost">{children}</Button> }
function AlertDialogAction({ onClick, children }: any) { return <Button variant="destructive" onClick={onClick}>{children}</Button> }
const toast = { success: (msg: string) => { try { console.log(`✓ ${msg}`) } catch {} }, error: (msg: string) => { try { console.log(`✗ ${msg}`) } catch {} } }

type Props = { title?: string; description?: string; userId?: string; userIds?: string[]; scope: string; zip_code?: string; showSearch?: boolean }
function visibilityBadge(v: PostVisibility, d: any) { if (v === 'published') return <Badge className="bg-green-600">{d.published}</Badge>; if (v === 'draft') return <Badge variant="secondary">{d.draft}</Badge>; return <Badge variant="outline">{d.unpublished}</Badge> }

export function PostsCmsPanel({ title = 'Posts CMS', description, userId, userIds, scope, zip_code, showSearch = true }: Props) {
  const [search, setSearch] = useState('')
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editBody, setEditBody] = useState('')
  const [editTag, setEditTag] = useState('')
  const [busy, setBusy] = useState(false)
  const [posts, setPosts] = useState<AdminPostDTO[]>([])
  const [audit, setAudit] = useState<any[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const { language } = useLanguage()
  const d = D[language] || D.en

  const refresh = async () => {
    try { setIsLoading(true); const filter = { user_id: userId, user_ids: userIds, zip_code: zip_code, search: search || undefined }; const [p, a] = await Promise.all([listAdminPosts(filter), listPostAuditLog({ user_id: userId, user_ids: userIds, limit: 200 })]); setPosts(p); setAudit(a) } catch (err: any) { toast.error(err?.message?? d.failedLoad) } finally { try { setIsLoading(false) } catch {} }
  }

  useEffect(() => { refresh() }, [search, userId, zip_code])
  const invalidate = () => { try { refresh() } catch {} }
  const beginEdit = (p: AdminPostDTO) => { setEditingId(p.id); setEditBody(p.body); setEditTag(p.tag?? '') }
  const saveEdit = async () => {
    if (!editingId) return; if (!editBody.trim()) { toast.error(d.cannotEmpty); return }
    setBusy(true)
    try { await updateAdminPost({ id: editingId, body: editBody.trim(), tag: editTag.trim() }); toast.success(d.updated); setEditingId(null); invalidate() } catch (err: any) { toast.error(err?.message?? d.failedUpdate) } finally { try { setBusy(false) } catch {} }
  }
  const onDelete = async (id: string) => { try { await deleteAdminPost({ id }); toast.success(d.deleted); if (editingId === id) setEditingId(null); invalidate() } catch (err: any) { toast.error(err?.message?? d.failedDelete) } }
  const onSetVis = async (id: string, visibility: PostVisibility) => { try { await setAdminPostVisibility({ id, visibility }); toast.success(`${d.marked} ${visibility}`); invalidate() } catch (err: any) { toast.error(err?.message?? d.failed) } }

  return (
    <section className="space-y-6">
      <header><h2 className="font-display text-xl font-semibold">{title || d.postsCms}</h2>{description && (<p className="mt-1 text-sm text-muted-foreground">{description}</p>)}</header>
      {showSearch && (<Input placeholder={d.searchBody} value={search} onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSearch(e.target.value)} maxLength={120} />)}
      <div className="space-y-3">
        <h3 className="text-sm font-semibold">{d.posts} ({posts.length}) {zip_code? `• ${zip_code}`:''}</h3>
        {isLoading && <p className="text-sm text-muted-foreground">{d.loading}</p>}
        {!isLoading && posts.length === 0 && (<p className="rounded-xl border border-dashed border-border p-4 text-sm text-muted-foreground">{d.noMatch}</p>)}
        {posts.map((p) => {
          const isEditing = editingId === p.id
          return (
            <article key={p.id} className="rounded-xl border border-border bg-card p-4">
              <div className="flex flex-wrap items-center gap-2">{visibilityBadge(p.visibility, d)}{p.author_is_bot && <Badge variant="outline">{d.bot}</Badge>}{p.tag && <Badge variant="outline">{p.tag}</Badge>}{p.zip_code && (<Badge variant="outline">{d.zip} {p.zip_code}</Badge>)}<span className="text-xs text-muted-foreground">{p.author_name?? p.user_id.slice(0, 8)}</span><span className="ml-auto text-xs text-muted-foreground">{new Date(p.created_at).toLocaleString()}</span></div>
              {isEditing? (
                <div className="mt-3 space-y-3"><label className="block text-sm"><span className="text-muted-foreground">{d.tag}</span><Input value={editTag} onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEditTag(e.target.value)} maxLength={40} /></label><label className="block text-sm"><span className="text-muted-foreground">{d.body} ({editBody.length}/2000)</span><Textarea value={editBody} onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setEditBody(e.target.value)} maxLength={2000} rows={6} /></label><div className="flex gap-2"><Button size="sm" onClick={saveEdit} disabled={busy}>{d.save}</Button><Button size="sm" variant="ghost" onClick={() => setEditingId(null)}>{d.cancel}</Button></div></div>
              ) : (<pre className="mt-2 whitespace-pre-wrap text-sm">{p.body}</pre>)}
              {!isEditing && (<div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => beginEdit(p)}>{d.edit}</Button>{p.visibility!== 'published' && (<Button size="sm" onClick={() => onSetVis(p.id, 'published')}>{d.publish}</Button>)}{p.visibility === 'published' && (<Button size="sm" variant="secondary" onClick={() => onSetVis(p.id, 'unpublished')}>{d.unpublish}</Button>)}{p.visibility!== 'draft' && (<Button size="sm" variant="ghost" onClick={() => onSetVis(p.id, 'draft')}>{d.markDraft}</Button>)}<AlertDialog><AlertDialogTrigger><Button size="sm" variant="destructive">{d.delete}</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{d.deleteTitle}</AlertDialogTitle><AlertDialogDescription>{d.deleteDesc}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{d.cancel}</AlertDialogCancel><AlertDialogAction onClick={() => onDelete(p.id)}>{d.delete}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>)}
            </article>
          )
        })}
      </div>
      <div className="space-y-3"><h3 className="text-sm font-semibold">{d.audit} ({audit.length})</h3><div className="rounded-xl border border-border bg-card">{audit.length === 0 && (<p className="p-4 text-sm text-muted-foreground">{d.noActions}</p>)}{audit.map((row) => (<div key={row.id} className="border-b border-border p-3 text-sm last:border-b-0"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className="text-xs uppercase">{row.action}</Badge><span className="font-medium">{row.actor_is_bot? '🤖 ' : ''}{row.actor_name?? row.actor_id?.slice(0, 8)?? 'system'}</span><span className="text-xs text-muted-foreground">{new Date(row.created_at).toLocaleString()}</span>{row.post_id && (<span className="ml-auto font-mono text-xs text-muted-foreground">{row.post_id.slice(0, 8)}</span>)}</div>{row.snapshot?.body && (<p className="mt-1 line-clamp-2 text-xs text-muted-foreground">"{String(row.snapshot.body).slice(0, 160)}"</p>)}</div>))}</div></div>
    </section>
  )
}
