'use client'
import { useState, useEffect, useId, useRef } from 'react'
import { toast } from 'sonner'
import MicRecorder from '@/components/mic/MicRecorder'
import { createClient } from '@/lib/supabase/client'
import { useLanguage } from '@/lib/language-context'

const D: Record<string, any> = {
  en: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue. False reporting can affect your account standing.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment or bullying", spam:"Spam or misleading", hate:"Hate speech", violence:"Violence or dangerous acts", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  es: { thanks:"Gracias por reportar", review:"Un moderador revisara este", confidential:"Los reportes son confidenciales.", close:"Cerrar", reportThis:"Reportar este", queue:"Los reportes van a moderacion. Reportes falsos afectan tu cuenta.", reason:"Razon", details:"Detalles (opcional)", placeholder:"Algo que ayude a revisar.", cancel:"Cancelar", sending:"Enviando...", submit:"Enviar reporte", submitted:"Reporte enviado", harassment:"Acoso o bullying", spam:"Spam o enganoso", hate:"Discurso de odio", violence:"Violencia o actos peligrosos", misinfo:"Desinformacion", illegal:"Actividad ilegal", other:"Otro" },
  fr: { thanks:"Merci pour le signalement", review:"Un moderateur examinera ce", confidential:"Signalements confidentiels.", close:"Fermer", reportThis:"Signaler ce", queue:"Les signalements vont a la moderation. Faux signalements affectent votre compte.", reason:"Raison", details:"Details (optionnel)", placeholder:"Tout ce qui aide l'examen.", cancel:"Annuler", sending:"Envoi...", submit:"Envoyer signalement", submitted:"Signalement envoye", harassment:"Harcelement", spam:"Spam ou trompeur", hate:"Discours haineux", violence:"Violence ou actes dangereux", misinfo:"Desinformation", illegal:"Activite illegale", other:"Autre" },
  de: { thanks:"Danke fur die Meldung", review:"Ein Moderator pruft dieses", confidential:"Meldungen sind vertraulich.", close:"Schliessen", reportThis:"Dieses melden", queue:"Meldungen gehen an Moderation. Falschmeldungen beeinflussen Konto.", reason:"Grund", details:"Details (optional)", placeholder:"Was bei Prufung hilft.", cancel:"Abbrechen", sending:"Senden...", submit:"Meldung senden", submitted:"Meldung gesendet", harassment:"Belastigung", spam:"Spam oder irrefuhrend", hate:"Hassrede", violence:"Gewalt oder gefahrlich", misinfo:"Fehlinformation", illegal:"Illegale Aktivitat", other:"Andere" },
  zh: { thanks:"感谢举报", review:"管理员将审核此", confidential:"举报保密。", close:"关闭", reportThis:"举报此", queue:"举报进入审核队列。虚假举报影响账户。", reason:"原因", details:"详情（可选）", placeholder:"有助于审核的任何信息。", cancel:"取消", sending:"发送中...", submit:"提交举报", submitted:"已提交举报", harassment:"骚扰或霸凌", spam:"垃圾或误导", hate:"仇恨言论", violence:"暴力或危险行为", misinfo:"虚假信息", illegal:"非法活动", other:"其他" },
  ja: { thanks:"報告ありがとう", review:"モデレーターがこの", confidential:"報告は機密です。", close:"閉じる", reportThis:"このを報告", queue:"報告はモデレーションへ。虚偽報告はアカウントに影響。", reason:"理由", details:"詳細（任意）", placeholder:"レビューに役立つ内容。", cancel:"キャンセル", sending:"送信中...", submit:"報告を送信", submitted:"報告を送信しました", harassment:"嫌がらせ", spam:"スパム", hate:"ヘイトスピーチ", violence:"暴力", misinfo:"誤情報", illegal:"違法行為", other:"その他" },
  ko: { thanks:"신고 감사합니다", review:"관리자가 이", confidential:"신고는 비공개입니다。", close:"닫기", reportThis:"이 신고", queue:"신고는 검토 대기열로。허위 신고는 계정에 영향。", reason:"사유", details:"세부사항(선택)", placeholder:"검토에 도움되는 내용。", cancel:"취소", sending:"전송중...", submit:"신고 제출", submitted:"신고 제출됨", harassment:"괴롭힘", spam:"스팸", hate:"혐오 발언", violence:"폭력", misinfo:"허위정보", illegal:"불법 활동", other:"기타" },
  pt: { thanks:"Obrigado por denunciar", review:"Um moderador vai revisar este", confidential:"Denuncias sao confidenciais.", close:"Fechar", reportThis:"Denunciar este", queue:"Denuncias vao para moderacao. Denuncias falsas afetam sua conta.", reason:"Motivo", details:"Detalhes (opcional)", placeholder:"O que ajuda na revisao.", cancel:"Cancelar", sending:"Enviando...", submit:"Enviar denuncia", submitted:"Denuncia enviada", harassment:"Assedio", spam:"Spam", hate:"Discurso de odio", violence:"Violencia", misinfo:"Desinformacao", illegal:"Atividade ilegal", other:"Outro" },
  it: { thanks:"Grazie per la segnalazione", review:"Un moderatore esaminera questo", confidential:"Segnalazioni riservate.", close:"Chiudi", reportThis:"Segnala questo", queue:"Segnalazioni in coda moderazione. False segnalazioni influiscono sull'account.", reason:"Motivo", details:"Dettagli (opzionale)", placeholder:"Qualcosa che aiuti la revisione.", cancel:"Annulla", sending:"Invio...", submit:"Invia segnalazione", submitted:"Segnalazione inviata", harassment:"Molestie", spam:"Spam", hate:"Incitamento odio", violence:"Violenza", misinfo:"Disinformazione", illegal:"Attivita illegale", other:"Altro" },
  nl: { thanks:"Bedankt voor melding", review:"Moderator beoordeelt dit", confidential:"Meldingen zijn vertrouwelijk.", close:"Sluiten", reportThis:"Dit melden", queue:"Meldingen naar moderatie. Valse meldingen beinvloeden account.", reason:"Reden", details:"Details (optioneel)", placeholder:"Wat helpt bij beoordeling.", cancel:"Annuleren", sending:"Verzenden...", submit:"Melding versturen", submitted:"Melding verzonden", harassment:"Intimidatie", spam:"Spam", hate:"Haatspraak", violence:"Geweld", misinfo:"Desinformatie", illegal:"Illegale activiteit", other:"Anders" },
  id: { thanks:"Terima kasih melapor", review:"Moderator akan meninjau ini", confidential:"Laporan rahasia.", close:"Tutup", reportThis:"Laporkan ini", queue:"Laporan ke antrian moderasi. Laporan palsu mempengaruhi akun.", reason:"Alasan", details:"Detail (opsional)", placeholder:"Apa pun yang membantu tinjauan.", cancel:"Batal", sending:"Mengirim...", submit:"Kirim laporan", submitted:"Laporan terkirim", harassment:"Pelecehan", spam:"Spam", hate:"Ujaran kebencian", violence:"Kekerasan", misinfo:"Misinformasi", illegal:"Aktivitas ilegal", other:"Lainnya" },
  vi: { thanks:"Cam on da bao cao", review:"Kiem duyet vien se xem xet", confidential:"Bao cao bao mat.", close:"Dong", reportThis:"Bao cao", queue:"Bao cao vao hang doi kiem duyet. Bao cao sai anh huong tai khoan.", reason:"Ly do", details:"Chi tiet (tuy chon)", placeholder:"Dieu gi giup xem xet.", cancel:"Huy", sending:"Dang gui...", submit:"Gui bao cao", submitted:"Da gui bao cao", harassment:"Quay roi", spam:"Spam", hate:"Ngon tu thu han", violence:"Bao luc", misinfo:"Sai lech", illegal:"Hoat dong bat hop phap", other:"Khac" },
  sv: { thanks:"Tack for rapport", review:"Moderator granskar detta", confidential:"Rapporter ar konfidentiella.", close:"Stang", reportThis:"Rapportera detta", queue:"Rapporter till moderationsko. Falska rapporter paverkar konto.", reason:"Anledning", details:"Detaljer (valfritt)", placeholder:"Vad som hjalper granskning.", cancel:"Avbryt", sending:"Skickar...", submit:"Skicka rapport", submitted:"Rapport skickad", harassment:"Trakasserier", spam:"Spam", hate:"Hatretorik", violence:"Vald", misinfo:"Desinformation", illegal:"Olaglig aktivitet", other:"Annat" },
  pl: { thanks:"Dzieki za zgloszenie", review:"Moderator sprawdzi to", confidential:"Zgloszenia poufne.", close:"Zamknij", reportThis:"Zglos to", queue:"Zgloszenia do moderacji. Falszywe zgloszenia wplywaja na konto.", reason:"Powod", details:"Szczegoly (opcjonalnie)", placeholder:"Co pomoze w weryfikacji.", cancel:"Anuluj", sending:"Wysylanie...", submit:"Wyslij zgloszenie", submitted:"Zgloszenie wyslane", harassment:"Nekanie", spam:"Spam", hate:"Mowa nienawisci", violence:"Przemoc", misinfo:"Dezinformacja", illegal:"Nielegalna aktywnosc", other:"Inne" },
  tr: { thanks:"Bildirdiginiz icin tesekkurler", review:"Moderator bunu inceleyecek", confidential:"Bildirimler gizlidir.", close:"Kapat", reportThis:"Bunu bildir", queue:"Bildirimler moderasyona gider. Yanlis bildirim hesabi etkiler.", reason:"Sebep", details:"Detaylar (istege bagli)", placeholder:"Incelemeye yardimci olacak sey.", cancel:"Iptal", sending:"Gonderiliyor...", submit:"Bildirim gonder", submitted:"Bildirim gonderildi", harassment:"Taciz", spam:"Spam", hate:"Nefret soylemi", violence:"Siddet", misinfo:"Yanlis bilgi", illegal:"Yasa disi faaliyet", other:"Diger" },
  ms: { thanks:"Terima kasih melapor", review:"Moderator akan semak ini", confidential:"Laporan sulit.", close:"Tutup", reportThis:"Lapor ini", queue:"Laporan ke barisan moderasi. Laporan palsu jejas akaun.", reason:"Sebab", details:"Butiran (pilihan)", placeholder:"Apa yang membantu semakan.", cancel:"Batal", sending:"Menghantar...", submit:"Hantar laporan", submitted:"Laporan dihantar", harassment:"Gangguan", spam:"Spam", hate:"Ucapan benci", violence:"Keganasan", misinfo:"Maklumat salah", illegal:"Aktiviti haram", other:"Lain" },
  ro: { thanks:"Multumesc pentru raportare", review:"Un moderator va revizui acest", confidential:"Rapoartele sunt confidentiale.", close:"Inchide", reportThis:"Raporteaza acest", queue:"Rapoartele merg la moderare. Raportari false afecteaza contul.", reason:"Motiv", details:"Detalii (optional)", placeholder:"Ce ajuta la verificare.", cancel:"Anuleaza", sending:"Se trimite...", submit:"Trimite raport", submitted:"Raport trimis", harassment:"Hartuire", spam:"Spam", hate:"Discurs de ura", violence:"Violenta", misinfo:"Dezinformare", illegal:"Activitate ilegala", other:"Altul" },
  cs: { thanks:"Diky za nahlaseni", review:"Moderator zkontroluje toto", confidential:"Hlaseni jsou duverna.", close:"Zavrit", reportThis:"Nahlasit toto", queue:"Hlaseni do fronty moderace. Falesna hlaseni ovlivnuji ucet.", reason:"Duvod", details:"Detaily (volitelne)", placeholder:"Co pomuze kontrole.", cancel:"Zrusit", sending:"Odesilani...", submit:"Odeslat hlaseni", submitted:"Hlaseni odeslano", harassment:"Obtězovani", spam:"Spam", hate:"Nenavistny projev", violence:"Nasili", misinfo:"Dezinformace", illegal:"Nelegalni cinnost", other:"Jine" },
  hu: { thanks:"Koszonjuk a jelentest", review:"Moderator atnezi ezt", confidential:"Jelentesek bizalmasak.", close:"Bezar", reportThis:"Jelentse ezt", queue:"Jelentesek moderacios sorba. Hamis jelentesek hatnak fiokra.", reason:"Ok", details:"Reszletek (opcionalis)", placeholder:"Mi segiti az ellenorzest.", cancel:"Megse", sending:"Kuldes...", submit:"Jelentes kuldese", submitted:"Jelentes elkuldve", harassment:"Zaklatas", spam:"Spam", hate:"Gyuloletbeszed", violence:"Eroszak", misinfo:"Dezinformacio", illegal:"Illegalis tevekenyseg", other:"Egyeb" },
  fi: { thanks:"Kiitos ilmoituksesta", review:"Moderaattori tarkistaa taman", confidential:"Ilmoitukset luottamuksellisia.", close:"Sulje", reportThis:"Ilmoita tama", queue:"Ilmoitukset moderointijonoon. Vaarat ilmoitukset vaikuttavat tiliin.", reason:"Syy", details:"Tiedot (valinnainen)", placeholder:"Mika auttaa tarkistuksessa.", cancel:"Peruuta", sending:"Lahetetaan...", submit:"Laheta ilmoitus", submitted:"Ilmoitus lahetetty", harassment:"Hairinta", spam:"Roskaposti", hate:"Vihapuhe", violence:"Vakivalta", misinfo:"Vaara tieto", illegal:"Laiton toiminta", other:"Muu" },
  no: { thanks:"Takk for rapport", review:"Moderator gjennomgar dette", confidential:"Rapporter er konfidensielle.", close:"Lukk", reportThis:"Rapporter dette", queue:"Rapporter til modereringsko. Falske rapporter pavirker konto.", reason:"Grunn", details:"Detaljer (valgfritt)", placeholder:"Hva som hjelper gjennomgang.", cancel:"Avbryt", sending:"Sender...", submit:"Send rapport", submitted:"Rapport sendt", harassment:"Trakassering", spam:"Spam", hate:"Hatefulle ytringer", violence:"Vold", misinfo:"Feilinformasjon", illegal:"Ulovlig aktivitet", other:"Annet" },
  da: { thanks:"Tak for anmeldelse", review:"Moderator gennemgar dette", confidential:"Anmeldelser er fortrolige.", close:"Luk", reportThis:"Anmeld dette", queue:"Anmeldelser til modereringsko. Falske anmeldelser pavirker konto.", reason:"Arsag", details:"Detaljer (valgfrit)", placeholder:"Hvad der hjaelper gennemgang.", cancel:"Annuller", sending:"Sender...", submit:"Send anmeldelse", submitted:"Anmeldelse sendt", harassment:"Chikane", spam:"Spam", hate:"Hadefuld tale", violence:"Vold", misinfo:"Misinformation", illegal:"Ulovlig aktivitet", other:"Andet" },
  hr: { thanks:"Hvala na prijavi", review:"Moderator ce pregledati ovo", confidential:"Prijave su povjerljive.", close:"Zatvori", reportThis:"Prijavi ovo", queue:"Prijave idu u red moderacije. Lazne prijave utjecu na racun.", reason:"Razlog", details:"Detalji (opcionalno)", placeholder:"Sto pomaze pregledu.", cancel:"Otkazi", sending:"Slanje...", submit:"Posalji prijavu", submitted:"Prijava poslana", harassment:"Uznemiravanje", spam:"Spam", hate:"Govor mrznje", violence:"Nasilje", misinfo:"Dezinformacije", illegal:"Nezakonita aktivnost", other:"Ostalo" },
  sk: { thanks:"Dakujeme za nahlasenie", review:"Moderator skontroluje toto", confidential:"Nahlasenia su doverne.", close:"Zavriet", reportThis:"Nahlasit toto", queue:"Nahlasenia do moderacnej fronty. Falesne nahlasenia ovplyvnuju ucet.", reason:"Dovod", details:"Detaily (volitelne)", placeholder:"Co pomoze kontrole.", cancel:"Zrusit", sending:"Odosielanie...", submit:"Odoslat nahlasenie", submitted:"Nahlasenie odoslane", harassment:"Obtazovanie", spam:"Spam", hate:"Nenavistny prejav", violence:"Nasilie", misinfo:"Dezinformacie", illegal:"Nelegalna cinnost", other:"Ine" },
  sl: { thanks:"Hvala za prijavo", review:"Moderator bo pregledal to", confidential:"Prijave so zaupne.", close:"Zapri", reportThis:"Prijavi to", queue:"Prijave v vrsto moderiranja. Lazne prijave vplivajo na racun.", reason:"Razlog", details:"Podrobnosti (neobvezno)", placeholder:"Kaj pomaga pregledu.", cancel:"Preklici", sending:"Posiljanje...", submit:"Poslji prijavo", submitted:"Prijava poslana", harassment:"Nadlegovanje", spam:"Spam", hate:"Sovrazni govor", violence:"Nasilje", misinfo:"Dezinformacije", illegal:"Nezakonita dejavnost", other:"Drugo" },
  et: { thanks:"Aitah teatamise eest", review:"Moderaator vaatab selle ule", confidential:"Teated on konfidentsiaalsed.", close:"Sulge", reportThis:"Teata sellest", queue:"Teated moderatsiooni jarjekorda. Vaar teated mojutavad kontot.", reason:"Pohjus", details:"Detailid (valikuline)", placeholder:"Mis aitab ulevaatust.", cancel:"Katkesta", sending:"Saatmine...", submit:"Saada teade", submitted:"Teade saadetud", harassment:"Ahistamine", spam:"Rams", hate:"Vihakone", violence:"Vagivald", misinfo:"Desinformatsioon", illegal:"Ebaseaduslik tegevus", other:"Muu" },
  az: { thanks:"Melumat verdiyiniz ucun tesekkurler", review:"Moderator bunu yoxlayacaq", confidential:"Melumatlar mexfidir.", close:"Bagla", reportThis:"Bunu bildir", queue:"Melumatlar moderasiya novbesine gedir. Yalan melumat hesaba tesir edir.", reason:"Sebeb", details:"Tefsilatlar (isteye bagli)", placeholder:"Yoxlamaga komek eden.", cancel:"Legv et", sending:"Gonderilir...", submit:"Melumat gonder", submitted:"Melumat gonderildi", harassment:"Taciz", spam:"Spam", hate:"Nifret nitqi", violence:"Zorakiliq", misinfo:"Yalan melumat", illegal:"Qanunsuz fealiyyet", other:"Diger" },
  uz: { thanks:"Xabar bergan uchun rahmat", review:"Moderator buni korib chiqadi", confidential:"Xabarlar maxfiy.", close:"Yopish", reportThis:"Buni xabar qilish", queue:"Xabarlar moderatsiya navbatiga. Yolgon xabarlar hisobga tasir qiladi.", reason:"Sabab", details:"Tafsilotlar (ixtiyoriy)", placeholder:"Korib chiqishga yordam beradigan.", cancel:"Bekor", sending:"Yuborilmoqda...", submit:"Xabar yuborish", submitted:"Xabar yuborildi", harassment:"Taciz", spam:"Spam", hate:"Nafrat nutqi", violence:"Zoravonlik", misinfo:"Noto gri malumot", illegal:"Noqonuniy faoliyat", other:"Boshqa" },
  bg: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  bn: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  th: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  el: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  he: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  ur: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  fa: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  sr: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  lv: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  lt: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  be: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  ka: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  hy: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  kk: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  ky: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  tg: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  mn: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  km: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  lo: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
  my: { thanks:"Thanks for reporting", review:"A moderator will review this", confidential:"Reports are confidential.", close:"Close", reportThis:"Report this", queue:"Reports go to our moderation queue.", reason:"Reason", details:"Details (optional)", placeholder:"Anything that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", submitted:"Report submitted", harassment:"Harassment", spam:"Spam", hate:"Hate speech", violence:"Violence", misinfo:"Misinformation", illegal:"Illegal activity", other:"Other" },
}

type ReportTargetType = 'post' | 'comment' | 'user' | 'business' | 'message'
type ReportCategory = 'harassment' | 'spam' | 'hate_speech' | 'violence' | 'misinformation' | 'illegal' | 'other'
const REPORT_CATEGORIES: ReportCategory[] = ['harassment','spam','hate_speech','violence','misinformation','illegal','other']

async function submitReport(data: { target_type: ReportTargetType; target_id: string; category: ReportCategory; details?: string; turnstile_token?: string }) {
  try {
    const supabase = createClient() as any
    let user: any = null
    try { const { data: u } = await supabase.auth.getUser(); user = u.user } catch {}
    if (!user) throw new Error('Not authenticated')
    const { error } = await supabase.from('reports').insert({ target_type: data.target_type, target_id: data.target_id, category: data.category, details: data.details || null, reporter_id: user.id })
    if (error) throw error
  } catch (e) { throw e }
}

type Props = { targetType: ReportTargetType; targetId: string; label?: string; onClose: () => void }
const TURNSTILE_SITE_KEY = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY

export function ReportDialog({ targetType, targetId, label, onClose }: Props) {
  const { language } = useLanguage()
  const t = D[language] || D.en
  const REPORT_LABEL: Record<ReportCategory, string> = {
    harassment: t.harassment, spam: t.spam, hate_speech: t.hate,
    violence: t.violence, misinformation: t.misinfo, illegal: t.illegal, other: t.other,
  }
  const [category, setCategory] = useState<ReportCategory>('harassment')
  const [details, setDetails] = useState('')
  const [busy, setBusy] = useState(false)
  const [done, setDone] = useState(false)
  const [error, setError] = useState('')
  const [turnstileToken, setTurnstileToken] = useState<string | null>(null)
  const noun = label?? targetType.replace(/_/g, ' ')

  async function onSubmit() {
    try { setBusy(true); setError(''); await submitReport({ target_type: targetType, target_id: targetId, category, details: details.trim() || undefined, turnstile_token: turnstileToken?? undefined }); setDone(true); try { toast.success(t.submitted) } catch {} }
    catch (e) { try { const msg = e instanceof Error? e.message : 'Failed to submit report'; setError(msg) } catch {} }
    finally { try { setBusy(false) } catch {} }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4" onClick={onClose}>
      <div className="w-full max-w-md rounded-2xl border border-border bg-card p-5 shadow-xl" onClick={(e) => e.stopPropagation()}>
        {done? (
          <>
            <h2 className="font-display text-lg font-semibold">{t.thanks}</h2>
            <p className="mt-2 text-sm text-muted-foreground">{t.review} {noun}. {t.confidential}</p>
            <div className="mt-4 flex justify-end"><button onClick={onClose} className="rounded-full bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">{t.close}</button></div>
          </>
        ) : (
          <>
            <h2 className="font-display text-lg font-semibold">{t.reportThis} {noun}</h2>
            <p className="mt-1 text-xs text-muted-foreground">{t.queue}</p>
            <label className="mt-4 block text-sm font-medium">{t.reason}</label>
            <select value={category} onChange={(e) => setCategory(e.target.value as ReportCategory)} className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2 text-sm">{REPORT_CATEGORIES.map((c) => (<option key={c} value={c}>{REPORT_LABEL[c]}</option>))}</select>
            <label className="mt-3 block text-sm font-medium">{t.details}</label>
            <textarea value={details} onChange={(e) => setDetails(e.target.value)} maxLength={1000} rows={3} className="mt-1 w-full resize-none rounded-xl border border-border bg-background px-3 py-2 text-sm" placeholder={t.placeholder} />
            <div className="mt-1 flex justify-end"><MicRecorder onTranscript={setDetails} /></div>
            {TURNSTILE_SITE_KEY && (<TurnstileWidgetSafe siteKey={TURNSTILE_SITE_KEY} onToken={setTurnstileToken} />)}
            {error && <p className="mt-2 text-sm text-destructive">{error}</p>}
            <div className="mt-4 flex justify-end gap-2">
              <button onClick={onClose} className="rounded-full border border-border px-4 py-2 text-sm hover:bg-secondary">{t.cancel}</button>
              <button onClick={()=>{ try { onSubmit() } catch {} }} disabled={busy || (!!TURNSTILE_SITE_KEY &&!turnstileToken)} className="rounded-full bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50">{busy? t.sending : t.submit}</button>
            </div>
          </>
        )}
      </div>
    </div>
  )
}

function TurnstileWidgetSafe({ siteKey, onToken }: { siteKey: string; onToken: (t: string) => void }) {
  const uid = useId().replace(/:/g,'')
  const containerId = `ts-${uid}-${siteKey.slice(0, 8)}`
  const renderedRef = useRef(false)
  useEffect(()=>{
    try {
      if (typeof window === 'undefined' ||!siteKey) return
      try { if (!document.querySelector('script[data-turnstile]')) { const s = document.createElement('script'); s.src = 'https://challenges.cloudflare.com/turnstile/v0/api.js'; s.async = true; s.defer = true; s.setAttribute('data-turnstile','1'); document.head.appendChild(s) } } catch {}
      const w = window as any
      const tryRender = () => { try { const el = document.getElementById(containerId); if (!el || renderedRef.current ||!w.turnstile) return false; renderedRef.current = true; w.turnstile.render(`#${containerId}`, { sitekey: siteKey, callback: (tok:string)=>{ try { onToken(tok) } catch {} } }); return true } catch { return false } }
      if (!tryRender()) { const iv = setInterval(()=>{ try { if (tryRender()) clearInterval(iv) } catch {} },250); const to = setTimeout(()=>{ try { clearInterval(iv) } catch {} },8000); return ()=>{ try { clearInterval(iv) } catch {}; try { clearTimeout(to) } catch {} } }
    } catch {}
  },[containerId, siteKey, onToken])
  return <div id={containerId} className="mt-3" />
}
