'use client'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import MicRecorder from '@/components/mic/MicRecorder'
import { useLanguage } from '@/lib/language-context'

const D: Record<string, any> = {
  en: { thanks:"Thanks for reporting", team:"Our team will review this post. Repeat-reported posts are automatically hidden pending review.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  es: { thanks:"Gracias por reportar", team:"Nuestro equipo revisara este post. Posts muy reportados se ocultan automaticamente.", close:"Cerrar", reportPost:"Reportar post", confidential:"Reportes confidenciales.", reason:"Razon", details:"Detalles (opcional)", placeholder:"Anade contexto que ayude a revisar.", cancel:"Cancelar", sending:"Enviando...", submit:"Enviar reporte", signIn:"Inicia sesion para reportar.", failed:"Fallo al reportar", reasons: ['Spam o estafa','Acoso o discurso de odio','Violencia o amenazas','Contenido sexual con menores','Contenido intimo no consensuado','Copyright / DMCA','Autolesion o contenido peligroso','Suplantacion','Otro'] },
  fr: { thanks:"Merci pour le signalement", team:"Notre equipe examinera ce post. Les posts signales plusieurs fois sont masques.", close:"Fermer", reportPost:"Signaler post", confidential:"Signalements confidentiels.", reason:"Raison", details:"Details (optionnel)", placeholder:"Ajoutez du contexte utile.", cancel:"Annuler", sending:"Envoi...", submit:"Envoyer signalement", signIn:"Connectez-vous pour signaler.", failed:"Echec signalement", reasons: ['Spam ou arnaque','Harcelement ou haine','Violence ou menaces','Contenu sexuel impliquant mineurs','Contenu intime non consensuel','Copyright / DMCA','Automutilation ou dangereux','Usurpation','Autre'] },
  de: { thanks:"Danke fur die Meldung", team:"Unser Team pruft diesen Post. Mehrfach gemeldete Posts werden automatisch verborgen.", close:"Schliessen", reportPost:"Post melden", confidential:"Meldungen vertraulich.", reason:"Grund", details:"Details (optional)", placeholder:"Kontext hinzufugen.", cancel:"Abbrechen", sending:"Senden...", submit:"Meldung senden", signIn:"Bitte anmelden zum Melden.", failed:"Meldung fehlgeschlagen", reasons: ['Spam oder Betrug','Belastigung oder Hassrede','Gewalt oder Drohungen','Sexueller Inhalt mit Minderjahrigen','Nicht einvernehmliche Intimitat','Copyright / DMCA','Selbstverletzung','Imitation','Andere'] },
  zh: { thanks:"感谢举报", team:"我们团队将审核此帖子。多次举报的帖子自动隐藏待审核。", close:"关闭", reportPost:"举报帖子", confidential:"举报保密。", reason:"原因", details:"详情（可选）", placeholder:"添加有助于审核的背景。", cancel:"取消", sending:"发送中...", submit:"提交举报", signIn:"请登录后举报。", failed:"举报失败", reasons: ['垃圾或诈骗','骚扰或仇恨言论','暴力或威胁','涉及未成年人的性内容','非自愿私密内容','版权 / DMCA','自残或危险内容','冒充','其他'] },
  ja: { thanks:"報告ありがとう", team:"チームがこの投稿を確認します。複数回報告された投稿は自動的に非表示。", close:"閉じる", reportPost:"投稿を報告", confidential:"報告は機密です。", reason:"理由", details:"詳細（任意）", placeholder:"レビューに役立つ背景を追加。", cancel:"キャンセル", sending:"送信中...", submit:"報告を送信", signIn:"報告するにはサインインしてください。", failed:"報告に失敗", reasons: ['スパム/詐欺','嫌がらせ/ヘイト','暴力/脅迫','未成年者の性的コンテンツ','同意なしの性的コンテンツ','著作権 / DMCA','自傷/危険','なりすまし','その他'] },
  ko: { thanks:"신고 감사", team:"팀이 이 게시물을 검토합니다. 반복 신고 게시물은 자동 숨김。", close:"닫기", reportPost:"게시물 신고", confidential:"신고는 비공개。", reason:"사유", details:"세부사항(선택)", placeholder:"검토에 도움되는 맥락 추가。", cancel:"취소", sending:"전송중...", submit:"신고 제출", signIn:"신고하려면 로그인하세요。", failed:"신고 실패", reasons: ['스팸/사기','괴롭힘/혐오','폭력/위협','미성년자 성 콘텐츠','비동의 성적 콘텐츠','저작권 / DMCA','자해/위험','사칭','기타'] },
  pt: { thanks:"Obrigado por denunciar", team:"Nossa equipe vai revisar este post. Posts muito denunciados sao ocultados automaticamente.", close:"Fechar", reportPost:"Denunciar post", confidential:"Denuncias confidenciais.", reason:"Motivo", details:"Detalhes (opcional)", placeholder:"Adicione contexto que ajude na revisao.", cancel:"Cancelar", sending:"Enviando...", submit:"Enviar denuncia", signIn:"Entre para denunciar.", failed:"Falha ao denunciar", reasons: ['Spam ou golpe','Assedio ou discurso de odio','Violencia ou ameacas','Conteudo sexual envolvendo menores','Conteudo intimo nao consensual','Copyright / DMCA','Autolesao ou perigoso','Personificacao','Outro'] },
  it: { thanks:"Grazie per la segnalazione", team:"Il nostro team esaminera questo post. I post segnalati piu volte sono nascosti automaticamente.", close:"Chiudi", reportPost:"Segnala post", confidential:"Segnalazioni riservate.", reason:"Motivo", details:"Dettagli (opzionale)", placeholder:"Aggiungi contesto utile alla revisione.", cancel:"Annulla", sending:"Invio...", submit:"Invia segnalazione", signIn:"Accedi per segnalare.", failed:"Segnalazione fallita", reasons: ['Spam o truffa','Molestie o odio','Violenza o minacce','Contenuto sessuale con minori','Contenuto intimo non consensuale','Copyright / DMCA','Autolesionismo o pericoloso','Furto identita','Altro'] },
  nl: { thanks:"Bedankt voor melding", team:"Ons team beoordeelt deze post. Vaak gemelde posts worden automatisch verborgen.", close:"Sluiten", reportPost:"Post melden", confidential:"Meldingen vertrouwelijk.", reason:"Reden", details:"Details (optioneel)", placeholder:"Voeg context toe die helpt.", cancel:"Annuleren", sending:"Verzenden...", submit:"Melding versturen", signIn:"Log in om te melden.", failed:"Melding mislukt", reasons: ['Spam of oplichting','Intimidatie of haat','Geweld of bedreigingen','Seksuele inhoud met minderjarigen','Niet-consensuele intimiteit','Copyright / DMCA','Zelfbeschadiging of gevaarlijk','Imitatie','Anders'] },
  tl: { thanks:"Thanks for reporting", team:"Our team will review this post. Repeat-reported posts are automatically hidden pending review.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  bn: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  id: { thanks:"Terima kasih melapor", team:"Tim kami akan meninjau post ini. Post yang sering dilaporkan otomatis disembunyikan.", close:"Tutup", reportPost:"Laporkan post", confidential:"Laporan rahasia.", reason:"Alasan", details:"Detail (opsional)", placeholder:"Tambahkan konteks yang membantu tinjauan.", cancel:"Batal", sending:"Mengirim...", submit:"Kirim laporan", signIn:"Silakan masuk untuk melapor.", failed:"Gagal melapor", reasons: ['Spam atau penipuan','Pelecehan atau ujaran kebencian','Kekerasan atau ancaman','Konten seksual melibatkan anak di bawah umur','Konten intim non-konsensual','Hak Cipta / DMCA','Menyakiti diri atau berbahaya','Peniruan identitas','Lainnya'] },
  vi: { thanks:"Cam on da bao cao", team:"Nhom chung toi se xem xet bai nay. Bai bi bao cao nhieu lan tu dong an.", close:"Dong", reportPost:"Bao cao bai", confidential:"Bao cao bao mat.", reason:"Ly do", details:"Chi tiet (tuy chon)", placeholder:"Them boi canh giup xem xet.", cancel:"Huy", sending:"Dang gui...", submit:"Gui bao cao", signIn:"Vui long dang nhap de bao cao.", failed:"Bao cao that bai", reasons: ['Spam hoac lua dao','Quay roi hoac thu han','Bao luc hoac de doa','Noi dung tinh duc lien quan tre em','Noi dung than mat khong dong thuan','Ban quyen / DMCA','Tu hai hoac nguy hiem','Mao danh','Khac'] },
  th: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  sv: { thanks:"Tack for rapport", team:"Vart team granskar detta inlagg. Upprepade rapporter dols automatiskt.", close:"Stang", reportPost:"Rapportera inlagg", confidential:"Rapporter konfidentiella.", reason:"Anledning", details:"Detaljer (valfritt)", placeholder:"Lagg till kontext som hjalper granskning.", cancel:"Avbryt", sending:"Skickar...", submit:"Skicka rapport", signIn:"Logga in for att rapportera.", failed:"Rapport misslyckades", reasons: ['Spam eller bedrageri','Trakasserier eller hat','Vald eller hot','Sexuellt innehall med minderariga','Icke-samtyckt intimitet','Copyright / DMCA','Sjalvskada eller farligt','Identitetsstold','Annat'] },
  pl: { thanks:"Dzieki za zgloszenie", team:"Nasz zespol sprawdzi ten post. Wielokrotnie zglaszane posty sa automatycznie ukrywane.", close:"Zamknij", reportPost:"Zglos post", confidential:"Zgloszenia poufne.", reason:"Powod", details:"Szczegoly (opcjonalnie)", placeholder:"Dodaj kontekst pomocny w weryfikacji.", cancel:"Anuluj", sending:"Wysylanie...", submit:"Wyslij zgloszenie", signIn:"Zaloguj sie aby zglosic.", failed:"Zgloszenie nieudane", reasons: ['Spam lub oszustwo','Nekanie lub mowa nienawisci','Przemoc lub grozby','Tresci seksualne z udzialem nieletnich','Niekonsensualne tresci intymne','Prawa autorskie / DMCA','Samookaleczenie lub niebezpieczne','Podszywanie sie','Inne'] },
  tr: { thanks:"Bildirdiginiz icin tesekkurler", team:"Ekibimiz bu gonderiyi inceleyecek. Cok bildirilen gonderiler otomatik gizlenir.", close:"Kapat", reportPost:"Gonderiyi bildir", confidential:"Bildirimler gizlidir.", reason:"Sebep", details:"Detaylar (istege bagli)", placeholder:"Incelemeye yardimci olacak baglam ekleyin.", cancel:"Iptal", sending:"Gonderiliyor...", submit:"Bildirim gonder", signIn:"Bildirmek icin giris yapin.", failed:"Bildirim basarisiz", reasons: ['Spam veya dolandiricilik','Taciz veya nefret soylemi','Siddet veya tehditler','Cocuklari iceren cinsel icerik','Rizaya dayanmayan mahrem icerik','Telif Hakki / DMCA','Kendine zarar veya tehlikeli icerik','Taklit','Diger'] },
  uk: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  el: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  he: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  ur: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  fa: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  ms: { thanks:"Terima kasih melapor", team:"Pasukan kami akan menyemak siaran ini. Siaran yang kerap dilaporkan disembunyikan automatik.", close:"Tutup", reportPost:"Lapor siaran", confidential:"Laporan sulit.", reason:"Sebab", details:"Butiran (pilihan)", placeholder:"Tambah konteks yang membantu semakan.", cancel:"Batal", sending:"Menghantar...", submit:"Hantar laporan", signIn:"Sila log masuk untuk melapor.", failed:"Gagal melapor", reasons: ['Spam atau penipuan','Gangguan atau ucapan benci','Keganasan atau ancaman','Kandungan seksual melibatkan kanak-kanak','Kandungan intim tanpa persetujuan','Hak Cipta / DMCA','Mencederakan diri atau berbahaya','Penyamaran','Lain-lain'] },
  ro: { thanks:"Multumesc pentru raportare", team:"Echipa noastra va revizui aceasta postare. Postarile raportate repetat sunt ascunse automat.", close:"Inchide", reportPost:"Raporteaza postarea", confidential:"Rapoartele sunt confidentiale.", reason:"Motiv", details:"Detalii (optional)", placeholder:"Adauga context util revizuirii.", cancel:"Anuleaza", sending:"Se trimite...", submit:"Trimite raport", signIn:"Autentifica-te pentru a raporta.", failed:"Raportare esuata", reasons: ['Spam sau inselatorie','Hartuire sau discurs de ura','Violenta sau amenintari','Continut sexual cu minori','Continut intim neconsensual','Drepturi de autor / DMCA','Autovatamare sau periculos','Uzurpare identitate','Altul'] },
  cs: { thanks:"Diky za nahlaseni", team:"Nas tym zkontroluje tento prispevek. Opakovane nahlasene prispevky se automaticky skryji.", close:"Zavrit", reportPost:"Nahlasit prispevek", confidential:"Hlaseni jsou duverna.", reason:"Duvod", details:"Detaily (volitelne)", placeholder:"Pridejte kontext pro kontrolu.", cancel:"Zrusit", sending:"Odesilani...", submit:"Odeslat hlaseni", signIn:"Prihlaste se pro nahlaseni.", failed:"Nahlaseni selhalo", reasons: ['Spam nebo podvod','Obtěžovani nebo nenavist','Nasili nebo hrozby','Sexualni obsah s nezletilymi','Nekonsensualni intimni obsah','Autorska prava / DMCA','Sebeposkozovani nebo nebezpecne','Vydavani se za nekoho','Jine'] },
  hu: { thanks:"Koszonjuk a jelentest", team:"Csapatunk atnezi ezt a posztot. Ismetelten jelentett posztok automatikusan elrejtve.", close:"Bezar", reportPost:"Poszt jelentese", confidential:"Jelentesek bizalmasak.", reason:"Ok", details:"Reszletek (opcionalis)", placeholder:"Adj hozza kontextust az ellenorzeshez.", cancel:"Megse", sending:"Kuldes...", submit:"Jelentes kuldese", signIn:"Jelentkezz be a jelenteshez.", failed:"Jelentes sikertelen", reasons: ['Spam vagy csalás','Zaklatas vagy gyuloletbeszed','Eroszak vagy fenyegetes','Kiskoruakat erinto szexualis tartalom','Beleegyezes nelkuli intim tartalom','Szerzoi jog / DMCA','Onsertes vagy veszelyes','Megszemelyesites','Egyeb'] },
  fi: { thanks:"Kiitos ilmoituksesta", team:"Tiimimme tarkistaa taman julkaisun. Toistuvasti ilmoitetut piilotetaan automaattisesti.", close:"Sulje", reportPost:"Ilmoita julkaisu", confidential:"Ilmoitukset luottamuksellisia.", reason:"Syy", details:"Tiedot (valinnainen)", placeholder:"Lisaa tarkistusta auttavaa kontekstia.", cancel:"Peruuta", sending:"Lahetetaan...", submit:"Laheta ilmoitus", signIn:"Kirjaudu ilmoittaaksesi.", failed:"Ilmoitus epaonnistui", reasons: ['Roskaposti tai huijaus','Hairinta tai vihapuhe','Vakivalta tai uhkaukset','Alaikaisiin liittyva seksuaalinen sisalto','Ilman suostumusta jaettu intiimi sisalto','Tekijanoikeus / DMCA','Itsetuhoinen tai vaarallinen','Esiintyminen toisena','Muu'] },
  no: { thanks:"Takk for rapport", team:"Teamet vart gjennomgar dette innlegget. Gjentatte rapporter skjules automatisk.", close:"Lukk", reportPost:"Rapporter innlegg", confidential:"Rapporter er konfidensielle.", reason:"Grunn", details:"Detaljer (valgfritt)", placeholder:"Legg til kontekst som hjelper gjennomgang.", cancel:"Avbryt", sending:"Sender...", submit:"Send rapport", signIn:"Logg inn for a rapportere.", failed:"Rapportering feilet", reasons: ['Spam eller svindel','Trakassering eller hatefulle ytringer','Vold eller trusler','Seksuelt innhold med mindrearige','Ikke-samtykkende intimt innhold','Opphavsrett / DMCA','Selvskading eller farlig','Impersonering','Annet'] },
  da: { thanks:"Tak for anmeldelse", team:"Vores team gennemgar dette opslag. Gentagne anmeldelser skjules automatisk.", close:"Luk", reportPost:"Anmeld opslag", confidential:"Anmeldelser er fortrolige.", reason:"Arsag", details:"Detaljer (valgfrit)", placeholder:"Tilfoj kontekst der hjaelper gennemgang.", cancel:"Annuller", sending:"Sender...", submit:"Send anmeldelse", signIn:"Log ind for at anmelde.", failed:"Anmeldelse fejlede", reasons: ['Spam eller svindel','Chikane eller hadefuld tale','Vold eller trusler','Seksuelt indhold med mindrearige','Ikke-samtykkende intimt indhold','Ophavsret / DMCA','Selvskade eller farligt','Impersonering','Andet'] },
  bg: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  hr: { thanks:"Hvala na prijavi", team:"Nas tim ce pregledati ovu objavu. Visestruko prijavljene objave automatski se skrivaju.", close:"Zatvori", reportPost:"Prijavi objavu", confidential:"Prijave su povjerljive.", reason:"Razlog", details:"Detalji (opcionalno)", placeholder:"Dodajte kontekst koji pomaze pregledu.", cancel:"Otkazi", sending:"Slanje...", submit:"Posalji prijavu", signIn:"Prijavite se za prijavu.", failed:"Prijava neuspjela", reasons: ['Spam ili prijevara','Uznemiravanje ili govor mrznje','Nasilje ili prijetnje','Seksualni sadrzaj koji ukljucuje maloljetnike','Nepristajuci intimni sadrzaj','Autorska prava / DMCA','Samoozljedivanje ili opasno','Lazno predstavljanje','Ostalo'] },
  sr: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  sk: { thanks:"Dakujeme za nahlasenie", team:"Nas tim skontroluje tento prispevok. Opakovane nahlasene prispevky sa automaticky skryju.", close:"Zavriet", reportPost:"Nahlasit prispevok", confidential:"Nahlasenia su doverne.", reason:"Dovod", details:"Detaily (volitelne)", placeholder:"Pridajte kontext pre kontrolu.", cancel:"Zrusit", sending:"Odosielanie...", submit:"Odoslat nahlasenie", signIn:"Prihlaste sa pre nahlasenie.", failed:"Nahlasenie zlyhalo", reasons: ['Spam alebo podvod','Obtazovanie alebo nenavist','Nasilie alebo hrozby','Sexualny obsah s neplnoletymi','Nekonsenzualny intimny obsah','Autorske prava / DMCA','Sebeposkodzovanie alebo nebezpecne','Vydavanie sa za niekoho','Ine'] },
  sl: { thanks:"Hvala za prijavo", team:"Nasa ekipa bo pregledala to objavo. Vec-krat prijavljene objave se samodejno skrijejo.", close:"Zapri", reportPost:"Prijavi objavo", confidential:"Prijave so zaupne.", reason:"Razlog", details:"Podrobnosti (neobvezno)", placeholder:"Dodajte kontekst, ki pomaga pregledu.", cancel:"Preklici", sending:"Posiljanje...", submit:"Poslji prijavo", signIn:"Prijavite se za prijavo.", failed:"Prijava ni uspela", reasons: ['Spam ali prevara','Nadlegovanje ali sovrazni govor','Nasilje ali groznje','Spolna vsebina z mladoletnimi','Nesoglasna intimna vsebina','Avtorske pravice / DMCA','Samoposkodovanje ali nevarno','Lazno predstavljanje','Drugo'] },
  et: { thanks:"Aitah teatamise eest", team:"Meie meeskond vaatab selle postituse ule. Korduvalt teatatud postitused peidetakse automaatselt.", close:"Sulge", reportPost:"Teata postitusest", confidential:"Teated on konfidentsiaalsed.", reason:"Pohjus", details:"Detailid (valikuline)", placeholder:"Lisa konteksti, mis aitab ulevaatust.", cancel:"Katkesta", sending:"Saatmine...", submit:"Saada teade", signIn:"Teatamiseks logige sisse.", failed:"Teatamine ebaonnestus", reasons: ['Rams voi kelmus','Ahistamine voi vihkamine','Vagivald voi ahvardused','Alaealisi kaasav seksuaalne sisu','Nousolekuta intiimne sisu','Autoriõigus / DMCA','Enesevigastamine voi ohtlik','Kehastumine','Muu'] },
  lv: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  lt: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  be: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  ka: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  hy: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  az: { thanks:"Melumat verdiyiniz ucun tesekkurler", team:"Komandamiz bu gonderini nezerden kecirecek. Tekrar bildirilmis gonderiler avtomatik gizlenir.", close:"Bagla", reportPost:"Gonderini bildir", confidential:"Melumatlar mexfidir.", reason:"Sebeb", details:"Tefsilatlar (isteye bagli)", placeholder:"Nezere alinmaga komek edecek kontekst elave edin.", cancel:"Legv et", sending:"Gonderilir...", submit:"Melumat gonder", signIn:"Bildirmek ucun daxil olun.", failed:"Bildiris ugursuz", reasons: ['Spam ve ya firildaq','Taciz ve ya nifret nitqi','Zorakiliq ve ya tehditler','Yetkinlik yasina catmamislarla bagli cinsi mezmun','Qarşiliqli raziliq olmadan intim mezmun','Muellif huququ / DMCA','Ozune zerer ve ya tehlukeli mezmun','Ozunu basqasi kimi gosterme','Diger'] },
  kk: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  ky: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  uz: { thanks:"Xabar bergan uchun rahmat", team:"Jamoamiz ushbu postni korib chiqadi. Takroran xabar qilingan postlar avtomatik yashiriladi.", close:"Yopish", reportPost:"Postni xabar qilish", confidential:"Xabarlar maxfiy.", reason:"Sabab", details:"Tafsilotlar (ixtiyoriy)", placeholder:"Korib chiqishga yordam beradigan kontekst qoshing.", cancel:"Bekor", sending:"Yuborilmoqda...", submit:"Xabar yuborish", signIn:"Xabar berish uchun kiring.", failed:"Xabar berish muvaffaqiyatsiz", reasons: ['Spam yoki firibgarlik','Taciz yoki nafrat nutqi','Zoravonlik yoki tahdidlar','Voyaga etmaganlar ishtirokidagi jinsiy kontent','Roziliksiz intim kontent','Mualliflik huquqi / DMCA','O ziga zarar yoki xavfli kontent','Boshqa birov nomidan ish korish','Boshqa'] },
  tg: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  mn: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  km: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  lo: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
  my: { thanks:"Thanks for reporting", team:"Our team will review this post.", close:"Close", reportPost:"Report post", confidential:"Reports are confidential.", reason:"Reason", details:"Details (optional)", placeholder:"Add any context that will help us review.", cancel:"Cancel", sending:"Sending...", submit:"Submit report", signIn:"Please sign in to report.", failed:"Failed to report", reasons: ['Spam or scam','Harassment or hate speech','Violence or threats','Sexual content involving minors','Non-consensual intimate content','Copyright / DMCA','Self-harm or dangerous content','Impersonation','Other'] },
}

export function ReportPostDialog({ postId, onClose }: { postId: string; onClose: () => void }) {
  const { language } = useLanguage()
  const d = D[language] || D.en
  const [reason, setReason] = useState(d.reasons[0])
  const [details, setDetails] = useState('')
  const [busy, setBusy] = useState(false)
  const [done, setDone] = useState(false)
  const [error, setError] = useState('')

  const submit = async () => {
    try {
      setBusy(true); setError('')
      const supabase = createClient() as any
      let user: any = null
      try { const { data } = await supabase.auth.getUser(); user = data.user } catch {}
      if (!user) { setError(d.signIn); return }
      try {
        const { error: err } = await supabase.from('post_reports').insert({ post_id: postId, reporter_id: user.id, reason, details: details.trim() || null })
        if (err) { if ((err as any).code === '23505') setDone(true); else setError(err.message); return }
        setDone(true)
      } catch (e:any) { setError(e?.message || d.failed) }
    } finally { try { setBusy(false) } catch {} }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4" onClick={onClose}>
      <div className="w-full max-w-md rounded-2xl border border-border bg-card p-5 shadow-xl" onClick={(e) => e.stopPropagation()}>
        {done? (
          <>
            <h2 className="font-display text-lg font-semibold">{d.thanks}</h2>
            <p className="mt-2 text-sm text-muted-foreground">{d.team}</p>
            <div className="mt-4 flex justify-end"><button onClick={onClose} className="rounded-full bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">{d.close}</button></div>
          </>
        ) : (
          <>
            <h2 className="font-display text-lg font-semibold">{d.reportPost}</h2>
            <p className="mt-1 text-xs text-muted-foreground">{d.confidential}</p>
            <label className="mt-4 block text-sm font-medium">{d.reason}</label>
            <select value={reason} onChange={(e) => setReason(e.target.value)} className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2 text-sm">{d.reasons.map((r: string) => <option key={r}>{r}</option>)}</select>
            <label className="mt-3 block text-sm font-medium">{d.details}</label>
            <textarea value={details} onChange={(e) => setDetails(e.target.value)} maxLength={500} rows={3} className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2 text-sm" placeholder={d.placeholder} />
            <div className="mt-1 flex justify-end"><MicRecorder onTranscript={setDetails} /></div>
            {error && <p className="mt-2 text-sm text-red-600">{error}</p>}
            <div className="mt-4 flex justify-end gap-2">
              <button onClick={onClose} className="rounded-full border border-border px-4 py-2 text-sm hover:bg-secondary">{d.cancel}</button>
              <button onClick={()=>{ try { submit() } catch {} }} disabled={busy} className="rounded-full bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50">{busy? d.sending : d.submit}</button>
            </div>
          </>
        )}
      </div>
    </div>
  )
}
