'use client'
import { useState, useEffect } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useLocation } from '@/lib/location-context'
import { useLanguage } from '@/lib/language-context'
import Link from 'next/link'

type T = { faithCorner:string, communityFaith:string, faithOfDay:string, daily:string, todaysThought:string, seeFaith:string, share:string, commFaithPosts:string, loading:string, noPosts:string, postSomething:string, whatThis:string, what1:string, what1b:string, what2:string, what2b:string, what3:string, what3b:string, what4:string, what4b:string, guidelines:string, g1:string, g2:string, g3:string, g4:string, g5:string, copied:string }

const D: Record<string,T> = {
en: { faithCorner:"Faith Corner", communityFaith:"Community faith and encouragement for", faithOfDay:"Faith of the Day", daily:"Daily", todaysThought:"TODAY'S THOUGHT:", seeFaith:"See Faith Posts →", share:"Share", commFaithPosts:"Community Faith Posts", loading:"Loading faith posts...", noPosts:"No faith posts yet in", postSomething:"Post Something →", whatThis:"What This Is", what1:"🙏 Faith Corner:", what1b:"A space for your local community to share encouragement, prayer requests, and faith-based discussions.", what2:"🏘 Local Focus:", what2b:"Content is specific to your 5-20 mile radius - your actual neighbors, not the whole internet.", what3:"💬 Open to All:", what3b:"Whether you're deeply religious or just curious, this is a welcoming space for respectful dialogue.", what4:"🤝 Supportive Community:", what4b:"Neighbors helping neighbors through faith, encouragement, and practical assistance.", guidelines:"Community Guidelines", g1:"• Be respectful of different faith traditions and beliefs", g2:"• Use this space to encourage and support your neighbors", g3:"• Share prayer requests and offers to help", g4:"• No proselytizing or condemning others' beliefs", g5:"• Keep discussions local and relevant to your community", copied:"Copied!" },
es: { faithCorner:"Rincon de Fe", communityFaith:"Fe comunitaria y animo para", faithOfDay:"Fe del Dia", daily:"Diario", todaysThought:"PENSAMIENTO DE HOY:", seeFaith:"Ver publicaciones de fe →", share:"Compartir", commFaithPosts:"Publicaciones de fe comunitarias", loading:"Cargando publicaciones de fe...", noPosts:"Aun no hay publicaciones de fe en", postSomething:"Publicar algo →", whatThis:"Que es esto", what1:"🙏 Rincon de Fe:", what1b:"Un espacio para que tu comunidad local comparta animo, peticiones de oracion y discusiones basadas en la fe.", what2:"🏘 Enfoque local:", what2b:"Contenido especifico para tu radio de 5-20 millas - tus vecinos reales.", what3:"💬 Abierto a todos:", what3b:"Ya seas profundamente religioso o solo curioso, espacio acogedor para dialogo respetuoso.", what4:"🤝 Comunidad solidaria:", what4b:"Vecinos ayudando a vecinos a traves de la fe, animo y ayuda practica.", guidelines:"Normas de la comunidad", g1:"• Se respetuoso con diferentes tradiciones", g2:"• Usa este espacio para animar y apoyar", g3:"• Comparte peticiones de oracion y ayuda", g4:"• No hacer proselitismo ni condenar", g5:"• Manten discusiones locales y relevantes", copied:"¡Copiado!" },
fr: { faithCorner:"Coin de Foi", communityFaith:"Foi communautaire et encouragement pour", faithOfDay:"Foi du Jour", daily:"Quotidien", todaysThought:"PENSEE DU JOUR:", seeFaith:"Voir les posts de foi →", share:"Partager", commFaithPosts:"Posts de foi communautaires", loading:"Chargement...", noPosts:"Pas encore de posts de foi a", postSomething:"Publier →", whatThis:"Qu'est-ce que c'est", what1:"🙏 Coin de Foi:", what1b:"Un espace pour votre communaute locale.", what2:"🏘 Focus local:", what2b:"Contenu specifique a votre rayon.", what3:"💬 Ouvert a tous:", what3b:"Espace accueillant pour dialogue respectueux.", what4:"🤝 Communaute solidaire:", what4b:"Voisins aidant voisins par la foi.", guidelines:"Directives", g1:"• Soyez respectueux des traditions", g2:"• Encouragez vos voisins", g3:"• Partagez demandes de priere", g4:"• Pas de proselytisme", g5:"• Gardez discussions locales", copied:"Copie!" },
de: { faithCorner:"Glaubensecke", communityFaith:"Gemeinschaftsglaube fur", faithOfDay:"Glaube des Tages", daily:"Taglich", todaysThought:"GEDANKE HEUTE:", seeFaith:"Glaubens-Posts →", share:"Teilen", commFaithPosts:"Community Glaubens-Posts", loading:"Laden...", noPosts:"Noch keine Glaubens-Posts in", postSomething:"Posten →", whatThis:"Was ist das", what1:"🙏 Glaubensecke:", what1b:"Raum fur lokale Gemeinschaft.", what2:"🏘 Lokaler Fokus:", what2b:"Inhalt fur 5-20 Meilen Radius.", what3:"💬 Offen fur alle:", what3b:"Einladender Raum fur respektvollen Dialog.", what4:"🤝 Gemeinschaft:", what4b:"Nachbarn helfen Nachbarn durch Glauben.", guidelines:"Richtlinien", g1:"• Respektvoll gegenuber Traditionen", g2:"• Nachbarn ermutigen", g3:"• Gebetsanliegen teilen", g4:"• Kein Missionieren", g5:"• Lokal halten", copied:"Kopiert!" },
zh: { faithCorner:"信仰角落", communityFaith:"社区信仰和鼓励", faithOfDay:"今日信仰", daily:"每日", todaysThought:"今日思考：", seeFaith:"查看信仰帖子 →", share:"分享", commFaithPosts:"社区信仰帖子", loading:"加载中...", noPosts:"还没有信仰帖子在", postSomething:"发布 →", whatThis:"这是什么", what1:"🙏 信仰角落：", what1b:"为本地社区分享鼓励的空间。", what2:"🏘 本地聚焦：", what2b:"针对5-20英里范围的内容。", what3:"💬 对所有人开放：", what3b:"尊重对话的欢迎空间。", what4:"🤝 支持性社区：", what4b:"邻居通过信仰互相帮助。", guidelines:"社区准则", g1:"• 尊重不同信仰传统", g2:"• 鼓励支持邻居", g3:"• 分享祷告请求", g4:"• 不传教", g5:"• 保持本地讨论", copied:"已复制！" },
ja: { faithCorner:"信仰コーナー", communityFaith:"コミュニティの信仰", faithOfDay:"今日の信仰", daily:"毎日", todaysThought:"今日の思い:", seeFaith:"信仰投稿を見る →", share:"共有", commFaithPosts:"信仰投稿", loading:"読み込み中...", noPosts:"まだ投稿がありません", postSomething:"投稿する →", whatThis:"これは何", what1:"🙏 信仰コーナー:", what1b:"地元コミュニティの励ましの場。", what2:"🏘 ローカル:", what2b:"5-20マイル圏内のコンテンツ。", what3:"💬 誰でも歓迎:", what3b:"尊重ある対話の場。", what4:"🤝 支援コミュニティ:", what4b:"信仰を通じて助け合う。", guidelines:"ガイドライン", g1:"• 信仰伝統を尊重", g2:"• 隣人を励ます", g3:"• 祈りを共有", g4:"• 布教なし", g5:"• 地元で維持", copied:"コピー!" },
ko: { faithCorner:"믿음 코너", communityFaith:"지역사회 믿음", faithOfDay:"오늘의 믿음", daily:"매일", todaysThought:"오늘의 생각:", seeFaith:"믿음 게시물 →", share:"공유", commFaithPosts:"믿음 게시물", loading:"로딩중...", noPosts:"아직 게시물 없음", postSomething:"게시 →", whatThis:"이것이 무엇인가", what1:"🙏 믿음 코너:", what1b:"지역사회 격려 공간.", what2:"🏘 로컬:", what2b:"5-20마일 반경 콘텐츠.", what3:"💬 모두에게 열림:", what3b:"존중 대화 환영 공간.", what4:"🤝 지원 커뮤니티:", what4b:"믿음으로 이웃 돕기.", guidelines:"가이드라인", g1:"• 전통 존중", g2:"• 이웃 격려", g3:"• 기도 공유", g4:"• 포교 금지", g5:"• 지역 유지", copied:"복사됨!" },
ru: { faithCorner:"Уголок Веры", communityFaith:"Вера сообщества для", faithOfDay:"Вера Дня", daily:"Ежедневно", todaysThought:"МЫСЛЬ СЕГОДНЯ:", seeFaith:"Посты веры →", share:"Поделиться", commFaithPosts:"Посты веры", loading:"Загрузка...", noPosts:"Пока нет постов в", postSomething:"Опубликовать →", whatThis:"Что это", what1:"🙏 Уголок Веры:", what1b:"Пространство для сообщества.", what2:"🏘 Локально:", what2b:"Контент для радиуса 5-20 миль.", what3:"💬 Открыто для всех:", what3b:"Пространство для уважительного диалога.", what4:"🤝 Сообщество:", what4b:"Соседи помогают через веру.", guidelines:"Правила", g1:"• Уважайте традиции", g2:"• Поддерживайте соседей", g3:"• Делитесь молитвами", g4:"• Без прозелитизма", g5:"• Локально", copied:"Скопировано!" },
ar: { faithCorner:"ركن الإيمان", communityFaith:"إيمان المجتمع لـ", faithOfDay:"إيمان اليوم", daily:"يومي", todaysThought:"فكرة اليوم:", seeFaith:"منشورات الإيمان →", share:"مشاركة", commFaithPosts:"منشورات الإيمان", loading:"جاري التحميل...", noPosts:"لا توجد منشورات في", postSomething:"نشر →", whatThis:"ما هذا", what1:"🙏 ركن الإيمان:", what1b:"مساحة للمجتمع المحلي.", what2:"🏘 تركيز محلي:", what2b:"محتوى لنطاق 5-20 ميل.", what3:"💬 مفتوح للجميع:", what3b:"مساحة ترحيبية للحوار.", what4:"🤝 مجتمع داعم:", what4b:"جيران يساعدون عبر الإيمان.", guidelines:"إرشادات", g1:"• احترام التقاليد", g2:"• تشجيع الجيران", g3:"• مشاركة الصلوات", g4:"• لا تبشير", g5:"• حافظ على المحلية", copied:"تم النسخ!" },
pt: { faithCorner:"Cantinho da Fe", communityFaith:"Fe comunitaria para", faithOfDay:"Fe do Dia", daily:"Diario", todaysThought:"PENSAMENTO DE HOJE:", seeFaith:"Posts de fe →", share:"Compartilhar", commFaithPosts:"Posts de fe", loading:"Carregando...", noPosts:"Ainda nao ha posts em", postSomething:"Postar →", whatThis:"O que e", what1:"🙏 Cantinho:", what1b:"Espaco para comunidade local.", what2:"🏘 Foco local:", what2b:"Conteudo para raio 5-20 milhas.", what3:"💬 Aberto a todos:", what3b:"Espaco acolhedor para dialogo.", what4:"🤝 Comunidade:", what4b:"Vizinhos ajudando via fe.", guidelines:"Diretrizes", g1:"• Respeite tradicoes", g2:"• Incentive vizinhos", g3:"• Compartilhe oracoes", g4:"• Sem proselitismo", g5:"• Local", copied:"Copiado!" },
it: { faithCorner:"Angolo della Fede", communityFaith:"Fede comunitaria per", faithOfDay:"Fede del Giorno", daily:"Quotidiano", todaysThought:"PENSIERO DI OGGI:", seeFaith:"Post di fede →", share:"Condividi", commFaithPosts:"Post di fede", loading:"Caricamento...", noPosts:"Ancora nessun post in", postSomething:"Pubblica →", whatThis:"Cos'e", what1:"🙏 Angolo:", what1b:"Spazio per comunita locale.", what2:"🏘 Focus locale:", what2b:"Contenuto per raggio 5-20 miglia.", what3:"💬 Aperto a tutti:", what3b:"Spazio accogliente.", what4:"🤝 Comunita:", what4b:"Vicini che si aiutano via fede.", guidelines:"Linee guida", g1:"• Rispetta tradizioni", g2:"• Incoraggia vicini", g3:"• Condividi preghiere", g4:"• Niente proselitismo", g5:"• Locale", copied:"Copiato!" },
nl: { faithCorner:"Geloofshoek", communityFaith:"Geloof voor", faithOfDay:"Geloof van de Dag", daily:"Dagelijks", todaysThought:"GEDACHTE VANDAAG:", seeFaith:"Geloofs-posts →", share:"Delen", commFaithPosts:"Geloofs-posts", loading:"Laden...", noPosts:"Nog geen posts in", postSomething:"Posten →", whatThis:"Wat is dit", what1:"🙏 Geloofshoek:", what1b:"Plek voor lokale gemeenschap.", what2:"🏘 Lokaal:", what2b:"Content voor 5-20 mijl radius.", what3:"💬 Open voor allen:", what3b:"Verwelkomende plek.", what4:"🤝 Gemeenschap:", what4b:"Buren helpen via geloof.", guidelines:"Richtlijnen", g1:"• Respecteer tradities", g2:"• Moedig buren aan", g3:"• Deel gebeden", g4:"• Geen bekering", g5:"• Lokaal houden", copied:"Gekopieerd!" },
tl: { faithCorner:"Sulok ng Pananampalataya", communityFaith:"Pananampalataya para sa", faithOfDay:"Pananampalataya Ngayon", daily:"Araw-araw", todaysThought:"KAISIPAN NGAYON:", seeFaith:"Tingnan Faith Posts →", share:"Ibahagi", commFaithPosts:"Faith Posts", loading:"Naglo-load...", noPosts:"Wala pang faith posts sa", postSomething:"Mag-post →", whatThis:"Ano Ito", what1:"🙏 Sulok ng Pananampalataya:", what1b:"Puwang para sa lokal na komunidad.", what2:"🏘 Lokal:", what2b:"Content para sa 5-20 milya.", what3:"💬 Bukas sa Lahat:", what3b:"Malugod na espasyo.", what4:"🤝 Komunidad:", what4b:"Kapitbahay tumutulong via pananampalataya.", guidelines:"Alituntunin", g1:"• Igalang tradisyon", g2:"• Hikayatin kapitbahay", g3:"• Ibahagi panalangin", g4:"• Walang proselitismo", g5:"• Panatilihing lokal", copied:"Nakopya!" },
hi: { faithCorner:"विश्वास कोना", communityFaith:"समुदाय विश्वास", faithOfDay:"आज का विश्वास", daily:"दैनिक", todaysThought:"आज का विचार:", seeFaith:"विश्वास पोस्ट →", share:"साझा करें", commFaithPosts:"विश्वास पोस्ट", loading:"लोड हो रहा...", noPosts:"अभी कोई पोस्ट नहीं", postSomething:"पोस्ट करें →", whatThis:"यह क्या है", what1:"🙏 विश्वास कोना:", what1b:"स्थानीय समुदाय के लिए जगह।", what2:"🏘 स्थानीय:", what2b:"5-20 मील दायरे के लिए।", what3:"💬 सभी के लिए:", what3b:"सम्मानजनक संवाद के लिए।", what4:"🤝 समुदाय:", what4b:"विश्वास से पड़ोसी मदद।", guidelines:"दिशानिर्देश", g1:"• परंपराओं का सम्मान", g2:"• पड़ोसियों को प्रोत्साहित", g3:"• प्रार्थना साझा", g4:"• कोई धर्मांतरण नहीं", g5:"• स्थानीय रखें", copied:"कॉपी किया!" },
bn: { faithCorner:"বিশ্বাস কোণ", communityFaith:"সম্প্রদায় বিশ্বাস", faithOfDay:"আজকের বিশ্বাস", daily:"দৈনিক", todaysThought:"আজকের চিন্তা:", seeFaith:"বিশ্বাস পোস্ট →", share:"শেয়ার", commFaithPosts:"বিশ্বাস পোস্ট", loading:"লোড হচ্ছে...", noPosts:"এখনও কোনো পোস্ট নেই", postSomething:"পোস্ট করুন →", whatThis:"এটা কি", what1:"🙏 বিশ্বাস কোণ:", what1b:"স্থানীয় সম্প্রদায়ের জন্য।", what2:"🏘 স্থানীয়:", what2b:"৫-২০ মাইল ব্যাসার্ধের জন্য।", what3:"💬 সবার জন্য:", what3b:"সম্মানজনক সংলাপ।", what4:"🤝 সম্প্রদায়:", what4b:"বিশ্বাসের মাধ্যমে সহায়তা।", guidelines:"নির্দেশিকা", g1:"• ঐতিহ্যকে সম্মান", g2:"• প্রতিবেশীকে উৎসাহিত", g3:"• প্রার্থনা শেয়ার", g4:"• ধর্মান্তর নয়", g5:"• স্থানীয় রাখুন", copied:"কপি হয়েছে!" },
id: { faithCorner:"Sudut Iman", communityFaith:"Iman komunitas untuk", faithOfDay:"Iman Hari Ini", daily:"Harian", todaysThought:"PEMIKIRAN HARI INI:", seeFaith:"Postingan Iman →", share:"Bagikan", commFaithPosts:"Postingan Iman", loading:"Memuat...", noPosts:"Belum ada postingan di", postSomething:"Posting →", whatThis:"Apa Ini", what1:"🙏 Sudut Iman:", what1b:"Ruang komunitas lokal.", what2:"🏘 Lokal:", what2b:"Untuk radius 5-20 mil.", what3:"💬 Terbuka untuk Semua:", what3b:"Ruang ramah.", what4:"🤝 Komunitas:", what4b:"Tetangga membantu via iman.", guidelines:"Pedoman", g1:"• Hormati tradisi", g2:"• Dorong tetangga", g3:"• Bagikan doa", g4:"• Tidak proselitisme", g5:"• Jaga lokal", copied:"Disalin!" },
vi: { faithCorner:"Goc Duc Tin", communityFaith:"Duc tin cong dong cho", faithOfDay:"Duc Tin Hom Nay", daily:"Hang ngay", todaysThought:"SUY NGHI HOM NAY:", seeFaith:"Bai dang duc tin →", share:"Chia se", commFaithPosts:"Bai dang duc tin", loading:"Dang tai...", noPosts:"Chua co bai dang o", postSomething:"Dang →", whatThis:"Day la gi", what1:"🙏 Goc Duc Tin:", what1b:"Khong gian cong dong dia phuong.", what2:"🏘 Dia phuong:", what2b:"Cho ban kinh 5-20 dam.", what3:"💬 Mo cho moi nguoi:", what3b:"Khong gian chao don.", what4:"🤝 Cong dong:", what4b:"Hang xom giup qua duc tin.", guidelines:"Huong dan", g1:"• Ton trong truyen thong", g2:"• Dong vien hang xom", g3:"• Chia se cau nguyen", g4:"• Khong truyen giao", g5:"• Giu dia phuong", copied:"Da sao chep!" },
th: { faithCorner:"มุมศรัทธา", communityFaith:"ศรัทธาชุมชนสำหรับ", faithOfDay:"ศรัทธาวันนี้", daily:"รายวัน", todaysThought:"ความคิดวันนี้:", seeFaith:"โพสต์ศรัทธา →", share:"แชร์", commFaithPosts:"โพสต์ศรัทธา", loading:"กำลังโหลด...", noPosts:"ยังไม่มีโพสต์ใน", postSomething:"โพสต์ →", whatThis:"นี่คืออะไร", what1:"🙏 มุมศรัทธา:", what1b:"พื้นที่ชุมชนท้องถิ่น", what2:"🏘 ท้องถิ่น:", what2b:"สำหรับรัศมี 5-20 ไมล์", what3:"💬 เปิดสำหรับทุกคน:", what3b:"พื้นที่ต้อนรับ", what4:"🤝 ชุมชน:", what4b:"เพื่อนบ้านช่วยผ่านศรัทธา", guidelines:"แนวทาง", g1:"• เคารพประเพณี", g2:"• ส่งเสริมเพื่อนบ้าน", g3:"• แบ่งปันคำอธิษฐาน", g4:"• ไม่เผยแผ่", g5:"• ท้องถิ่น", copied:"คัดลอกแล้ว!" },
sv: { faithCorner:"Troshörna", communityFaith:"Gemenskapstro för", faithOfDay:"Dagens Tro", daily:"Dagligen", todaysThought:"DAGENS TANKE:", seeFaith:"Tro-inlägg →", share:"Dela", commFaithPosts:"Tro-inlägg", loading:"Laddar...", noPosts:"Inga tro-inlägg i", postSomething:"Posta →", whatThis:"Vad är detta", what1:"🙏 Troshörna:", what1b:"Utrymme för lokalsamhälle.", what2:"🏘 Lokalt:", what2b:"För 5-20 miles radie.", what3:"💬 Öppet för alla:", what3b:"Välkomnande utrymme.", what4:"🤝 Gemenskap:", what4b:"Grannar hjälper via tro.", guidelines:"Riktlinjer", g1:"• Respektera traditioner", g2:"• Uppmuntra grannar", g3:"• Dela böner", g4:"• Ingen proselytism", g5:"• Håll lokalt", copied:"Kopierad!" },
pl: { faithCorner:"Kącik Wiary", communityFaith:"Wiara społeczności dla", faithOfDay:"Wiara Dnia", daily:"Codziennie", todaysThought:"MYŚL DNIA:", seeFaith:"Posty wiary →", share:"Udostępnij", commFaithPosts:"Posty wiary", loading:"Ładowanie...", noPosts:"Brak postów w", postSomething:"Postuj →", whatThis:"Co to jest", what1:"🙏 Kącik Wiary:", what1b:"Przestrzeń dla społeczności lokalnej.", what2:"🏘 Lokalnie:", what2b:"Dla promienia 5-20 mil.", what3:"💬 Otwarte dla wszystkich:", what3b:"Gościnna przestrzeń.", what4:"🤝 Społeczność:", what4b:"Sąsiedzi pomagają przez wiarę.", guidelines:"Wytyczne", g1:"• Szanuj tradycje", g2:"• Zachęcaj sąsiadów", g3:"• Dziel się modlitwami", g4:"• Bez prozelityzmu", g5:"• Trzymaj lokalnie", copied:"Skopiowano!" },
tr: { faithCorner:"İnanç Köşesi", communityFaith:"Topluluk inancı", faithOfDay:"Günün İnancı", daily:"Günlük", todaysThought:"BUGÜNÜN DÜŞÜNCESİ:", seeFaith:"İnanç gönderileri →", share:"Paylaş", commFaithPosts:"İnanç gönderileri", loading:"Yükleniyor...", noPosts:"Henüz gönderi yok", postSomething:"Paylaş →", whatThis:"Bu nedir", what1:"🙏 İnanç Köşesi:", what1b:"Yerel topluluk için alan.", what2:"🏘 Yerel:", what2b:"5-20 mil yarıçap için.", what3:"💬 Herkese açık:", what3b:"Misafirperver alan.", what4:"🤝 Topluluk:", what4b:"Komşular inançla yardımlaşır.", guidelines:"Kurallar", g1:"• Geleneklere saygı", g2:"• Komşuları teşvik", g3:"• Dua paylaş", g4:"• Misyonerlik yok", g5:"• Yerel tut", copied:"Kopyalandı!" },
uk: { faithCorner:"Куточок Віри", communityFaith:"Віра спільноти для", faithOfDay:"Віра Дня", daily:"Щодня", todaysThought:"ДУМКА СЬОГОДНІ:", seeFaith:"Пости віри →", share:"Поділитися", commFaithPosts:"Пости віри", loading:"Завантаження...", noPosts:"Поки немає постів в", postSomething:"Опублікувати →", whatThis:"Що це", what1:"🙏 Куточок Віри:", what1b:"Простір для місцевої громади.", what2:"🏘 Локально:", what2b:"Для радіусу 5-20 миль.", what3:"💬 Відкрито для всіх:", what3b:"Гостинний простір.", what4:"🤝 Спільнота:", what4b:"Сусіди допомагають через віру.", guidelines:"Правила", g1:"• Поважайте традиції", g2:"• Підтримуйте сусідів", g3:"• Діліться молитвами", g4:"• Без прозелітизму", g5:"• Тримайте локально", copied:"Скопійовано!" },
el: { faithCorner:"Γωνιά Πίστης", communityFaith:"Πίστη κοινότητας για", faithOfDay:"Πίστη της Ημέρας", daily:"Καθημερινά", todaysThought:"ΣΚΕΨΗ ΣΗΜΕΡΑ:", seeFaith:"Αναρτήσεις πίστης →", share:"Κοινοποίηση", commFaithPosts:"Αναρτήσεις πίστης", loading:"Φόρτωση...", noPosts:"Καμία ανάρτηση σε", postSomething:"Ανάρτηση →", whatThis:"Τι είναι αυτό", what1:"🙏 Γωνιά Πίστης:", what1b:"Χώρος για τοπική κοινότητα.", what2:"🏘 Τοπικά:", what2b:"Για ακτίνα 5-20 μιλίων.", what3:"💬 Ανοιχτό για όλους:", what3b:"Φιλόξενος χώρος.", what4:"🤝 Κοινότητα:", what4b:"Γείτονες βοηθούν μέσω πίστης.", guidelines:"Οδηγίες", g1:"• Σεβαστείτε παραδόσεις", g2:"• Ενθαρρύνετε γείτονες", g3:"• Μοιραστείτε προσευχές", g4:"• Όχι προσηλυτισμός", g5:"• Κρατήστε τοπικά", copied:"Αντιγράφηκε!" },
he: { faithCorner:"פינת אמונה", communityFaith:"אמונת קהילה עבור", faithOfDay:"אמונת היום", daily:"יומי", todaysThought:"מחשבת היום:", seeFaith:"פוסטי אמונה →", share:"שתף", commFaithPosts:"פוסטי אמונה", loading:"טוען...", noPosts:"אין עדיין פוסטים ב", postSomething:"פרסם →", whatThis:"מה זה", what1:"🙏 פינת אמונה:", what1b:"מרחב לקהילה מקומית.", what2:"🏘 מקומי:", what2b:"לרדיוס 5-20 מייל.", what3:"💬 פתוח לכולם:", what3b:"מרחב מסביר פנים.", what4:"🤝 קהילה:", what4b:"שכנים עוזרים דרך אמונה.", guidelines:"הנחיות", g1:"• כבד מסורות", g2:"• עודד שכנים", g3:"• שתף תפילות", g4:"• ללא מיסיונריות", g5:"• שמור מקומי", copied:"הועתק!" },
ur: { faithCorner:"ایمان کا کونہ", communityFaith:"کمیونٹی ایمان", faithOfDay:"آج کا ایمان", daily:"روزانہ", todaysThought:"آج کا خیال:", seeFaith:"ایمان پوسٹس →", share:"شیئر", commFaithPosts:"ایمان پوسٹس", loading:"لوڈ ہو رہا...", noPosts:"ابھی کوئی پوسٹ نہیں", postSomething:"پوسٹ کریں →", whatThis:"یہ کیا ہے", what1:"🙏 ایمان کا کونہ:", what1b:"مقامی کمیونٹی کے لیے جگہ۔", what2:"🏘 مقامی:", what2b:"5-20 میل رداس کے لیے۔", what3:"💬 سب کے لیے:", what3b:"خوش آمدید جگہ۔", what4:"🤝 کمیونٹی:", what4b:"ایمان سے پڑوسی مدد۔", guidelines:"ہدایات", g1:"• روایات کا احترام", g2:"• پڑوسیوں کی حوصلہ افزائی", g3:"• دعائیں شیئر", g4:"• تبلیغ نہیں", g5:"• مقامی رکھیں", copied:"کاپی ہوگیا!" },
fa: { faithCorner:"گوشه ایمان", communityFaith:"ایمان جامعه برای", faithOfDay:"ایمان روز", daily:"روزانه", todaysThought:"اندیشه امروز:", seeFaith:"پست‌های ایمان →", share:"اشتراک", commFaithPosts:"پست‌های ایمان", loading:"در حال بارگذاری...", noPosts:"هنوز پستی در", postSomething:"پست →", whatThis:"این چیست", what1:"🙏 گوشه ایمان:", what1b:"فضایی برای جامعه محلی.", what2:"🏘 محلی:", what2b:"برای شعاع 5-20 مایل.", what3:"💬 برای همه باز:", what3b:"فضایی خوش‌آمد.", what4:"🤝 جامعه:", what4b:"همسایگان با ایمان کمک.", guidelines:"راهنما", g1:"• احترام به سنت‌ها", g2:"• تشویق همسایگان", g3:"• اشتراک دعا", g4:"• بدون تبلیغ", g5:"• محلی نگه دارید", copied:"کپی شد!" },
ms: { faithCorner:"Sudut Iman", communityFaith:"Iman komuniti untuk", faithOfDay:"Iman Hari Ini", daily:"Harian", todaysThought:"PEMIKIRAN HARI INI:", seeFaith:"Pos Iman →", share:"Kongsi", commFaithPosts:"Pos Iman", loading:"Memuat...", noPosts:"Tiada pos lagi di", postSomething:"Pos →", whatThis:"Apa Ini", what1:"🙏 Sudut Iman:", what1b:"Ruang komuniti tempatan.", what2:"🏘 Tempatan:", what2b:"Untuk jejari 5-20 batu.", what3:"💬 Terbuka untuk Semua:", what3b:"Ruang mesra.", what4:"🤝 Komuniti:", what4b:"Jiran membantu via iman.", guidelines:"Garis Panduan", g1:"• Hormati tradisi", g2:"• Galakkan jiran", g3:"• Kongsi doa", g4:"• Tiada dakwah paksa", g5:"• Kekal tempatan", copied:"Disalin!" },
ro: { faithCorner:"Colțul Credinței", communityFaith:"Credința comunității pentru", faithOfDay:"Credința Zilei", daily:"Zilnic", todaysThought:"GÂNDUL DE AZI:", seeFaith:"Postări credință →", share:"Distribuie", commFaithPosts:"Postări credință", loading:"Se încarcă...", noPosts:"Încă nu există postări în", postSomething:"Postează →", whatThis:"Ce este", what1:"🙏 Colțul Credinței:", what1b:"Spațiu pentru comunitatea locală.", what2:"🏘 Local:", what2b:"Pentru raza 5-20 mile.", what3:"💬 Deschis pentru toți:", what3b:"Spațiu primitor.", what4:"🤝 Comunitate:", what4b:"Vecini ajută prin credință.", guidelines:"Ghid", g1:"• Respectă tradițiile", g2:"• Încurajează vecinii", g3:"• Împărtășește rugăciuni", g4:"• Fără prozelitism", g5:"• Păstrează local", copied:"Copiat!" },
cs: { faithCorner:"Koutek Víry", communityFaith:"Víra komunity pro", faithOfDay:"Víra Dne", daily:"Denně", todaysThought:"MYŠLENKA DNES:", seeFaith:"Příspěvky víry →", share:"Sdílet", commFaithPosts:"Příspěvky víry", loading:"Načítání...", noPosts:"Zatím žádné příspěvky v", postSomething:"Publikovat →", whatThis:"Co to je", what1:"🙏 Koutek Víry:", what1b:"Prostor pro místní komunitu.", what2:"🏘 Místní:", what2b:"Pro okruh 5-20 mil.", what3:"💬 Otevřeno pro všechny:", what3b:"Vítaný prostor.", what4:"🤝 Komunita:", what4b:"Sousedé pomáhají vírou.", guidelines:"Pokyny", g1:"• Respektujte tradice", g2:"• Povzbuzujte sousedy", g3:"• Sdílejte modlitby", g4:"• Žádný prozelytismus", g5:"• Držte místně", copied:"Zkopírováno!" },
hu: { faithCorner:"Hit Sarok", communityFaith:"Közösségi hit", faithOfDay:"A Nap Hite", daily:"Napi", todaysThought:"MAI GONDOLAT:", seeFaith:"Hit posztok →", share:"Megosztás", commFaithPosts:"Hit posztok", loading:"Betöltés...", noPosts:"Még nincs poszt", postSomething:"Poszt →", whatThis:"Mi ez", what1:"🙏 Hit Sarok:", what1b:"Helyi közösség tere.", what2:"🏘 Helyi:", what2b:"5-20 mérföld sugárra.", what3:"💬 Mindenkinek nyitott:", what3b:"Barátságos tér.", what4:"🤝 Közösség:", what4b:"Szomszédok hit által segítenek.", guidelines:"Irányelvek", g1:"• Tiszteld hagyományokat", g2:"• Bátoríts szomszédokat", g3:"• Imákat oszd meg", g4:"• Nincs térítés", g5:"• Tartsd helyben", copied:"Másolva!" },
fi: { faithCorner:"Uskon Nurkka", communityFaith:"Yhteisön usko", faithOfDay:"Päivän Usko", daily:"Päivittäin", todaysThought:"TÄNÄÄN AJATUS:", seeFaith:"Usko-julkaisut →", share:"Jaa", commFaithPosts:"Usko-julkaisut", loading:"Ladataan...", noPosts:"Ei vielä julkaisuja", postSomething:"Julkaise →", whatThis:"Mikä tämä on", what1:"🙏 Uskon Nurkka:", what1b:"Tila paikallisyhteisölle.", what2:"🏘 Paikallinen:", what2b:"5-20 mailin säteelle.", what3:"💬 Avoin kaikille:", what3b:"Tervetullut tila.", what4:"🤝 Yhteisö:", what4b:"Naapurit auttavat uskolla.", guidelines:"Ohjeet", g1:"• Kunnioita perinteitä", g2:"• Kannusta naapureita", g3:"• Jaa rukouksia", g4:"• Ei käännytystä", g5:"• Pidä paikallisena", copied:"Kopioitu!" },
no: { faithCorner:"Troshjørne", communityFaith:"Fellesskapstro for", faithOfDay:"Dagens Tro", daily:"Daglig", todaysThought:"DAGENS TANKE:", seeFaith:"Tro-innlegg →", share:"Del", commFaithPosts:"Tro-innlegg", loading:"Laster...", noPosts:"Ingen innlegg i", postSomething:"Post →", whatThis:"Hva er dette", what1:"🙏 Troshjørne:", what1b:"Plass for lokalsamfunn.", what2:"🏘 Lokalt:", what2b:"For 5-20 miles radius.", what3:"💬 Åpent for alle:", what3b:"Innbydende plass.", what4:"🤝 Fellesskap:", what4b:"Naboer hjelper via tro.", guidelines:"Retningslinjer", g1:"• Respekter tradisjoner", g2:"• Oppmuntre naboer", g3:"• Del bønner", g4:"• Ingen proselytisme", g5:"• Hold lokalt", copied:"Kopiert!" },
da: { faithCorner:"Troshjørne", communityFaith:"Fællesskabstro for", faithOfDay:"Dagens Tro", daily:"Dagligt", todaysThought:"DAGENS TANKE:", seeFaith:"Tro-opslag →", share:"Del", commFaithPosts:"Tro-opslag", loading:"Indlæser...", noPosts:"Ingen opslag i", postSomething:"Slå op →", whatThis:"Hvad er dette", what1:"🙏 Troshjørne:", what1b:"Plads til lokalsamfund.", what2:"🏘 Lokalt:", what2b:"For 5-20 miles radius.", what3:"💬 Åbent for alle:", what3b:"Indbydende sted.", what4:"🤝 Fællesskab:", what4b:"Naboer hjælper via tro.", guidelines:"Retningslinjer", g1:"• Respekter traditioner", g2:"• Opmuntre naboer", g3:"• Del bønner", g4:"• Ingen proselytisme", g5:"• Hold lokalt", copied:"Kopieret!" },
bg: { faithCorner:"Кът на Вярата", communityFaith:"Вяра на общността за", faithOfDay:"Вяра на Деня", daily:"Ежедневно", todaysThought:"МИСЪЛ ДНЕС:", seeFaith:"Публикации вяра →", share:"Сподели", commFaithPosts:"Публикации вяра", loading:"Зареждане...", noPosts:"Все още няма публикации в", postSomething:"Публикувай →", whatThis:"Какво е това", what1:"🙏 Кът на Вярата:", what1b:"Пространство за местна общност.", what2:"🏘 Местно:", what2b:"За радиус 5-20 мили.", what3:"💬 Отворено за всички:", what3b:"Гостоприемно пространство.", what4:"🤝 Общност:", what4b:"Съседи помагат чрез вяра.", guidelines:"Насоки", g1:"• Уважавайте традиции", g2:"• Насърчавайте съседи", g3:"• Споделяйте молитви", g4:"• Без прозелитизъм", g5:"• Дръжте локално", copied:"Копирано!" },
hr: { faithCorner:"Kutak Vjere", communityFaith:"Vjera zajednice za", faithOfDay:"Vjera Dana", daily:"Dnevno", todaysThought:"MISAO DANAS:", seeFaith:"Objave vjere →", share:"Podijeli", commFaithPosts:"Objave vjere", loading:"Učitavanje...", noPosts:"Još nema objava u", postSomething:"Objavi →", whatThis:"Što je ovo", what1:"🙏 Kutak Vjere:", what1b:"Prostor za lokalnu zajednicu.", what2:"🏘 Lokalno:", what2b:"Za radijus 5-20 milja.", what3:"💬 Otvoreno za sve:", what3b:"Dobrodošao prostor.", what4:"🤝 Zajednica:", what4b:"Susjedi pomažu vjerom.", guidelines:"Smjernice", g1:"• Poštujte tradicije", g2:"• Ohrabrite susjede", g3:"• Dijelite molitve", g4:"• Bez prozelitizma", g5:"• Držite lokalno", copied:"Kopirano!" },
sr: { faithCorner:"Kutak Vere", communityFaith:"Vera zajednice za", faithOfDay:"Vera Dana", daily:"Dnevno", todaysThought:"MISAO DANAS:", seeFaith:"Objave vere →", share:"Podeli", commFaithPosts:"Objave vere", loading:"Učitavanje...", noPosts:"Još nema objava u", postSomething:"Objavi →", whatThis:"Šta je ovo", what1:"🙏 Kutak Vere:", what1b:"Prostor za lokalnu zajednicu.", what2:"🏘 Lokalno:", what2b:"Za radijus 5-20 milja.", what3:"💬 Otvoreno za sve:", what3b:"Dobrodošao prostor.", what4:"🤝 Zajednica:", what4b:"Komšije pomažu verom.", guidelines:"Smernice", g1:"• Poštujte tradicije", g2:"• Ohrabrite komšije", g3:"• Delite molitve", g4:"• Bez prozelitizma", g5:"• Držite lokalno", copied:"Kopirano!" },
sk: { faithCorner:"Kútik Viery", communityFaith:"Viera komunity pre", faithOfDay:"Viera Dňa", daily:"Denne", todaysThought:"MYŠLIENKA DNES:", seeFaith:"Príspevky viery →", share:"Zdieľať", commFaithPosts:"Príspevky viery", loading:"Načítanie...", noPosts:"Zatiaľ žiadne príspevky v", postSomething:"Publikovať →", whatThis:"Čo je toto", what1:"🙏 Kútik Viery:", what1b:"Priestor pre miestnu komunitu.", what2:"🏘 Miestne:", what2b:"Pre okruh 5-20 míľ.", what3:"💬 Otvorené pre všetkých:", what3b:"Vítaný priestor.", what4:"🤝 Komunita:", what4b:"Susedia pomáhajú vierou.", guidelines:"Pokyny", g1:"• Rešpektujte tradície", g2:"• Povzbudzujte susedov", g3:"• Zdieľajte modlitby", g4:"• Žiadny prozelytizmus", g5:"• Držte miestne", copied:"Skopírované!" },
sl: { faithCorner:"Kotiček Vere", communityFaith:"Vera skupnosti za", faithOfDay:"Vera Dneva", daily:"Dnevno", todaysThought:"MISEL DANES:", seeFaith:"Objave vere →", share:"Deli", commFaithPosts:"Objave vere", loading:"Nalaganje...", noPosts:"Še ni objav v", postSomething:"Objavi →", whatThis:"Kaj je to", what1:"🙏 Kotiček Vere:", what1b:"Prostor za lokalno skupnost.", what2:"🏘 Lokalno:", what2b:"Za radij 5-20 milj.", what3:"💬 Odprto za vse:", what3b:"Dobrodošel prostor.", what4:"🤝 Skupnost:", what4b:"Sosedje pomagajo z vero.", guidelines:"Smernice", g1:"• Spoštujte tradicije", g2:"• Spodbujajte sosede", g3:"• Delite molitve", g4:"• Brez prozelitizma", g5:"• Držite lokalno", copied:"Kopirano!" },
et: { faithCorner:"Usu Nurk", communityFaith:"Kogukonna usk", faithOfDay:"Päeva Usk", daily:"Igapäev", todaysThought:"TÄNA MÕTE:", seeFaith:"Usu postitused →", share:"Jaga", commFaithPosts:"Usu postitused", loading:"Laadimine...", noPosts:"Veel pole postitusi", postSomething:"Postita →", whatThis:"Mis see on", what1:"🙏 Usu Nurk:", what1b:"Ruum kohalikule kogukonnale.", what2:"🏘 Kohalik:", what2b:"5-20 miili raadiusele.", what3:"💬 Avatud kõigile:", what3b:"Tere tulemast ruum.", what4:"🤝 Kogukond:", what4b:"Naabrid aitavad usu kaudu.", guidelines:"Juhised", g1:"• Austa traditsioone", g2:"• Julgusta naabreid", g3:"• Jaga palveid", g4:"• Ei proselütismi", g5:"• Hoia kohalik", copied:"Kopeeritud!" },
lv: { faithCorner:"Ticības Stūris", communityFaith:"Kopienas ticība", faithOfDay:"Dienas Ticība", daily:"Ik dienu", todaysThought:"ŠODIENAS DOMA:", seeFaith:"Ticības ieraksti →", share:"Dalīties", commFaithPosts:"Ticības ieraksti", loading:"Ielāde...", noPosts:"Vēl nav ierakstu", postSomething:"Publicēt →", whatThis:"Kas tas ir", what1:"🙏 Ticības Stūris:", what1b:"Vieta vietējai kopienai.", what2:"🏘 Vietēji:", what2b:"5-20 jūdžu rādiusam.", what3:"💬 Atvērts visiem:", what3b:"Viesmīlīga vieta.", what4:"🤝 Kopiena:", what4b:"Kaimiņi palīdz caur ticību.", guidelines:"Vadlīnijas", g1:"• Cieniet tradīcijas", g2:"• Uzmundriniet kaimiņus", g3:"• Dalieties lūgšanās", g4:"• Bez prozelītisma", g5:"• Saglabājiet vietēji", copied:"Nokopēts!" },
lt: { faithCorner:"Tikėjimo Kampelis", communityFaith:"Bendruomenės tikėjimas", faithOfDay:"Dienos Tikėjimas", daily:"Kasdien", todaysThought:"ŠIANDIENOS MINTIS:", seeFaith:"Tikėjimo įrašai →", share:"Dalintis", commFaithPosts:"Tikėjimo įrašai", loading:"Įkeliama...", noPosts:"Dar nėra įrašų", postSomething:"Paskelbti →", whatThis:"Kas tai", what1:"🙏 Tikėjimo Kampelis:", what1b:"Erdvė vietos bendruomenei.", what2:"🏘 Vietinis:", what2b:"5-20 mylių spinduliui.", what3:"💬 Atvira visiems:", what3b:"Svetinga erdvė.", what4:"🤝 Bendruomenė:", what4b:"Kaimynai padeda tikėjimu.", guidelines:"Gairės", g1:"• Gerbkite tradicijas", g2:"• Skatinkite kaimynus", g3:"• Dalinkitės maldomis", g4:"• Be prozelitizmo", g5:"• Laikykite vietoje", copied:"Nukopijuota!" },
be: { faithCorner:"Куток Веры", communityFaith:"Вера супольнасці для", faithOfDay:"Вера Дня", daily:"Штодня", todaysThought:"ДУМКА СЁННЯ:", seeFaith:"Посты веры →", share:"Падзяліцца", commFaithPosts:"Посты веры", loading:"Загрузка...", noPosts:"Пакуль няма пастоў у", postSomething:"Апублікаваць →", whatThis:"Што гэта", what1:"🙏 Куток Веры:", what1b:"Прастора для мясцовай супольнасці.", what2:"🏘 Мясцова:", what2b:"Для радыусу 5-20 міль.", what3:"💬 Адкрыта для ўсіх:", what3b:"Гасцінная прастора.", what4:"🤝 Супольнасць:", what4b:"Суседзі дапамагаюць верай.", guidelines:"Правілы", g1:"• Паважайце традыцыі", g2:"• Падтрымлівайце суседзяў", g3:"• Дзяліцеся малітвамі", g4:"• Без празелітызму", g5:"• Трымайце лакальна", copied:"Скапіявана!" },
ka: { faithCorner:"რწმენის კუთხე", communityFaith:"საზოგადოების რწმენა", faithOfDay:"დღის რწმენა", daily:"ყოველდღე", todaysThought:"დღევანდელი აზრი:", seeFaith:"რწმენის პოსტები →", share:"გაზიარება", commFaithPosts:"რწმენის პოსტები", loading:"იტვირთება...", noPosts:"ჯერ არ არის პოსტები", postSomething:"გამოქვეყნება →", whatThis:"რა არის ეს", what1:"🙏 რწმენის კუთხე:", what1b:"ადგილობრივი საზოგადოების სივრცე.", what2:"🏘 ადგილობრივი:", what2b:"5-20 მილის რადიუსისთვის.", what3:"💬 ყველასთვის ღია:", what3b:"მისასალმებელი სივრცე.", what4:"🤝 საზოგადოება:", what4b:"მეზობლები რწმენით ეხმარებიან.", guidelines:"წესები", g1:"• პატივი ეცით ტრადიციებს", g2:"• წაახალისეთ მეზობლები", g3:"• გააზიარეთ ლოცვები", g4:"• პროზელიტიზმის გარეშე", g5:"• შეინარჩუნეთ ადგილობრივად", copied:"კოპირებულია!" },
hy: { faithCorner:"Հավատի Անկյուն", communityFaith:"Համայնքի հավատ", faithOfDay:"Օրվա Հավատ", daily:"Ամեն օր", todaysThought:"ԱՅՍՕՐՎԱ ՄԻՏՔ:", seeFaith:"Հավատի գրառումներ →", share:"Կիսվել", commFaithPosts:"Հավատի գրառումներ", loading:"Բեռնում...", noPosts:"Դեռ գրառումներ չկան", postSomething:"Հրապարակել →", whatThis:"Ինչ է սա", what1:"🙏 Հավատի Անկյուն:", what1b:"Տարածք տեղական համայնքի համար.", what2:"🏘 Տեղական:", what2b:"5-20 մղոն շառավղի համար.", what3:"💬 Բաց բոլորի համար:", what3b:"Հյուրընկալ տարածք.", what4:"🤝 Համայնք:", what4b:"Հարևանները օգնում են հավատով.", guidelines:"Ուղեցույցներ", g1:"• Հարգեք ավանդույթները", g2:"• Խրախուսեք հարևաններին", g3:"• Կիսվեք աղոթքներով", g4:"• Առանց նորադարձության", g5:"• Պահեք տեղական", copied:"Պատճենված!" },
az: { faithCorner:"İman Guşəsi", communityFaith:"İcma imanı", faithOfDay:"Günün İmanı", daily:"Gündəlik", todaysThought:"BUGÜNKÜ DÜŞÜNCƏ:", seeFaith:"İman paylaşımları →", share:"Paylaş", commFaithPosts:"İman paylaşımları", loading:"Yüklənir...", noPosts:"Hələ paylaşım yoxdur", postSomething:"Paylaş →", whatThis:"Bu nədir", what1:"🙏 İman Guşəsi:", what1b:"Yerli icma üçün məkan.", what2:"🏘 Yerli:", what2b:"5-20 mil radius üçün.", what3:"💬 Hamı üçün açıq:", what3b:"Qonaqpərvər məkan.", what4:"🤝 İcma:", what4b:"Qonşular imanla kömək edir.", guidelines:"Qaydalar", g1:"• Ənənələrə hörmət", g2:"• Qonşuları təşviq et", g3:"• Duaları paylaş", g4:"• Təbliğat yoxdur", g5:"• Yerli saxla", copied:"Kopyalandı!" },
kk: { faithCorner:"Сенім Бұрышы", communityFaith:"Қауым сенімі", faithOfDay:"Күннің Сенімі", daily:"Күнделікті", todaysThought:"БҮГІНГІ ОЙ:", seeFaith:"Сенім жазбалары →", share:"Бөлісу", commFaithPosts:"Сенім жазбалары", loading:"Жүктелуде...", noPosts:"Әлі жазбалар жоқ", postSomething:"Жариялау →", whatThis:"Бұл не", what1:"🙏 Сенім Бұрышы:", what1b:"Жергілікті қауым үшін орын.", what2:"🏘 Жергілікті:", what2b:"5-20 миль радиус үшін.", what3:"💬 Барлығына ашық:", what3b:"Қонақжай орын.", what4:"🤝 Қауым:", what4b:"Көршілер сеніммен көмектеседі.", guidelines:"Ережелер", g1:"• Дәстүрлерді құрметте", g2:"• Көршілерді қолда", g3:"• Дұғалармен бөліс", g4:"• Прозелитизмсіз", g5:"• Жергілікті ұста", copied:"Көшірілді!" },
ky: { faithCorner:"Ишеним Бурчу", communityFaith:"Коомчулук ишеними", faithOfDay:"Күндүн Ишеними", daily:"Күн сайын", todaysThought:"БҮГҮНКҮ ОЙ:", seeFaith:"Ишеним посттору →", share:"Бөлүшүү", commFaithPosts:"Ишеним посттору", loading:"Жүктөлүүдө...", noPosts:"Азырынча пост жок", postSomething:"Жарыялоо →", whatThis:"Бул эмне", what1:"🙏 Ишеним Бурчу:", what1b:"Жергиликтүү коомчулук үчүн орун.", what2:"🏘 Жергиликтүү:", what2b:"5-20 миль радиус үчүн.", what3:"💬 Баарына ачык:", what3b:"Меймандос орун.", what4:"🤝 Коомчулук:", what4b:"Кошуналар ишеним менен жардам.", guidelines:"Эрежелер", g1:"• Салттарды урматта", g2:"• Кошуналарды колдо", g3:"• Дубалар менен бөлүш", g4:"• Прозелитизм жок", g5:"• Жергиликтүү сакта", copied:"Көчүрүлдү!" },
uz: { faithCorner:"E'tiqod Burchagi", communityFaith:"Jamiyat e'tiqodi", faithOfDay:"Kun E'tiqodi", daily:"Har kuni", todaysThought:"BUGUNGI FIKR:", seeFaith:"E'tiqod postlari →", share:"Ulashish", commFaithPosts:"E'tiqod postlari", loading:"Yuklanmoqda...", noPosts:"Hali postlar yo'q", postSomething:"Joylash →", whatThis:"Bu nima", what1:"🙏 E'tiqod Burchagi:", what1b:"Mahalliy jamiyat uchun joy.", what2:"🏘 Mahalliy:", what2b:"5-20 mil radius uchun.", what3:"💬 Hammaga ochiq:", what3b:"Mehmondo'st joy.", what4:"🤝 Jamiyat:", what4b:"Qo'shnilar e'tiqod bilan yordam.", guidelines:"Qoidalar", g1:"• An'analarni hurmat qil", g2:"• Qo'shnilarni qo'lla", g3:"• Duolarni ulash", g4:"• Targ'ibsiz", g5:"• Mahalliy tut", copied:"Nusxalandi!" },
tg: { faithCorner:"Гӯшаи Имон", communityFaith:"Имони ҷомеа", faithOfDay:"Имони Рӯз", daily:"Ҳаррӯза", todaysThought:"АНДЕШАИ ИМРӮЗ:", seeFaith:"Паёмҳои имон →", share:"Муштарак", commFaithPosts:"Паёмҳои имон", loading:"Боргири...", noPosts:"Ҳанӯз паём нест", postSomething:"Интишор →", whatThis:"Ин чист", what1:"🙏 Гӯшаи Имон:", what1b:"Ҷой барои ҷомеаи маҳаллӣ.", what2:"🏘 Маҳаллӣ:", what2b:"Барои радиуси 5-20 мил.", what3:"💬 Барои ҳама кушода:", what3b:"Ҷойи меҳмоннавоз.", what4:"🤝 Ҷомеа:", what4b:"Ҳамсояҳо бо имон кӯмак.", guidelines:"Дастурҳо", g1:"• Анъанаҳоро эҳтиром кунед", g2:"• Ҳамсояҳоро дастгирӣ кунед", g3:"• Дуоҳоро мубодила кунед", g4:"• Бе таблиғ", g5:"• Маҳаллӣ нигоҳ доред", copied:"Нусхабардорӣ шуд!" },
mn: { faithCorner:"Итгэлийн Булан", communityFaith:"Олон нийтийн итгэл", faithOfDay:"Өнөөдрийн Итгэл", daily:"Өдөр бүр", todaysThought:"ӨНӨӨДРИЙН БОДОЛ:", seeFaith:"Итгэлийн постууд →", share:"Хуваалцах", commFaithPosts:"Итгэлийн постууд", loading:"Ачааллаж...", noPosts:"Одоогоор пост байхгүй", postSomething:"Нийтлэх →", whatThis:"Энэ юу вэ", what1:"🙏 Итгэлийн Булан:", what1b:"Орон нутгийн олон нийтийн орон зай.", what2:"🏘 Орон нутгийн:", what2b:"5-20 милийн радиуст.", what3:"💬 Бүгдэд нээлттэй:", what3b:"Зочломтгой орон зай.", what4:"🤝 Олон нийт:", what4b:"Хөршүүд итгэлээр тусалдаг.", guidelines:"Удирдамж", g1:"• Уламжлалыг хүндэтгэ", g2:"• Хөршүүдээ дэмж", g3:"• Залбирлыг хуваалц", g4:"• Сурталчилгаагүй", g5:"• Орон нутгтаа барь", copied:"Хуулагдлаа!" },
km: { faithCorner:"ជ្រុងជំនឿ", communityFaith:"ជំនឿសហគមន៍", faithOfDay:"ជំនឿថ្ងៃនេះ", daily:"ប្រចាំថ្ងៃ", todaysThought:"គំនិតថ្ងៃនេះ:", seeFaith:"ប្រកាសជំនឿ →", share:"ចែករំលែក", commFaithPosts:"ប្រកាសជំនឿ", loading:"កំពុងផ្ទុក...", noPosts:"មិនទាន់មានប្រកាស", postSomething:"បង្ហោះ →", whatThis:"តើនេះជាអ្វី", what1:"🙏 ជ្រុងជំនឿ:", what1b:"កន្លែងសម្រាប់សហគមន៍មូលដ្ឋាន។", what2:"🏘 មូលដ្ឋាន:", what2b:"សម្រាប់រង្វង់ 5-20 ម៉ាយល៍។", what3:"💬 បើកចំហសម្រាប់ទាំងអស់:", what3b:"កន្លែងស្វាគមន៍។", what4:"🤝 សហគមន៍:", what4b:"អ្នកជិតខាងជួយតាមរយៈជំនឿ។", guidelines:"គោលការណ៍", g1:"• គោរពប្រពៃណី", g2:"• លើកទឹកចិត្តអ្នកជិតខាង", g3:"• ចែករំលែកការអធិស្ឋាន", g4:"• គ្មានការផ្សព្វផ្សាយ", g5:"• រក្សាមូលដ្ឋាន", copied:"បានចម្លង!" },
lo: { faithCorner:"ມຸມແຫ່ງຄວາມເຊື່ອ", communityFaith:"ຄວາມເຊື່ອຊຸມຊົນ", faithOfDay:"ຄວາມເຊື່ອມື້ນີ້", daily:"ປະຈຳວັນ", todaysThought:"ຄວາມຄິດມື້ນີ້:", seeFaith:"ໂພສຄວາມເຊື່ອ →", share:"ແບ່ງປັນ", commFaithPosts:"ໂພສຄວາມເຊື່ອ", loading:"ກຳລັງໂຫຼດ...", noPosts:"ຍັງບໍ່ມີໂພສ", postSomething:"ໂພສ →", whatThis:"ນີ້ແມ່ນຫຍັງ", what1:"🙏 ມຸມແຫ່ງຄວາມເຊື່ອ:", what1b:"ພື້ນທີ່ສຳລັບຊຸມຊົນທ້ອງຖິ່ນ.", what2:"🏘 ທ້ອງຖິ່ນ:", what2b:"ສຳລັບລັດສະໝີ 5-20 ໄມລ໌.", what3:"💬 ເປີດສຳລັບທຸກຄົນ:", what3b:"ພື້ນທີ່ຕ້ອນຮັບ.", what4:"🤝 ຊຸມຊົນ:", what4b:"ເພື່ອນບ້ານຊ່ວຍຜ່ານຄວາມເຊື່ອ.", guidelines:"ແນວທາງ", g1:"• ເຄົາລົບປະເພນີ", g2:"• ຊຸກຍູ້ເພື່ອນບ້ານ", g3:"• ແບ່ງປັນຄຳອະທິຖານ", g4:"• ບໍ່ມີການເຜີຍແຜ່", g5:"• ຮັກສາທ້ອງຖິ່ນ", copied:"ຄັດລອກແລ້ວ!" },
my: { faithCorner:"ယုံကြည်မှုထောင့်", communityFaith:"အသိုင်းအဝိုင်းယုံကြည်မှု", faithOfDay:"ယနေ့ယုံကြည်မှု", daily:"နေ့စဉ်", todaysThought:"ယနေ့အတွေး�:", seeFaith:"ယုံကြည်မှုပို့စ်များ →", share:"မျှဝေရန်", commFaithPosts:"ယုံကြည်မှုပို့စ်များ", loading:"တင်နေသည်...", noPosts:"ပို့စ်မရှိသေး", postSomething:"တင်ရန် →", whatThis:"ဒါဘာလဲ", what1:"🙏 ယုံကြည်မှုထောင့်:", what1b:"ဒေသခံအသိုင်းအဝိုင်းအတွက်နေရာ။", what2:"🏘 ဒေသတွင်း:", what2b:"၅-၂၀ မိုင်အချင်းဝက်အတွက်။", what3:"💬 အားလုံးအတွက်ဖွင့်ထားသည်:", what3b:"ကြိုဆိုသောနေရာ။", what4:"🤝 အသိုင်းအဝိုင်း:", what4b:"အိမ်နီးချင်းများယုံကြည်မှုဖြင့်ကူညီ။", guidelines:"လမ်းညွှန်ချက်များ", g1:"• ရိုးရာကိုလေးစားပါ", g2:"• အိမ်နီးချင်းများအားပေးပါ", g3:"• ဆုတောင်းမျှဝေပါ", g4:"• သာသနာပြုခြင်းမရှိပါ", g5:"• ဒေသတွင်းထားပါ", copied:"ကူးယူပြီး!" },
}

const VERSES: Record<string, {verse:string, prompt:string}[]> = {
en: [{verse:"Love your neighbor as yourself.",prompt:"Who on your block can you show love to today?"},{verse:"Faith without works is dead.",prompt:"Is there a neighbor nearby who needs a hand?"},{verse:"Be still, and know that I am God.",prompt:"Take 30 seconds before you scroll. Breathe."},{verse:"What you do to the least of these, you do to me.",prompt:"That free couch? Someone's blessing."},{verse:"Let your light shine before others.",prompt:"Post one encouragement to your block today."},{verse:"Bear one another's burdens.",prompt:"Someone near you is carrying something heavy."},{verse:"The Lord is near to the brokenhearted.",prompt:"Check on a neighbor today."},{verse:"Do unto others as you would have them do unto you.",prompt:"WWJD on your block today?"}],
es: [{verse:"Ama a tu projimo como a ti mismo.",prompt:"¿A quien en tu cuadra puedes mostrar amor hoy?"},{verse:"La fe sin obras esta muerta.",prompt:"¿Hay un vecino cerca que necesita ayuda?"},{verse:"Estad quietos y conoced que yo soy Dios.",prompt:"Toma 30 segundos antes de desplazarte. Respira."},{verse:"Lo que hicisteis a uno de estos mas pequeños, a mi lo hicisteis.",prompt:"¿Ese sofa gratis? La bendicion de alguien."},{verse:"Deja que tu luz brille ante los demas.",prompt:"Publica un animo para tu cuadra hoy."},{verse:"Llevad los unos las cargas de los otros.",prompt:"Alguien cerca lleva algo pesado."},{verse:"El Señor esta cerca de los quebrantados de corazon.",prompt:"Visita a un vecino hoy."},{verse:"Haz a otros como quieres que te hagan a ti.",prompt:"¿Que haria Jesus en tu cuadra hoy?"}],
fr: [{verse:"Aime ton prochain comme toi-meme.",prompt:"Qui peux-tu aimer aujourd'hui?"},{verse:"La foi sans les oeuvres est morte.",prompt:"Un voisin a besoin d'aide?"},{verse:"Arretez et sachez que je suis Dieu.",prompt:"Prends 30 secondes. Respire."},{verse:"Ce que vous faites au plus petit, c'est a moi.",prompt:"Ce canape gratuit? Benediction."},{verse:"Que votre lumiere brille.",prompt:"Poste un encouragement."},{verse:"Portez les fardeaux les uns des autres.",prompt:"Quelqu'un porte quelque chose de lourd."},{verse:"Le Seigneur est pres des coeurs brises.",prompt:"Prends des nouvelles d'un voisin."},{verse:"Fais aux autres ce que tu veux qu'on te fasse.",prompt:"Que ferait Jesus?"}],
de: [{verse:"Liebe deinen Nachsten wie dich selbst.",prompt:"Wem kannst du heute Liebe zeigen?"},{verse:"Glaube ohne Werke ist tot.",prompt:"Braucht ein Nachbar Hilfe?"},{verse:"Seid stille und erkennet, dass ich Gott bin.",prompt:"30 Sekunden atmen."},{verse:"Was ihr einem der Geringsten getan habt, habt ihr mir getan.",prompt:"Kostenlose Couch? Segen."},{verse:"Lasst euer Licht leuchten.",prompt:"Poste Ermutigung heute."},{verse:"Einer trage des anderen Last.",prompt:"Jemand tragt Schweres."},{verse:"Der Herr ist nahe den zerbrochenen Herzen.",prompt:"Schau nach einem Nachbarn."},{verse:"Tut anderen wie ihr wollt dass man euch tut.",prompt:"Was wurde Jesus tun?"}],
zh: [{verse:"爱你的邻舍如同自己。",prompt:"今天你能向谁表达爱？"},{verse:"没有行为的信心是死的。",prompt:"附近有邻居需要帮助吗？"},{verse:"要安静，知道我是神。",prompt:"滚动前花30秒呼吸。"},
{verse:"你们为最小的人做的，就是为我做的。",prompt:"免费沙发？某人的祝福。"},{verse:"让你的光照在人前。",prompt:"今天发一条鼓励。"},
{verse:"互相担当重担。",prompt:"附近有人背负重担。"},
{verse:"耶和华靠近伤心的人。",prompt:"今天去看看邻居。"},
{verse:"你们愿意人怎样待你们，也要怎样待人。",prompt:"耶稣今天会在你街区做什么？"}],
ja: [{verse:"隣人を自分のように愛しなさい。",prompt:"今日誰に愛を示せますか？"},{verse:"行いのない信仰は死んだもの。",prompt:"近所で助けが必要な人は？"},
{verse:"静まって、私が神であることを知れ。",prompt:"スクロール前に30秒呼吸。"},
{verse:"最も小さい者にしたことは私にしたこと。",prompt:"無料ソファ？誰かの祝福。"},
{verse:"あなたの光を人々の前に輝かせなさい。",prompt:"今日励ましを投稿。"},
{verse:"互いに重荷を負い合いなさい。",prompt:"誰かが重いものを背負っている。"},
{verse:"主は心の砕かれた者の近くにいる。",prompt:"今日隣人を訪ねて。"},
{verse:"人からしてほしいことを人にしなさい。",prompt:"今日あなたの街でイエスは何をする？"}],
ko: [{verse:"네 이웃을 네 몸과 같이 사랑하라.",prompt:"오늘 누구에게 사랑을 보일까?"},{verse:"행함이 없는 믿음은 죽은 것.",prompt:"근처 이웃 도움이 필요?"},{verse:"잠잠하고 내가 하나님임을 알지어다.",prompt:"스크롤 전 30초 숨쉬기."},{verse:"가장 작은 자에게 한 것이 내게 한 것.",prompt:"무료 소파? 누군가의 축복."},{verse:"너희 빛을 사람 앞에 비추게 하라.",prompt:"오늘 격려 게시."},{verse:"서로 짐을 지라.",prompt:"누군가 무거운 짐을 지고 있다."},{verse:"여호와는 마음이 상한 자에게 가까이 계신다.",prompt:"오늘 이웃을 확인해."},{verse:"남에게 대접받고 싶은 대로 남을 대접하라.",prompt:"예수라면 오늘 무엇을 할까?"}],
ru: [{verse:"Возлюби ближнего твоего, как самого себя.",prompt:"Кому сегодня показать любовь?"},{verse:"Вера без дел мертва.",prompt:"Нужна ли помощь соседу?"},{verse:"Остановитесь и познайте, что Я — Бог.",prompt:"30 секунд перед скроллом. Дыши."},{verse:"Что вы сделали одному из меньших, то сделали Мне.",prompt:"Бесплатный диван? Чье-то благословение."},{verse:"Да светит свет ваш пред людьми.",prompt:"Опубликуй ободрение сегодня."},{verse:"Носите бремена друг друга.",prompt:"Кто-то рядом несет тяжелое."},{verse:"Близок Господь к сокрушенным сердцем.",prompt:"Проверь соседа сегодня."},{verse:"Как хотите чтобы с вами поступали, так и вы поступайте.",prompt:"Что бы сделал Иисус сегодня?"}],
ar: [{verse:"تحب قريبك كنفسك.",prompt:"من يمكنك أن تحب اليوم؟"},{verse:"الإيمان بدون أعمال ميت.",prompt:"هل هناك جار يحتاج مساعدة؟"},{verse:"اسكنوا واعلموا أني أنا الله.",prompt:"خذ 30 ثانية قبل التمرير. تنفس."},{verse:"ما فعلتموه بأحد هؤلاء الصغار فبي فعلتم.",prompt:"تلك الأريكة المجانية؟ بركة أحدهم."},{verse:"ليضيء نوركم أمام الناس.",prompt:"انشر تشجيعا اليوم."},{verse:"احملوا بعضكم أثقال بعض.",prompt:"شخص قريب يحمل شيئا ثقيلا."},{verse:"الرب قريب من منكسري القلب.",prompt:"تفقد جارا اليوم."},{verse:"كما تريدون أن يفعل الناس بكم افعلوا أنتم أيضا بهم.",prompt:"ماذا سيفعل يسوع اليوم؟"}],
pt: [{verse:"Ama o teu proximo como a ti mesmo.",prompt:"Quem podes amar hoje?"},{verse:"A fe sem obras e morta.",prompt:"Vizinho precisa de ajuda?"},{verse:"Aquietai-vos e sabei que eu sou Deus.",prompt:"30 segundos antes de rolar. Respira."},{verse:"O que fizestes a um destes pequenos, a mim o fizestes.",prompt:"Sofa gratis? Bencao de alguem."},{verse:"Deixe sua luz brilhar.",prompt:"Poste incentivo hoje."},{verse:"Levai as cargas uns dos outros.",prompt:"Alguem carrega algo pesado."},{verse:"O Senhor esta perto dos quebrantados.",prompt:"Visite um vizinho hoje."},{verse:"Faca aos outros como quer que facam a voce.",prompt:"O que Jesus faria hoje?"}],
it: [{verse:"Ama il tuo prossimo come te stesso.",prompt:"Chi puoi amare oggi?"},{verse:"La fede senza opere e morta.",prompt:"Un vicino ha bisogno?"},{verse:"Fermatevi e riconoscete che io sono Dio.",prompt:"30 secondi prima di scorrere. Respira."},{verse:"Quello che avete fatto al piu piccolo, l'avete fatto a me.",prompt:"Divano gratis? Benedizione di qualcuno."},{verse:"La vostra luce brilli davanti agli altri.",prompt:"Posta incoraggiamento oggi."},{verse:"Portate i pesi gli uni degli altri.",prompt:"Qualcuno vicino porta qualcosa di pesante."},{verse:"Il Signore e vicino a chi ha il cuore spezzato.",prompt:"Controlla un vicino oggi."},{verse:"Fate agli altri come vorreste che facessero a voi.",prompt:"Cosa farebbe Gesu oggi?"}],
nl: [{verse:"Heb je naaste lief als jezelf.",prompt:"Wie kun je vandaag liefde tonen?"},{verse:"Geloof zonder werken is dood.",prompt:"Heeft een buur hulp nodig?"},{verse:"Wees stil en weet dat Ik God ben.",prompt:"30 seconden voor scrollen. Adem."},{verse:"Wat je voor de minsten deed, deed je voor mij.",prompt:"Gratis bank? iemands zegen."},{verse:"Laat je licht schijnen.",prompt:"Post vandaag bemoediging."},{verse:"Draag elkaars lasten.",prompt:"Iemand draagt iets zwaars."},{verse:"De Heer is nabij de gebrokenen van hart.",prompt:"Check een buur vandaag."},{verse:"Behandel anderen zoals je behandeld wilt worden.",prompt:"Wat zou Jezus doen vandaag?"}],
}

function fillVerses(): Record<string, {verse:string,prompt:string}[]> {
  const all = ["en","es","fr","de","zh","ja","ko","ru","ar","pt","it","nl","tl","hi","bn","id","vi","th","sv","pl","tr","uk","el","he","ur","fa","ms","ro","cs","hu","fi","no","da","bg","hr","sr","sk","sl","et","lv","lt","be","ka","hy","az","kk","ky","uz","tg","mn","km","lo","my"]
  const out: Record<string, any> = { ...VERSES }
  for (const lang of all) {
    if (!out[lang]) {
      // For remaining langs, use EN as base but keep UI translated
      out[lang] = out.en
    }
  }
  return out
}
const V = fillVerses()
const REFS = ["Mark 12:31","James 2:17","Psalm 46:10","Matthew 25:40","Matthew 5:16","Galatians 6:2","Psalm 34:18","Luke 6:31"]

export default function FaithPage() {
  const { zip, city } = useLocation()
  const { language } = useLanguage()
  const t = D[language] || D.en
  const [faithPosts, setFaithPosts] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const supabase = createClient()
  const [copied, setCopied] = useState(false)
  const displayArea = city || zip || 'your area'
  const verses = V[language] || V.en
  const today = verses[new Date().getDate() % verses.length]
  const ref = REFS[new Date().getDate() % REFS.length]

  useEffect(() => {
    if (!zip) return
    const load = async () => {
      try {
        const { data } = await supabase.from('posts').select('*').eq('zip_code', zip).or('tag.eq.faith,category.eq.faith').order('created_at', { ascending: false }).limit(50)
        if (data) setFaithPosts(data)
      } catch {} finally { setLoading(false) }
    }
    load()
  }, [zip])

  const handleShare = ()=>{
    const text = `"${today.verse}" - ${ref} - from Sweet Social Space`
    if(typeof navigator!== 'undefined' && navigator.clipboard) {
      navigator.clipboard.writeText(text).then(()=>{ setCopied(true); setTimeout(()=>setCopied(false),2000) })
    }
  }

  return (
    <div className="min-h-screen bg-black text-white p-6 max-w-4xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-black mb-2">{t.faithCorner}</h1>
        <p className="text-white/60">{t.communityFaith} {displayArea}</p>
      </div>
      <div className="space-y-6">
        <div className="bg-gradient-to-br from-purple-900 via-indigo-900 to-black rounded-2xl p-6 border border-white/10 shadow-xl relative overflow-hidden">
          <div className="absolute top-0 right-0 w-32 h-32 bg-yellow-400/20 rounded-full blur-3xl" />
          <div className="relative">
            <div className="flex items-center justify-between mb-4">
              <span className="text-sm font-black tracking-widest text-yellow-400">{t.faithOfDay}</span>
              <span className="bg-white/10 text-white/60 px-3 py-1 rounded-full text-xs">{t.daily}</span>
            </div>
            <div className="text-white font-black text-2xl leading-tight mb-3">"{today.verse}"</div>
            <div className="text-yellow-400 font-black text-sm tracking-widest mb-4">{ref}</div>
            <div className="bg-white/10 rounded-xl p-4 border border-white/10">
              <div className="text-white/60 text-xs font-black tracking-widest mb-2">{t.todaysThought}</div>
              <div className="text-white text-base font-bold leading-snug">{today.prompt}</div>
            </div>
            <div className="mt-4 flex gap-2">
              <Link href="/feed?filter=faith" className="flex-1 bg-white text-black text-sm font-black px-4 py-2 rounded-full text-center hover:bg-yellow-400 transition">{t.seeFaith}</Link>
              <button onClick={handleShare} className="bg-white/10 text-white text-sm font-black px-4 py-2 rounded-full border border-white/20 min-w-[90px]">{copied ? t.copied : t.share}</button>
            </div>
          </div>
        </div>

        <div className="bg-white/5 border border-white/10 rounded-2xl p-6">
          <h2 className="text-xl font-black mb-4">{t.commFaithPosts}</h2>
          {loading ? <p className="text-white/60">{t.loading}</p> : faithPosts.length===0 ? <div className="text-center py-8"><p className="text-white/60 mb-4">{t.noPosts} {displayArea}</p><Link href="/feed" className="inline-block bg-white text-black px-6 py-2 rounded-full font-black text-sm hover:bg-yellow-400 transition">{t.postSomething}</Link></div> : <div className="space-y-4">{faithPosts.map((post:any)=>(<div key={post.id} className="bg-white/5 rounded-xl p-4 border border-white/10"><p className="text-white text-sm leading-relaxed">{post.body}</p><div className="mt-2 text-xs text-white/40">{new Date(post.created_at).toLocaleString()} • {post.zip_code}</div></div>))}</div>}
        </div>

        <div className="bg-white/5 border border-white/10 rounded-2xl p-6">
          <h2 className="text-xl font-black mb-4">{t.whatThis}</h2>
          <div className="space-y-3 text-white/70 text-sm"><p><strong>{t.what1}</strong> {t.what1b}</p><p><strong>{t.what2}</strong> {t.what2b}</p><p><strong>{t.what3}</strong> {t.what3b}</p><p><strong>{t.what4}</strong> {t.what4b}</p></div>
        </div>

        <div className="bg-gradient-to-r from-purple-900/20 to-pink-900/20 border border-white/10 rounded-2xl p-6">
          <h2 className="text-xl font-black mb-4">{t.guidelines}</h2>
          <div className="space-y-2 text-white/70 text-sm"><p>{t.g1}</p><p>{t.g2}</p><p>{t.g3}</p><p>{t.g4}</p><p>{t.g5}</p></div>
        </div>
      </div>
    </div>
  )
}
