export async function GET(req: Request) {
  const { searchParams } = new URL(req.url)
  const lang = (searchParams.get('lang') || 'en').toLowerCase().split('-')[0]

  // Full 53-lang verse translations for common verses that OurManna returns often
  const DICT: Record<string, Record<string, string>> = {
    en: {
      "The Lord is near to the brokenhearted.": "The Lord is near to the brokenhearted.",
      "Love your neighbor as yourself.": "Love your neighbor as yourself.",
      "Faith without works is dead.": "Faith without works is dead.",
      "Be still, and know that I am God.": "Be still, and know that I am God.",
      "Love is patient, love is kind.": "Love is patient, love is kind.",
      "For God so loved the world.": "For God so loved the world.",
    },
    es: {
      "The Lord is near to the brokenhearted.": "El Señor está cerca de los quebrantados de corazón.",
      "Love your neighbor as yourself.": "Ama a tu prójimo como a ti mismo.",
      "Faith without works is dead.": "La fe sin obras está muerta.",
      "Be still, and know that I am God.": "Estad quietos y conoced que yo soy Dios.",
      "Love is patient, love is kind.": "El amor es paciente, el amor es bondadoso.",
      "For God so loved the world.": "Porque de tal manera amó Dios al mundo.",
    },
    fr: {
      "The Lord is near to the brokenhearted.": "Le Seigneur est près de ceux qui ont le cœur brisé.",
      "Love your neighbor as yourself.": "Aime ton prochain comme toi-même.",
      "Faith without works is dead.": "La foi sans les œuvres est morte.",
      "Be still, and know that I am God.": "Arrêtez et sachez que je suis Dieu.",
      "Love is patient, love is kind.": "L'amour est patient, l'amour est bon.",
      "For God so loved the world.": "Car Dieu a tant aimé le monde.",
    },
    de: {
      "The Lord is near to the brokenhearted.": "Der Herr ist nahe denen, die zerbrochenen Herzens sind.",
      "Love your neighbor as yourself.": "Liebe deinen Nächsten wie dich selbst.",
      "Faith without works is dead.": "Glaube ohne Werke ist tot.",
      "Be still, and know that I am God.": "Seid stille und erkennt, dass ich Gott bin.",
      "Love is patient, love is kind.": "Die Liebe ist langmütig und freundlich.",
      "For God so loved the world.": "Denn so sehr hat Gott die Welt geliebt.",
    },
    zh: {
      "The Lord is near to the brokenhearted.": "耶和华靠近伤心的人。",
      "Love your neighbor as yourself.": "要爱人如己。",
      "Faith without works is dead.": "信心若没有行为就是死的。",
      "Be still, and know that I am God.": "你们要休息，要知道我是神。",
      "Love is patient, love is kind.": "爱是恒久忍耐，又有恩慈。",
      "For God so loved the world.": "神爱世人，甚至将他的独生子赐给他们。",
    },
    ja: {
      "The Lord is near to the brokenhearted.": "主は心の打ち砕かれた者の近くにおられる。",
      "Love your neighbor as yourself.": "自分を愛するように隣人を愛しなさい。",
      "Faith without works is dead.": "行いのない信仰は死んだものです。",
      "Be still, and know that I am God.": "静まって、私こそ神であることを知れ。",
      "Love is patient, love is kind.": "愛は寛容であり、愛は親切です。",
      "For God so loved the world.": "神はその独り子をお与えになったほどに世を愛された。",
    },
    ko: {
      "The Lord is near to the brokenhearted.": "여호와는 마음이 상한 자를 가까이 하시나니",
      "Love your neighbor as yourself.": "네 이웃을 네 자신과 같이 사랑하라.",
      "Faith without works is dead.": "행함이 없는 믿음은 죽은 것이다.",
      "Be still, and know that I am God.": "잠잠하고 내가 하나님 됨을 알지어다.",
      "Love is patient, love is kind.": "사랑은 오래 참고 사랑은 온유하며",
      "For God so loved the world.": "하나님이 세상을 이처럼 사랑하사",
    },
    ru: {
      "The Lord is near to the brokenhearted.": "Близок Господь к сокрушенным сердцем.",
      "Love your neighbor as yourself.": "Возлюби ближнего твоего, как самого себя.",
      "Faith without works is dead.": "Вера без дел мертва.",
      "Be still, and know that I am God.": "Остановитесь и познайте, что Я — Бог.",
      "Love is patient, love is kind.": "Любовь долготерпит, милосердствует.",
      "For God so loved the world.": "Ибо так возлюбил Бог мир.",
    },
    ar: {
      "The Lord is near to the brokenhearted.": "قريب هو الرب من المنكسري القلوب.",
      "Love your neighbor as yourself.": "تحب قريبك كنفسك.",
      "Faith without works is dead.": "الإيمان بدون أعمال ميت.",
      "Be still, and know that I am God.": "كفوا واعلموا أني أنا الله.",
      "Love is patient, love is kind.": "المحبة تتأنى وترفق.",
      "For God so loved the world.": "لأنه هكذا أحب الله العالم.",
    },
    pt: {
      "The Lord is near to the brokenhearted.": "O Senhor está perto dos que têm o coração quebrantado.",
      "Love your neighbor as yourself.": "Ame o seu próximo como a si mesmo.",
      "Faith without works is dead.": "A fé sem obras é morta.",
      "Be still, and know that I am God.": "Aquietai-vos e sabei que eu sou Deus.",
      "Love is patient, love is kind.": "O amor é paciente, o amor é bondoso.",
      "For God so loved the world.": "Porque Deus amou o mundo de tal maneira.",
    },
    it: {
      "The Lord is near to the brokenhearted.": "Il Signore è vicino a quelli che hanno il cuore spezzato.",
      "Love your neighbor as yourself.": "Ama il tuo prossimo come te stesso.",
      "Faith without works is dead.": "La fede senza le opere è morta.",
      "Be still, and know that I am God.": "Fermatevi e sappiate che io sono Dio.",
      "Love is patient, love is kind.": "L'amore è paziente, è benigno l'amore.",
      "For God so loved the world.": "Dio ha tanto amato il mondo.",
    },
    nl: {
      "The Lord is near to the brokenhearted.": "De Heer is nabij de gebroken harten.",
      "Love your neighbor as yourself.": "Heb je naaste lief als jezelf.",
      "Faith without works is dead.": "Geloof zonder werken is dood.",
      "Be still, and know that I am God.": "Wees stil en weet dat Ik God ben.",
      "Love is patient, love is kind.": "De liefde is geduldig en vriendelijk.",
      "For God so loved the world.": "Want God had de wereld zo lief.",
    },
    tl: {
      "The Lord is near to the brokenhearted.": "Malapit ang Panginoon sa may pusong wasak.",
      "Love your neighbor as yourself.": "Mahalin mo ang iyong kapwa gaya ng iyong sarili.",
      "Faith without works is dead.": "Ang pananampalatayang walang gawa ay patay.",
      "Be still, and know that I am God.": "Tumahimik kayo at kilalanin ninyo na ako ang Diyos.",
      "Love is patient, love is kind.": "Ang pag-ibig ay matiyaga at mabait.",
      "For God so loved the world.": "Gayon na lamang ang pag-ibig ng Diyos sa sanlibutan.",
    },
    hi: {
      "The Lord is near to the brokenhearted.": "यहोवा टूटे मन वालों के समीप रहता है।",
      "Love your neighbor as yourself.": "अपने पड़ोसी से अपने समान प्रेम रख।",
      "Faith without works is dead.": "कर्म बिना विश्वास मरा हुआ है।",
      "Be still, and know that I am God.": "चुप हो जाओ और जान लो कि मैं ही परमेश्वर हूँ।",
      "Love is patient, love is kind.": "प्रेम धीरजवंत है और कृपालु है।",
      "For God so loved the world.": "परमेश्वर ने जगत से ऐसा प्रेम रखा।",
    },
    bn: {
      "The Lord is near to the brokenhearted.": "সদাপ্রভু ভগ্নহৃদয়দের কাছাকাছি থাকেন।",
      "Love your neighbor as yourself.": "তোমার প্রতিবেশীকে নিজের মতো ভালোবাসো।",
      "Faith without works is dead.": "কর্মবিহীন বিশ্বাস মৃত।",
      "Be still, and know that I am God.": "স্থির হও এবং জানো আমিই ঈশ্বর।",
      "Love is patient, love is kind.": "প্রেম ধৈর্যশীল, প্রেম দয়ালু।",
      "For God so loved the world.": "কারণ ঈশ্বর জগৎকে এমন প্রেম করলেন।",
    },
    id: {
      "The Lord is near to the brokenhearted.": "Tuhan dekat kepada orang-orang yang patah hati.",
      "Love your neighbor as yourself.": "Kasihilah sesamamu seperti dirimu sendiri.",
      "Faith without works is dead.": "Iman tanpa perbuatan adalah mati.",
      "Be still, and know that I am God.": "Diamlah dan ketahuilah bahwa Akulah Allah.",
      "Love is patient, love is kind.": "Kasih itu sabar, kasih itu murah hati.",
      "For God so loved the world.": "Karena begitu besar kasih Allah akan dunia ini.",
    },
    vi: {
      "The Lord is near to the brokenhearted.": "Đức Giê-hô-va ở gần những người có lòng đau thương.",
      "Love your neighbor as yourself.": "Hãy yêu người lân cận như mình.",
      "Faith without works is dead.": "Đức tin không có việc làm là chết.",
      "Be still, and know that I am God.": "Hãy yên lặng và biết rằng ta là Đức Chúa Trời.",
      "Love is patient, love is kind.": "Tình yêu thương hay nhịn nhục, hay nhân từ.",
      "For God so loved the world.": "Vì Đức Chúa Trời yêu thương thế gian.",
    },
    th: {
      "The Lord is near to the brokenhearted.": "พระเจ้าทรงอยู่ใกล้ผู้ที่ชอกช้ำใจ",
      "Love your neighbor as yourself.": "จงรักเพื่อนบ้านเหมือนรักตนเอง",
      "Faith without works is dead.": "ความเชื่อที่ไม่มีการกระทำก็ตายแล้ว",
      "Be still, and know that I am God.": "จงนิ่งเสียและรู้เถอะว่าเราคือพระเจ้า",
      "Love is patient, love is kind.": "ความรักนั้นก็อดทนนานและกระทำคุณให้",
      "For God so loved the world.": "เพราะว่าพระเจ้าทรงรักโลก",
    },
    sv: {
      "The Lord is near to the brokenhearted.": "Herren är nära de som har ett förkrossat hjärta.",
      "Love your neighbor as yourself.": "Du ska älska din nästa som dig själv.",
      "Faith without works is dead.": "Tro utan gärningar är död.",
      "Be still, and know that I am God.": "Var stilla och besinna att jag är Gud.",
      "Love is patient, love is kind.": "Kärleken är tålmodig och god.",
      "For God so loved the world.": "Så älskade Gud världen.",
    },
    pl: {
      "The Lord is near to the brokenhearted.": "Pan jest blisko skruszonych w sercu.",
      "Love your neighbor as yourself.": "Będziesz miłował bliźniego swego jak siebie samego.",
      "Faith without works is dead.": "Wiara bez uczynków jest martwa.",
      "Be still, and know that I am God.": "Uspokójcie się i uznajcie, że Ja jestem Bogiem.",
      "Love is patient, love is kind.": "Miłość cierpliwa jest, łaskawa jest miłość.",
      "For God so loved the world.": "Tak bowiem Bóg umiłował świat.",
    },
    tr: {
      "The Lord is near to the brokenhearted.": "Rab yüreği kırık olanlara yakındır.",
      "Love your neighbor as yourself.": "Komşunu kendin gibi sev.",
      "Faith without works is dead.": "Eylemsiz iman ölüdür.",
      "Be still, and know that I am God.": "Sakin olun ve bilin ki ben Tanrıyım.",
      "Love is patient, love is kind.": "Sevgi sabırlıdır, sevgi şefkatlidir.",
      "For God so loved the world.": "Çünkü Tanrı dünyayı öyle sevdi.",
    },
    uk: {
      "The Lord is near to the brokenhearted.": "Близький Господь до зламаних серцем.",
      "Love your neighbor as yourself.": "Люби ближнього свого, як самого себе.",
      "Faith without works is dead.": "Віра без діл мертва.",
      "Be still, and know that I am God.": "Вгамуйтесь і пізнайте, що Я — Бог.",
      "Love is patient, love is kind.": "Любов довготерпить, любов милосердствує.",
      "For God so loved the world.": "Так бо Бог полюбив світ.",
    },
    el: {
      "The Lord is near to the brokenhearted.": "Ο Κύριος είναι κοντά στους συντετριμμένους την καρδία.",
      "Love your neighbor as yourself.": "Αγάπα τον πλησίον σου ως σεαυτόν.",
      "Faith without works is dead.": "Η πίστη χωρίς έργα είναι νεκρή.",
      "Be still, and know that I am God.": "Ησυχάσατε και γνωρίσατε ότι εγώ είμαι ο Θεός.",
      "Love is patient, love is kind.": "Η αγάπη μακροθυμεί, χρηστεύεται η αγάπη.",
      "For God so loved the world.": "Τόσο αγάπησε ο Θεός τον κόσμο.",
    },
    he: {
      "The Lord is near to the brokenhearted.": "קרוב ה' לנשברי לב.",
      "Love your neighbor as yourself.": "ואהבת לרעך כמוך.",
      "Faith without works is dead.": "אמונה בלי מעשים מתה היא.",
      "Be still, and know that I am God.": "הרפו ודעו כי אנכי אלהים.",
      "Love is patient, love is kind.": "האהבה סבלנית וטובה.",
      "For God so loved the world.": "כי כה אהב אלהים את העולם.",
    },
    ur: {
      "The Lord is near to the brokenhearted.": "خداوند شکستہ دلوں کے نزدیک ہے۔",
      "Love your neighbor as yourself.": "اپنے پڑوسی سے اپنے جیسی محبت رکھ۔",
      "Faith without works is dead.": "اعمال کے بغیر ایمان مردہ ہے۔",
      "Be still, and know that I am God.": "خاموش ہو جاؤ اور جان لو کہ میں خدا ہوں۔",
      "Love is patient, love is kind.": "محبت صابر اور مہربان ہے۔",
      "For God so loved the world.": "کیونکہ خدا نے دنیا سے ایسی محبت رکھی۔",
    },
    fa: {
      "The Lord is near to the brokenhearted.": "خداوند نزدیک شکستہ‌دلان است.",
      "Love your neighbor as yourself.": "همسایه‌ات را چون خویشتن دوست بدار.",
      "Faith without works is dead.": "ایمان بدون اعمال مرده است.",
      "Be still, and know that I am God.": "آرام باشید و بدانید من خدا هستم.",
      "Love is patient, love is kind.": "محبت بردبار و مهربان است.",
      "For God so loved the world.": "زیرا خدا جهان را آنقدر محبت نمود.",
    },
    ms: {
      "The Lord is near to the brokenhearted.": "Tuhan dekat kepada orang yang patah hati.",
      "Love your neighbor as yourself.": "Kasihilah sesamamu seperti dirimu sendiri.",
      "Faith without works is dead.": "Iman tanpa perbuatan adalah mati.",
      "Be still, and know that I am God.": "Diamlah dan ketahuilah bahawa Akulah Allah.",
      "Love is patient, love is kind.": "Kasih itu sabar, kasih itu murah hati.",
      "For God so loved the world.": "Kerana begitu besar kasih Allah akan dunia.",
    },
    ro: {
      "The Lord is near to the brokenhearted.": "Domnul este aproape de cei cu inima zdrobită.",
      "Love your neighbor as yourself.": "Iubește-ți aproapele ca pe tine însuți.",
      "Faith without works is dead.": "Credința fără fapte este moartă.",
      "Be still, and know that I am God.": "Opriți-vă și să știți că Eu sunt Dumnezeu.",
      "Love is patient, love is kind.": "Dragostea este îndelung răbdătoare, este plină de bunătate.",
      "For God so loved the world.": "Fiindcă atât de mult a iubit Dumnezeu lumea.",
    },
    cs: {
      "The Lord is near to the brokenhearted.": "Hospodin je blízko těm, kdo mají zkroušené srdce.",
      "Love your neighbor as yourself.": "Miluj svého bližního jako sám sebe.",
      "Faith without works is dead.": "Víra bez skutků je mrtvá.",
      "Be still, and know that I am God.": "Utište se a poznejte, že já jsem Bůh.",
      "Love is patient, love is kind.": "Láska je trpělivá, laskavá je láska.",
      "For God so loved the world.": "Neboť Bůh tak miloval svět.",
    },
    hu: {
      "The Lord is near to the brokenhearted.": "Közel van az Úr a megtört szívűekhez.",
      "Love your neighbor as yourself.": "Szeresd felebarátodat, mint magadat.",
      "Faith without works is dead.": "A hit cselekedetek nélkül halott.",
      "Be still, and know that I am God.": "Csendesedjetek el és ismerjétek el, hogy én vagyok az Isten.",
      "Love is patient, love is kind.": "A szeretet türelmes, jóságos a szeretet.",
      "For God so loved the world.": "Mert úgy szerette Isten a világot.",
    },
    fi: {
      "The Lord is near to the brokenhearted.": "Herra on lähellä niitä, joilla on särkynyt sydän.",
      "Love your neighbor as yourself.": "Rakasta lähimmäistäsi niin kuin itseäsi.",
      "Faith without works is dead.": "Usko ilman tekoja on kuollut.",
      "Be still, and know that I am God.": "Heretkää ja tietäkää, että minä olen Jumala.",
      "Love is patient, love is kind.": "Rakkaus on pitkämielinen, laupias on rakkaus.",
      "For God so loved the world.": "Sillä niin on Jumala maailmaa rakastanut.",
    },
    no: {
      "The Lord is near to the brokenhearted.": "Herren er nær dem som har et nedbrutt hjerte.",
      "Love your neighbor as yourself.": "Du skal elske din neste som deg selv.",
      "Faith without works is dead.": "Tro uten gjerninger er død.",
      "Be still, and know that I am God.": "Vær stille og kjenn at jeg er Gud.",
      "Love is patient, love is kind.": "Kjærligheten er tålmodig, kjærligheten er god.",
      "For God so loved the world.": "For så har Gud elsket verden.",
    },
    da: {
      "The Lord is near to the brokenhearted.": "Herren er nær hos de sønderknuste hjerter.",
      "Love your neighbor as yourself.": "Du skal elske din næste som dig selv.",
      "Faith without works is dead.": "Tro uden gerninger er død.",
      "Be still, and know that I am God.": "Hold inde og erkend at jeg er Gud.",
      "Love is patient, love is kind.": "Kærligheden er tålmodig, kærligheden er mild.",
      "For God so loved the world.": "For således elskede Gud verden.",
    },
    bg: {
      "The Lord is near to the brokenhearted.": "Господ е близо до съкрушените по сърце.",
      "Love your neighbor as yourself.": "Обичай ближния си както себе си.",
      "Faith without works is dead.": "Вярата без дела е мъртва.",
      "Be still, and know that I am God.": "Успокойте се и познайте, че Аз съм Бог.",
      "Love is patient, love is kind.": "Любовта дълго търпи, благосклонна е.",
      "For God so loved the world.": "Защото Бог толкова възлюби света.",
    },
    hr: {
      "The Lord is near to the brokenhearted.": "Blizu je Gospodin onima koji su slomljena srca.",
      "Love your neighbor as yourself.": "Ljubi bližnjega svoga kao sebe samoga.",
      "Faith without works is dead.": "Vjera bez djela je mrtva.",
      "Be still, and know that I am God.": "Prestanite i spoznajte da sam ja Bog.",
      "Love is patient, love is kind.": "Ljubav je strpljiva, dobrostiva je ljubav.",
      "For God so loved the world.": "Jer Bog je tako ljubio svijet.",
    },
    sr: {
      "The Lord is near to the brokenhearted.": "Близу је Господ онима који су скрушена срца.",
      "Love your neighbor as yourself.": "Љуби ближњег свог као себе самог.",
      "Faith without works is dead.": "Вера без дела је мртва.",
      "Be still, and know that I am God.": "Престаните и познајте да сам ја Бог.",
      "Love is patient, love is kind.": "Љубав дуго трпи, благотворна је љубав.",
      "For God so loved the world.": "Јер Бог тако заволе свет.",
    },
    sk: {
      "The Lord is near to the brokenhearted.": "Blízko je Pán tým, čo majú skrúšené srdce.",
      "Love your neighbor as yourself.": "Miluj svojho blížneho ako seba samého.",
      "Faith without works is dead.": "Viera bez skutkov je mŕtva.",
      "Be still, and know that I am God.": "Utište sa a poznajte, že ja som Boh.",
      "Love is patient, love is kind.": "Láska je trpezlivá, láska je dobrotivá.",
      "For God so loved the world.": "Lebo tak miloval Boh svet.",
    },
    sl: {
      "The Lord is near to the brokenhearted.": "Gospod je blizu tistim, ki so strtega srca.",
      "Love your neighbor as yourself.": "Ljubi svojega bližnjega kakor samega sebe.",
      "Faith without works is dead.": "Vera brez del je mrtva.",
      "Be still, and know that I am God.": "Nehajte in spoznajte, da sem jaz Bog.",
      "Love is patient, love is kind.": "Ljubezen je potrpežljiva, dobrotljiva je ljubezen.",
      "For God so loved the world.": "Bog je namreč svet tako vzljubil.",
    },
    et: {
      "The Lord is near to the brokenhearted.": "Issand on lähedal neile, kellel on purustatud süda.",
      "Love your neighbor as yourself.": "Armasta oma ligimest nagu iseennast.",
      "Faith without works is dead.": "Usk ilma tegudeta on surnud.",
      "Be still, and know that I am God.": "Jääge vait ja tundke, et mina olen Jumal.",
      "Love is patient, love is kind.": "Armastus on pikameelne, armastus on lahke.",
      "For God so loved the world.": "Sest nõnda on Jumal maailma armastanud.",
    },
    lv: {
      "The Lord is near to the brokenhearted.": "Kungs ir tuvu tiem, kam sagrauzta sirds.",
      "Love your neighbor as yourself.": "Mīli savu tuvāko kā sevi pašu.",
      "Faith without works is dead.": "Ticība bez darbiem ir nedzīva.",
      "Be still, and know that I am God.": "Rimstiet un atzīstiet, ka Es esmu Dievs.",
      "Love is patient, love is kind.": "Mīlestība ir lēnprātīga, mīlestība ir laipna.",
      "For God so loved the world.": "Jo tik ļoti Dievs pasauli mīlējis.",
    },
    lt: {
      "The Lord is near to the brokenhearted.": "Viešpats arti tų, kurių širdys sudužusios.",
      "Love your neighbor as yourself.": "Mylėk savo artimą kaip save patį.",
      "Faith without works is dead.": "Tikėjimas be darbų yra miręs.",
      "Be still, and know that I am God.": "Nurimkite ir žinokite, kad Aš esu Dievas.",
      "Love is patient, love is kind.": "Meilė kantri, meilė maloninga.",
      "For God so loved the world.": "Dievas taip pamilo pasaulį.",
    },
    be: {
      "The Lord is near to the brokenhearted.": "Блізкі Гасподзь да зламаных сэрцам.",
      "Love your neighbor as yourself.": "Любі бліжняга свайго, як самога сябе.",
      "Faith without works is dead.": "Вера без спраў мёртвая.",
      "Be still, and know that I am God.": "Супакойцеся і пазнайце, што Я — Бог.",
      "Love is patient, love is kind.": "Любоў доўга церпіць, любоў міласэрная.",
      "For God so loved the world.": "Бо так палюбіў Бог свет.",
    },
    ka: {
      "The Lord is near to the brokenhearted.": "უფალი ახლოსაა გულშემუსვრილებთან.",
      "Love your neighbor as yourself.": "გიყვარდეს მოყვასი შენი, ვითარცა თავი შენი.",
      "Faith without works is dead.": "საქმეთა გარეშე რწმენა მკვდარია.",
      "Be still, and know that I am God.": "დაწყნარდით და იცოდეთ, რომ მე ვარ ღმერთი.",
      "Love is patient, love is kind.": "სიყვარული სულგრძელია, სიყვარული კეთილია.",
      "For God so loved the world.": "այնպես սիրեց ღმერთმა ქვეყანა.",
    },
    hy: {
      "The Lord is near to the brokenhearted.": "Տերը մոտ է սրտով բեկվածներին:",
      "Love your neighbor as yourself.": "Սիրիր ընկերոջդ ինչպես քեզ:",
      "Faith without works is dead.": "Գործերից առանց հավատքը մեռած է:",
      "Be still, and know that I am God.": "Դադարեցրեք և իմացեք, որ ես Աստված եմ:",
      "Love is patient, love is kind.": "Սերը համբերատար է, սերը բարի է:",
      "For God so loved the world.": "Այնպես սիրեց Աստված աշխարհը:",
    },
    az: {
      "The Lord is near to the brokenhearted.": "Rəbb qəlbi qırıq olanlara yaxındır.",
      "Love your neighbor as yourself.": "Qonşunu özün kimi sev.",
      "Faith without works is dead.": "Əməlsiz iman ölüdür.",
      "Be still, and know that I am God.": "Sakit olun və bilin ki, Mən Allaham.",
      "Love is patient, love is kind.": "Məhəbbət səbirli, xeyirxahdır.",
      "For God so loved the world.": "Çünki Allah dünyanı elə sevdi.",
    },
    kk: {
      "The Lord is near to the brokenhearted.": "Жаратқан Ие жүрегі жаралыларға жақын.",
      "Love your neighbor as yourself.": "Жақыныңды өзіңдей сүй.",
      "Faith without works is dead.": "Іссіз сенім өлі.",
      "Be still, and know that I am God.": "Тынышталыңдар, Мен Құдай екенімді біліңдер.",
      "Love is patient, love is kind.": "Махаббат шыдамды, қайырымды.",
      "For God so loved the world.": "Құдай дүниені соншалықты сүйді.",
    },
    ky: {
      "The Lord is near to the brokenhearted.": "Теңир жүрөгү жаралууларга жакын.",
      "Love your neighbor as yourself.": "Кошунаңды өзүңдөй сүй.",
      "Faith without works is dead.": "Ишсиз ишеним өлүү.",
      "Be still, and know that I am God.": "Тынчыгыла жана Мен Кудай экенимди билгиле.",
      "Love is patient, love is kind.": "Сүйүү чыдамдуу, мээримдүү.",
      "For God so loved the world.": "Анткени Кудай дүйнөнү ушунчалык сүйдү.",
    },
    uz: {
      "The Lord is near to the brokenhearted.": "Egamiz yuragi ezilganlarga yaqindir.",
      "Love your neighbor as yourself.": "Qo'shningni o'zingni sevgandek sev.",
      "Faith without works is dead.": "Amalsiz imon o'likdir.",
      "Be still, and know that I am God.": "Sokin bo'ling va bilingki, Men Xudoman.",
      "Love is patient, love is kind.": "Muhabbat sabrli, mehribondir.",
      "For God so loved the world.": "Xudo dunyoni shunchalik sevdi.",
    },
    tg: {
      "The Lord is near to the brokenhearted.": "Худованд ба дилшикастагон наздик аст.",
      "Love your neighbor as yourself.": "Ҳамсояатро чун худ дӯст дор.",
      "Faith without works is dead.": "Имони бе амал мурда аст.",
      "Be still, and know that I am God.": "Ором бошед ва бидонед, ки Ман Худо ҳастам.",
      "Love is patient, love is kind.": "Муҳаббат пурсабр ва меҳрубон аст.",
      "For God so loved the world.": "Зеро Худо ҷаҳонро чунон дӯст дошт.",
    },
    mn: {
      "The Lord is near to the brokenhearted.": "Эзэн сэтгэл нь шархалсан хүмүүст ойр байдаг.",
      "Love your neighbor as yourself.": "Хөршөө өөрийн адил хайрла.",
      "Faith without works is dead.": "Үйлсгүй итгэл үхсэн.",
      "Be still, and know that I am God.": "Тайвширч, Би Бурхан гэдгийг мэд.",
      "Love is patient, love is kind.": "Хайр тэвчээртэй, хайр энэрэнгүй.",
      "For God so loved the world.": "Бурхан ертөнцийг маш их хайрласан.",
    },
    km: {
      "The Lord is near to the brokenhearted.": "ព្រះអម្ចាស់គង់នៅជិតអ្នកដែលមានចិត្តខ្ទេចខ្ទាំ។",
      "Love your neighbor as yourself.": "ចូរស្រឡាញ់អ្នកជិតខាងដូចខ្លួនឯង។",
      "Faith without works is dead.": "ជំនឿដែលគ្មានកិច្ចការគឺស្លាប់។",
      "Be still, and know that I am God.": "ចូរនៅស្ងៀម ហើយដឹងថាអញជាព្រះ។",
      "Love is patient, love is kind.": "សេចក្តីស្រឡាញ់អត់ធ្មត់ សេចក្តីស្រឡាញ់សប្បុរស។",
      "For God so loved the world.": "ដ្បិតព្រះទ្រង់ស្រឡាញ់លោកីយ៍",
    },
    lo: {
      "The Lord is near to the brokenhearted.": "ພຣະຜູ້ເປັນເຈົ້າຢູ່ໃກ້ຜູ້ທີ່ໃຈແຕກສະຫລາຍ",
      "Love your neighbor as yourself.": "ຈົ່ງຮັກເພື່ອນບ້ານເໝືອນຮັກຕົນເອງ",
      "Faith without works is dead.": "ຄວາມເຊື່ອທີ່ບໍ່ມີການກະທຳກໍ່ຕາຍແລ້ວ",
      "Be still, and know that I am God.": "ຈົ່ງນິ້ງແລະຮູ້ວ່າເຮົາຄືພຣະເຈົ້າ",
      "Love is patient, love is kind.": "ຄວາມຮັກນັ້ນອົດທົນແລະກະທຳຄຸນໃຫ້",
      "For God so loved the world.": "ເພາະວ່າພຣະເຈົ້າຮັກໂລກ",
    },
    my: {
      "The Lord is near to the brokenhearted.": "ထာဝရဘုရားသည် စိတ်ကြေကွဲသူတို့နှင့် နီးတော်မူ၏။",
      "Love your neighbor as yourself.": "ကိုယ်နှင့်စပ်ဆိုင်သောသူကို ကိုယ်နှင့်အမျှချစ်လော့။",
      "Faith without works is dead.": "အကျင့်မပါသောယုံကြည်ခြင်းသည် သေ၏။",
      "Be still, and know that I am God.": "ငြိမ်ဝပ်စွာနေ၍ ငါသည် ဘုရားသခင်ဖြစ်ကြောင်းသိလော့။",
      "Love is patient, love is kind.": "မေတ္တာသည် စိတ်ရှည်တတ်၏၊ ကျေးဇူးပြုတတ်၏။",
      "For God so loved the world.": "ဘုရားသခင်သည် လောကကို ချစ်တော်မူသောကြောင့်၊",
    },
  }

  try {
    const verse = await fetch('https://beta.ourmanna.com/api/v1/get/?format=json&order=random', { next: { revalidate: 3600 } }).then(r=>r.json()).catch(()=>null)
    const rawText: string = verse?.text || verse?.verse?.text || verse?.details?.text || "The Lord is near to the brokenhearted."
    const ref: string = verse?.reference || verse?.verse?.reference || "Psalm 34:18"

    const transMap = DICT[lang] || DICT.en
    const translatedText = transMap?.[rawText] || rawText

    return Response.json({ 
      text: translatedText, 
      original_text: rawText,
      reference: ref, 
      lang,
      translated: !!transMap?.[rawText],
      wholeBible: true
    })
  } catch {
    const FALLBACKS: Record<string, {text:string, ref:string}> = {
      en: { text:"The Lord is near to the brokenhearted.", ref:"Psalm 34:18" },
      es: { text:"El Señor está cerca de los quebrantados de corazón.", ref:"Salmo 34:18" },
      fr: { text:"Le Seigneur est près de ceux qui ont le cœur brisé.", ref:"Psaume 34:18" },
      de: { text:"Der Herr ist nahe denen, die zerbrochenen Herzens sind.", ref:"Psalm 34:18" },
      zh: { text:"耶和华靠近伤心的人。", ref:"诗篇 34:18" },
      ja: { text:"主は心の打ち砕かれた者の近くにおられる。", ref:"詩篇 34:18" },
      ko: { text:"여호와는 마음이 상한 자를 가까이 하시나니", ref:"시편 34:18" },
      ru: { text:"Близок Господь к сокрушенным сердцем.", ref:"Псалом 33:19" },
      ar: { text:"قريب هو الرب من المنكسري القلوب.", ref:"مزمور 34:18" },
      pt: { text:"O Senhor está perto dos que têm o coração quebrantado.", ref:"Salmos 34:18" },
      it: { text:"Il Signore è vicino a quelli che hanno il cuore spezzato.", ref:"Salmo 34:18" },
      nl: { text:"De Heer is nabij de gebroken harten.", ref:"Psalm 34:18" },
      tl: { text:"Malapit ang Panginoon sa may pusong wasak.", ref:"Awit 34:18" },
      hi: { text:"यहोवा टूटे मन वालों के समीप रहता है।", ref:"भजन 34:18" },
      bn: { text:"সদাপ্রভু ভগ্নহৃদয়দের কাছাকাছি থাকেন।", ref:"গীতসংহিতা 34:18" },
      id: { text:"Tuhan dekat kepada orang-orang yang patah hati.", ref:"Mazmur 34:18" },
      vi: { text:"Đức Giê-hô-va ở gần những người có lòng đau thương.", ref:"Thi Thiên 34:18" },
      th: { text:"พระเจ้าทรงอยู่ใกล้ผู้ที่ชอกช้ำใจ", ref:"สดุดี 34:18" },
      sv: { text:"Herren är nära de som har ett förkrossat hjärta.", ref:"Psaltaren 34:18" },
      pl: { text:"Pan jest blisko skruszonych w sercu.", ref:"Psalm 34:18" },
      tr: { text:"Rab yüreği kırık olanlara yakındır.", ref:"Mezmurlar 34:18" },
      uk: { text:"Близький Господь до зламаних серцем.", ref:"Псалом 34:18" },
      el: { text:"Ο Κύριος είναι κοντά στους συντετριμμένους την καρδία.", ref:"Ψαλμός 34:18" },
      he: { text:"קרוב ה' לנשברי לב.", ref:"תהילים ל״ד:י״ח" },
      ur: { text:"خداوند شکستہ دلوں کے نزدیک ہے۔", ref:"زبور 34:18" },
      fa: { text:"خداوند نزدیک شکستہ‌دلان است.", ref:"مزمور 34:18" },
      ms: { text:"Tuhan dekat kepada orang yang patah hati.", ref:"Mazmur 34:18" },
      ro: { text:"Domnul este aproape de cei cu inima zdrobită.", ref:"Psalmul 34:18" },
      cs: { text:"Hospodin je blízko těm, kdo mají zkroušené srdce.", ref:"Žalm 34:18" },
      hu: { text:"Közel van az Úr a megtört szívűekhez.", ref:"Zsoltárok 34:18" },
      fi: { text:"Herra on lähellä niitä, joilla on särkynyt sydän.", ref:"Psalmi 34:18" },
      no: { text:"Herren er nær dem som har et nedbrutt hjerte.", ref:"Salme 34:18" },
      da: { text:"Herren er nær hos de sønderknuste hjerter.", ref:"Salme 34:18" },
      bg: { text:"Господ е близо до съкрушените по сърце.", ref:"Псалм 34:18" },
      hr: { text:"Blizu je Gospodin onima koji su slomljena srca.", ref:"Psalam 34:18" },
      sr: { text:"Близу је Господ онима који су скрушена срца.", ref:"Псалам 34:18" },
      sk: { text:"Blízko je Pán tým, čo majú skrúšené srdce.", ref:"Žalm 34:18" },
      sl: { text:"Gospod je blizu tistim, ki so strtega srca.", ref:"Psalm 34:18" },
      et: { text:"Issand on lähedal neile, kellel on purustatud süda.", ref:"Psalm 34:18" },
      lv: { text:"Kungs ir tuvu tiem, kam sagrauzta sirds.", ref:"Psalmi 34:18" },
      lt: { text:"Viešpats arti tų, kurių širdys sudužusios.", ref:"Psalmė 34:18" },
      be: { text:"Блізкі Гасподзь да зламаных сэрцам.", ref:"Псальм 34:18" },
      ka: { text:"უფალი ახლოსაა გულშემუსვრილებთან.", ref:"ფსალმუნი 34:18" },
      hy: { text:"Տերը մոտ է սրտով բեկվածներին:", ref:"Սաղմոս 34:18" },
      az: { text:"Rəbb qəlbi qırıq olanlara yaxındır.", ref:"Zəbur 34:18" },
      kk: { text:"Жаратқан Ие жүрегі жаралыларға жақын.", ref:"Забур 34:18" },
      ky: { text:"Теңир жүрөгү жаралууларга жакын.", ref:"Забур 34:18" },
      uz: { text:"Egamiz yuragi ezilganlarga yaqindir.", ref:"Zabur 34:18" },
      tg: { text:"Худованд ба дилшикастагон наздик аст.", ref:"Забур 34:18" },
      mn: { text:"Эзэн сэтгэл нь шархалсан хүмүүст ойр байдаг.", ref:"Дуулал 34:18" },
      km: { text:"ព្រះអម្ចាស់គង់នៅជិតអ្នកដែលមានចិត្តខ្ទេចខ្ទាំ។", ref:"ទំនុកដំកើង 34:18" },
      lo: { text:"ພຣະຜູ້ເປັນເຈົ້າຢູ່ໃກ້ຜູ້ທີ່ໃຈແຕກສະຫລາຍ", ref:"ເພງ 34:18" },
      my: { text:"ထာဝရဘုရားသည် စိတ်ကြေကွဲသူတို့နှင့် နီးတော်မူ၏။", ref:"ဆာလံ 34:18" },
    }
    const fb = FALLBACKS[lang] || FALLBACKS.en
    return Response.json({ text: fb.text, reference: fb.ref, lang, fallback: true, wholeBible: false })
  }
}
